#!/usr/bin/env python3
"""Generate deposit/pc-general-part-tests.l4.

Why a generator: the facts records here are wide (up to 45 fields) and L4 has
no record-update syntax, so every fixture must restate every field. Hand-typing
that is where a silently wrong field creeps in. Each fixture below names ONLY
the leaves its Illustration states; every other BOOLEAN is FALSE and every other
STRING blank - the charge generator's own schema-completion default.

The field lists are read from deposit/pc-general-part.l4 itself, so a field
added there is picked up here. Expected values are the Illustrations', cited on
the line above each #ASSERT; none was edited to match the code.

Run:  python3 notes/gen-general-part-tests.py > deposit/pc-general-part-tests.l4
"""
import re, sys, pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = (ROOT / "deposit" / "pc-general-part.l4").read_text()


def fields_of(record):
    """[(name, type)] of a DECLARE ... HAS block in the module."""
    m = re.search(r"^DECLARE `%s` HAS\n(.*?)(?=^\S|\Z)" % re.escape(record), SRC, re.M | re.S)
    if not m:
        sys.exit("no record %s" % record)
    lines = m.group(1).split("\n")
    out, i = [], 0
    while i < len(lines):
        ln = lines[i]
        if re.match(r"^    \S", ln) and not ln.strip().startswith("--"):
            body = ln.strip()
            mm = re.match(r"^(`[^`]+`|\S+)\s+IS AN? (\w+)", body)
            if mm:
                out.append((mm.group(1), mm.group(2)))
            else:
                name = body
                nxt = lines[i + 1].strip()
                mm = re.match(r"^IS AN? (\w+)", nxt)
                out.append((name, mm.group(1)))
                i += 1
        i += 1
    return out


def bq(name):
    return name if name.startswith("`") else name


def fixture(label, record, comment, **given):
    """A full record, with the named leaves set and every other one defaulted."""
    fs = fields_of(record)
    names = {n.strip("`"): n for n, _ in fs}
    for k in given:
        if k not in names:
            sys.exit("fixture %s: %s has no field %r" % (label, record, k))
    lines = []
    if comment:
        for c in comment.strip().split("\n"):
            lines.append("-- " + c)
    lines.append("`%s` MEANS `%s` WITH" % (label, record))
    for n, t in fs:
        key = n.strip("`")
        if key in given:
            v = given[key]
            if isinstance(v, bool):
                v = "TRUE" if v else "FALSE"
            elif isinstance(v, str) and not v.startswith("`"):
                v = '"%s"' % v.replace('"', '\\"')
        elif t == "BOOLEAN":
            v = "FALSE"
        elif t == "STRING":
            v = '""'
        elif t == "Particulars":
            v = "`the particulars in the illustrations`"
        elif t == "Pronoun":
            v = "he"
        else:
            sys.exit("no default for %s %s" % (n, t))
        lines.append("    %s IS %s" % (n, v))
    return "\n".join(lines) + "\n"


out = []
w = out.append

w("""-- Tests for pc-general-part.l4 - Chapters 1, 3, 5, 5A and 23 of the Penal
-- Code 1871. GENERATED by notes/gen-general-part-tests.py; edit that, not this.
--
-- Expected values come from the Code: each Illustration that can be expressed
-- is an #ASSERT, cited on the line above; boundary cases sit either side of
-- every threshold. A fixture states only the leaves its Illustration states;
-- every other leaf is FALSE and every other string blank, which is also what the
-- charge generator's schema completion does with an unknown element.
--
-- Illustrations NOT expressed, and why, are in notes/general-part-coverage.md.

IMPORT prelude
IMPORT `pc-domain`
IMPORT `pc-general`
IMPORT `pc-general-part`

§ `Fixtures shared by every chapter`

`the particulars in the illustrations` MEANS Particulars WITH
    accused            IS "A"
    date               IS "the 1st day of March 2026"
    time               IS ""
    place              IS "Block 1 Orchard Road"
    `co-accused`       IS ""
    `common intention` IS FALSE
""")

# --------------------------------------------------------------------------
w("\n§ `Chapter 1 - ss 4, 4A, 4B and the Schedule`\n\n")
E = "Extraterritorial Facts"
w(fixture("s 4, a citizen officer abroad", E, "A public servant, a citizen, acting in the course of his employment abroad.",
          **{"public servant": True, "a citizen of Singapore": True, "acting in the course of his employment": True,
             "commits an act or omission outside Singapore": True,
             "would constitute an offence under the law in force in Singapore if committed in Singapore": True}))
w(fixture("s 4, a permanent resident purporting to act", E, "A public servant, a permanent resident, purporting to act in the course of his employment.",
          **{"public servant": True, "a permanent resident of Singapore": True, "purporting to act in the course of his employment": True,
             "commits an act or omission outside Singapore": True,
             "would constitute an offence under the law in force in Singapore if committed in Singapore": True}))
w(fixture("s 4, a foreign officer", E, "A public servant who is neither a citizen nor a permanent resident.",
          **{"public servant": True, "acting in the course of his employment": True,
             "commits an act or omission outside Singapore": True,
             "would constitute an offence under the law in force in Singapore if committed in Singapore": True}))
w(fixture("s 4A, a citizen abroad", E, "A citizen (not a public servant) who does abroad what would be an offence under Chapter 6.",
          **{"a citizen of Singapore": True, "commits an act or omission outside Singapore": True,
             "would constitute an offence under Chapter 6 or 6B if committed in Singapore": True}))
w(fixture("s 4B(1)(a), a scam split across borders", E, "A specified offence, one physical element here and another abroad.",
          **{"a specified offence": True, "a relevant act of the offence occurs in Singapore": True,
             "any other relevant act of the offence occurs outside Singapore": True}))
w(fixture("s 4B(1)(c), a loss in Singapore", E, "A specified offence done wholly abroad, intending a loss that falls in Singapore.",
          **{"a specified offence": True,
             "the offence involved an intention to make a gain or cause a loss or exposure to a risk of loss or to cause harm to any person in body, mind, reputation or property": True,
             "that gain, loss or harm occurs in Singapore": True}))
w(fixture("s 4B, not a specified offence", E, "The same as (1)(a), but not a specified offence.",
          **{"a relevant act of the offence occurs in Singapore": True,
             "any other relevant act of the offence occurs outside Singapore": True}))
w("""
#ASSERT `deemed committed in Singapore within section 4` `s 4, a citizen officer abroad`
#ASSERT `deemed committed in Singapore within section 4` `s 4, a permanent resident purporting to act`
#ASSERT NOT (`deemed committed in Singapore within section 4` `s 4, a foreign officer`)
-- s 4A needs no public office
#ASSERT `deemed committed in Singapore within section 4A` `s 4A, a citizen abroad`
#ASSERT NOT (`deemed committed in Singapore within section 4` `s 4A, a citizen abroad`)
#ASSERT `deemed committed in Singapore within section 4B` `s 4B(1)(a), a scam split across borders`
#ASSERT `deemed committed in Singapore within section 4B` `s 4B(1)(c), a loss in Singapore`
#ASSERT NOT (`deemed committed in Singapore within section 4B` `s 4B, not a specified offence`)

-- the Schedule: items 3, 9, 13, 14 by section; item 15 by fault element; the
-- item 15 exclusion; an unlisted section with no fraud element
#ASSERT `specified offence within the Schedule` "379A" FALSE FALSE
#ASSERT `specified offence within the Schedule` "420" FALSE FALSE
#ASSERT `specified offence within the Schedule` "477A" FALSE FALSE
#ASSERT `specified offence within the Schedule` "489I" FALSE FALSE
#ASSERT `specified offence within the Schedule` "424B" FALSE FALSE
#ASSERT NOT (`specified offence within the Schedule` "416A" FALSE FALSE)
#ASSERT NOT (`specified offence within the Schedule` "302" FALSE FALSE)
#ASSERT `specified offence within the Schedule` "section 6 of some other Act" TRUE FALSE
#ASSERT NOT (`specified offence within the Schedule` "section 6 of the Prevention of Corruption Act 1960" TRUE TRUE)
""")

# --------------------------------------------------------------------------
w("\n§ `Chapter 3 - Punishments`\n\n")
w("""-- Punishments as data, copied from the sections, for the Chapter 3 tests.
`s 323 punishment` MEANS Punishment WITH
    section                  IS "323"
    words                    IS "imprisonment for a term which may extend to 3 years, or with fine which may extend to $5,000, or with both"
    death                    IS `not prescribed`
    `imprisonment for life`  IS `not prescribed`
    imprisonment             IS `or with`
    `maximum term in months` IS JUST 36
    `minimum term in months` IS NOTHING
    `forfeiture of property` IS `not prescribed`
    fine                     IS `or with`
    `maximum fine`           IS JUST 5000
    `minimum fine`           IS NOTHING
    caning                   IS `not prescribed`
    `minimum strokes`        IS NOTHING
    `maximum strokes`        IS NOTHING
    `or with both`           IS TRUE

-- s 403 is s 379 with a 2-year term: "imprisonment for a term which may extend
-- to 2 years, or with fine, or with both" (checked against inputs/PC1871.txt).
`s 379 punishment` MEANS Punishment WITH
    section                  IS "379"
    words                    IS "imprisonment for a term which may extend to 3 years, or with fine, or with both"
    death                    IS `not prescribed`
    `imprisonment for life`  IS `not prescribed`
    imprisonment             IS `or with`
    `maximum term in months` IS JUST 36
    `minimum term in months` IS NOTHING
    `forfeiture of property` IS `not prescribed`
    fine                     IS `or with`
    `maximum fine`           IS NOTHING
    `minimum fine`           IS NOTHING
    caning                   IS `not prescribed`
    `minimum strokes`        IS NOTHING
    `maximum strokes`        IS NOTHING
    `or with both`           IS TRUE

`s 403 punishment` MEANS Punishment WITH
    section                  IS "403"
    words                    IS "imprisonment for a term which may extend to 2 years, or with fine, or with both"
    death                    IS `not prescribed`
    `imprisonment for life`  IS `not prescribed`
    imprisonment             IS `or with`
    `maximum term in months` IS JUST 24
    `minimum term in months` IS NOTHING
    `forfeiture of property` IS `not prescribed`
    fine                     IS `or with`
    `maximum fine`           IS NOTHING
    `minimum fine`           IS NOTHING
    caning                   IS `not prescribed`
    `minimum strokes`        IS NOTHING
    `maximum strokes`        IS NOTHING
    `or with both`           IS TRUE

-- s 392 (the day-time limb): "imprisonment for a term of not less than 2 years
-- and not more than 10 years and shall also be punished with caning with not
-- less than 6 strokes" - the robbery of the s 512(4) Illustration.
`s 392 punishment` MEANS Punishment WITH
    section                  IS "392"
    words                    IS "imprisonment for a term of not less than 2 years and not more than 10 years and shall also be punished with caning with not less than 6 strokes"
    death                    IS `not prescribed`
    `imprisonment for life`  IS `not prescribed`
    imprisonment             IS `shall be punished with`
    `maximum term in months` IS JUST 120
    `minimum term in months` IS JUST 24
    `forfeiture of property` IS `not prescribed`
    fine                     IS `not prescribed`
    `maximum fine`           IS NOTHING
    `minimum fine`           IS NOTHING
    caning                   IS `shall be punished with`
    `minimum strokes`        IS JUST 6
    `maximum strokes`        IS NOTHING
    `or with both`           IS FALSE

-- s 364 (kidnapping in order to murder): "death or imprisonment for life and
-- shall, if he is not sentenced to death, also be liable to caning"
`s 364 punishment` MEANS Punishment WITH
    section                  IS "364"
    words                    IS "death or imprisonment for life and shall, if he is not sentenced to death, also be liable to caning"
    death                    IS `or with`
    `imprisonment for life`  IS `or with`
    imprisonment             IS `not prescribed`
    `maximum term in months` IS NOTHING
    `minimum term in months` IS NOTHING
    `forfeiture of property` IS `not prescribed`
    fine                     IS `not prescribed`
    `maximum fine`           IS NOTHING
    `minimum fine`           IS NOTHING
    caning                   IS `shall also be liable to`
    `minimum strokes`        IS NOTHING
    `maximum strokes`        IS NOTHING
    `or with both`           IS FALSE

-- s 395: "imprisonment for a term of not less than 5 years and not more than 20
-- years and shall also be punished with caning with not less than 12 strokes"
`s 395 punishment` MEANS Punishment WITH
    section                  IS "395"
    words                    IS "imprisonment for a term of not less than 5 years and not more than 20 years and shall also be punished with caning with not less than 12 strokes"
    death                    IS `not prescribed`
    `imprisonment for life`  IS `not prescribed`
    imprisonment             IS `shall be punished with`
    `maximum term in months` IS JUST 240
    `minimum term in months` IS JUST 60
    `forfeiture of property` IS `not prescribed`
    fine                     IS `not prescribed`
    `maximum fine`           IS NOTHING
    `minimum fine`           IS NOTHING
    caning                   IS `shall be punished with`
    `minimum strokes`        IS JUST 12
    `maximum strokes`        IS NOTHING
    `or with both`           IS FALSE

-- s 72: the same punishment for all - nothing to choose
#ASSERT (`the lower punishment within section 72 of` `s 379 punishment` `and` `s 379 punishment`)'s section EQUALS "379"
-- s 72: the same kinds, the same way, differing only in term - the lower term
#ASSERT (`the lower punishment within section 72 of` `s 379 punishment` `and` `s 403 punishment`)'s section EQUALS "403"
#ASSERT (`the lower punishment within section 72 of` `s 403 punishment` `and` `s 379 punishment`)'s section EQUALS "403"
-- s 72 across kinds (s 323's capped fine against s 379's uncapped one) is
-- REFUSED by name; run `#EVAL` below to see it.
#EVAL `the lower punishment within section 72 of` `s 323 punishment` `and` `s 379 punishment`

-- s 74E with ss 73-74D: twice the maximum term and the maximum fine
#ASSERT (`twice the maximum punishment of` `s 323 punishment` `under section` "73")'s `maximum term in months` EQUALS JUST 72
#ASSERT (`twice the maximum punishment of` `s 323 punishment` `under section` "73")'s `maximum fine` EQUALS JUST 10000
#ASSERT (`twice the maximum punishment of` `s 323 punishment` `under section` "73")'s section EQUALS "323 read with 73"
-- a fine with no stated maximum stays unstated
#ASSERT (`twice the maximum punishment of` `s 379 punishment` `under section` "74B")'s `maximum fine` EQUALS NOTHING
-- s 74E(2)(a): an imprisonment with a minimum term is not enhanced (FORK GP-5)
#ASSERT (`twice the maximum punishment of` `s 392 punishment` `under section` "74A")'s `maximum term in months` EQUALS JUST 120
#ASSERT (`twice the maximum punishment of` `s 392 punishment` `under section` "74A")'s `minimum term in months` EQUALS JUST 24
-- s 74E(2)(b): the strokes are not enhanced
#ASSERT (`twice the maximum punishment of` `s 392 punishment` `under section` "74A")'s `minimum strokes` EQUALS JUST 6
#ASSERT (`twice the maximum punishment of` `s 392 punishment` `under section` "74A")'s `maximum strokes` EQUALS NOTHING

-- s 74B: "below 14 years of age", both sides of the line
#ASSERT `below 14 years of age` 13
#ASSERT NOT (`below 14 years of age` 14)
#ASSERT NOT (`below 14 years of age` 15)

""")
D = "Domestic Worker Enhancement Facts"
dw = {"the victim is a female house servant": True,
      "employed in, or in connection with, the domestic services of her employer's private dwelling house": True,
      "required to reside in her employer's private dwelling house": True,
      "convicted of an offence under this Code": True, "the offence is committed against that domestic worker": True}
w(fixture("s 73, an employer's hurt", D, "An employer convicted of voluntarily causing hurt (s 323) to a live-in domestic worker.",
          **dict(dw, **{"the offender is an employer of the domestic worker": True})))
w(fixture("s 73, a household member", D, "A member of the employer's household, likewise.",
          **dict(dw, **{"the offender is a member of the employer's household": True})))
w(fixture("s 73, a live-out worker", D, "The employer's victim is not required to reside in the house: not a domestic worker within s 73(4).",
          **dict(dw, **{"the offender is an employer of the domestic worker": True,
                        "required to reside in her employer's private dwelling house": False})))
w(fixture("s 73, an excluded offence", D, "An offence punishable with death or imprisonment for life (s 73(4) excluded offence (b)).",
          **dict(dw, **{"the offender is an employer of the domestic worker": True,
                        "the offence is punishable with death or imprisonment for life": True})))
w(fixture("s 73, s 304B", D, "An offence under s 304B (excluded offence (a)).",
          **dict(dw, **{"the offender is an employer of the domestic worker": True,
                        "the offence is under section 304B, 304C or 335A": True})))
w(fixture("s 73(2) proved", D, "The employer proves the relationship did not affect her ability to protect herself.",
          **dict(dw, **{"the offender is an employer of the domestic worker": True,
                        "the offender proves that the relationship did not adversely affect the victim's ability to protect herself": True})))
w("""
#ASSERT `enhanced penalty under s 73` `s 73, an employer's hurt`
#ASSERT `enhanced penalty under s 73` `s 73, a household member`
#ASSERT NOT (`domestic worker within section 73` `s 73, a live-out worker`)
#ASSERT NOT (`enhanced penalty under s 73` `s 73, a live-out worker`)
#ASSERT NOT (`enhanced penalty under s 73` `s 73, an excluded offence`)
#ASSERT NOT (`enhanced penalty under s 73` `s 73, s 304B`)
#ASSERT NOT (`enhanced penalty under s 73` `s 73(2) proved`)
""")
R = "Racial or Religious Aggravation Facts"
w(fixture("s 74(4)(a), hostility shown", R, "", **{"convicted of an offence under this Code": True,
          "demonstrates towards the victim hostility based on the victim's membership of a racial or religious group": True}))
w(fixture("s 74(4)(b), hostility the motive", R, "", **{"convicted of an offence under this Code": True,
          "motivated by hostility towards members of a racial or religious group based on their membership of that group": True}))
w(fixture("s 74(2)(a), an offence under s 298", R, "", **{"convicted of an offence under this Code": True,
          "the offence is under section 298 or 298A": True,
          "demonstrates towards the victim hostility based on the victim's membership of a racial or religious group": True}))
w(fixture("s 74, no hostility", R, "", **{"convicted of an offence under this Code": True}))
w("""
#ASSERT `enhanced penalty under s 74` `s 74(4)(a), hostility shown`
#ASSERT `enhanced penalty under s 74` `s 74(4)(b), hostility the motive`
#ASSERT NOT (`enhanced penalty under s 74` `s 74(2)(a), an offence under s 298`)
#ASSERT NOT (`enhanced penalty under s 74` `s 74, no hostility`)
""")
V = "Vulnerable Person Enhancement Facts"
vp = {"convicted of an offence under this Code which may be committed against a vulnerable person": True,
      "the offence is committed against the victim": True, "the victim is an individual": True,
      "by reason of mental or physical infirmity, disability or incapacity": True,
      "substantially unable to protect himself from abuse, neglect or self-neglect": True,
      "knew or ought reasonably to have known that the victim was a vulnerable person": True}
w(fixture("s 74A, a bedridden victim", V, "", **vp))
w(fixture("s 74A, not known", V, "The offender neither knew nor ought to have known.",
          **dict(vp, **{"knew or ought reasonably to have known that the victim was a vulnerable person": False})))
w(fixture("s 74A, s 376F", V, "", **dict(vp, **{"the offence is under section 304B, 304C, 335A or 376F": True})))
w(fixture("s 74A(2A) proved", V, "", **dict(vp, **{"the offender proves that the victim was capable of protecting himself as an ordinary person would": True})))
w("""
#ASSERT `enhanced penalty under s 74A` `s 74A, a bedridden victim`
#ASSERT NOT (`enhanced penalty under s 74A` `s 74A, not known`)
#ASSERT NOT (`enhanced penalty under s 74A` `s 74A, s 376F`)
#ASSERT NOT (`enhanced penalty under s 74A` `s 74A(2A) proved`)
""")
C = "Child Victim Enhancement Facts"
cv = {"convicted of an offence under this Code which may be committed against a person below 14 years of age": True,
      "the offence is committed against the victim": True,
      "knew or ought reasonably to have known that the victim was a person below 14 years of age": True}
w(fixture("s 74B, a victim aged 13", C, "The leaf is set from the helper, so the threshold is the one tested above.",
          **dict(cv, **{"the victim is below 14 years of age": "`below 14 years of age` 13"})))
w(fixture("s 74B, a victim aged 14", C, "", **dict(cv, **{"the victim is below 14 years of age": "`below 14 years of age` 14"})))
w(fixture("s 74B(1)(a), an express child limb", C, "",
          **dict(cv, **{"the victim is below 14 years of age": True,
                        "it is expressly provided that an enhanced or mandatory minimum sentence applies to the offence when committed against a person below 14 years of age": True})))
w("""
#ASSERT `enhanced penalty under s 74B` `s 74B, a victim aged 13`
#ASSERT NOT (`enhanced penalty under s 74B` `s 74B, a victim aged 14`)
#ASSERT NOT (`enhanced penalty under s 74B` `s 74B(1)(a), an express child limb`)
""")
I = "Intimate Relationship Enhancement Facts"
w(fixture("s 74C, a partner", I, "", **{"convicted of an offence under Chapter 16": True, "the offence is committed against the victim": True,
          "the victim was or is in an intimate relationship with the offender": True,
          "knew or ought reasonably to have known of the intimate relationship": True}))
w(fixture("s 74C, a Chapter 16 offence punishable with life", I, "", **{"convicted of an offence under Chapter 16": True,
          "the offence is punishable with death or imprisonment for life": True, "the offence is committed against the victim": True,
          "the victim was or is in an intimate relationship with the offender": True,
          "knew or ought reasonably to have known of the intimate relationship": True}))
L = "Close Relationship Enhancement Facts"
cl = {"convicted of an offence under Chapter 16": True, "the offence is committed against the victim": True,
      "A and B had frequent contact with each other": True, "knew or ought reasonably to have known of the close relationship": True}
w(fixture("s 74D, a live-in relative", L, "", **dict(cl, **{"they live in the same household": True})))
w(fixture("s 74D(6)(b), a frequent visitor", L, "", **dict(cl, **{
    "A or B visits the household to which the other belongs so often and for such periods of time that it is reasonable to regard them as members of the same household": True})))
w(fixture("s 74D(5)(b), no frequent contact", L, "", **dict(cl, **{"they live in the same household": True,
          "A and B had frequent contact with each other": False})))
w("""
#ASSERT `enhanced penalty under s 74C` `s 74C, a partner`
#ASSERT NOT (`enhanced penalty under s 74C` `s 74C, a Chapter 16 offence punishable with life`)
#ASSERT `enhanced penalty under s 74D` `s 74D, a live-in relative`
#ASSERT `enhanced penalty under s 74D` `s 74D(6)(b), a frequent visitor`
#ASSERT NOT (`close relationship within section 74D` `s 74D(5)(b), no frequent contact`)
#ASSERT NOT (`enhanced penalty under s 74D` `s 74D(5)(b), no frequent contact`)
""")

# --------------------------------------------------------------------------
w("\n§ `Chapter 5 - Abetment`\n\n")
A = "Abetment Facts"
murder = {"the offence abetted": "murder", "the section punishing the offence abetted": "302",
          "the offence abetted is punishable with death or imprisonment for life": True,
          "the offence abetted is punishable with imprisonment": True,
          "no express provision is made by this Code for the punishment of such abetment": True,
          "no express provision is made by this Code or by any other written law for the punishment of such abetment": True}
inst = {"instigates any person to do that thing": True}
w(fixture("s 107 illus", A, """s 107 Explanation 1, Illustration: B, knowing C is not Z, intentionally represents
to A (a public officer with a warrant for Z) that C is Z, and thereby intentionally
causes A to apprehend C. B abets by instigation the apprehension of C.""",
          **{"the person abetted": "A", "the offence abetted": "the apprehension of C",
             "by intentional misrepresentation": True,
             "voluntarily causes or procures, or attempts to cause or procure, a thing to be done": True}))
w(fixture("s 108 illus (a)", A, "s 108 Explanation 2, Illustration (a): A instigates B to murder C. B refuses to do so.",
          **dict(murder, **inst, **{"the person abetted": "B", "the thing abetted is the commission of an offence": True,
                                     "that offence is not committed in consequence of the abetment": True})))
w(fixture("s 108 illus (b)", A, """s 108 Explanation 2, Illustration (b): A instigates B to murder D. B, in pursuance of
the instigation, stabs D. D recovers. A is guilty of instigating B to commit murder.""",
          **dict(murder, **inst, **{"the person abetted": "B", "the thing abetted is the commission of an offence": True,
                                     "that offence is not committed in consequence of the abetment": True})))
w(fixture("s 108 Expl 3 illus (a)", A, """s 108 Explanation 3, Illustration (a): A, with a guilty intention, abets a child or
a person of unsound mind to commit an act which would be an offence if committed by a
person capable by law ... A, whether the act is committed or not, is guilty of abetting.""",
          **dict(inst, **{"the thing abetted is an act which would be an offence if committed by a person capable by law of committing an offence with the same intention or knowledge as that of the abettor": True})))
w(fixture("s 108 Expl 3 illus (b)", A, """s 108 Explanation 3, Illustration (b): A, intending to murder Z, instigates B, a
child below 7, to do an act which causes Z's death. B does it. A is liable as if B had
committed murder.""",
          **dict(murder, **inst, **{"the person abetted": "B",
                                     "the thing abetted is an act which would be an offence if committed by a person capable by law of committing an offence with the same intention or knowledge as that of the abettor": True,
                                     "the act abetted is committed": True, "in consequence of the instigation": True})))
w(fixture("s 108 Expl 3 illus (d)", A, """s 108 Explanation 3, Illustration (d): A instigates B to take Z's property, inducing
B to believe it is A's. B takes it in good faith, so commits no theft. A is guilty of
abetting theft, and liable as if B had committed theft.""",
          **dict(inst, **{"the person abetted": "B", "the offence abetted": "theft", "the section punishing the offence abetted": "379",
                          "the thing abetted is an act which would be an offence if committed by a person capable by law of committing an offence with the same intention or knowledge as that of the abettor": True,
                          "the act abetted is committed": True, "in consequence of the instigation": True,
                          "no express provision is made by this Code for the punishment of such abetment": True})))
w(fixture("s 108 Expl 4 illus", A, """s 108 Explanation 4, Illustration: A instigates B to instigate C to murder Z. B does,
and C commits murder in consequence. A is liable to the same punishment. The thing A
abets is B's abetment, itself an offence.""",
          **dict(murder, **inst, **{"the person abetted": "B", "the thing abetted is the commission of an offence": True,
                                     "the act abetted is committed": True, "in consequence of the instigation": True})))
w(fixture("s 108 Expl 5 illus", A, """s 108 Explanation 5, Illustration: C agrees with B to procure poison for a plan
of A's he knows only through B, procures and delivers it; A administers it; Z dies. C
engaged in the conspiracy in pursuance of which Z was murdered.""",
          **dict(murder, **{"the person abetted": "B", "the thing abetted is the commission of an offence": True,
                            "engages with one or more other persons in a conspiracy for the doing of that thing": True,
                            "an act or illegal omission takes place in pursuance of that conspiracy": True,
                            "in order to the doing of that thing": True,
                            "the act abetted is committed": True, "in pursuance of the conspiracy": True})))
w(fixture("s 108A illus", A, """s 108A Illustration: A, in Singapore, instigates B, a foreigner in Java, to commit
murder in Java. A is guilty of abetting murder.""",
          **dict(inst, **{"the person abetted": "B", "the offence abetted": "murder", "abets in Singapore": True,
                          "the act abetted is to be committed without and beyond Singapore and would constitute an offence if committed in Singapore": True})))
w(fixture("s 108B, abetment from abroad", A, """s 108B (no Illustration): the instigation is sent from abroad; the offence is
committed in Singapore. Nothing in the ladder asks where the abetment was done.""",
          **dict(inst, **{"the person abetted": "B", "the offence abetted": "theft", "abets in Singapore": False,
                          "the thing abetted is the commission of an offence": True})))
w(fixture("s 109 illus (a)", A, "s 109 Illustration (a): A offers a bribe to B, a public servant ... B accepts the bribe. A has abetted the offence defined in s 161.",
          **dict(inst, **{"the person abetted": "B", "the offence abetted": "accepting a gratification as a public servant",
                          "the section punishing the offence abetted": "161",
                          "the thing abetted is the commission of an offence": True, "the act abetted is committed": True,
                          "in consequence of the instigation": True,
                          "no express provision is made by this Code for the punishment of such abetment": True})))
w(fixture("s 109 illus (b)", A, "s 109 Illustration (b): A instigates B to give false evidence. B, in consequence, commits that offence.",
          **dict(inst, **{"the person abetted": "B", "the person abetted described as": "a witness",
                          "the offence abetted": "giving false evidence",
                          "the section punishing the offence abetted": "193",
                          "the manner of the abetment": "by asking him to testify that he saw Z at the scene",
                          "the thing abetted is the commission of an offence": True, "the act abetted is committed": True,
                          "in consequence of the instigation": True,
                          "no express provision is made by this Code for the punishment of such abetment": True})))
w(fixture("s 109 illus (c)", A, """s 109 Illustration (c): A and B conspire to poison Z. A procures the poison and
delivers it to B, who administers it in A's absence. A is guilty of abetting murder by
conspiracy.""",
          **dict(murder, **{"the person abetted": "B", "the thing abetted is the commission of an offence": True,
                            "engages with one or more other persons in a conspiracy for the doing of that thing": True,
                            "an act or illegal omission takes place in pursuance of that conspiracy": True,
                            "in order to the doing of that thing": True,
                            "the act abetted is committed": True, "in pursuance of the conspiracy": True})))
w(fixture("s 109 illus (b), not committed", A, "The same instigation to give false evidence; B does not give it (s 116 Illustration (b)).",
          **dict(inst, **{"the person abetted": "B", "the offence abetted": "giving false evidence",
                          "the section punishing the offence abetted": "193",
                          "the thing abetted is the commission of an offence": True,
                          "the offence abetted is punishable with imprisonment": True,
                          "that offence is not committed in consequence of the abetment": True,
                          "no express provision is made by this Code or by any other written law for the punishment of such abetment": True})))
w(fixture("s 111 illus (a)", A, """s 111 Illustration (a): A instigates a child to poison Z's food; the child, by
mistake, poisons Y's food beside it, under the influence of the instigation and as a
probable consequence of it.""",
          **dict(inst, **{"a different act is done": True, "the act done was a probable consequence of the abetment": True,
                          "the act done was committed under the influence of the instigation, or with the aid or in pursuance of the conspiracy which constituted the abetment": True})))
w(fixture("s 111 illus (b)", A, """s 111 Illustration (b): A instigates B to burn Z's house. B also commits theft there.
The theft was a distinct act, and not a probable consequence of the burning.""",
          **dict(inst, **{"a different act is done": True,
                          "the act done was committed under the influence of the instigation, or with the aid or in pursuance of the conspiracy which constituted the abetment": True})))
w(fixture("s 111 illus (c)", A, """s 111 Illustration (c): A instigates B and C to break into a house for robbery and
arms them. Resisted by Z, they murder Z. If that murder was the probable consequence,
A is liable for murder.""",
          **dict(inst, **{"a different act is done": True, "the act done was a probable consequence of the abetment": True,
                          "the act done was committed under the influence of the instigation, or with the aid or in pursuance of the conspiracy which constituted the abetment": True})))
w(fixture("s 112 illus", A, """s 112 Illustration: A instigates B to resist a distress; B does, and also voluntarily
causes grievous hurt to the officer. A knew B was likely to (so the hurt was a probable
consequence). A is liable for each offence.""",
          **dict(inst, **{"a different act is done": True, "the act done was a probable consequence of the abetment": True,
                          "the act done was committed under the influence of the instigation, or with the aid or in pursuance of the conspiracy which constituted the abetment": True,
                          "the act done is committed in addition to the act abetted": True,
                          "the act done constitutes a distinct offence": True})))
w(fixture("s 113 illus", A, """s 113 Illustration: A instigates B to cause grievous hurt to Z; Z dies. If A knew the
grievous hurt was likely to cause death, A is liable for murder.""",
          **dict(inst, **{"the act is abetted with the intention of causing a particular effect": True,
                          "the act causes a different effect from that intended by the abettor": True,
                          "the abettor knew that the act abetted was likely to cause that effect": True})))
w(fixture("s 113 illus, not known", A, "The same, but A did not know death was likely.",
          **dict(inst, **{"the act is abetted with the intention of causing a particular effect": True,
                          "the act causes a different effect from that intended by the abettor": True})))
w(fixture("s 114, present", A, "An instigator who is present when the theft he instigated is committed.",
          **dict(inst, **{"the offence abetted": "theft", "the thing abetted is the commission of an offence": True,
                          "the act abetted is committed": True, "in consequence of the instigation": True,
                          "no express provision is made by this Code for the punishment of such abetment": True,
                          "is present when the act or offence is committed": True})))
w(fixture("s 115 illus", A, """s 115 Illustration: A instigates B to murder Z. The offence is not committed. A shall
be punished with imprisonment up to 20 years, and shall also be liable to fine or caning.""",
          **dict(murder, **inst, **{"the person abetted": "B", "the thing abetted is the commission of an offence": True,
                                     "the manner of the abetment": "by offering him $10,000 to kill one Z",
                                     "that offence is not committed in consequence of the abetment": True})))
w(fixture("s 116 illus (a)", A, "s 116 Illustration (a): A offers a bribe to B, a public servant ... B refuses to accept it.",
          **dict(inst, **{"the person abetted": "B", "the offence abetted": "accepting a gratification as a public servant",
                          "the section punishing the offence abetted": "161",
                          "the thing abetted is the commission of an offence": True,
                          "the offence abetted is punishable with imprisonment": True,
                          "that offence is not committed in consequence of the abetment": True,
                          "no express provision is made by this Code or by any other written law for the punishment of such abetment": True})))
w(fixture("s 116 illus (d)", A, """s 116 Illustration (d): B abets the commission of a robbery by A, a police officer.
The robbery is not committed. B is liable to the same punishment as if he had committed
robbery.""",
          **dict(inst, **{"the person abetted": "A", "the offence abetted": "robbery",
                          "the section punishing the offence abetted": "392",
                          "the thing abetted is the commission of an offence": True,
                          "the offence abetted is punishable with imprisonment": True,
                          "that offence is not committed in consequence of the abetment": True,
                          "no express provision is made by this Code or by any other written law for the punishment of such abetment": True})))
w(fixture("s 116 illus (c)", A, """s 116 Illustration (c): A, a police officer, whose duty it is to prevent robbery,
abets the commission of robbery. The robbery is not committed. A is liable to the
maximum term of imprisonment provided for that offence. (No leaf asks about A's office:
the current s 116(1) gives every such abettor the offence's own punishment - FORK GP-7.)""",
          **dict(inst, **{"the person abetted": "B", "the offence abetted": "robbery",
                          "the section punishing the offence abetted": "392",
                          "the thing abetted is the commission of an offence": True,
                          "the offence abetted is punishable with imprisonment": True,
                          "that offence is not committed in consequence of the abetment": True,
                          "no express provision is made by this Code or by any other written law for the punishment of such abetment": True})))
w(fixture("s 117 illus", A, """s 117 Illustration: A affixes a placard at a worksite where more than 10 persons are
employed, instigating the workers to damage property there if their demand for a pay
rise is not met. A has committed an offence under this section.""",
          **dict(inst, **{"the offence abetted": "mischief", "the section punishing the offence abetted": "426",
                          "the manner of the abetment": "by affixing a placard at the worksite calling on the workers to damage property there",
                          "the thing abetted is the commission of an offence": True,
                          "abets the commission of the offence by a number or class of persons exceeding 10": "`exceeding 10` 11"})))
w(fixture("s 117, ten workers", A, "The same, with exactly 10 workers addressed.",
          **dict(inst, **{"the offence abetted": "mischief", "the thing abetted is the commission of an offence": True,
                          "abets the commission of the offence by a number or class of persons exceeding 10": "`exceeding 10` 10"})))
w(fixture("no abetment", A, "The thing is an offence, but the accused neither instigated, conspired nor aided.",
          **{"the offence abetted": "theft", "the section punishing the offence abetted": "379",
             "the thing abetted is the commission of an offence": True, "the act abetted is committed": True,
             "in consequence of the instigation": True,
             "no express provision is made by this Code for the punishment of such abetment": True}))
w(fixture("s 107(1)(c), aid", A, "Aid under s 107(1)(c) with Explanation 2: A keeps watch while B breaks in, which facilitates the theft.",
          **{"the person abetted": "B", "the offence abetted": "theft", "the section punishing the offence abetted": "379",
             "the aid is intentional": True, "by any act or illegal omission": True,
             "does anything, prior to or at the time of the commission of the act, in order to facilitate its commission": True,
             "thereby facilitates the commission of the act": True,
             "the thing abetted is the commission of an offence": True, "the act abetted is committed": True,
             "with the aid which constitutes the abetment": True,
             "no express provision is made by this Code for the punishment of such abetment": True}))
w(fixture("s 107(1)(c), aid that did not facilitate", A, "The same, but the watch did not in fact facilitate anything (Explanation 2: 'and thereby facilitates').",
          **{"the person abetted": "B", "the offence abetted": "theft", "the section punishing the offence abetted": "379",
             "the aid is intentional": True, "by any act or illegal omission": True,
             "does anything, prior to or at the time of the commission of the act, in order to facilitate its commission": True,
             "the thing abetted is the commission of an offence": True, "the act abetted is committed": True,
             "with the aid which constitutes the abetment": True,
             "no express provision is made by this Code for the punishment of such abetment": True}))
w("""
-- s 107 Explanation 1 Illustration: "B abets by instigation the apprehension of C"
#ASSERT `instigates within section 107` `s 107 illus`
#ASSERT `abets the doing of a thing` `s 107 illus`

-- s 108 Explanation 2 Illustration (a): "A is guilty of abetting B to commit murder"
#ASSERT `abets an offence` `s 108 illus (a)`
-- ... murder was not committed, so not s 109; s 115 (murder is punishable with death)
#ASSERT NOT (`offence under s 109` `s 108 illus (a)`)
#ASSERT `offence under s 115` `s 108 illus (a)`
-- s 108 Explanation 2 Illustration (b): "A is guilty of instigating B to commit murder"
#ASSERT `abets an offence` `s 108 illus (b)`
#ASSERT `offence under s 115` `s 108 illus (b)`

-- s 108 Explanation 3 Illustration (a): "A, whether the act is committed or not, is guilty of abetting an offence"
#ASSERT `abets an offence` `s 108 Expl 3 illus (a)`
-- s 108 Explanation 3 Illustration (b): "A is liable to be punished in the same manner as if B ... had committed murder"
#ASSERT `offence under s 109` `s 108 Expl 3 illus (b)`
-- s 108 Explanation 3 Illustration (d): "A is guilty of abetting theft, and is liable to the same punishment as if B had committed theft"
#ASSERT `offence under s 109` `s 108 Expl 3 illus (d)`
-- s 108 Explanation 4 Illustration: "A is also liable to the same punishment"
#ASSERT `offence under s 109` `s 108 Expl 4 illus`
-- s 108 Explanation 5 Illustration: "C has therefore committed the offence defined in this section, and is liable to the punishment for murder"
#ASSERT `abets the doing of a thing` `s 108 Expl 5 illus`
#ASSERT `offence under s 109` `s 108 Expl 5 illus`
-- s 108A Illustration: "A is guilty of abetting murder"
#ASSERT `abets an offence` `s 108A illus`
-- s 108B: an abetment from abroad of an offence in Singapore is still an abetment
#ASSERT `abets an offence` `s 108B, abetment from abroad`

-- s 109 Illustration (a): "A has abetted the offence defined in section 161"
#ASSERT `offence under s 109` `s 109 illus (a)`
-- s 109 Illustration (b): "A is guilty of abetting that offence, and is liable to the same punishment as B"
#ASSERT `offence under s 109` `s 109 illus (b)`
-- s 109 Illustration (c): "A is guilty of abetting that offence by conspiracy, and is liable to the punishment for murder"
#ASSERT `offence under s 109` `s 109 illus (c)`

-- s 111 Illustration (a): "A is liable in the same manner, and to the same extent, as if he had instigated the child to put the poison into the food of Y"
#ASSERT `liable for the act done within section 111` `s 111 illus (a)`
-- s 111 Illustration (b): "A ... is not guilty of abetting the theft"
#ASSERT NOT (`liable for the act done within section 111` `s 111 illus (b)`)
-- s 111 Illustration (c): "if that murder was the probable consequence of the abetment, A is liable to the punishment provided for murder"
#ASSERT `liable for the act done within section 111` `s 111 illus (c)`
-- s 112 Illustration: "A will also be liable to punishment for each of the offences"
#ASSERT `liable for each of the offences within section 112` `s 112 illus`
-- s 113 Illustration: "if A knew that the grievous hurt abetted was likely to cause death, A is liable to be punished with the punishment provided for murder"
#ASSERT `liable for the effect caused within section 113` `s 113 illus`
#ASSERT NOT (`liable for the effect caused within section 113` `s 113 illus, not known`)
-- s 114: present, so deemed to have committed the offence
#ASSERT `deemed to have committed the offence within section 114` `s 114, present`

-- s 115 Illustration: "A shall be punished with imprisonment for a term that may extend to 20 years, and shall also be liable to fine or to caning"
#ASSERT `offence under s 115` `s 115 illus`
#ASSERT (`charge under s 115` `s 115 illus`)'s punishment EQUALS "imprisonment for a term that may extend to 20 years, and shall also be liable to fine or to caning"
#ASSERT (`charge under s 115` `s 115 illus`)'s text EQUALS "You, A, are charged that you, on or about the 1st day of March 2026, at Block 1 Orchard Road, Singapore, did abet the commission of murder by instigating one B, to wit, by offering him $10,000 to kill one Z, an offence punishable under section 302 with death or imprisonment for life, which offence was not committed in consequence of your abetment, and you have thereby committed an offence punishable under section 115 of the Penal Code 1871."
#ASSERT NOT (`punishable with death or imprisonment for life` `punishment prescribed by s 115`)
#ASSERT `punishable with imprisonment for` 240 `months or upwards within section 41` `punishment prescribed by s 115`
-- s 115 is the express provision s 116's proviso excludes: an abetment of murder not
-- committed is s 115, not s 116 (FORK GP-13)
#ASSERT NOT (`offence under s 116` `s 115 illus`)
#ASSERT NOT (`offence under s 116` `s 108 illus (a)`)
-- s 115 and s 109 are exclusive on the facts: murder committed is s 109
#ASSERT NOT (`offence under s 115` `s 109 illus (c)`)

-- s 116 Illustration (a): "A is punishable under this section for abetting the offence in section 161"
#ASSERT `offence under s 116` `s 116 illus (a)`
-- s 116 Illustration (b): "if B does not give false evidence, A has nevertheless committed the offence defined in this section"
#ASSERT `offence under s 116` `s 109 illus (b), not committed`
#ASSERT NOT (`offence under s 109` `s 109 illus (b), not committed`)
-- s 116 Illustration (c): "though the robbery is not committed, A is liable to the maximum term of imprisonment provided for that offence"
#ASSERT `offence under s 116` `s 116 illus (c)`
#ASSERT (`the punishment under s 116 for abetting an offence punishable with` `s 392 punishment`)'s `maximum term in months` EQUALS (`s 392 punishment`'s `maximum term in months`)
-- s 116 Illustration (d): "B is liable to the same punishment as if he had committed the offence of robbery"
#ASSERT `offence under s 116` `s 116 illus (d)`
-- s 116(2)-(3) over robbery's punishment: minimum terms and strokes go; no fine appears (s 116(3))
#ASSERT (`the punishment under s 116 for abetting an offence punishable with` `s 392 punishment`)'s `minimum term in months` EQUALS NOTHING
#ASSERT (`the punishment under s 116 for abetting an offence punishable with` `s 392 punishment`)'s `minimum strokes` EQUALS NOTHING
#ASSERT (`the punishment under s 116 for abetting an offence punishable with` `s 392 punishment`)'s `maximum term in months` EQUALS JUST 120
#ASSERT (`the punishment under s 116 for abetting an offence punishable with` `s 392 punishment`)'s fine EQUALS `not prescribed`
#ASSERT (`the punishment under s 116 for abetting an offence punishable with` `s 392 punishment`)'s caning EQUALS `or with`
-- ... and an offence with no minimum keeps its punishment, relabelled
#ASSERT (`the punishment under s 116 for abetting an offence punishable with` `s 379 punishment`)'s words EQUALS (`s 379 punishment`'s words)
#ASSERT (`the punishment under s 116 for abetting an offence punishable with` `s 379 punishment`)'s section EQUALS "379 read with 116"
#ASSERT (`the punishment under s 109 for abetting an offence punishable with` `s 379 punishment`)'s section EQUALS "379 read with 109"

-- s 117 Illustration: "A has committed an offence under this section"
#ASSERT `offence under s 117` `s 117 illus`
#ASSERT NOT (`offence under s 117` `s 117, ten workers`)
#ASSERT `exceeding 10` 11
#ASSERT NOT (`exceeding 10` 10)

-- s 107(1)(c) with Explanation 2
#ASSERT `abets the doing of a thing` `s 107(1)(c), aid`
#ASSERT `offence under s 109` `s 107(1)(c), aid`
#ASSERT NOT (`abets the doing of a thing` `s 107(1)(c), aid that did not facilitate`)

-- The s 109 charge, as text (a charge "read with section 109")
#ASSERT (`charge under s 109` `s 109 illus (b)`)'s `made out`
#ASSERT (`charge under s 109` `s 109 illus (b)`)'s section EQUALS "193 read with 109"
#ASSERT (`charge under s 109` `s 109 illus (b)`)'s text EQUALS "You, A, are charged that you, on or about the 1st day of March 2026, at Block 1 Orchard Road, Singapore, did abet the commission of giving false evidence by instigating one B, a witness, to wit, by asking him to testify that he saw Z at the scene, which offence was committed in consequence of your abetment, and you have thereby committed an offence punishable under section 193 read with section 109 of the Penal Code 1871."
#ASSERT (`charge under s 109` `s 107(1)(c), aid`)'s text EQUALS "You, A, are charged that you, on or about the 1st day of March 2026, at Block 1 Orchard Road, Singapore, did abet the commission of theft by intentionally aiding one B, which offence was committed in consequence of your abetment, and you have thereby committed an offence punishable under section 379 read with section 109 of the Penal Code 1871."
-- ... and the refusal, when nothing was done to abet
#ASSERT NOT ((`charge under s 109` `no abetment`)'s `made out`)
#ASSERT (`charge under s 109` `no abetment`)'s text EQUALS ""
#ASSERT (`charge under s 109` `no abetment`)'s refusal EQUALS "A charge under section 379 read with section 109 would assert that the facts fulfil every legal condition of abetment of theft (CPC s 123(5)). On the facts given they do not: instigates any person to do that thing, engages in a conspiracy for its doing, or intentionally aids its doing (section 107); the elements of sections 107 and 108 taken together."
-- the s 116 charge, when the false evidence was not given
#ASSERT (`charge under s 116` `s 109 illus (b), not committed`)'s section EQUALS "193 read with 116"
#ASSERT (`charge under s 116` `s 109 illus (b), not committed`)'s `made out`
#ASSERT (`charge under s 117` `s 117 illus`)'s text EQUALS "You, A, are charged that you, on or about the 1st day of March 2026, at Block 1 Orchard Road, Singapore, did abet the commission of mischief by a number or class of persons exceeding 10, to wit, by affixing a placard at the worksite calling on the workers to damage property there, and you have thereby committed an offence punishable under section 117 of the Penal Code 1871."
""")

K = "Concealment of Design Facts"
w(fixture("s 118 illus", K, """s 118 Illustration: A, knowing that a gang-robbery is about to be committed at B,
falsely informs the police that one is about to be committed at C, and thereby misleads
the police with intent to facilitate the offence. The gang-robbery is committed at B.
A is punishable under this section. (The Illustration treats gang-robbery as an
offence punishable with death or imprisonment for life.)""",
          **{"the offence designed": "gang-robbery", "the section punishing the offence designed": "395",
             "the design": "to commit gang-robbery at B",
             "intending to facilitate the commission of the offence": True,
             "makes a representation which he knows to be false respecting the design": True,
             "the manner of the concealment": "by falsely informing the police that a gang-robbery was about to be committed at C",
             "the offence designed is punishable with death or imprisonment for life": True,
             "the offence designed is punishable with imprisonment": True,
             "the offence designed is committed": True}))
w(fixture("s 118 illus, gang-robbery as s 395 now punishes it", K, """The s 118 Illustration's facts, with the leaf computed from s 395's own punishment
rather than taken from the Illustration (FORK GP-14).""",
          **{"the offence designed": "gang-robbery", "the section punishing the offence designed": "395",
             "the design": "to commit gang-robbery at B",
             "intending to facilitate the commission of the offence": True,
             "makes a representation which he knows to be false respecting the design": True,
             "the offence designed is punishable with death or imprisonment for life": "`punishable with death or imprisonment for life` `s 395 punishment`",
             "the offence designed is punishable with imprisonment": "`punishable with imprisonment` `s 395 punishment`",
             "the offence designed is committed": True}))
w(fixture("s 119 illus", K, """s 119 Illustration: A, a police officer legally bound to give information of all
designs to commit robbery, knowing that B designs to commit robbery, omits to give it,
with intent to facilitate the offence. A has by an illegal omission concealed the
existence of B's design.""",
          **{"the offence designed": "robbery", "the section punishing the offence designed": "392",
             "the design": "of one B to commit robbery",
             "being a public servant": True, "the commission of the offence is his duty as such public servant to prevent": True,
             "intending to facilitate the commission of the offence": True, "voluntarily": True,
             "conceals, by any act or illegal omission, the existence of a design to commit the offence": True,
             "the offence designed is punishable with imprisonment": True}))
w(fixture("s 120, a concealed theft", K, "Knowing it likely to facilitate a theft, A hides his brother's plan to steal; the theft is not committed.",
          **{"the offence designed": "theft", "the section punishing the offence designed": "379",
             "the design": "of one B to commit theft",
             "knowing it to be likely that he will thereby facilitate the commission of the offence": True, "voluntarily": True,
             "conceals, by any act or illegal omission, the existence of a design to commit the offence": True,
             "the offence designed is punishable with imprisonment": True}))
w(fixture("s 120, concealed involuntarily", K, "The same, but the concealment was not voluntary.",
          **{"the offence designed": "theft", "the section punishing the offence designed": "379",
             "knowing it to be likely that he will thereby facilitate the commission of the offence": True,
             "conceals, by any act or illegal omission, the existence of a design to commit the offence": True,
             "the offence designed is punishable with imprisonment": True}))
w("""
-- s 118 Illustration: "A is punishable under this section"
#ASSERT `offence under s 118` `s 118 illus`
#ASSERT (`charge under s 118` `s 118 illus`)'s punishment EQUALS "imprisonment for a term which may extend to 7 years ... and, in either case, shall also be liable to fine"
#ASSERT (`charge under s 118` `s 118 illus`)'s text EQUALS "You, A, are charged that you, on or about the 1st day of March 2026, at Block 1 Orchard Road, Singapore, did, intending to facilitate the commission of gang-robbery, an offence punishable under section 395, make a representation which you knew to be false respecting a design to commit gang-robbery at B, to wit, by falsely informing the police that a gang-robbery was about to be committed at C, which offence was committed, and you have thereby committed an offence punishable under section 118 of the Penal Code 1871."
-- FINDING (FORK GP-14): the s 118 Illustration says "A is punishable under this section",
-- but gang-robbery as s 395 now punishes it is not punishable with death or imprisonment
-- for life. This assertion is the Illustration's conclusion on the Code's current s 395;
-- it is EXPECTED TO FAIL, and is left failing.
#ASSERT `offence under s 118` `s 118 illus, gang-robbery as s 395 now punishes it`
-- ... on those facts it is s 120 that applies
#ASSERT `offence under s 120` `s 118 illus, gang-robbery as s 395 now punishes it`
-- s 119 Illustration: "A ... is liable to punishment according to this section"
#ASSERT `offence under s 119` `s 119 illus`
#ASSERT (`charge under s 119` `s 119 illus`)'s punishment EQUALS "imprisonment for a term which may extend to one-fourth part of the longest term provided for that offence, or with such fine as is provided for that offence, or with both"
-- s 119 is not s 118: robbery is not punishable with death or imprisonment for life
#ASSERT NOT (`offence under s 118` `s 119 illus`)
-- s 120
#ASSERT `offence under s 120` `s 120, a concealed theft`
#ASSERT NOT (`offence under s 120` `s 120, concealed involuntarily`)
#ASSERT (`charge under s 120` `s 120, a concealed theft`)'s punishment EQUALS "if the offence is not committed, to one-eighth of the longest term provided for that offence; or with such fine as is provided for the offence, or with both"
-- one-eighth and one-fourth of theft's 3 years; one-half of robbery's 10
#ASSERT `the fraction` (1/8) `of the longest term provided for` `s 379 punishment` EQUALS 4.5
#ASSERT `the fraction` (1/4) `of the longest term provided for` `s 379 punishment` EQUALS 9
#ASSERT `the fraction` (1/2) `of the longest term provided for` `s 392 punishment` EQUALS 60
-- a fraction of imprisonment for life is refused by name; see it with #EVAL
#EVAL `the fraction` (1/4) `of the longest term provided for` `s 364 punishment`
""")

# --------------------------------------------------------------------------
w("\n§ `Chapter 5A - Criminal conspiracy`\n\n")
Q = "Criminal Conspiracy Facts"
w(fixture("s 120A, an agreement to cheat", Q, "A agrees with B to cheat a bank. No express provision punishes the conspiracy.",
          **{"the other party": "one B", "the offence agreed upon": "cheating", "the section punishing the offence agreed upon": "420",
             "the agreement": "to deceive DBS Bank into releasing a loan of $50,000",
             "agrees with another person": True, "to commit an offence": True,
             "no express provision is made in this Code for the punishment of such a conspiracy": True}))
w(fixture("s 120A(4), an agreement for abroad", Q, "A, in Singapore, agrees with B to commit abroad an act that would be cheating here.",
          **{"the other party": "one B", "the offence agreed upon": "cheating", "the section punishing the offence agreed upon": "420",
             "agrees with another person": True, "is a party in Singapore": True,
             "to commit an act outside Singapore which would constitute an offence if committed in Singapore": True,
             "no express provision is made in this Code for the punishment of such a conspiracy": True}))
w(fixture("s 120A, no agreement", Q, "B proposes the cheat; A never agrees.",
          **{"the other party": "one B", "the offence agreed upon": "cheating", "the section punishing the offence agreed upon": "420",
             "to commit an offence": True,
             "no express provision is made in this Code for the punishment of such a conspiracy": True}))
w("""
#ASSERT `is a party to a criminal conspiracy` `s 120A, an agreement to cheat`
#ASSERT `offence under s 120B` `s 120A, an agreement to cheat`
#ASSERT `is a party to a criminal conspiracy` `s 120A(4), an agreement for abroad`
#ASSERT NOT (`is a party to a criminal conspiracy` `s 120A, no agreement`)
#ASSERT (`charge under s 120B` `s 120A, an agreement to cheat`)'s section EQUALS "120B read with 420"
#ASSERT (`charge under s 120B` `s 120A, an agreement to cheat`)'s text EQUALS "You, A, are charged that you, on or about the 1st day of March 2026, at Block 1 Orchard Road, Singapore, were a party to a criminal conspiracy with one B to commit cheating, to wit, to deceive DBS Bank into releasing a loan of $50,000, and you have thereby committed an offence punishable under section 120B read with section 420 of the Penal Code 1871."
#ASSERT (`charge under s 120B` `s 120A, no agreement`)'s refusal EQUALS "A charge under section 120B read with section 420 would assert that the facts fulfil every legal condition of criminal conspiracy to commit cheating (CPC s 123(5)). On the facts given they do not: agrees with another person; the elements of section 120A taken together."
""")

# --------------------------------------------------------------------------
w("\n§ `Chapter 23 - Attempts`\n\n")
T = "Attempt Facts"
theft = {"the offence attempted": "theft", "the section punishing the offence attempted": "379",
         "the punishment prescribed for the offence attempted": "imprisonment for a term which may extend to 3 years, or with fine, or with both",
         "the offence is punishable by this Code or by any other written law": True,
         "with the intention of committing that offence": True,
         "does an act towards the commission of that offence": True,
         "the act is strongly corroborative of an intention to commit the offence": True,
         "no express provision is made for the punishment of such attempt": True}
w(fixture("s 511 illus (a)", T, """s 511 Illustration (a): A breaks open a box to steal jewels and finds none. He has
taken a substantial step towards theft, and is guilty of attempted theft.""",
          **dict(theft, **{"the particulars of the attempt": "of some jewels, by breaking open a box"})))
w(fixture("s 511 illus (b)", T, "s 511 Illustration (b): A thrusts his hand into Z's empty pocket. A is guilty of attempted theft.", **theft))
w(fixture("s 511 illus (c)", T, """s 511 Illustration (c): A takes from Z's bag a device he believes is Z's; it is in fact
his own, lent to Z. A is guilty of attempted theft.""", **theft))
w(fixture("s 511 illus (d)", T, """s 511 Illustration (d): A memorises Z's safe code to steal the cash, tries several
times and fails. A is guilty of attempted theft.""", **theft))
w(fixture("s 511, a step not corroborative", T, "An act towards the offence that is not strongly corroborative of the intention.",
          **dict(theft, **{"the act is strongly corroborative of an intention to commit the offence": False})))
w(fixture("s 512(1) illus", T, """s 512(1) Illustration: A attempts to kidnap B in order that B may be murdered, and
fails. Kidnapping in order to murder (s 364) is punishable with death or imprisonment
for life. A shall be punished with imprisonment up to 20 years, and shall also be
liable to fine or to caning.""",
          **{"the offence attempted": "kidnapping in order to murder", "the section punishing the offence attempted": "364",
             "the offence is punishable by this Code or by any other written law": True,
             "with the intention of committing that offence": True,
             "does an act towards the commission of that offence": True,
             "the act is strongly corroborative of an intention to commit the offence": True,
             "the offence attempted is punishable with death or imprisonment for life": "`punishable with death or imprisonment for life` `s 364 punishment`",
             "no express provision is made for the punishment of such attempt": True}))
w(fixture("s 512(4) illus", T, """s 512(4) Illustration: A attempts robbery and does not succeed. s 393 makes express
provision for an attempt to commit robbery (FORK GP-10), so the leaf is FALSE here.""",
          **{"the offence attempted": "robbery", "the section punishing the offence attempted": "392",
             "the offence is punishable by this Code or by any other written law": True,
             "with the intention of committing that offence": True,
             "does an act towards the commission of that offence": True,
             "the act is strongly corroborative of an intention to commit the offence": True,
             "the offence attempted is punishable with death or imprisonment for life": "`punishable with death or imprisonment for life` `s 392 punishment`",
             "the punishment prescribed for the offence is fixed by law or a minimum sentence": "`fixed by law or carries a minimum sentence` `s 392 punishment`",
             "no express provision is made for the punishment of such attempt": False}))
w("""
-- s 511 Illustrations (a)-(d): each "is guilty of attempted theft", impossibility notwithstanding (s 511(3))
#ASSERT `attempts to commit an offence` `s 511 illus (a)`
#ASSERT `offence under s 512(2)` `s 511 illus (a)`
#ASSERT `attempts to commit an offence` `s 511 illus (b)`
#ASSERT `offence under s 512(2)` `s 511 illus (b)`
#ASSERT `attempts to commit an offence` `s 511 illus (c)`
#ASSERT `offence under s 512(2)` `s 511 illus (c)`
#ASSERT `attempts to commit an offence` `s 511 illus (d)`
#ASSERT `offence under s 512(2)` `s 511 illus (d)`
-- s 511(2): not strongly corroborative, not a substantial step
#ASSERT NOT (`attempts to commit an offence` `s 511, a step not corroborative`)
-- s 512(1) Illustration
#ASSERT `offence under s 512(1)` `s 512(1) illus`
#ASSERT NOT (`offence under s 512(2)` `s 512(1) illus`)
#ASSERT (`charge under s 512(1)` `s 512(1) illus`)'s punishment EQUALS "imprisonment for a term which may extend to 20 years, and shall also be liable to fine or to caning"
#ASSERT (`charge under s 512(1)` `s 512(1) illus`)'s section EQUALS "364 read with 511"
-- s 512(4) Illustration, on the punishment: not bound by robbery's minimum term or
-- minimum strokes, and no fine ("the court may not sentence A to a fine")
#ASSERT (`the punishment under s 512(2) for attempting an offence punishable with` `s 392 punishment`)'s `minimum term in months` EQUALS NOTHING
#ASSERT (`the punishment under s 512(2) for attempting an offence punishable with` `s 392 punishment`)'s `minimum strokes` EQUALS NOTHING
#ASSERT (`the punishment under s 512(2) for attempting an offence punishable with` `s 392 punishment`)'s caning EQUALS `or with`
#ASSERT (`the punishment under s 512(2) for attempting an offence punishable with` `s 392 punishment`)'s imprisonment EQUALS `or with`
#ASSERT (`the punishment under s 512(2) for attempting an offence punishable with` `s 392 punishment`)'s fine EQUALS `not prescribed`
#ASSERT (`the punishment under s 512(2) for attempting an offence punishable with` `s 392 punishment`)'s `maximum term in months` EQUALS JUST 120
#ASSERT NOT (`fixed by law or carries a minimum sentence` (`the punishment under s 512(2) for attempting an offence punishable with` `s 392 punishment`))
-- s 512(4) Illustration, on the offence: s 393 expressly punishes an attempt to commit
-- robbery, so s 512(2) does not frame it (FORK GP-10)
#ASSERT NOT (`offence under s 512(2)` `s 512(4) illus`)
-- FINDING (FORK GP-10): the s 512(4) Illustration treats attempted robbery as punishable
-- under s 512(2)-(3) ("A may be sentenced to 6 months imprisonment with no caning for
-- attempted robbery"). This assertion is that conclusion on the Code's facts, where
-- s 393 makes express provision; it is EXPECTED TO FAIL, and is left failing.
#ASSERT `offence under s 512(2)` `s 512(4) illus`
-- the charge, as text, and a refusal
#ASSERT (`charge under s 512(2)` `s 511 illus (a)`)'s `made out`
#ASSERT (`charge under s 512(2)` `s 511 illus (a)`)'s section EQUALS "379 read with 511"
#ASSERT (`charge under s 512(2)` `s 511 illus (a)`)'s text EQUALS "You, A, are charged that you, on or about the 1st day of March 2026, at Block 1 Orchard Road, Singapore, did attempt to commit theft of some jewels, by breaking open a box, and you have thereby committed an offence punishable under section 379 read with section 511 of the Penal Code 1871."
#ASSERT (`charge under s 512(2)` `s 511 illus (a)`)'s punishment EQUALS "such punishment as is prescribed for that offence (imprisonment for a term which may extend to 3 years, or with fine, or with both)"
#ASSERT (`charge under s 512(2)` `s 511, a step not corroborative`)'s refusal EQUALS "A charge under section 379 read with section 511 would assert that the facts fulfil every legal condition of attempt to commit theft (CPC s 123(5)). On the facts given they do not: takes a substantial step towards the commission of that offence - an act strongly corroborative of an intention to commit it (section 511(2))."
""")

sys.stdout.write("".join(out))
