#!/usr/bin/env python3
"""Generate vn14-tests-tables.l4: one assertion per edge of every row of the three tables the
document prints, with each expected figure parsed from the raw text, never typed.

  python3 -I tools/gen_table_tests.py ../../source/raw/manulife-group-linked.txt > vn14-tests-tables.l4

Tables: 12.3 (the child Sum Insured ratios, src:666-677), 24.2(e) (the guaranteed rates,
src:1239-1249) and 25.2 (the Policy Administration Charge by calendar year, src:1296-1301,
a rule printed as prose that generates a table). Vietnamese number format: "29.000" is
twenty-nine thousand (the dot groups thousands) and "3,0%" is three point zero percent.
"""
import re
import sys
import unicodedata


def lines(raw, a, b):
    return " ".join(unicodedata.normalize("NFC", raw[k - 1]) for k in range(a, b + 1))


def vn_int(s):
    return int(s.replace(".", ""))


def vn_pct(s):
    return s.replace(",", ".") + "%"


def main():
    raw = open(sys.argv[1], encoding="utf-8").read().split("\n")
    out = []
    w = out.append
    w("@lang en")
    w("IMPORT prelude")
    w("IMPORT daydate")
    w("IMPORT `vn14-nouns`")
    w("IMPORT `vn14-ch2-benefits`")
    w("IMPORT `vn14-ch4-fund-and-charges`")
    w("")
    w("-- GENERATED by tools/gen_table_tests.py from ../../source/raw/manulife-group-linked.txt.")
    w("-- Do not edit by hand: rerun the script. Every expected figure below was parsed from the")
    w("-- raw text by the script; none was copied from an evaluation of the L4.")
    w("")
    w("§ `Tests generated from the tables the document prints`")

    # 12.3
    t = lines(raw, 666, 677)
    pcts = re.findall(r"(\d+)%", t)
    uppers = [int(x) for x in re.findall(r"đến dưới (\d+) Tuổi", t)]
    lowers = [None] + [int(x) for x in re.findall(r"Từ (\d+) Tuổi", t)]
    assert "Từ một (01) tháng Tuổi" in t and len(pcts) == 4 and len(uppers) == 4 and len(lowers) == 4, (pcts, uppers, lowers)
    w("")
    w("§§ `Article 12.3 — one row per age band, both edges (src:666-677)`")
    w("")
    for i, (pct, up) in enumerate(zip(pcts, uppers)):
        lo_m = 1 if i == 0 else 12 * lowers[i]
        hi_m = 12 * up - 1
        for m in (lo_m, hi_m):
            w(f"#ASSERT `12.3 — the adjustment ratio at an age at death, in completed months, of` {m} EQUALS {pct}%")
    under = re.search(r"dưới bốn \((\d+)\)", lines(raw, 659, 662))
    assert under
    w(f"-- 12.3 reaches only a child under four ({int(under.group(1))}): at {12 * int(under.group(1))} months the ratio is 100%.")
    w(f"#ASSERT `12.3 — the adjustment ratio at an age at death, in completed months, of` {12 * int(under.group(1))} EQUALS 100%")
    w("#ASSERT REFUSED `12.3 — the adjustment ratio at an age at death, in completed months, of` 0")

    # 24.2(e)
    t = lines(raw, 1239, 1249)
    years = [int(x) for x in re.findall(r"thứ (\d+)", t)]
    rates = re.findall(r"(\d+,\d+)%", t)
    assert years == [1, 5, 6, 10, 11] and len(rates) == 3, (years, rates)
    w("")
    w("§§ `Article 24.2(e) — one row per band of insurance years, both edges (src:1239-1249)`")
    w("")
    rows = [(years[0], years[1], rates[0]), (years[2], years[3], rates[1]), (years[4], None, rates[2])]
    for lo, hi, r in rows:
        for y in ([lo, hi] if hi else [lo, lo + 1, 40]):
            w(f"#ASSERT `24.2(e) — the guaranteed rate in insurance year` {y} EQUALS {vn_pct(r)}")
    w("#ASSERT REFUSED `24.2(e) — the guaranteed rate in insurance year` 0")

    # 25.2
    t = lines(raw, 1296, 1301)
    m0 = re.search(r"năm dương lịch (\d{4}) là ([\d.]+)", t)
    m1 = re.search(r"tăng ([\d.]+)", t)
    m2 = re.search(r"tối đa ([\d.]+)", t)
    assert m0 and m1 and m2
    y0, base, step, cap = int(m0.group(1)), vn_int(m0.group(2)), vn_int(m1.group(1)), vn_int(m2.group(1))
    w("")
    w(f"§§ `Article 25.2 — the charge for every calendar year {y0} to 2040 (src:1296-1301)`")
    w("")
    w(f"-- Parsed: {base} dong a month in {y0}, rising {step} a year, capped at {cap}.")
    for y in range(y0, 2041):
        fee = min(base + step * (y - y0), cap)
        w(f"#ASSERT `25.2 — the Policy Administration Charge per month in calendar year` {y} `with an approved maximum of` NOTHING EQUALS {fee}")
    w(f"#ASSERT REFUSED `25.2 — the Policy Administration Charge per month in calendar year` {y0 - 1} `with an approved maximum of` NOTHING")
    print("\n".join(out))


if __name__ == "__main__":
    main()
