#!/usr/bin/env python3
"""Generate pru-tests-annex.l4: one #ASSERT per row of the payout-rate annex.
The expected figure is read from the RAW TEXT (the line on which the PDF prints the row's
figure), never typed. Which figure line a row belongs to is given below: for most rows it is
the row's own line; for rows drawn in a shared cell it is the cell's figure line, read from the
page images of PDF pages 23-24 (section 3's grouping cannot be read from the text layout).
Usage: python3 -I gen_annex_tests.py RAW.txt OUT.l4"""
import re, sys
raw = open(sys.argv[1], encoding="utf-8").read().split("\n")
def fig(n):
    m = re.search(r"(\d+)%\s*$", raw[n - 1])
    if not m: raise SystemExit(f"no figure on src line {n}: {raw[n-1]!r}")
    return m.group(1)
def rowtext(n):
    return re.sub(r"\s+", " ", raw[n - 1]).strip()
# (function, constructor expression, row line, figure line, grouping note)
ROWS = [
 ("the table rate for the permanent injury", "`loss of both hands`", 1018, 1021, "cell"),
 ("the table rate for the permanent injury", "`loss of both legs`", 1019, 1021, "cell"),
 ("the table rate for the permanent injury", "`loss of both eyes`", 1020, 1021, "cell"),
 ("the table rate for the permanent injury", "`loss of one hand and one leg`", 1021, 1021, "cell"),
 ("the table rate for the permanent injury", "`loss of one hand and one eye`", 1022, 1021, "cell"),
 ("the table rate for the permanent injury", "`loss of one leg and one eye`", 1023, 1021, "cell"),
 ("the table rate for the permanent injury", "(`brain injury` `a head injury that meets Article 1.19`)", 1024, 1021, "cell"),
 ("the table rate for the permanent injury", "`loss of one hand`", 1025, 1026, "cell"),
 ("the table rate for the permanent injury", "`loss of one leg`", 1026, 1026, "cell"),
 ("the table rate for the permanent injury", "`loss of one eye`", 1027, 1026, "cell"),
 ("the table rate for the permanent injury", "`loss of one thumb`", 1028, 1028, "row"),
 ("the table rate for the permanent injury", "`loss of one finger`", 1029, 1029, "row"),
 ("the table rate for the permanent injury", "`loss of all the fingers of one hand`", 1030, 1030, "row"),
 ("the table rate for the permanent injury", "`loss of one toe`", 1031, 1031, "row"),
 ("the table rate for the internal organ injury", "`pneumothorax or haemothorax from external trauma`", 1039, 1039, "row"),
 ("the table rate for the internal organ injury", "`ruptured spleen`", 1043, 1043, "row"),
 ("the table rate for the internal organ injury", "`ruptured liver`", 1044, 1044, "row"),
 ("the table rate for the internal organ injury", "`perforated stomach, small intestine or colon`", 1045, 1045, "row"),
 ("the table rate for the internal organ injury", "`ruptured pancreas`", 1046, 1046, "row"),
 ("the table rate for the internal organ injury", "`kidney injury with one of the listed conditions`", 1049, 1049, "row"),
 ("the table rate for the internal organ injury", "`torn or severed urethra`", 1052, 1052, "row"),
 ("the table rate for the internal organ injury", "`torn bladder wall`", 1060, 1060, "row"),
 ("the table rate for the internal organ injury", "`severed ureter`", 1061, 1061, "row"),
 ("the table rate for the internal organ injury", "`injury to both kidneys in the same Accident`", 1062, 1062, "row"),
 ("the table rate for a fracture of", "`the spine, except the coccyx`", 1064, 1064, "row"),
 ("the table rate for a fracture of", "`the pelvis`", 1066, 1066, "row"),
 ("the table rate for a fracture of", "`the sternum`", 1068, 1068, "row"),
 ("the table rate for a fracture of", "`one or more leg bones: femur, patella, tibia, fibula`", 1069, 1068, "page image p.24: same cell as the sternum"),
 ("the table rate for a fracture of", "`the clavicle`", 1071, 1073, "page image p.24: 15% cell"),
 ("the table rate for a fracture of", "`the elbow`", 1072, 1073, "page image p.24: 15% cell"),
 ("the table rate for a fracture of", "`a wrist bone`", 1073, 1073, "row"),
 ("the table rate for a fracture of", "`the ankle`", 1074, 1073, "page image p.24: 15% cell"),
 ("the table rate for a fracture of", "`one or more arm bones: humerus, radius, ulna`", 1075, 1073, "page image p.24: 15% cell"),
 ("the table rate for a fracture of", "`a rib`", 1077, 1077, "row"),
 ("the table rate for a fracture of", "`the coccyx`", 1078, 1077, "page image p.24: 10% cell"),
 ("the table rate for a fracture of", "`one or more of: hand, finger, foot, thumb, toe or nose bones, or a bone not listed above`", 1080, 1084, "page image p.24: 2% cell"),
]
# Burn rows: (row line, threshold, third-degree?, figure line)
BURNS = [(1091, 20, True), (1093, 15, True), (1095, 20, False), (1097, 9, True)]
out = []
w = out.append
w("@lang en")
w("IMPORT prelude")
w("IMPORT `pru-nouns`")
w("IMPORT `pru-annex`")
w("IMPORT `pru-general`")
w("")
w("-- GENERATED by tools/gen_annex_tests.py from ../../source/raw/prudential-notes.txt. Do not edit by hand.")
w("-- One assertion per row of the payout-rate annex. Each expected figure is read by the script from")
w("-- the raw-text line on which the PDF prints it; for rows drawn in a shared cell, the cell's figure")
w("-- line was read from the page image (PDF pages 23-24), and the comment says so.")
w("")
w("§ `Annex tests`")
w("")
w("`a head injury that meets Article 1.19` MEANS")
w("    `A head injury` WITH")
w("        `continuous coma, in hours`                                         IS 100")
w("        `Glasgow score of 6 or less throughout 96 hours of hospital treatment` IS TRUE")
w("        `needed life support`                                               IS TRUE")
w("        `coma directly caused by alcohol, an addictive substance or illness` IS FALSE")
w("        `depressed skull fracture`                                          IS FALSE")
w("        `dural tear with acute subdural haematoma shown on CT or MRI`        IS FALSE")
w("        `needed brain surgery`                                              IS FALSE")
w("        `only a linear vault fracture or a skull-base fracture`             IS FALSE")
w("")
w("#ASSERT `Article 1.19 — a brain injury` `a head injury that meets Article 1.19`")
w("")
n = 0
for fn, ctor, row, fl, note in ROWS:
    f = fig(fl)
    w(f"-- row at src line {row}; figure \"{f}%\" read from src line {fl} ({note})")
    w(f"#ASSERT `{fn}` {ctor} EQUALS {f}%")
    n += 1
w("")
w("-- Burns, section 4: each row's threshold, on both sides. The threshold and the figure are read")
w("-- from the row's own line.")
for row, _, third in BURNS:
    t = raw[row - 1]
    th = re.search(r"Ít nhất (\d+)% diện tích", t).group(1)
    f = fig(row)
    deg3 = "third" if third else "second"
    other = "second" if third else "third"
    w(f"-- row at src line {row}: at least {th}% of skin area at {deg3} degree -> {f}%")
    w(f"#ASSERT `the table rate for the burn` (`A burn` WITH `percent of body skin area with {deg3}-degree burns` IS {th}, `percent of body skin area with {other}-degree burns` IS 0) EQUALS {f}%")
    n += 1
w("-- Just below each threshold, the next row down (or nothing) applies.")
w("#ASSERT `the table rate for the burn` (`A burn` WITH `percent of body skin area with third-degree burns` IS 19.9, `percent of body skin area with second-degree burns` IS 0) EQUALS 75%")
w("#ASSERT `the table rate for the burn` (`A burn` WITH `percent of body skin area with third-degree burns` IS 14.9, `percent of body skin area with second-degree burns` IS 0) EQUALS 25%")
w("#ASSERT `the table rate for the burn` (`A burn` WITH `percent of body skin area with third-degree burns` IS 0, `percent of body skin area with second-degree burns` IS 19.9) EQUALS 0")
w("#ASSERT `the table rate for the burn` (`A burn` WITH `percent of body skin area with third-degree burns` IS 8.9, `percent of body skin area with second-degree burns` IS 0) EQUALS 0")
w("")
w("-- The \"one or more\" rows (src 1069, 1075, 1080) and only those.")
for ctor, exp in [("`one or more leg bones: femur, patella, tibia, fibula`", "TRUE"), ("`one or more arm bones: humerus, radius, ulna`", "TRUE"),
                  ("`one or more of: hand, finger, foot, thumb, toe or nose bones, or a bone not listed above`", "TRUE"), ("`a rib`", "FALSE"), ("`the sternum`", "FALSE")]:
    w(f"#ASSERT `the row covers one or more bones` {ctor} EQUALS {exp}")
w("")
open(sys.argv[2], "w", encoding="utf-8").write("\n".join(out) + "\n")
print(f"{n} table rows asserted")
