"""Chapter 8 - Offences relating to unlawful assembly (ss 141-160)."""
from lib import *

HEADER = """-- Singapore Penal Code 1871 - Chapter 8, Offences relating to unlawful assembly
-- (ss 141-160). Part of the state-public group (Chapters 6-10).
--
-- Source: Penal Code 1871, 2020 Revised Edition, SSO current version as at
-- 09 Sep 2026 (inputs/PC1871.txt). Each section's text is quoted above its rules.
--
-- GENERATED by notes/state-public-gen/build.py from the hand-written ladders in
-- notes/state-public-gen/part_assembly.py; edit there and rebuild.
--
-- The shape. s 141 defines an "unlawful assembly"; s 142 a "member" of one;
-- s 146 makes every member guilty of "rioting" when force is used in
-- prosecution of the common object. Those three are predicates over ONE record,
-- `Unlawful Assembly Facts`, and the punishing sections 143, 144, 145, 147 and
-- 148 call them, so each call is one box on the ladder with its own ladder
-- stacked beneath it (the catalogue's `definitionFns`), as robbery calls theft
-- in the reference row. s 149 (constructive liability) is a predicate with no
-- charge of its own: it is "read with" the charge for the offence committed.
-- ss 150-158 each take their own record.
--
-- "unlawful assembly" (s 141) is this group's definition, which other groups
-- read (PLAN section 1): the export is `unlawful assembly within section 141`."""


UA = "Unlawful Assembly Facts"
OBJ_A = "the common object is to overawe by criminal force, or show of criminal force, the Legislative or Executive Government, or any public servant in the exercise of the lawful power of such public servant"
OBJ_B = "the common object is to resist the execution of any law, or of any legal process"
OBJ_C = "the common object is to commit any offence"
OBJ_D = "the common object is, by means of criminal force, or show of criminal force, to any person, to take or obtain possession of any property, or to deprive any person of the enjoyment of a right of way, or of the use of water or other incorporeal right, or to enforce any right or supposed right"
OBJ_E = "the common object is, by means of criminal force, or show of criminal force, to compel any person to do what he is not legally bound to do, or to omit to do what he is legally entitled to do"
ARMED = "armed with any deadly weapon, or with anything which, used as a weapon of offence, is likely to cause death"
ARMED_DESC = "Was the accused armed with a deadly weapon, or with anything which, used as a weapon of offence, is likely to cause death? A wooden pole sharpened at the end is such a thing (s 144 illustration, applied to ss 148 and 158)."


def module():
    out = [HEADER, "", "IMPORT prelude", "IMPORT `pc-domain`", "IMPORT `pc-general`",
           "IMPORT `pc-state-public-common`", "",
           "§ `Chapter 8 - Offences relating to unlawful assembly`", ""]
    A = out.append

    A("§§ `The facts of one assembly - ss 141-149`")
    A("")
    A(facts(UA, "Penal Code 1871 ss 141-149; s 40(3)", [
        ("an assembly of 5 or more persons", "B", "Was it an assembly of 5 or more persons? (Helper: `5 or more persons` over the count.)"),
        (OBJ_A, "B", "(a) Was the common object of the persons composing the assembly to overawe, by criminal force (s 350) or show of criminal force, the Legislative or Executive Government, or a public servant exercising lawful power?"),
        (OBJ_B, "B", "(b) Was the common object to resist the execution of any law or legal process?"),
        (OBJ_C, "B", "(c) Was the common object to commit any offence? By s 40(3), \"offence\" in s 141 includes an offence under another law punishable with imprisonment for 6 months or upwards."),
        (OBJ_D, "B", "(d) Was the common object, by criminal force or show of criminal force, to take or obtain possession of property, to deprive anyone of a right of way, water or other incorporeal right, or to enforce a right or supposed right?"),
        (OBJ_E, "B", "(e) Was the common object, by criminal force or show of criminal force, to compel anyone to do what they are not legally bound to do, or omit what they are legally entitled to do? (Explanation: an assembly lawful when it assembled may later become unlawful - answer as at the time in question.)"),
        ("being aware of facts which render the assembly an unlawful assembly", "B", "s 142: Was the accused aware of the facts which made the assembly an unlawful assembly?"),
        ("intentionally", "B", "s 142: Did the accused join or continue in it intentionally (s 26C)?"),
        ("joins that assembly", "B", "Did the accused join the assembly?"),
        ("continues in it", "B", "Did the accused continue in the assembly?"),
        ("armed", "B", ARMED_DESC),
        ("knowing that such unlawful assembly has been commanded in the manner prescribed by law to disperse", "B", "s 145: Did the accused know the unlawful assembly had been commanded, in the manner prescribed by law, to disperse?"),
        ("force or violence is used by the unlawful assembly or by any member thereof", "B", "s 146: Was force or violence used by the unlawful assembly or by any member of it?"),
        ("in prosecution of the common object of such assembly", "B", "s 146: Was the force or violence used in prosecution of the assembly's common object?"),
        ("an offence is committed by any member of the unlawful assembly", "B", "s 149: Was an offence committed by a member of the unlawful assembly?"),
        ("in prosecution of the common object of that assembly", "B", "s 149: Was that offence committed in prosecution of the assembly's common object?"),
        ("such as the members of that assembly knew to be likely to be committed in prosecution of that object", "B", "s 149: Was that offence one the members knew to be likely to be committed in prosecution of that object?"),
        ("at the time of the committing of that offence, is a member of the same assembly", "B", "s 149: Was the accused a member of the same assembly at the time that offence was committed?"),
        ("the common object", "S", "The common object, as it is to read after \"whose common object was\" - for example \"to cause hurt to one Zainal bin Osman\""),
        ("the weapon", "S", "The weapon, as it is to read after \"being armed with\" - for example \"a parang\"; leave blank if not armed"),
        TO_WIT,
    ]))
    A("")

    # 141
    A(section("141", "Unlawful assembly"))
    A("")
    A(rule("unlawful assembly within section 141", UA,
           "Whether an assembly is an \"unlawful assembly\" within section 141 of the Penal Code 1871",
           f"""        "An"
    AND f's `an assembly of 5 or more persons`
    AND "is designated an 'unlawful assembly', if the common object of the persons composing that assembly is -"
    AND (    f's `{OBJ_A}`
         OR  f's `{OBJ_B}`
         OR  f's `{OBJ_C}`
         OR  f's `{OBJ_D}`
         OR  f's `{OBJ_E}` )"""))
    A("")

    # 142
    A(section("142", "Being a member of an unlawful assembly"))
    A("")
    A(rule("member of an unlawful assembly within section 142", UA,
           "Whether the accused is \"a member of an unlawful assembly\" within section 142 of the Penal Code 1871",
           """        "Whoever, being"
    AND f's `being aware of facts which render the assembly an unlawful assembly`
    AND f's intentionally
    AND (    f's `joins that assembly`
         OR  f's `continues in it` )
    AND "is said to be a member of an"
    AND `unlawful assembly within section 141` f"""))
    A("")

    m_member = [("f's `an assembly of 5 or more persons`", "an assembly of 5 or more persons"),
                (f"f's `{OBJ_A}` OR f's `{OBJ_B}` OR f's `{OBJ_C}` OR f's `{OBJ_D}` OR f's `{OBJ_E}`", "a common object within section 141(a) to (e)"),
                ("f's `being aware of facts which render the assembly an unlawful assembly`", "being aware of facts which render the assembly an unlawful assembly"),
                ("f's intentionally", "intentionally"),
                ("f's `joins that assembly` OR f's `continues in it`", "joins that assembly, or continues in it"),
                ("`member of an unlawful assembly within section 142` f", "the elements of sections 141 and 142 taken together")]
    member_recital = """CONCAT "were a member of an unlawful assembly whose common object was ", f's `the common object`"""

    # 143
    A(section("143", "Punishment"))
    A("")
    A(simple_pun("143", "2 years", 24))
    A("")
    A(rule("offence under s 143", UA,
           "Whether the accused has committed an offence punishable under section 143 of the Penal Code 1871 (being a member of an unlawful assembly)",
           """        "Whoever is a"
    ... `member of an unlawful assembly within section 142` f"""))
    A("")
    A(charge("143", "being a member of an unlawful assembly", "offence under s 143",
             member_recital + """, `the to-wit clause` (f's `to wit`)""", m_member, UA))
    A("")

    # 144
    A(section("144", "Joining an unlawful assembly armed with any deadly weapon"))
    A("")
    A(pun("144", "imprisonment for a term which may extend to 5 years, or with fine, or with caning, or with any combination of such punishments",
          imp="or", mx=60, fine="or", caning="or", both=True))
    A("")
    A(rule("offence under s 144", UA,
           "Whether the accused has committed an offence punishable under section 144 of the Penal Code 1871 (joining an unlawful assembly armed with a deadly weapon)",
           f"""        "Whoever, being"
    AND f's armed
    AND "is a"
    AND `member of an unlawful assembly within section 142` f""",
           comment="FORK SP-144: \"or with any combination of such punishments\" is recorded as\n`or with both` TRUE, the nearest the shared record has."))
    A("")
    A(charge("144", "joining an unlawful assembly armed with a deadly weapon", "offence under s 144",
             """CONCAT "being armed with ", f's `the weapon`, ", which, used as a weapon of offence, was likely to cause death, ", (""" + member_recital + """), `the to-wit clause` (f's `to wit`)""",
             [("f's armed", ARMED)] + m_member, UA))
    A("")

    # 145
    A(section("145", "Joining or continuing in an unlawful assembly, knowing that it has been commanded to disperse"))
    A("")
    A(simple_pun("145", "5 years", 60))
    A("")
    A(rule("offence under s 145", UA,
           "Whether the accused has committed an offence punishable under section 145 of the Penal Code 1871 (joining or continuing in an unlawful assembly knowing it has been commanded to disperse)",
           """        "Whoever"
    AND (    f's `joins that assembly`
         OR  f's `continues in it` )
    AND "in an"
    AND `unlawful assembly within section 141` f
    AND f's `knowing that such unlawful assembly has been commanded in the manner prescribed by law to disperse`"""))
    A("")
    A(charge("145", "joining or continuing in an unlawful assembly, knowing that it has been commanded to disperse", "offence under s 145",
             """CONCAT "did ", (IF f's `joins that assembly` THEN "join" ELSE "continue in"), " an unlawful assembly whose common object was ", f's `the common object`, ", knowing that the said unlawful assembly had been commanded in the manner prescribed by law to disperse", `the to-wit clause` (f's `to wit`)""",
             [("f's `joins that assembly` OR f's `continues in it`", "joins or continues in"),
              ("`unlawful assembly within section 141` f", "an unlawful assembly (section 141)"),
              ("f's `knowing that such unlawful assembly has been commanded in the manner prescribed by law to disperse`", "knowing that such unlawful assembly has been commanded in the manner prescribed by law to disperse")],
             UA))
    A("")

    # 146
    A(section("146", "Force used by one member in prosecution of common object"))
    A("")
    A(rule("guilty of rioting", UA,
           "Whether the accused is guilty of the offence of \"rioting\" within section 146 of the Penal Code 1871",
           """        "Whenever"
    AND f's `force or violence is used by the unlawful assembly or by any member thereof`
    AND f's `in prosecution of the common object of such assembly`
    AND "every"
    AND `member of an unlawful assembly within section 142` f
    AND "is guilty of the offence of rioting\""""))
    A("")

    m_riot = m_member + [("f's `force or violence is used by the unlawful assembly or by any member thereof`", "force or violence is used by the unlawful assembly or by any member thereof"),
                         ("f's `in prosecution of the common object of such assembly`", "in prosecution of the common object of such assembly"),
                         ("`guilty of rioting` f", "the elements of section 146 taken together")]
    riot_recital = member_recital + """, ", and in prosecution of the common object of the said assembly, force or violence was used by the said assembly or a member of it", `the to-wit clause` (f's `to wit`), ", and you were thereby guilty of rioting\""""

    # 147
    A(section("147", "Punishment for rioting"))
    A("")
    A(pun("147", "imprisonment for a term which may extend to 7 years and shall also be liable to caning",
          imp="sh", mx=84, caning="al"))
    A("")
    A(rule("offence under s 147", UA,
           "Whether the accused has committed an offence punishable under section 147 of the Penal Code 1871 (rioting)",
           """        "Whoever is"
    ... `guilty of rioting` f"""))
    A("")
    A(charge("147", "rioting", "offence under s 147", riot_recital, m_riot, UA))
    A("")

    # 148
    A(section("148", "Rioting, armed with a deadly weapon"))
    A("")
    A(pun("148", "imprisonment for a term which may extend to 10 years and shall also be liable to caning",
          imp="sh", mx=120, caning="al"))
    A("")
    A(rule("offence under s 148", UA,
           "Whether the accused has committed an offence punishable under section 148 of the Penal Code 1871 (rioting, armed with a deadly weapon)",
           """        "Whoever is"
    AND `guilty of rioting` f
    AND "being"
    AND f's armed"""))
    A("")
    A(charge("148", "rioting, armed with a deadly weapon", "offence under s 148",
             """CONCAT "being armed with ", f's `the weapon`, ", which, used as a weapon of offence, was likely to cause death, ", (""" + riot_recital + ")",
             m_riot + [("f's armed", ARMED)], UA))
    A("")

    # 149
    A(section("149", "Every member of an unlawful assembly to be deemed guilty of any offence committed in prosecution of common object"))
    A("")
    A(rule("guilty of that offence within section 149", UA,
           "Whether the accused is guilty, by section 149 of the Penal Code 1871, of an offence committed by another member of the same unlawful assembly",
           """        "If"
    AND f's `an offence is committed by any member of the unlawful assembly`
    AND (    f's `in prosecution of the common object of that assembly`
         OR  f's `such as the members of that assembly knew to be likely to be committed in prosecution of that object` )
    AND "every person who,"
    AND f's `at the time of the committing of that offence, is a member of the same assembly`
    AND "that is, a"
    AND `member of an unlawful assembly within section 142` f
    AND "is guilty of that offence\"""",
           comment="No `offence under s 149` and no charge: s 149 punishes nothing of its own. It makes\nthe member guilty of the other offence, which is charged under ITS section \"read with\nsection 149\" (`frame the charge read with`, pc-general). Coverage: deeming rule."))
    A("")

    # 150
    A(section("150", "Hiring, or conniving at hiring, of persons to join an unlawful assembly"))
    A("")
    A(facts("Hiring for Unlawful Assembly Facts", "Penal Code 1871 s 150", [
        ("hires, or engages, or employs", "B", "Did the accused hire, engage or employ a person?"),
        ("promotes or connives at the hiring, engagement, or employment", "B", "Did the accused promote, or connive at, the hiring, engagement or employment of a person?"),
        ("of any person to join or become a member of any unlawful assembly", "B", "Was that person to join, or become a member of, an unlawful assembly?"),
        ("unlawful assembly", "B", "Is (or was) the assembly an unlawful assembly within section 141? (Drill-down: `unlawful assembly within section 141`.)"),
        ("the person hired", "P", "The person hired, as the charge names them"),
        ("the common object", "S", "The common object of the assembly, as it is to read after \"whose common object was\""),
        TO_WIT,
    ]))
    A("")
    A(pun("150", "as a member of such unlawful assembly - under section 143, imprisonment for a term which may extend to 2 years, or with fine, or with both",
          imp="or", mx=24, fine="or", both=True))
    A("")
    A(rule("hires persons to join an unlawful assembly", "Hiring for Unlawful Assembly Facts",
           "Whether the accused hires, or promotes or connives at the hiring of, a person to join an unlawful assembly, within section 150 of the Penal Code 1871",
           """        "Whoever"
    AND (    f's `hires, or engages, or employs`
         OR  f's `promotes or connives at the hiring, engagement, or employment` )
    AND f's `of any person to join or become a member of any unlawful assembly`
    AND f's `unlawful assembly`""",
           comment="FORK SP-150: s 150 makes the hirer \"punishable as a member of such unlawful\nassembly\" - the punishment is s 143's, and it is recorded so. Liability for the\nhireling's further offences \"in the same manner as if he ... himself had committed\nsuch offence\" is charged under that offence's section read with s 150; not built here."))
    A("")
    A(rule("offence under s 150", "Hiring for Unlawful Assembly Facts",
           "Whether the accused has committed an offence punishable under section 150 of the Penal Code 1871 (hiring persons to join an unlawful assembly)",
           """        "Whoever"
    ... `hires persons to join an unlawful assembly` f"""))
    A("")
    A(charge("150", "hiring persons to join an unlawful assembly", "offence under s 150",
             """CONCAT "did ", (IF f's `hires, or engages, or employs` THEN "hire" ELSE "connive at the hiring of"), " ", `one person` (f's `the person hired`), " to join an unlawful assembly whose common object was ", f's `the common object`, `the to-wit clause` (f's `to wit`)""",
             [("f's `hires, or engages, or employs` OR f's `promotes or connives at the hiring, engagement, or employment`", "hires, engages or employs, or promotes or connives at the hiring of"),
              ("f's `of any person to join or become a member of any unlawful assembly`", "any person to join or become a member of any unlawful assembly"),
              ("f's `unlawful assembly`", "an unlawful assembly (section 141)")],
             "Hiring for Unlawful Assembly Facts"))
    A("")

    # 151
    A(section("151", "Knowingly joining or continuing in any assembly of 5 or more persons after it has been commanded to disperse"))
    A("")
    A(facts("Assembly Commanded to Disperse Facts", "Penal Code 1871 s 151", [
        ("knowingly", "B", "Did the accused act knowingly (s 26D)?"),
        ("joins", "B", "Did the accused join the assembly?"),
        ("continues in", "B", "Did the accused continue in the assembly?"),
        ("any assembly of 5 or more persons", "B", "Was it an assembly of 5 or more persons? (Helper: `5 or more persons`.)"),
        ("likely to cause a disturbance of the public peace", "B", "Was the assembly likely to cause a disturbance of the public peace?"),
        ("after such assembly has been lawfully commanded to disperse", "B", "Had the assembly been lawfully commanded to disperse before the accused joined or continued in it?"),
        TO_WIT,
    ]))
    A("")
    A(simple_pun("151", "2 years", 24))
    A("")
    A(rule("joins an assembly commanded to disperse", "Assembly Commanded to Disperse Facts",
           "Whether the accused knowingly joins or continues in an assembly of 5 or more persons likely to disturb the public peace after it has been lawfully commanded to disperse, within section 151 of the Penal Code 1871",
           """        "Whoever"
    AND f's knowingly
    AND (    f's joins
         OR  f's `continues in` )
    AND f's `any assembly of 5 or more persons`
    AND f's `likely to cause a disturbance of the public peace`
    AND f's `after such assembly has been lawfully commanded to disperse`""",
           comment="The Explanation (an unlawful assembly is punishable under s 145) points elsewhere;\nit does not remove the assembly from s 151, so it adds no leaf here (FORK SP-151)."))
    A("")
    A(rule("offence under s 151", "Assembly Commanded to Disperse Facts",
           "Whether the accused has committed an offence punishable under section 151 of the Penal Code 1871 (knowingly joining or continuing in an assembly of 5 or more persons after it has been commanded to disperse)",
           """        "Whoever"
    ... `joins an assembly commanded to disperse` f"""))
    A("")
    A(charge("151", "knowingly joining or continuing in an assembly of 5 or more persons after it has been commanded to disperse", "offence under s 151",
             """CONCAT "did knowingly ", (IF f's joins THEN "join" ELSE "continue in"), " an assembly of 5 or more persons likely to cause a disturbance of the public peace, after such assembly had been lawfully commanded to disperse", `the to-wit clause` (f's `to wit`)""",
             [("f's knowingly", "knowingly"),
              ("f's joins OR f's `continues in`", "joins or continues in"),
              ("f's `any assembly of 5 or more persons`", "an assembly of 5 or more persons"),
              ("f's `likely to cause a disturbance of the public peace`", "likely to cause a disturbance of the public peace"),
              ("f's `after such assembly has been lawfully commanded to disperse`", "after such assembly has been lawfully commanded to disperse")],
             "Assembly Commanded to Disperse Facts"))
    A("")
    A("-- s 151A. [Repealed by Act 51 of 2007]")
    A("")

    # 152
    A(section("152", "Assaulting or obstructing public servant when suppressing riot, etc."))
    A("")
    A(facts("Obstructing Riot Suppression Facts", "Penal Code 1871 s 152", [
        ("assaults", "B", "Did the accused assault the public servant (s 351 - defined in pc-body-a; joined at integration)?"),
        ("threatens to assault", "B", "Did the accused threaten to assault the public servant?"),
        ("obstructs", "B", "Did the accused obstruct the public servant?"),
        ("attempts to obstruct", "B", "Did the accused attempt to obstruct the public servant?"),
        ("uses criminal force to such public servant", "B", "Did the accused use criminal force (s 350 - defined in pc-body-a; joined at integration) on the public servant?"),
        ("threatens or attempts to use criminal force to such public servant", "B", "Did the accused threaten or attempt to use criminal force on the public servant?"),
        PS, THE_PS,
        ("in the discharge of his duty as such public servant in endeavouring to disperse an unlawful assembly or to suppress a riot or an affray", "B", "Was the public servant, in the discharge of duty as such, trying to disperse an unlawful assembly or to suppress a riot or an affray?"),
        TO_WIT,
    ]))
    A("")
    A(simple_pun("152", "8 years", 96))
    A("")
    A(rule("assaults or obstructs a public servant suppressing a riot", "Obstructing Riot Suppression Facts",
           "Whether the accused assaults, obstructs or uses criminal force on a public servant dispersing an unlawful assembly or suppressing a riot or affray, within section 152 of the Penal Code 1871",
           """        "Whoever"
    AND (    f's assaults
         OR  f's `threatens to assault`
         OR  f's obstructs
         OR  f's `attempts to obstruct`
         OR  f's `uses criminal force to such public servant`
         OR  f's `threatens or attempts to use criminal force to such public servant` )
    AND "any"
    AND f's `public servant`
    AND f's `in the discharge of his duty as such public servant in endeavouring to disperse an unlawful assembly or to suppress a riot or an affray`"""))
    A("")
    A(rule("offence under s 152", "Obstructing Riot Suppression Facts",
           "Whether the accused has committed an offence punishable under section 152 of the Penal Code 1871 (assaulting or obstructing a public servant when suppressing a riot)",
           """        "Whoever"
    ... `assaults or obstructs a public servant suppressing a riot` f"""))
    A("")
    A(charge("152", "assaulting or obstructing a public servant when suppressing a riot", "offence under s 152",
             """CONCAT "did ", `joined with` ", and " (concat (LIST (`included if` (f's assaults) "assault"), (`included if` (f's `threatens to assault`) "threaten to assault"), (`included if` (f's obstructs) "obstruct"), (`included if` (f's `attempts to obstruct`) "attempt to obstruct"), (`included if` (f's `uses criminal force to such public servant`) "use criminal force to"), (`included if` (f's `threatens or attempts to use criminal force to such public servant`) "threaten or attempt to use criminal force to"))), " ", `one person` (f's `the public servant`), ", a public servant, in the discharge of ", `possessive pronoun` (f's `the public servant`'s pronoun), " duty as such public servant in endeavouring to disperse an unlawful assembly or to suppress a riot or an affray", `the to-wit clause` (f's `to wit`)""",
             [("f's assaults OR f's `threatens to assault` OR f's obstructs OR f's `attempts to obstruct` OR f's `uses criminal force to such public servant` OR f's `threatens or attempts to use criminal force to such public servant`", "assaults or threatens to assault, obstructs or attempts to obstruct, or uses or threatens or attempts to use criminal force"),
              ("f's `public servant`", "any public servant"),
              ("f's `in the discharge of his duty as such public servant in endeavouring to disperse an unlawful assembly or to suppress a riot or an affray`", "in the discharge of his duty in endeavouring to disperse an unlawful assembly or to suppress a riot or an affray")],
             "Obstructing Riot Suppression Facts"))
    A("")

    # 153
    A(section("153", "Intentionally or rashly giving provocation, with intent to cause riot"))
    A("")
    A(facts("Provocation to Riot Facts", "Penal Code 1871 s 153", [
        ("intentionally", "B", "Did the accused act intentionally (s 26C)?"),
        ("rashly", "B", "Did the accused act rashly (s 26E)?"),
        ("by doing anything which is illegal", "B", "Did the accused do something illegal (s 43)?"),
        ("gives provocation to any person", "B", "Did that give provocation to anyone?"),
        ("intending that such provocation will cause the offence of rioting to be committed", "B", "Did the accused intend the provocation to cause rioting (s 146)?"),
        ("knowing it to be likely that such provocation will cause the offence of rioting to be committed", "B", "Did the accused know the provocation was likely to cause rioting?"),
        ("the offence of rioting is committed in consequence of such provocation", "B", "Was rioting in fact committed in consequence of the provocation? This chooses the punishment (3 years if so, 1 year if not); it is not an element."),
        TO_WIT,
    ]))
    A("")
    A(simple_pun("153", "3 years", 36, name="punishment prescribed by s 153, if the offence of rioting is committed"))
    A("")
    A(simple_pun("153", "one year", 12, name="punishment prescribed by s 153, if the offence of rioting is not committed"))
    A("")
    A(rule("gives provocation with intent to cause riot", "Provocation to Riot Facts",
           "Whether the accused intentionally or rashly, by an illegal act, gives provocation intending or knowing it likely to cause rioting, within section 153 of the Penal Code 1871",
           """        "Whoever"
    AND (    f's intentionally
         OR  f's rashly )
    AND f's `by doing anything which is illegal`
    AND f's `gives provocation to any person`
    AND (    f's `intending that such provocation will cause the offence of rioting to be committed`
         OR  f's `knowing it to be likely that such provocation will cause the offence of rioting to be committed` )"""))
    A("")
    A(rule("offence under s 153", "Provocation to Riot Facts",
           "Whether the accused has committed an offence punishable under section 153 of the Penal Code 1871 (giving provocation with intent to cause riot)",
           """        "Whoever"
    ... `gives provocation with intent to cause riot` f"""))
    A("")
    A(charge("153", "giving provocation with intent to cause riot", "offence under s 153",
             """CONCAT "did ", (IF f's intentionally THEN "intentionally" ELSE "rashly"), ", by doing an illegal act, give provocation, ", (IF f's `intending that such provocation will cause the offence of rioting to be committed` THEN "intending" ELSE "knowing it to be likely"), " that such provocation would cause the offence of rioting to be committed", (IF f's `the offence of rioting is committed in consequence of such provocation` THEN ", and the offence of rioting was committed in consequence of such provocation" ELSE ""), `the to-wit clause` (f's `to wit`)""",
             [("f's intentionally OR f's rashly", "intentionally or rashly"),
              ("f's `by doing anything which is illegal`", "by doing anything which is illegal"),
              ("f's `gives provocation to any person`", "gives provocation to any person"),
              ("f's `intending that such provocation will cause the offence of rioting to be committed` OR f's `knowing it to be likely that such provocation will cause the offence of rioting to be committed`", "intending or knowing it to be likely that such provocation will cause rioting")],
             "Provocation to Riot Facts",
             punexpr="IF f's `the offence of rioting is committed in consequence of such provocation` THEN " + pw("punishment prescribed by s 153, if the offence of rioting is committed") + " ELSE " + pw("punishment prescribed by s 153, if the offence of rioting is not committed")))
    A("")

    # 154
    A(section("154", "Owner or occupier of land on which an unlawful assembly is held"))
    A("")
    A(facts("Land of Unlawful Assembly Facts", "Penal Code 1871 s 154", [
        ("any unlawful assembly or riot takes place", "B", "Did an unlawful assembly (s 141) or riot (s 146) take place?"),
        ("upon the land", "B", "Was it held or committed upon the land in question?"),
        ("owner or occupier of the land", "B", "Is the accused the owner or occupier of the land?"),
        ("any person having or claiming an interest in such land", "B", "Does the accused have or claim an interest in the land?"),
        ("he or his agent or manager, knowing that such offence is being or has been committed", "B", "Did the accused, or the accused's agent or manager, know the offence was being or had been committed?"),
        ("having reason to believe it is likely to be committed", "B", "Did the accused, or the accused's agent or manager, have reason to believe (s 26) it was likely to be committed?"),
        ("do not give the earliest notice thereof in his or their power to the principal officer at the nearest police station", "B", "Did they fail to give the earliest notice in their power to the principal officer at the nearest police station?"),
        ("do not, having reason to believe that it is about to be committed, use all lawful means in his or their power to prevent it", "B", "Having reason to believe it was about to be committed, did they fail to use all lawful means in their power to prevent it?"),
        ("do not, in the event of its taking place, use all lawful means in his or their power to disperse or suppress the riot or unlawful assembly", "B", "When it took place, did they fail to use all lawful means in their power to disperse or suppress it?"),
        TO_WIT,
    ]))
    A("")
    A(pun("154", "fine not exceeding $5,000", fine="sh", maxfine=5000))
    A("")
    A(rule("owner or occupier fails to prevent or report an unlawful assembly", "Land of Unlawful Assembly Facts",
           "Whether the owner or occupier of, or a claimant to, land on which an unlawful assembly or riot takes place is punishable under section 154 of the Penal Code 1871",
           """        "Whenever"
    AND f's `any unlawful assembly or riot takes place`
    AND f's `upon the land`
    AND (    f's `owner or occupier of the land`
         OR  f's `any person having or claiming an interest in such land` )
    AND "shall be punishable ... if"
    AND (    f's `he or his agent or manager, knowing that such offence is being or has been committed`
         OR  f's `having reason to believe it is likely to be committed` )
    AND (    f's `do not give the earliest notice thereof in his or their power to the principal officer at the nearest police station`
         OR  f's `do not, having reason to believe that it is about to be committed, use all lawful means in his or their power to prevent it`
         OR  f's `do not, in the event of its taking place, use all lawful means in his or their power to disperse or suppress the riot or unlawful assembly` )""",
           comment="FORK SP-154: the three duties are cumulative, so failing ANY of them is read as\nthe offence (the section's \"and do not ... and do not\" lists what must all be done)."))
    A("")
    A(rule("offence under s 154", "Land of Unlawful Assembly Facts",
           "Whether the accused has committed an offence punishable under section 154 of the Penal Code 1871 (owner or occupier of land on which an unlawful assembly is held)",
           """        `owner or occupier fails to prevent or report an unlawful assembly` f"""))
    A("")
    A(charge("154", "failure by the owner or occupier of land to report or suppress an unlawful assembly or riot", "offence under s 154",
             """CONCAT "being ", (IF f's `owner or occupier of the land` THEN "the owner or occupier of" ELSE "a person having or claiming an interest in"), " land upon which an unlawful assembly or riot took place, did not ", `joined with` ", or did not " (concat (LIST (`included if` (f's `do not give the earliest notice thereof in his or their power to the principal officer at the nearest police station`) "give the earliest notice thereof in your power to the principal officer at the nearest police station"), (`included if` (f's `do not, having reason to believe that it is about to be committed, use all lawful means in his or their power to prevent it`) "use all lawful means in your power to prevent it"), (`included if` (f's `do not, in the event of its taking place, use all lawful means in his or their power to disperse or suppress the riot or unlawful assembly`) "use all lawful means in your power to disperse or suppress it"))), `the to-wit clause` (f's `to wit`)""",
             [("f's `any unlawful assembly or riot takes place` AND f's `upon the land`", "an unlawful assembly or riot takes place upon the land"),
              ("f's `owner or occupier of the land` OR f's `any person having or claiming an interest in such land`", "owner or occupier of the land, or a person having or claiming an interest in it"),
              ("f's `he or his agent or manager, knowing that such offence is being or has been committed` OR f's `having reason to believe it is likely to be committed`", "knowing that the offence is being or has been committed, or having reason to believe it is likely"),
              ("f's `do not give the earliest notice thereof in his or their power to the principal officer at the nearest police station` OR f's `do not, having reason to believe that it is about to be committed, use all lawful means in his or their power to prevent it` OR f's `do not, in the event of its taking place, use all lawful means in his or their power to disperse or suppress the riot or unlawful assembly`", "does not give the earliest notice, or does not use all lawful means to prevent, disperse or suppress it")],
             "Land of Unlawful Assembly Facts"))
    A("")

    # 155, 156
    RB = "Riot for Benefit Facts"
    A(section("155", "Liability of person for whose benefit a riot is committed"))
    A("")
    A(facts(RB, "Penal Code 1871 ss 155, 156", [
        ("a riot is committed", "B", "Was a riot (s 146) committed?"),
        ("for the benefit or on behalf of the person", "B", "Was it committed for the benefit, or on behalf, of the person concerned?"),
        ("owner or occupier of any land respecting which such riot takes place", "B", "Is that person the owner or occupier of land the riot concerned?"),
        ("claims any interest in such land, or in the subject of any dispute which gave rise to the riot", "B", "Does that person claim an interest in that land, or in the subject of the dispute that gave rise to the riot?"),
        ("has accepted or derived any benefit therefrom", "B", "Has that person accepted or derived any benefit from the riot?"),
        ("the accused is that person", "B", "s 155: Is the accused that person?"),
        ("the accused is the agent or manager of that person", "B", "s 156: Is the accused that person's agent or manager?"),
        ("having reason to believe that such riot was likely to be committed, or that the unlawful assembly by which such riot was committed was likely to be held", "B", "Did the accused (for s 155: or the accused's agent or manager) have reason to believe (s 26) the riot, or the unlawful assembly that committed it, was likely?"),
        ("shall not use all lawful means in his or their power to prevent such riot or assembly from taking place, and for suppressing and dispersing the same", "B", "Did they fail to use all lawful means in their power to prevent the riot or assembly, and to suppress and disperse it?"),
        ("the person", "P", "The person for whose benefit the riot was committed, as the charge names them (for s 156)"),
        TO_WIT,
    ]))
    A("")
    A(pun("155", "fine", fine="sh"))
    A("")
    A(rule("riot committed for the benefit of that person", RB,
           "Whether a riot is committed for the benefit or on behalf of an owner, occupier, claimant or beneficiary, within sections 155 and 156 of the Penal Code 1871",
           """        "Whenever"
    AND f's `a riot is committed`
    AND f's `for the benefit or on behalf of the person`
    AND (    f's `owner or occupier of any land respecting which such riot takes place`
         OR  f's `claims any interest in such land, or in the subject of any dispute which gave rise to the riot`
         OR  f's `has accepted or derived any benefit therefrom` )"""))
    A("")
    A(rule("offence under s 155", RB,
           "Whether the accused has committed an offence punishable under section 155 of the Penal Code 1871 (liability of the person for whose benefit a riot is committed)",
           """        `riot committed for the benefit of that person` f
    AND "such person"
    AND f's `the accused is that person`
    AND "shall be punishable with fine, if he or his agent or manager,"
    AND f's `having reason to believe that such riot was likely to be committed, or that the unlawful assembly by which such riot was committed was likely to be held`
    AND f's `shall not use all lawful means in his or their power to prevent such riot or assembly from taking place, and for suppressing and dispersing the same`"""))
    A("")
    m155 = [("`riot committed for the benefit of that person` f", "a riot committed for the benefit or on behalf of an owner, occupier, claimant or beneficiary"),
            ("f's `having reason to believe that such riot was likely to be committed, or that the unlawful assembly by which such riot was committed was likely to be held`", "having reason to believe that such riot or assembly was likely"),
            ("f's `shall not use all lawful means in his or their power to prevent such riot or assembly from taking place, and for suppressing and dispersing the same`", "not using all lawful means to prevent, suppress and disperse it")]
    A(charge("155", "failure by the person for whose benefit a riot is committed to prevent it", "offence under s 155",
             """CONCAT "being a person for whose benefit a riot was committed, and having reason to believe that such riot was likely to be committed, did not use all lawful means in your power to prevent such riot from taking place, and for suppressing and dispersing the same", `the to-wit clause` (f's `to wit`)""",
             [m155[0], ("f's `the accused is that person`", "the accused is that person")] + m155[1:], RB))
    A("")
    A(section("156", "Liability of agent of owner or occupier for whose benefit a riot is committed"))
    A("")
    A(pun("156", "fine", fine="sh"))
    A("")
    A(rule("offence under s 156", RB,
           "Whether the accused has committed an offence punishable under section 156 of the Penal Code 1871 (liability of the agent of the person for whose benefit a riot is committed)",
           """        `riot committed for the benefit of that person` f
    AND "the"
    AND f's `the accused is the agent or manager of that person`
    AND "shall be punishable with fine, if such agent or manager,"
    AND f's `having reason to believe that such riot was likely to be committed, or that the unlawful assembly by which such riot was committed was likely to be held`
    AND f's `shall not use all lawful means in his or their power to prevent such riot or assembly from taking place, and for suppressing and dispersing the same`"""))
    A("")
    A(charge("156", "failure by the agent or manager of the person for whose benefit a riot is committed to prevent it", "offence under s 156",
             """CONCAT "being the agent or manager of ", `one person` (f's `the person`), ", for whose benefit a riot was committed, and having reason to believe that such riot was likely to be committed, did not use all lawful means in your power to prevent such riot from taking place, and for suppressing and dispersing the same", `the to-wit clause` (f's `to wit`)""",
             [m155[0], ("f's `the accused is the agent or manager of that person`", "the accused is the agent or manager of that person")] + m155[1:], RB))
    A("")

    # 157
    A(section("157", "Harbouring persons hired for an unlawful assembly"))
    A("")
    A(facts("Harbouring Hired Persons Facts", "Penal Code 1871 s 157", [
        ("harbours, receives or assembles any persons", "B", "Did the accused harbour, receive or assemble persons? (\"Harbour\" is defined only for Chapters 6 and 7 (ss 130A, 140A); here it has its ordinary meaning - FORK SP-157.)"),
        ("in any house or premises in his occupation or charge, or under his control", "B", "Was it in a house or premises in the accused's occupation or charge, or under the accused's control?"),
        ("knowing that such persons have been hired, engaged or employed, or are about to be hired, engaged or employed, to join or become members of an unlawful assembly", "B", "Did the accused know those persons had been, or were about to be, hired, engaged or employed to join an unlawful assembly?"),
        ("with the intention of permitting or facilitating them to join or become members of an unlawful assembly", "B", "Did the accused intend to permit or facilitate their joining the unlawful assembly?"),
        ("with the intention of screening them or any of them from punishment", "B", "Did the accused intend to screen them, or any of them, from punishment?"),
        ("the premises", "S", "The house or premises, as it is to read in the charge"),
        TO_WIT,
    ]))
    A("")
    A(simple_pun("157", "2 years", 24))
    A("")
    A(rule("harbours persons hired for an unlawful assembly", "Harbouring Hired Persons Facts",
           "Whether the accused harbours persons hired for an unlawful assembly, within section 157 of the Penal Code 1871",
           """        "Whoever"
    AND f's `harbours, receives or assembles any persons`
    AND f's `in any house or premises in his occupation or charge, or under his control`
    AND f's `knowing that such persons have been hired, engaged or employed, or are about to be hired, engaged or employed, to join or become members of an unlawful assembly`
    AND (    f's `with the intention of permitting or facilitating them to join or become members of an unlawful assembly`
         OR  f's `with the intention of screening them or any of them from punishment` )"""))
    A("")
    A(rule("offence under s 157", "Harbouring Hired Persons Facts",
           "Whether the accused has committed an offence punishable under section 157 of the Penal Code 1871 (harbouring persons hired for an unlawful assembly)",
           """        "Whoever"
    ... `harbours persons hired for an unlawful assembly` f"""))
    A("")
    A(charge("157", "harbouring persons hired for an unlawful assembly", "offence under s 157",
             """CONCAT "did harbour, in ", f's `the premises`, ", under your control, persons, knowing that such persons had been hired to join an unlawful assembly, with the intention of ", (IF f's `with the intention of permitting or facilitating them to join or become members of an unlawful assembly` THEN "permitting or facilitating them to join such unlawful assembly" ELSE "screening them from punishment"), `the to-wit clause` (f's `to wit`)""",
             [("f's `harbours, receives or assembles any persons`", "harbours, receives or assembles any persons"),
              ("f's `in any house or premises in his occupation or charge, or under his control`", "in any house or premises in his occupation or charge, or under his control"),
              ("f's `knowing that such persons have been hired, engaged or employed, or are about to be hired, engaged or employed, to join or become members of an unlawful assembly`", "knowing that such persons have been or are about to be hired to join an unlawful assembly"),
              ("f's `with the intention of permitting or facilitating them to join or become members of an unlawful assembly` OR f's `with the intention of screening them or any of them from punishment`", "with the intention of permitting or facilitating their joining, or of screening them from punishment")],
             "Harbouring Hired Persons Facts"))
    A("")

    # 158
    A(section("158", "Being hired to take part in an unlawful assembly or riot"))
    A("")
    A(facts("Hired for Unlawful Assembly Facts", "Penal Code 1871 s 158", [
        ("is engaged or hired", "B", "Was the accused engaged or hired?"),
        ("offers or attempts to be hired or engaged", "B", "Did the accused offer, or attempt, to be hired or engaged?"),
        ("to do or assist in doing any of the acts specified in section 141", "B", "Was it to do, or assist in doing, any of the acts specified in section 141 (the common objects (a) to (e))?"),
        ("goes armed, or engages or offers to go armed, with any deadly weapon, or with anything which used as a weapon of offence is likely to cause death", "B", "Did the accused, being so hired, go armed - or engage or offer to go armed - with a deadly weapon, or anything which used as a weapon of offence is likely to cause death (s 144 illustration: a sharpened wooden pole)? This chooses the higher punishment."),
        ("the acts", "S", "The acts the accused was hired to do, as they are to read in the charge"),
        TO_WIT,
    ]))
    A("")
    A(simple_pun("158", "2 years", 24))
    A("")
    A(simple_pun("158", "5 years", 60, name="punishment prescribed by s 158, where the person so hired goes armed"))
    A("")
    A(rule("is hired to take part in an unlawful assembly", "Hired for Unlawful Assembly Facts",
           "Whether the accused is hired, or offers to be hired, to do any of the acts specified in section 141, within section 158 of the Penal Code 1871",
           """        "Whoever"
    AND (    f's `is engaged or hired`
         OR  f's `offers or attempts to be hired or engaged` )
    AND f's `to do or assist in doing any of the acts specified in section 141`"""))
    A("")
    A(rule("offence under s 158", "Hired for Unlawful Assembly Facts",
           "Whether the accused has committed an offence punishable under section 158 of the Penal Code 1871 (being hired to take part in an unlawful assembly or riot)",
           """        "Whoever"
    ... `is hired to take part in an unlawful assembly` f"""))
    A("")
    A(charge("158", "being hired to take part in an unlawful assembly or riot", "offence under s 158",
             """CONCAT "did ", (IF f's `is engaged or hired` THEN "engage to be hired" ELSE "offer to be hired"), " to do ", f's `the acts`, ", being acts specified in section 141 of the Penal Code 1871", (IF f's `goes armed, or engages or offers to go armed, with any deadly weapon, or with anything which used as a weapon of offence is likely to cause death` THEN ", and, being so hired, did go armed with a weapon of offence likely to cause death" ELSE ""), `the to-wit clause` (f's `to wit`)""",
             [("f's `is engaged or hired` OR f's `offers or attempts to be hired or engaged`", "is engaged or hired, or offers or attempts to be"),
              ("f's `to do or assist in doing any of the acts specified in section 141`", "to do or assist in doing any of the acts specified in section 141")],
             "Hired for Unlawful Assembly Facts",
             punexpr="IF f's `goes armed, or engages or offers to go armed, with any deadly weapon, or with anything which used as a weapon of offence is likely to cause death` THEN " + pw("punishment prescribed by s 158, where the person so hired goes armed") + " ELSE " + pw("punishment prescribed by s 158")))
    A("")
    A("-- s 159. [Repealed by Act 51 of 2007]")
    A("-- s 160. [Repealed by Act 51 of 2007]")
    A("")
    return "\n".join(out)


def tests():
    T = []
    A = T.append
    A("§ `Chapter 8 - tests`")
    A("")
    A("§§ `s 141 - the 5-person threshold`")
    A("-- s 141 \"an assembly of 5 or more persons\": both sides of the line")
    A("#ASSERT `5 or more persons` 5")
    A("#ASSERT NOT `5 or more persons` 4")
    A("#ASSERT `5 or more persons` 6")
    A("")
    rioters = ["an assembly of 5 or more persons", OBJ_C, "being aware of facts which render the assembly an unlawful assembly",
               "intentionally", "joins that assembly"]
    A("§§ `ss 141-149 - the riot`")
    A(fixture("the riot", UA,
              [f"an assembly of 5 or more persons" if False else "an assembly of 5 or more persons"] + rioters[1:] +
              ["force or violence is used by the unlawful assembly or by any member thereof", "in prosecution of the common object of such assembly"],
              {"the common object": "to cause hurt to one Zainal bin Osman", "to wit": "by one or more of you punching and kicking the said Zainal bin Osman"},
              comment="Six men gather to beat Z; the accused knowingly joins them; one of them punches Z."))
    A(fixture("the riot, with the count below 5", UA,
              rioters[1:] + ["force or violence is used by the unlawful assembly or by any member thereof", "in prosecution of the common object of such assembly"],
              {"the common object": "to cause hurt to one Zainal bin Osman"},
              comment="The same, where only four gathered (`5 or more persons` 4 is FALSE)."))
    A(fixture("the riot, armed", UA,
              rioters + ["armed", "force or violence is used by the unlawful assembly or by any member thereof", "in prosecution of the common object of such assembly"],
              {"the common object": "to cause hurt to one Zainal bin Osman", "the weapon": "a wooden pole sharpened at the end"},
              comment="s 144 illus (applied to s 148): a wooden pole sharpened at the end is a thing which, used as a\nweapon of offence, is likely to cause death - so the `armed` leaf is TRUE for it."))
    A(fixture("a lawful gathering", UA, ["an assembly of 5 or more persons", "being aware of facts which render the assembly an unlawful assembly", "intentionally", "joins that assembly"],
              comment="Five or more persons, but no common object within s 141(a)-(e)."))
    A(fixture("an unwitting member", UA, ["an assembly of 5 or more persons", OBJ_C, "intentionally", "joins that assembly"],
              comment="s 142: the accused joins without being aware of the facts that make the assembly unlawful."))
    A("#ASSERT `unlawful assembly within section 141` `the riot`")
    A("#ASSERT NOT `unlawful assembly within section 141` `the riot, with the count below 5`")
    A("#ASSERT NOT `unlawful assembly within section 141` `a lawful gathering`")
    A("#ASSERT `member of an unlawful assembly within section 142` `the riot`")
    A("#ASSERT NOT `member of an unlawful assembly within section 142` `an unwitting member`")
    A("#ASSERT `offence under s 143` `the riot`")
    A("#ASSERT NOT `offence under s 143` `an unwitting member`")
    A("#ASSERT NOT `offence under s 144` `the riot`")
    A("-- s 144 illus")
    A("#ASSERT `offence under s 144` `the riot, armed`")
    A("#ASSERT `guilty of rioting` `the riot`")
    A("#ASSERT `offence under s 147` `the riot`")
    A("#ASSERT NOT `offence under s 147` `the riot, with the count below 5`")
    A("#ASSERT NOT `offence under s 148` `the riot`")
    A("-- s 148 illus (\"subject to the same illustration as section 144\")")
    A("#ASSERT `offence under s 148` `the riot, armed`")
    A("#ASSERT (`charge under s 147` `the riot`)'s text EQUALS \"You, Tan Ah Kow, are charged that you, on or about the 3rd day of March 2026, at about 10.15 am, at Block 123 Ang Mo Kio Avenue 3, Singapore, were a member of an unlawful assembly whose common object was to cause hurt to one Zainal bin Osman, and in prosecution of the common object of the said assembly, force or violence was used by the said assembly or a member of it, to wit, by one or more of you punching and kicking the said Zainal bin Osman, and you were thereby guilty of rioting, and you have thereby committed an offence punishable under section 147 of the Penal Code 1871.\"")
    A("#ASSERT (`charge under s 147` `the riot`)'s punishment EQUALS \"imprisonment for a term which may extend to 7 years and shall also be liable to caning\"")
    A("#ASSERT (`charge under s 147` `the riot, with the count below 5`)'s refusal EQUALS \"A charge under section 147 would assert that the facts fulfil every legal condition of rioting (CPC s 123(5)). On the facts given they do not: an assembly of 5 or more persons; the elements of sections 141 and 142 taken together; the elements of section 146 taken together.\"")
    A("-- s 147 prescribes a maximum term, so s 41 can be applied to it")
    A("#ASSERT `punishable with imprisonment for` 84 `months or upwards within section 41` `punishment prescribed by s 147`")
    A("")
    A("§§ `s 145, s 149`")
    A(fixture("stayed after the order to disperse", UA,
              ["an assembly of 5 or more persons", OBJ_B, "continues in it", "knowing that such unlawful assembly has been commanded in the manner prescribed by law to disperse"],
              {"the common object": "to resist the execution of a writ of possession"}))
    A("#ASSERT `offence under s 145` `stayed after the order to disperse`")
    A(fixture("a member when the other hit Z", UA,
              rioters + ["an offence is committed by any member of the unlawful assembly",
                         "such as the members of that assembly knew to be likely to be committed in prosecution of that object",
                         "at the time of the committing of that offence, is a member of the same assembly"],
              comment="s 149: another member causes hurt to Z, an offence the members knew likely in prosecution of\nthe common object; the accused was a member at the time."))
    A("#ASSERT `guilty of that offence within section 149` `a member when the other hit Z`")
    A("#ASSERT NOT `guilty of that offence within section 149` `the riot`")
    A("")
    A("§§ `ss 150-158`")
    A(fixture("150: paying the gang", "Hiring for Unlawful Assembly Facts",
              ["hires, or engages, or employs", "of any person to join or become a member of any unlawful assembly", "unlawful assembly"]))
    A("#ASSERT `offence under s 150` `150: paying the gang`")
    A(fixture("151: a crowd told to disperse", "Assembly Commanded to Disperse Facts",
              ["knowingly", "joins", "any assembly of 5 or more persons", "likely to cause a disturbance of the public peace", "after such assembly has been lawfully commanded to disperse"]))
    A("#ASSERT `offence under s 151` `151: a crowd told to disperse`")
    A(fixture("152: pushing the riot police", "Obstructing Riot Suppression Facts",
              ["obstructs", "public servant", "in the discharge of his duty as such public servant in endeavouring to disperse an unlawful assembly or to suppress a riot or an affray"],
              {}, {"the public servant": "`Sergeant Lim`"}))
    A("#ASSERT `offence under s 152` `152: pushing the riot police`")
    A("#ASSERT (`charge under s 152` `152: pushing the riot police`)'s text EQUALS \"You, Tan Ah Kow, are charged that you, on or about the 3rd day of March 2026, at about 10.15 am, at Block 123 Ang Mo Kio Avenue 3, Singapore, did obstruct one Lim Ah Seng, a police officer attached to Ang Mo Kio Police Division, a public servant, in the discharge of his duty as such public servant in endeavouring to disperse an unlawful assembly or to suppress a riot or an affray, and you have thereby committed an offence punishable under section 152 of the Penal Code 1871.\"")
    A(fixture("153: provocation, riot follows", "Provocation to Riot Facts",
              ["rashly", "by doing anything which is illegal", "gives provocation to any person",
               "knowing it to be likely that such provocation will cause the offence of rioting to be committed", "the offence of rioting is committed in consequence of such provocation"]))
    A(fixture("153: provocation, no riot", "Provocation to Riot Facts",
              ["rashly", "by doing anything which is illegal", "gives provocation to any person",
               "knowing it to be likely that such provocation will cause the offence of rioting to be committed"]))
    A("-- s 153: the offence is the same; the punishment turns on whether rioting followed")
    A("#ASSERT `offence under s 153` `153: provocation, riot follows`")
    A("#ASSERT `offence under s 153` `153: provocation, no riot`")
    A("#ASSERT (`charge under s 153` `153: provocation, riot follows`)'s punishment EQUALS \"imprisonment for a term which may extend to 3 years, or with fine, or with both\"")
    A("#ASSERT (`charge under s 153` `153: provocation, no riot`)'s punishment EQUALS \"imprisonment for a term which may extend to one year, or with fine, or with both\"")
    A(fixture("154: silent landlord", "Land of Unlawful Assembly Facts",
              ["any unlawful assembly or riot takes place", "upon the land", "owner or occupier of the land",
               "he or his agent or manager, knowing that such offence is being or has been committed",
               "do not give the earliest notice thereof in his or their power to the principal officer at the nearest police station"]))
    A("#ASSERT `offence under s 154` `154: silent landlord`")
    A(fixture("155: riot for the claimant", "Riot for Benefit Facts",
              ["a riot is committed", "for the benefit or on behalf of the person", "claims any interest in such land, or in the subject of any dispute which gave rise to the riot",
               "the accused is that person",
               "having reason to believe that such riot was likely to be committed, or that the unlawful assembly by which such riot was committed was likely to be held",
               "shall not use all lawful means in his or their power to prevent such riot or assembly from taking place, and for suppressing and dispersing the same"]))
    A("#ASSERT `offence under s 155` `155: riot for the claimant`")
    A("-- the same facts do not make out s 156, which is the AGENT's offence")
    A("#ASSERT NOT `offence under s 156` `155: riot for the claimant`")
    A(fixture("157: the safe house", "Harbouring Hired Persons Facts",
              ["harbours, receives or assembles any persons", "in any house or premises in his occupation or charge, or under his control",
               "knowing that such persons have been hired, engaged or employed, or are about to be hired, engaged or employed, to join or become members of an unlawful assembly",
               "with the intention of screening them or any of them from punishment"]))
    A("#ASSERT `offence under s 157` `157: the safe house`")
    A(fixture("158: hired and armed", "Hired for Unlawful Assembly Facts",
              ["is engaged or hired", "to do or assist in doing any of the acts specified in section 141",
               "goes armed, or engages or offers to go armed, with any deadly weapon, or with anything which used as a weapon of offence is likely to cause death"],
              comment="s 158 illus (\"subject to the same illustration as section 144\"): armed with a sharpened wooden pole."))
    A("-- s 158 illus")
    A("#ASSERT `offence under s 158` `158: hired and armed`")
    A("#ASSERT (`charge under s 158` `158: hired and armed`)'s punishment EQUALS \"imprisonment for a term which may extend to 5 years, or with fine, or with both\"")
    A("")
    return "\n".join(T)
