"""Chapters 6 (Offences against the State), 6A (Piracy), 6B (Genocide), 7 (Armed forces): ss 121-140B."""
from lib import *

HEADER = """-- Singapore Penal Code 1871 - Chapter 6 (Offences against the State, ss 121-130A),
-- Chapter 6A (Piracy, ss 130B-130C), Chapter 6B (Genocide, ss 130D-130E) and
-- Chapter 7 (Offences relating to the armed forces, ss 131-140B). Part of the
-- state-public group (Chapters 6-10).
--
-- Source: Penal Code 1871, 2020 Revised Edition, SSO current version as at
-- 09 Sep 2026 (inputs/PC1871.txt). Each section's text is quoted above its rules.
--
-- GENERATED by notes/state-public-gen/build.py from the hand-written ladders in
-- notes/state-public-gen/part_state.py; edit there and rebuild.
--
-- Many of these sections are abetment offences ("whoever abets ..."): "abets"
-- is s 107's word (pc-general-part), carried as a flat leaf and joined at
-- integration. ss 130A and 140A define "harbour" for their own Chapter only;
-- s 140B carries Chapter 7 over to the Singapore Police Force, and is encoded
-- as an OR beside every "officer or serviceman" leaf, cited."""

ARMED_MEMBER = ("an officer or a serviceman in the Singapore Armed Forces or any visiting forces lawfully present in Singapore", "B",
                "Is (or was) the person concerned an officer or a serviceman in the Singapore Armed Forces, or in any visiting forces lawfully present in Singapore?")
POLICE_MEMBER = ("a member of the Singapore Police Force or any volunteer, auxiliary or special force attached to it", "B",
                 "s 140B: Is (or was) the person concerned a member of the Singapore Police Force, or of a volunteer, auxiliary or special force attached to or under its jurisdiction? Chapter 7 applies to them \"with the necessary modifications\".")
MEMBER_LADDER = f"""(    f's `{ARMED_MEMBER[0]}`
         OR  f's `{POLICE_MEMBER[0]}` )"""
MEMBER_EXPR = f"f's `{ARMED_MEMBER[0]}` OR f's `{POLICE_MEMBER[0]}`"


def life_or_term(sec, years, fine_if_not_life=True, name=None, death=False):
    words = ("death or with imprisonment for life, or with " if death else "imprisonment for life or ") + \
        f"for a term which may extend to {years} years"
    return words


def module():
    out = [HEADER, "", "IMPORT prelude", "IMPORT `pc-domain`", "IMPORT `pc-general`",
           "IMPORT `pc-state-public-common`", "",
           "§ `Chapter 6 - Offences against the State`", ""]
    A = out.append

    # 121
    A(section("121", "Waging or attempting to wage war or abetting the waging of war against the Government"))
    A("")
    WW = "Waging War Facts"
    A(facts(WW, "Penal Code 1871 s 121", [
        ("wages war against the Government", "B", "Did the accused wage war against the Government? Joining an insurrection against the Government is waging war (s 121 illustration)."),
        ("attempts to wage such war", "B", "Did the accused attempt to wage such war?"),
        ("abets the waging of such war", "B", "Did the accused abet the waging of such war (s 107 - pc-general-part; joined at integration)?"),
        TO_WIT,
    ]))
    A("")
    A(pun("121", "death, or with imprisonment for life", death="or", life="or"))
    A("")
    A(rule("wages, attempts or abets war against the Government", WW,
           "Whether the accused wages, attempts to wage, or abets the waging of war against the Government, within section 121 of the Penal Code 1871",
           """        "Whoever"
    AND (    f's `wages war against the Government`
         OR  f's `attempts to wage such war`
         OR  f's `abets the waging of such war` )""",
           comment="Not named `wages war against the Government`: that is the first leaf's name, and a\nrule named like a field of its own input silently calls ITSELF where the ladder reads\nthe field - measured: `assertion could not be evaluated: Stack overflow`, no other\ndiagnostic. notes/state-public-forks.md SP-0."))
    A("")
    A(rule("offence under s 121", WW,
           "Whether the accused has committed an offence punishable under section 121 of the Penal Code 1871 (waging war against the Government)",
           """        "Whoever"
    ... `wages, attempts or abets war against the Government` f"""))
    A("")
    A(charge("121", "waging or attempting to wage war or abetting the waging of war against the Government", "offence under s 121",
             """CONCAT "did ", `joined with` ", or " (concat (LIST (`included if` (f's `wages war against the Government`) "wage war"), (`included if` (f's `attempts to wage such war`) "attempt to wage war"), (`included if` (f's `abets the waging of such war`) "abet the waging of war"))), " against the Government", `the to-wit clause` (f's `to wit`)""",
             [("f's `wages war against the Government` OR f's `attempts to wage such war` OR f's `abets the waging of such war`", "wages war against the Government, or attempts to wage, or abets the waging of, such war")],
             WW))
    A("")

    # 121A-121C
    PP = "Plot against the President Facts"
    A(section("121A", "Offences against the President's person"))
    A("")
    A(facts(PP, "Penal Code 1871 ss 121A, 121B, 121C", [
        ("plans the death of or hurt to or unlawful imprisonment or restraint of the President", "B", "s 121A: Did the accused plan the death of, hurt to, or unlawful imprisonment or restraint of the President?"),
        ("plans the unlawful deprivation or deposition of the President from the sovereignty of Singapore", "B", "s 121B: Did the accused plan the unlawful deprivation or deposition of the President from the sovereignty of Singapore?"),
        ("plans the overawing by criminal force of the Government", "B", "s 121B: Did the accused plan the overawing of the Government by criminal force (s 350)?"),
        ("abets the commission of any of the offences punishable by section 121A or 121B", "B", "s 121C: Did the accused abet (s 107) the commission of an offence punishable by s 121A or 121B?"),
        TO_WIT,
    ]))
    A("")
    A(pun("121A", "imprisonment for life or for a term which may extend to 20 years and shall, if he is not sentenced to imprisonment for life, also be liable to fine",
          life="or", imp="or", mx=240, fine="al"))
    A("")
    A(rule("offence under s 121A", PP,
           "Whether the accused has committed an offence punishable under section 121A of the Penal Code 1871 (offences against the President's person)",
           """        "Whoever"
    ... f's `plans the death of or hurt to or unlawful imprisonment or restraint of the President`""",
           comment="ss 121A-121D each define and punish in one clause with a single element group;\nthe offence ladder is the defining predicate."))
    A("")
    A(charge("121A", "offences against the President's person", "offence under s 121A",
             """CONCAT "did plan the death of or hurt to or unlawful imprisonment or restraint of the President", `the to-wit clause` (f's `to wit`)""",
             [("f's `plans the death of or hurt to or unlawful imprisonment or restraint of the President`", "plans the death of or hurt to or unlawful imprisonment or restraint of the President")], PP))
    A("")
    A(section("121B", "Offences against authority"))
    A("")
    A(pun("121B", "imprisonment for life or for a term which may extend to 20 years and shall, if he is not sentenced to imprisonment for life, also be liable to fine",
          life="or", imp="or", mx=240, fine="al"))
    A("")
    A(rule("offence under s 121B", PP,
           "Whether the accused has committed an offence punishable under section 121B of the Penal Code 1871 (offences against authority)",
           """        "Whoever"
    AND (    f's `plans the unlawful deprivation or deposition of the President from the sovereignty of Singapore`
         OR  f's `plans the overawing by criminal force of the Government` )"""))
    A("")
    A(charge("121B", "offences against authority", "offence under s 121B",
             """CONCAT "did plan ", (IF f's `plans the unlawful deprivation or deposition of the President from the sovereignty of Singapore` THEN "the unlawful deprivation or deposition of the President from the sovereignty of Singapore" ELSE "the overawing by criminal force of the Government"), `the to-wit clause` (f's `to wit`)""",
             [("f's `plans the unlawful deprivation or deposition of the President from the sovereignty of Singapore` OR f's `plans the overawing by criminal force of the Government`", "plans the unlawful deprivation or deposition of the President, or the overawing by criminal force of the Government")], PP))
    A("")
    A(section("121C", "Abetting offences under section 121A or 121B"))
    A("")
    A(pun("121C", "the punishment provided for those offences - under sections 121A and 121B, imprisonment for life or for a term which may extend to 20 years and, if not sentenced to imprisonment for life, also liable to fine",
          life="or", imp="or", mx=240, fine="al"))
    A("")
    A(rule("offence under s 121C", PP,
           "Whether the accused has committed an offence punishable under section 121C of the Penal Code 1871 (abetting an offence under section 121A or 121B)",
           """        "Whoever"
    ... f's `abets the commission of any of the offences punishable by section 121A or 121B`""",
           comment="FORK SP-121C: the punishment is \"the punishment provided for those offences\",\nwhich ss 121A and 121B state identically; recorded as theirs."))
    A("")
    A(charge("121C", "abetting an offence under section 121A or 121B", "offence under s 121C",
             """CONCAT "did abet the commission of an offence punishable by section 121A or 121B of the Penal Code 1871", `the to-wit clause` (f's `to wit`)""",
             [("f's `abets the commission of any of the offences punishable by section 121A or 121B`", "abets the commission of an offence punishable by section 121A or 121B")], PP))
    A("")

    # 121D
    OI = "Omission to Inform of Offence against the State Facts"
    A(section("121D", "Intentional omission to give information of offences against section 121, 121A, 121B or 121C by a person bound to inform"))
    A("")
    A(facts(OI, "Penal Code 1871 s 121D", [
        ("knowing that any offence punishable under section 121, 121A, 121B or 121C has been committed", "B", "Did the accused know that an offence punishable under s 121, 121A, 121B or 121C had been committed?"),
        ("having reason to believe that any offence punishable under section 121, 121A, 121B or 121C has been committed", "B", "Did the accused have reason to believe (s 26) that such an offence had been committed?"),
        ("intentionally", "B", "Did the accused act intentionally (s 26C)?"),
        ("omits to give any information respecting that offence which he is legally bound to give", "B", "Did the accused fail to give information about that offence which the accused was legally bound (s 43) to give?"),
        TO_WIT,
    ]))
    A("")
    A(simple_pun("121D", "10 years", 120))
    A("")
    A(rule("offence under s 121D", OI,
           "Whether the accused has committed an offence punishable under section 121D of the Penal Code 1871 (intentional omission to give information of an offence against the State)",
           """        "Whoever"
    AND (    f's `knowing that any offence punishable under section 121, 121A, 121B or 121C has been committed`
         OR  f's `having reason to believe that any offence punishable under section 121, 121A, 121B or 121C has been committed` )
    AND f's intentionally
    AND f's `omits to give any information respecting that offence which he is legally bound to give`"""))
    A("")
    A(charge("121D", "intentional omission to give information of an offence against the State", "offence under s 121D",
             """CONCAT (IF f's `knowing that any offence punishable under section 121, 121A, 121B or 121C has been committed` THEN "knowing" ELSE "having reason to believe"), " that an offence punishable under section 121, 121A, 121B or 121C of the Penal Code 1871 had been committed, did intentionally omit to give information respecting that offence which you were legally bound to give", `the to-wit clause` (f's `to wit`)""",
             [("f's `knowing that any offence punishable under section 121, 121A, 121B or 121C has been committed` OR f's `having reason to believe that any offence punishable under section 121, 121A, 121B or 121C has been committed`", "knowing or having reason to believe that such an offence has been committed"),
              ("f's intentionally", "intentionally"),
              ("f's `omits to give any information respecting that offence which he is legally bound to give`", "omits to give information he is legally bound to give")], OI))
    A("")

    # 122
    PW = "Preparing War Facts"
    A(section("122", "Collecting arms, etc., with the intention of waging war against the Government"))
    A("")
    A(facts(PW, "Penal Code 1871 s 122", [
        ("collects men, arms or ammunition", "B", "Did the accused collect men, arms or ammunition?"),
        ("otherwise prepares to wage war", "B", "Did the accused otherwise prepare to wage war?"),
        ("with the intention of either waging or being prepared to wage war against the Government", "B", "Did the accused intend to wage, or to be prepared to wage, war against the Government?"),
        TO_WIT,
    ]))
    A("")
    A(pun("122", "imprisonment for life or imprisonment for a term not exceeding 20 years, and shall, if he is not sentenced to imprisonment for life, also be liable to fine",
          life="or", imp="or", mx=240, fine="al"))
    A("")
    A(rule("offence under s 122", PW,
           "Whether the accused has committed an offence punishable under section 122 of the Penal Code 1871 (collecting arms with the intention of waging war against the Government)",
           """        "Whoever"
    AND (    f's `collects men, arms or ammunition`
         OR  f's `otherwise prepares to wage war` )
    AND f's `with the intention of either waging or being prepared to wage war against the Government`"""))
    A("")
    A(charge("122", "collecting arms with the intention of waging war against the Government", "offence under s 122",
             """CONCAT "did ", (IF f's `collects men, arms or ammunition` THEN "collect men, arms or ammunition" ELSE "prepare to wage war"), ", with the intention of waging or being prepared to wage war against the Government", `the to-wit clause` (f's `to wit`)""",
             [("f's `collects men, arms or ammunition` OR f's `otherwise prepares to wage war`", "collects men, arms or ammunition, or otherwise prepares to wage war"),
              ("f's `with the intention of either waging or being prepared to wage war against the Government`", "with the intention of waging or being prepared to wage war against the Government")], PW))
    A("")

    # 123
    CD = "Concealing Design to Wage War Facts"
    A(section("123", "Concealing with intent to facilitate a design to wage war"))
    A("")
    A(facts(CD, "Penal Code 1871 s 123", [
        ("by any act", "B", "Was the concealment by an act?"),
        ("by any illegal omission", "B", "Was the concealment by an illegal (s 43) omission?"),
        ("conceals the existence of a design to wage war against the Government", "B", "Did the accused conceal the existence of a design to wage war against the Government?"),
        ("intending by such concealment to facilitate the waging of such war", "B", "Did the accused intend the concealment to facilitate the waging of that war?"),
        ("knowing it to be likely that such concealment will facilitate the waging of such war", "B", "Did the accused know it likely the concealment would facilitate it?"),
        TO_WIT,
    ]))
    A("")
    A(pun("123", "imprisonment for a term which may extend to 15 years, and shall also be liable to fine", imp="sh", mx=180, fine="al"))
    A("")
    A(rule("offence under s 123", CD,
           "Whether the accused has committed an offence punishable under section 123 of the Penal Code 1871 (concealing a design to wage war)",
           """        "Whoever"
    AND (    f's `by any act`
         OR  f's `by any illegal omission` )
    AND f's `conceals the existence of a design to wage war against the Government`
    AND (    f's `intending by such concealment to facilitate the waging of such war`
         OR  f's `knowing it to be likely that such concealment will facilitate the waging of such war` )"""))
    A("")
    A(charge("123", "concealing with intent to facilitate a design to wage war", "offence under s 123",
             """CONCAT "did conceal the existence of a design to wage war against the Government, ", (IF f's `intending by such concealment to facilitate the waging of such war` THEN "intending" ELSE "knowing it to be likely"), " by such concealment to facilitate the waging of such war", `the to-wit clause` (f's `to wit`)""",
             [("f's `by any act` OR f's `by any illegal omission`", "by an act or an illegal omission"),
              ("f's `conceals the existence of a design to wage war against the Government`", "conceals the existence of a design to wage war against the Government"),
              ("f's `intending by such concealment to facilitate the waging of such war` OR f's `knowing it to be likely that such concealment will facilitate the waging of such war`", "intending, or knowing it likely, that the concealment will facilitate the war")], CD))
    A("")

    # 124
    AP = "Assaulting the President Facts"
    A(section("124", "Assaulting President, etc., with intent to compel or restrain the exercise of any lawful power"))
    A("")
    A(facts(AP, "Penal Code 1871 s 124", [
        ("with the intention of inducing or compelling the President or a Member of Parliament or the Cabinet to exercise or refrain from exercising in any manner any of their lawful powers", "B", "Did the accused intend to induce or compel the President, a Member of Parliament or the Cabinet to exercise, or refrain from exercising, any of their lawful powers?"),
        ("assaults", "B", "Did the accused assault the President or such Member (s 351 - pc-body-a; joined at integration)?"),
        ("wrongfully restrains", "B", "Did the accused wrongfully restrain them (s 339 - pc-body-a; joined at integration)?"),
        ("attempts wrongfully to restrain", "B", "Did the accused attempt wrongfully to restrain them?"),
        ("overawes by means of criminal force, or the show of criminal force", "B", "Did the accused overawe them by criminal force or the show of criminal force?"),
        ("attempts so to overawe", "B", "Did the accused attempt so to overawe them?"),
        TO_WIT,
    ]))
    A("")
    A(pun("124", "imprisonment for life or for a term which may extend to 20 years, and shall, if he is not sentenced to imprisonment for life, also be liable to fine",
          life="or", imp="or", mx=240, fine="al"))
    A("")
    A(rule("offence under s 124", AP,
           "Whether the accused has committed an offence punishable under section 124 of the Penal Code 1871 (assaulting the President, etc., with intent to compel or restrain the exercise of lawful power)",
           """        "Whoever,"
    AND f's `with the intention of inducing or compelling the President or a Member of Parliament or the Cabinet to exercise or refrain from exercising in any manner any of their lawful powers`
    AND (    f's assaults
         OR  f's `wrongfully restrains`
         OR  f's `attempts wrongfully to restrain`
         OR  f's `overawes by means of criminal force, or the show of criminal force`
         OR  f's `attempts so to overawe` )
    AND "the President or such Member\""""))
    A("")
    A(charge("124", "assaulting the President or a Member of Parliament with intent to compel or restrain the exercise of lawful power", "offence under s 124",
             """CONCAT "with the intention of inducing or compelling the President or a Member of Parliament or the Cabinet to exercise or refrain from exercising a lawful power, did ", `joined with` ", or " (concat (LIST (`included if` (f's assaults) "assault"), (`included if` (f's `wrongfully restrains`) "wrongfully restrain"), (`included if` (f's `attempts wrongfully to restrain`) "attempt wrongfully to restrain"), (`included if` (f's `overawes by means of criminal force, or the show of criminal force`) "overawe by means of criminal force"), (`included if` (f's `attempts so to overawe`) "attempt so to overawe"))), " the President or such Member", `the to-wit clause` (f's `to wit`)""",
             [("f's `with the intention of inducing or compelling the President or a Member of Parliament or the Cabinet to exercise or refrain from exercising in any manner any of their lawful powers`", "with the intention of inducing or compelling the exercise or non-exercise of a lawful power"),
              ("f's assaults OR f's `wrongfully restrains` OR f's `attempts wrongfully to restrain` OR f's `overawes by means of criminal force, or the show of criminal force` OR f's `attempts so to overawe`", "assaults, wrongfully restrains or attempts to, or overawes by criminal force or attempts to")], AP))
    A("")

    # 125-127
    AL = "War against an Allied Power Facts"
    A(section("125", "Waging war against any power in alliance or at peace with Singapore"))
    A("")
    A(facts(AL, "Penal Code 1871 ss 125, 126, 127", [
        ("wages war against the government of any power in alliance or at peace with the Government", "B", "s 125: Did the accused wage war against the government of a power in alliance or at peace with the Government?"),
        ("attempts to wage such war", "B", "s 125: Did the accused attempt to wage such war?"),
        ("abets the waging of such war", "B", "s 125: Did the accused abet (s 107) the waging of such war?"),
        ("commits depredation", "B", "s 126: Did the accused commit depredation (plunder)?"),
        ("makes preparations to commit depredation", "B", "s 126: Did the accused make preparations to commit depredation?"),
        ("on the territories of any power in alliance or at peace with the Government", "B", "s 126: ... on the territories of a power in alliance or at peace with the Government?"),
        ("receives any property", "B", "s 127: Did the accused receive property?"),
        ("knowing the same to have been taken in the commission of any of the offences mentioned in sections 125 and 126", "B", "s 127: Did the accused know it had been taken in committing an offence mentioned in s 125 or 126?"),
        ("the property", "S", "s 127: The property received, as it is to read in the charge"),
        TO_WIT,
    ]))
    A("")
    A(pun("125", "imprisonment for life, or with imprisonment for a term which may extend to 15 years, to which fine may be added, or with fine",
          life="or", imp="or", mx=180, fine="or"))
    A("")
    A(rule("offence under s 125", AL,
           "Whether the accused has committed an offence punishable under section 125 of the Penal Code 1871 (waging war against a power in alliance or at peace with Singapore)",
           """        "Whoever"
    AND (    f's `wages war against the government of any power in alliance or at peace with the Government`
         OR  f's `attempts to wage such war`
         OR  f's `abets the waging of such war` )""",
           comment="FORK SP-125: \"imprisonment ... to which fine may be added, or with fine\" - fine is recorded\n`or with` (it may stand alone); that it may also be ADDED to a term is in the words only."))
    A("")
    A(charge("125", "waging war against a power in alliance or at peace with Singapore", "offence under s 125",
             """CONCAT "did ", `joined with` ", or " (concat (LIST (`included if` (f's `wages war against the government of any power in alliance or at peace with the Government`) "wage war"), (`included if` (f's `attempts to wage such war`) "attempt to wage war"), (`included if` (f's `abets the waging of such war`) "abet the waging of war"))), " against the government of a power at peace with the Government", `the to-wit clause` (f's `to wit`)""",
             [("f's `wages war against the government of any power in alliance or at peace with the Government` OR f's `attempts to wage such war` OR f's `abets the waging of such war`", "wages, attempts to wage, or abets the waging of war against a power in alliance or at peace with the Government")], AL))
    A("")
    A(section("126", "Committing depredation on the territories of any power in alliance or at peace with Singapore"))
    A("")
    A(pun("126", "imprisonment for a term which may extend to 10 years, and shall also be liable to fine, and any property used, or intended to be used, in committing such depredation, or acquired by such depredation, shall be forfeited",
          imp="sh", mx=120, fine="al", forf="sh"))
    A("")
    A(rule("offence under s 126", AL,
           "Whether the accused has committed an offence punishable under section 126 of the Penal Code 1871 (committing depredation on the territories of a power at peace with Singapore)",
           """        "Whoever"
    AND (    f's `commits depredation`
         OR  f's `makes preparations to commit depredation` )
    AND f's `on the territories of any power in alliance or at peace with the Government`"""))
    A("")
    A(charge("126", "committing depredation on the territories of a power at peace with Singapore", "offence under s 126",
             """CONCAT "did ", (IF f's `commits depredation` THEN "commit depredation" ELSE "make preparations to commit depredation"), " on the territories of a power at peace with the Government", `the to-wit clause` (f's `to wit`)""",
             [("f's `commits depredation` OR f's `makes preparations to commit depredation`", "commits, or prepares to commit, depredation"),
              ("f's `on the territories of any power in alliance or at peace with the Government`", "on the territories of a power in alliance or at peace with the Government")], AL))
    A("")
    A(section("127", "Receiving property taken by war or depredation mentioned in sections 125 and 126"))
    A("")
    A(pun("127", "imprisonment for a term which may extend to 7 years, and shall also be liable to fine, and the property so received shall be forfeited",
          imp="sh", mx=84, fine="al", forf="sh"))
    A("")
    A(rule("offence under s 127", AL,
           "Whether the accused has committed an offence punishable under section 127 of the Penal Code 1871 (receiving property taken by war or depredation)",
           """        "Whoever"
    AND f's `receives any property`
    AND f's `knowing the same to have been taken in the commission of any of the offences mentioned in sections 125 and 126`"""))
    A("")
    A(charge("127", "receiving property taken by war or depredation", "offence under s 127",
             """CONCAT "did receive ", f's `the property`, ", knowing the same to have been taken in the commission of an offence mentioned in section 125 or 126 of the Penal Code 1871", `the to-wit clause` (f's `to wit`)""",
             [("f's `receives any property`", "receives any property"),
              ("f's `knowing the same to have been taken in the commission of any of the offences mentioned in sections 125 and 126`", "knowing it to have been taken in committing an offence under section 125 or 126")], AL))
    A("")

    # 128, 129
    PC = "Prisoner of State Custody Facts"
    A(section("128", "Public servant voluntarily allowing prisoner of State or war in his custody to escape"))
    A("")
    A(facts(PC, "Penal Code 1871 ss 128, 129", [
        PS,
        ("having the custody of any prisoner of State or prisoner of war", "B", "Did the accused have custody of a prisoner of State or prisoner of war?"),
        ("voluntarily", "B", "s 128: Did the accused allow the escape voluntarily (s 26A)?"),
        ("negligently", "B", "s 129: Did the accused suffer the escape negligently (s 26F)?"),
        ("such prisoner escapes from the place in which he is confined", "B", "Did the prisoner escape from the place of confinement? (s 130 Explanation: a prisoner at large on parole within limits escapes by going beyond them.)"),
        ("the prisoner", "P", "The prisoner, as the charge names them"),
        TO_WIT,
    ]))
    A("")
    A(pun("128", "imprisonment for life, or imprisonment for a term which may extend to 15 years, and shall, if he is not sentenced to imprisonment for life, also be liable to fine",
          life="or", imp="or", mx=180, fine="al"))
    A("")
    A(rule("offence under s 128", PC,
           "Whether the accused has committed an offence punishable under section 128 of the Penal Code 1871 (public servant voluntarily allowing a prisoner of State or war to escape)",
           """        "Whoever, being a"
    AND f's `public servant`
    AND f's `having the custody of any prisoner of State or prisoner of war`
    AND f's voluntarily
    AND "allows"
    AND f's `such prisoner escapes from the place in which he is confined`"""))
    A("")
    m_pc = [("f's `public servant`", "being a public servant"),
            ("f's `having the custody of any prisoner of State or prisoner of war`", "having the custody of a prisoner of State or prisoner of war"),
            ("f's `such prisoner escapes from the place in which he is confined`", "such prisoner escapes from the place in which he is confined")]
    A(charge("128", "public servant voluntarily allowing a prisoner of State or war in his custody to escape", "offence under s 128",
             """CONCAT "being a public servant having the custody of ", `one person` (f's `the prisoner`), ", a prisoner of State or prisoner of war, did voluntarily allow the said prisoner to escape from the place in which ", `subject pronoun` (f's `the prisoner`'s pronoun), " was confined", `the to-wit clause` (f's `to wit`)""",
             m_pc[:2] + [("f's voluntarily", "voluntarily")] + m_pc[2:], PC))
    A("")
    A(section("129", "Public servant negligently suffering prisoner of State or war in his custody to escape"))
    A("")
    A(pun("129", "imprisonment for a term which may extend to 7 years, and shall also be liable to fine", imp="sh", mx=84, fine="al"))
    A("")
    A(rule("offence under s 129", PC,
           "Whether the accused has committed an offence punishable under section 129 of the Penal Code 1871 (public servant negligently suffering a prisoner of State or war to escape)",
           """        "Whoever, being a"
    AND f's `public servant`
    AND f's `having the custody of any prisoner of State or prisoner of war`
    AND f's negligently
    AND "suffers"
    AND f's `such prisoner escapes from the place in which he is confined`"""))
    A("")
    A(charge("129", "public servant negligently suffering a prisoner of State or war in his custody to escape", "offence under s 129",
             """CONCAT "being a public servant having the custody of ", `one person` (f's `the prisoner`), ", a prisoner of State or prisoner of war, did negligently suffer the said prisoner to escape from the place of confinement in which ", `subject pronoun` (f's `the prisoner`'s pronoun), " was confined", `the to-wit clause` (f's `to wit`)""",
             m_pc[:2] + [("f's negligently", "negligently")] + m_pc[2:], PC))
    A("")

    # 130
    AE = "Aiding Escape of Prisoner of State Facts"
    A(section("130", "Aiding escape of, rescuing, or harbouring such prisoner"))
    A("")
    A(facts(AE, "Penal Code 1871 s 130 and its Explanation; s 130A", [
        ("knowingly", "B", "Did the accused act knowingly (s 26D)? Read as governing every limb (FORK SP-130)."),
        ("aids or assists any prisoner of State or prisoner of war in escaping from lawful custody", "B", "Did the accused aid or assist a prisoner of State or of war in escaping from lawful custody? (Explanation: a prisoner at large on parole within limits in Singapore escapes by going beyond them.)"),
        ("rescues or attempts to rescue any such prisoner", "B", "Did the accused rescue, or attempt to rescue, such a prisoner?"),
        ("harbours or conceals any such prisoner who has escaped from lawful custody", "B", "Did the accused harbour (s 130A: including supplying shelter, food, drink, money, clothes, arms, ammunition or conveyance, or helping to evade apprehension) or conceal such a prisoner who had escaped?"),
        ("offers or attempts to offer any resistance to the recapture of such prisoner", "B", "Did the accused offer, or attempt to offer, resistance to the prisoner's recapture?"),
        ("the prisoner", "P", "The prisoner, as the charge names them"),
        TO_WIT,
    ]))
    A("")
    A(pun("130", "imprisonment for life, or with imprisonment for a term which may extend to 15 years, and shall, if he is not sentenced to imprisonment for life, also be liable to fine",
          life="or", imp="or", mx=180, fine="al"))
    A("")
    A(rule("offence under s 130", AE,
           "Whether the accused has committed an offence punishable under section 130 of the Penal Code 1871 (aiding the escape of, rescuing or harbouring a prisoner of State or war)",
           """        "Whoever"
    AND f's knowingly
    AND (    f's `aids or assists any prisoner of State or prisoner of war in escaping from lawful custody`
         OR  f's `rescues or attempts to rescue any such prisoner`
         OR  f's `harbours or conceals any such prisoner who has escaped from lawful custody`
         OR  f's `offers or attempts to offer any resistance to the recapture of such prisoner` )"""))
    A("")
    A(charge("130", "aiding the escape of, rescuing or harbouring a prisoner of State or war", "offence under s 130",
             """CONCAT "did knowingly ", `joined with` ", and " (concat (LIST (`included if` (f's `aids or assists any prisoner of State or prisoner of war in escaping from lawful custody`) "aid"), (`included if` (f's `rescues or attempts to rescue any such prisoner`) "rescue or attempt to rescue"), (`included if` (f's `harbours or conceals any such prisoner who has escaped from lawful custody`) "harbour"), (`included if` (f's `offers or attempts to offer any resistance to the recapture of such prisoner`) "offer resistance to the recapture of"))), " ", `one person` (f's `the prisoner`), ", a prisoner of State or prisoner of war", `the to-wit clause` (f's `to wit`)""",
             [("f's knowingly", "knowingly"),
              ("f's `aids or assists any prisoner of State or prisoner of war in escaping from lawful custody` OR f's `rescues or attempts to rescue any such prisoner` OR f's `harbours or conceals any such prisoner who has escaped from lawful custody` OR f's `offers or attempts to offer any resistance to the recapture of such prisoner`", "aids the escape of, rescues, harbours or conceals, or resists the recapture of, such a prisoner")], AE))
    A("")

    # 130A / 140A
    A(section("130A", "\"Harbour\""))
    A("")
    HB = "Harbour Facts"
    A(facts(HB, "Penal Code 1871 ss 130A, 140A", [
        ("harbours the person in the ordinary sense of the word", "B", "Did the accused harbour the person in the ordinary sense - give them refuge? (\"harbour\" INCLUDES the limbs below; it is not confined to them.)"),
        ("supplies the person with shelter, food, drink, money, clothes, arms, ammunition, or means of conveyance", "B", "Did the accused supply the person with shelter, food, drink, money, clothes, arms, ammunition or means of conveyance?"),
        ("assists the person in any way to evade apprehension", "B", "Did the accused assist the person in any way to evade apprehension?"),
    ]))
    A("")
    A(rule("harbours within section 130A", HB,
           "Whether the accused \"harbours\" a person, as Chapter 6 of the Penal Code 1871 uses the word (s 130A)",
           """        "In this Chapter, 'harbour' includes"
    ..  f's `harbours the person in the ordinary sense of the word`
    OR  f's `supplies the person with shelter, food, drink, money, clothes, arms, ammunition, or means of conveyance`
    OR  f's `assists the person in any way to evade apprehension`""",
           comment="\"includes\" widens the word, so the ordinary meaning is kept as a first limb.\nNo charge: a definition. It is the drill-down for the harbouring leaf of s 130."))
    A("")

    # Chapter 6A
    A("§ `Chapter 6A - Piracy`")
    A("")
    PI = "Piracy Facts"
    A(section("130B", "Piracy by law of nations"))
    A("")
    A(facts(PI, "Penal Code 1871 s 130B", [
        ("does any act that, by the law of nations, is piracy", "B", "Did the accused do an act that is piracy by the law of nations? (A question of international law - for example art 101 of the UN Convention on the Law of the Sea - which is not in this job's inputs; the answer is the investigator's to supply.)"),
        ("while committing or attempting to commit piracy, murders or attempts to murder another person or does any act that is likely to endanger the life of another person", "B", "While committing or attempting to commit piracy, did the accused murder or attempt to murder another person, or do an act likely to endanger another person's life? This chooses the punishment (death); murder is s 300 - pc-body-a."),
        TO_WIT,
    ]))
    A("")
    A(pun("130B(2)", "imprisonment for life and shall be liable to caning", life="sh", caning="al"))
    A("")
    A(pun("130B(2)", "death", death="sh", name="punishment prescribed by s 130B(2), where the pirate murders or endangers life"))
    A("")
    A(rule("commits piracy", PI,
           "Whether the accused \"commits piracy\" within section 130B(1) of the Penal Code 1871",
           """        "(1) A person commits piracy who"
    ... f's `does any act that, by the law of nations, is piracy`"""))
    A("")
    A(rule("offence under s 130B(2)", PI,
           "Whether the accused has committed an offence punishable under section 130B(2) of the Penal Code 1871 (piracy)",
           """        "(2) Whoever"
    ... `commits piracy` f"""))
    A("")
    A(charge("130B(2)", "piracy by the law of nations", "offence under s 130B(2)",
             """CONCAT "did commit piracy, being an act that by the law of nations is piracy", (IF f's `while committing or attempting to commit piracy, murders or attempts to murder another person or does any act that is likely to endanger the life of another person` THEN ", and while committing such piracy did an act likely to endanger the life of another person" ELSE ""), `the to-wit clause` (f's `to wit`)""",
             [("f's `does any act that, by the law of nations, is piracy`", "does an act that, by the law of nations, is piracy")], PI,
             punexpr="IF f's `while committing or attempting to commit piracy, murders or attempts to murder another person or does any act that is likely to endanger the life of another person` THEN " + pw("punishment prescribed by s 130B(2), where the pirate murders or endangers life") + " ELSE " + pw("punishment prescribed by s 130B(2)")))
    A("")
    PA = "Piratical Acts Facts"
    A(section("130C", "Piratical acts"))
    A("")
    A(facts(PA, "Penal Code 1871 s 130C", [
        ("steals a Singapore ship", "B", "(a) Did the accused steal a Singapore ship (theft, s 378 - pc-property; joined at integration)?"),
        ("steals or without lawful authority throws overboard, damages or destroys anything that is part of the cargo, supplies or fittings in a Singapore ship", "B", "(b) Did the accused steal, or without lawful authority throw overboard, damage or destroy, any of the cargo, supplies or fittings in a Singapore ship?"),
        ("does or attempts to do a mutinous act on a Singapore ship", "B", "(c) Did the accused do, or attempt to do, a mutinous act on a Singapore ship?"),
        ("counsels or procures a person to do anything mentioned in paragraph (a), (b) or (c)", "B", "(d) Did the accused counsel or procure anyone to do any of those things?"),
        ("the ship", "S", "The Singapore ship, as it is to read in the charge"),
        TO_WIT,
    ]))
    A("")
    A(pun("130C", "imprisonment for a term not exceeding 15 years and shall be liable to caning", imp="sh", mx=180, caning="al"))
    A("")
    A(rule("offence under s 130C", PA,
           "Whether the accused has committed an offence punishable under section 130C of the Penal Code 1871 (piratical acts)",
           """        "Whoever, while in or out of Singapore -"
    ..  f's `steals a Singapore ship`
    OR  f's `steals or without lawful authority throws overboard, damages or destroys anything that is part of the cargo, supplies or fittings in a Singapore ship`
    OR  f's `does or attempts to do a mutinous act on a Singapore ship`
    OR  f's `counsels or procures a person to do anything mentioned in paragraph (a), (b) or (c)`"""))
    A("")
    A(charge("130C", "piratical acts", "offence under s 130C",
             """CONCAT "did ", `joined with` ", and " (concat (LIST (`included if` (f's `steals a Singapore ship`) "steal"), (`included if` (f's `steals or without lawful authority throws overboard, damages or destroys anything that is part of the cargo, supplies or fittings in a Singapore ship`) "without lawful authority damage the cargo, supplies or fittings in"), (`included if` (f's `does or attempts to do a mutinous act on a Singapore ship`) "do a mutinous act on"), (`included if` (f's `counsels or procures a person to do anything mentioned in paragraph (a), (b) or (c)`) "counsel or procure a piratical act on"))), " ", f's `the ship`, ", a Singapore ship", `the to-wit clause` (f's `to wit`)""",
             [("f's `steals a Singapore ship` OR f's `steals or without lawful authority throws overboard, damages or destroys anything that is part of the cargo, supplies or fittings in a Singapore ship` OR f's `does or attempts to do a mutinous act on a Singapore ship` OR f's `counsels or procures a person to do anything mentioned in paragraph (a), (b) or (c)`", "one of the acts in section 130C(a) to (d)")], PA))
    A("")

    # Chapter 6B
    A("§ `Chapter 6B - Genocide`")
    A("")
    GE = "Genocide Facts"
    A(section("130D", "Genocide"))
    A("")
    A(facts(GE, "Penal Code 1871 ss 130D, 130E", [
        ("with intent to destroy, in whole or in part, a national, an ethnical, a racial or a religious group", "B", "Did the accused act with intent to destroy, in whole or in part, a national, ethnical, racial or religious group?"),
        ("killing members of the group", "B", "(a) killing members of the group?"),
        ("causing serious bodily or mental harm to members of the group", "B", "(b) causing serious bodily or mental harm to members of the group?"),
        ("deliberately inflicting on the group conditions of life calculated to bring about its physical destruction in whole or in part", "B", "(c) deliberately inflicting on the group conditions of life calculated to bring about its physical destruction in whole or in part?"),
        ("imposing measures intended to prevent births within the group", "B", "(d) imposing measures intended to prevent births within the group?"),
        ("forcibly transferring children of the group to another group", "B", "(e) forcibly transferring children of the group to another group?"),
        ("the offence consists of the killing of any person", "B", "s 130E(a): Does the offence consist of the killing of any person? This chooses the punishment (death); it is not an element."),
        ("the group", "S", "The group, as it is to read in the charge"),
        TO_WIT,
    ]))
    A("")
    A(rule("commits genocide", GE,
           "Whether the accused \"commits genocide\" within section 130D of the Penal Code 1871",
           """        "A person commits genocide who,"
    AND f's `with intent to destroy, in whole or in part, a national, an ethnical, a racial or a religious group`
    AND "commits any of the following acts:"
    AND (    f's `killing members of the group`
         OR  f's `causing serious bodily or mental harm to members of the group`
         OR  f's `deliberately inflicting on the group conditions of life calculated to bring about its physical destruction in whole or in part`
         OR  f's `imposing measures intended to prevent births within the group`
         OR  f's `forcibly transferring children of the group to another group` )"""))
    A("")
    A(section("130E", "Punishment for genocide"))
    A("")
    A(pun("130E(a)", "death", death="sh"))
    A("")
    A(pun("130E(b)", "imprisonment for life or with imprisonment for a term which may extend to 20 years", life="or", imp="or", mx=240))
    A("")
    A(rule("offence under s 130E", GE,
           "Whether the accused has committed an offence punishable under section 130E of the Penal Code 1871 (genocide)",
           """        "Whoever"
    ... `commits genocide` f"""))
    A("")
    A(charge("130E", "genocide", "offence under s 130E",
             """CONCAT "with intent to destroy, in whole or in part, ", f's `the group`, ", did commit genocide", `the to-wit clause` (f's `to wit`)""",
             [("f's `with intent to destroy, in whole or in part, a national, an ethnical, a racial or a religious group`", "with intent to destroy, in whole or in part, a national, ethnical, racial or religious group"),
              ("f's `killing members of the group` OR f's `causing serious bodily or mental harm to members of the group` OR f's `deliberately inflicting on the group conditions of life calculated to bring about its physical destruction in whole or in part` OR f's `imposing measures intended to prevent births within the group` OR f's `forcibly transferring children of the group to another group`", "one of the acts in section 130D(a) to (e)"),
              ("`commits genocide` f", "the elements of section 130D taken together")], GE,
             secexpr="(IF f's `the offence consists of the killing of any person` THEN \"130E(a)\" ELSE \"130E(b)\")",
             punexpr="IF f's `the offence consists of the killing of any person` THEN " + pw("punishment prescribed by s 130E(a)") + " ELSE " + pw("punishment prescribed by s 130E(b)")))
    A("")

    # Chapter 7
    A("§ `Chapter 7 - Offences relating to the armed forces`")
    A("")
    AF = "Armed Forces Facts"
    A(section("131", "Abetting mutiny, or attempting to seduce an officer or a serviceman from his duty"))
    A("")
    A(facts(AF, "Penal Code 1871 ss 131-138, 140B", [
        ARMED_MEMBER, POLICE_MEMBER,
        ("abets the committing of mutiny by such officer or serviceman", "B", "ss 131, 132: Did the accused abet (s 107) the committing of mutiny by such an officer or serviceman?"),
        ("attempts to seduce such officer or serviceman from his allegiance or his duty", "B", "s 131: Did the accused attempt to seduce such an officer or serviceman from allegiance or duty?"),
        ("mutiny is committed in consequence of that abetment", "B", "s 132: Was mutiny committed in consequence of the abetment?"),
        ("abets an assault by such officer or serviceman on any superior officer being in the execution of his office", "B", "ss 133, 134: Did the accused abet an assault by such an officer or serviceman on a superior officer in the execution of office?"),
        ("such assault is committed in consequence of that abetment", "B", "s 134: Was the assault committed in consequence of the abetment?"),
        ("abets the desertion of such officer or serviceman", "B", "s 135: Did the accused abet the desertion of such an officer or serviceman?"),
        ("knowing or having reason to believe that such officer or serviceman has deserted", "B", "s 136: Did the accused know or have reason to believe (s 26) that such an officer or serviceman had deserted?"),
        ("harbours such officer or serviceman", "B", "s 136: Did the accused harbour them (s 140A: including supplying shelter, food, drink, money, clothes, arms, ammunition or conveyance, or helping to evade apprehension)?"),
        ("with the intention of preventing the officer or serviceman from being apprehended", "B", "s 136: ... intending to prevent their apprehension?"),
        ("abets what he knows to be an act of insubordination by such officer or serviceman", "B", "s 138: Did the accused abet what the accused knew to be an act of insubordination by such an officer or serviceman?"),
        ("such act of insubordination is committed in consequence of that abetment", "B", "s 138: Was the act of insubordination committed in consequence of the abetment?"),
        ("the serviceman", "P", "The officer or serviceman, as the charge names them"),
        TO_WIT,
    ]))
    A("")
    A(pun("131", "imprisonment for life, or with imprisonment for a term which may extend to 10 years, and shall, if he is not sentenced to imprisonment for life, also be liable to fine",
          life="or", imp="or", mx=120, fine="al"))
    A("")
    A(rule("offence under s 131", AF,
           "Whether the accused has committed an offence punishable under section 131 of the Penal Code 1871 (abetting mutiny, or attempting to seduce an officer or serviceman from duty)",
           f"""        "Whoever"
    AND (    f's `abets the committing of mutiny by such officer or serviceman`
         OR  f's `attempts to seduce such officer or serviceman from his allegiance or his duty` )
    AND "the person concerned being"
    AND {MEMBER_LADDER}"""))
    A("")
    A(charge("131", "abetting mutiny, or attempting to seduce an officer or a serviceman from his duty", "offence under s 131",
             """CONCAT "did ", (IF f's `abets the committing of mutiny by such officer or serviceman` THEN "abet the committing of mutiny by " ELSE "attempt to seduce from his allegiance or his duty "), `one person` (f's `the serviceman`), `the to-wit clause` (f's `to wit`)""",
             [("f's `abets the committing of mutiny by such officer or serviceman` OR f's `attempts to seduce such officer or serviceman from his allegiance or his duty`", "abets mutiny by, or attempts to seduce from allegiance or duty"),
              (MEMBER_EXPR, "an officer or serviceman in the Singapore Armed Forces or visiting forces (or, by section 140B, the Singapore Police Force)")], AF))
    A("")
    A(section("132", "Abetment of mutiny, if mutiny is committed in consequence thereof"))
    A("")
    A(pun("132", "death or with imprisonment for life, or with imprisonment for a term which may extend to 10 years, and shall, if he is not sentenced to death or imprisonment for life, also be liable to fine",
          death="or", life="or", imp="or", mx=120, fine="al"))
    A("")
    A(rule("offence under s 132", AF,
           "Whether the accused has committed an offence punishable under section 132 of the Penal Code 1871 (abetment of mutiny, if mutiny is committed in consequence)",
           f"""        "Whoever"
    AND f's `abets the committing of mutiny by such officer or serviceman`
    AND {MEMBER_LADDER}
    AND "shall, if"
    AND f's `mutiny is committed in consequence of that abetment`"""))
    A("")
    A(charge("132", "abetment of mutiny, mutiny being committed in consequence", "offence under s 132",
             """CONCAT "did abet the committing of mutiny by ", `one person` (f's `the serviceman`), ", and mutiny was committed in consequence of that abetment", `the to-wit clause` (f's `to wit`)""",
             [("f's `abets the committing of mutiny by such officer or serviceman`", "abets the committing of mutiny"),
              (MEMBER_EXPR, "by an officer or serviceman in the Singapore Armed Forces or visiting forces (or, by section 140B, the Singapore Police Force)"),
              ("f's `mutiny is committed in consequence of that abetment`", "mutiny is committed in consequence of that abetment")], AF))
    A("")
    A(section("133", "Abetment of an assault by an officer or a serviceman on his superior officer, when in the execution of his office"))
    A("")
    A(pun("133", "imprisonment for a term which may extend to 3 years, and shall also be liable to fine", imp="sh", mx=36, fine="al"))
    A("")
    A(rule("offence under s 133", AF,
           "Whether the accused has committed an offence punishable under section 133 of the Penal Code 1871 (abetment of an assault by an officer or serviceman on a superior officer)",
           f"""        "Whoever"
    AND f's `abets an assault by such officer or serviceman on any superior officer being in the execution of his office`
    AND {MEMBER_LADDER}"""))
    A("")
    m133 = [("f's `abets an assault by such officer or serviceman on any superior officer being in the execution of his office`", "abets an assault on a superior officer in the execution of his office"),
            (MEMBER_EXPR, "by an officer or serviceman in the Singapore Armed Forces or visiting forces (or, by section 140B, the Singapore Police Force)")]
    A(charge("133", "abetment of an assault by an officer or a serviceman on a superior officer", "offence under s 133",
             """CONCAT "did abet an assault by ", `one person` (f's `the serviceman`), " on a superior officer being in the execution of his office", `the to-wit clause` (f's `to wit`)""", m133, AF))
    A("")
    A(section("134", "Abetment of such assault, if the assault is committed"))
    A("")
    A(pun("134", "imprisonment for a term which may extend to 7 years, and shall also be liable to fine", imp="sh", mx=84, fine="al"))
    A("")
    A(rule("offence under s 134", AF,
           "Whether the accused has committed an offence punishable under section 134 of the Penal Code 1871 (abetment of an assault on a superior officer, the assault being committed)",
           f"""        `offence under s 133` f
    AND "shall, if"
    AND f's `such assault is committed in consequence of that abetment`"""))
    A("")
    A(charge("134", "abetment of an assault by an officer or a serviceman on a superior officer, the assault being committed", "offence under s 134",
             """CONCAT "did abet an assault by ", `one person` (f's `the serviceman`), " on a superior officer being in the execution of his office, and such assault was committed in consequence of that abetment", `the to-wit clause` (f's `to wit`)""",
             m133 + [("f's `such assault is committed in consequence of that abetment`", "such assault is committed in consequence of that abetment")], AF))
    A("")
    A(section("135", "Abetment of the desertion of an officer or a serviceman"))
    A("")
    A(simple_pun("135", "2 years", 24))
    A("")
    A(rule("offence under s 135", AF,
           "Whether the accused has committed an offence punishable under section 135 of the Penal Code 1871 (abetment of the desertion of an officer or serviceman)",
           f"""        "Whoever"
    AND f's `abets the desertion of such officer or serviceman`
    AND {MEMBER_LADDER}"""))
    A("")
    A(charge("135", "abetment of the desertion of an officer or a serviceman", "offence under s 135",
             """CONCAT "did abet the desertion of ", `one person` (f's `the serviceman`), `the to-wit clause` (f's `to wit`)""",
             [("f's `abets the desertion of such officer or serviceman`", "abets the desertion"),
              (MEMBER_EXPR, "of an officer or serviceman in the Singapore Armed Forces or visiting forces (or, by section 140B, the Singapore Police Force)")], AF))
    A("")
    A(section("136", "Harbouring a deserter"))
    A("")
    A(simple_pun("136", "2 years", 24))
    A("")
    A(rule("offence under s 136", AF,
           "Whether the accused has committed an offence punishable under section 136 of the Penal Code 1871 (harbouring a deserter)",
           f"""        "Whoever"
    AND f's `knowing or having reason to believe that such officer or serviceman has deserted`
    AND {MEMBER_LADDER}
    AND f's `harbours such officer or serviceman`
    AND f's `with the intention of preventing the officer or serviceman from being apprehended`"""))
    A("")
    A(charge("136", "harbouring a deserter", "offence under s 136",
             """CONCAT "knowing or having reason to believe that ", `one person` (f's `the serviceman`), " had deserted, did harbour ", `object pronoun` (f's `the serviceman`'s pronoun), " with the intention of preventing ", `object pronoun` (f's `the serviceman`'s pronoun), " from being apprehended", `the to-wit clause` (f's `to wit`)""",
             [("f's `knowing or having reason to believe that such officer or serviceman has deserted`", "knowing or having reason to believe that he has deserted"),
              (MEMBER_EXPR, "an officer or serviceman in the Singapore Armed Forces or visiting forces (or, by section 140B, the Singapore Police Force)"),
              ("f's `harbours such officer or serviceman`", "harbours such officer or serviceman"),
              ("f's `with the intention of preventing the officer or serviceman from being apprehended`", "with the intention of preventing his apprehension")], AF))
    A("")

    # 137
    DV = "Deserter on Merchant Vessel Facts"
    A(section("137", "Deserter concealed on board merchant vessel through negligence of master"))
    A("")
    A(facts(DV, "Penal Code 1871 s 137; s 140B", [
        ("the master or person in charge of a merchant vessel", "B", "Is the accused the master or person in charge of a merchant vessel?"),
        ("on board of which any deserter from the Singapore Armed Forces or any visiting forces lawfully present in Singapore is concealed", "B", "Was a deserter from the Singapore Armed Forces or visiting forces (or, by s 140B, the Singapore Police Force) concealed on board?"),
        ("he might have known of such concealment, but for some neglect of his duty as such master or person in charge, or but for some want of discipline on board of the vessel", "B", "Might the accused have known of the concealment but for some neglect of duty, or some want of discipline on board? (\"though ignorant of such concealment\" - actual ignorance is no answer.)"),
        ("the vessel", "S", "The vessel, as it is to read in the charge"),
        TO_WIT,
    ]))
    A("")
    A(pun("137", "fine not exceeding $1,500", fine="sh", maxfine=1500))
    A("")
    A(rule("offence under s 137", DV,
           "Whether the accused has committed an offence punishable under section 137 of the Penal Code 1871 (deserter concealed on board a merchant vessel through the negligence of the master)",
           """        "The"
    AND f's `the master or person in charge of a merchant vessel`
    AND f's `on board of which any deserter from the Singapore Armed Forces or any visiting forces lawfully present in Singapore is concealed`
    AND "shall, though ignorant of such concealment, be punished ... if"
    AND f's `he might have known of such concealment, but for some neglect of his duty as such master or person in charge, or but for some want of discipline on board of the vessel`"""))
    A("")
    A(charge("137", "deserter concealed on board a merchant vessel through the negligence of the master", "offence under s 137",
             """CONCAT "being the master of ", f's `the vessel`, ", a merchant vessel on board of which a deserter from the Singapore Armed Forces was concealed, might have known of such concealment but for some neglect of your duty as such master or some want of discipline on board of the vessel", `the to-wit clause` (f's `to wit`)""",
             [("f's `the master or person in charge of a merchant vessel`", "the master or person in charge of a merchant vessel"),
              ("f's `on board of which any deserter from the Singapore Armed Forces or any visiting forces lawfully present in Singapore is concealed`", "a deserter concealed on board"),
              ("f's `he might have known of such concealment, but for some neglect of his duty as such master or person in charge, or but for some want of discipline on board of the vessel`", "might have known of the concealment but for neglect of duty or want of discipline")], DV))
    A("")

    A(section("138", "Abetment of act of insubordination by an officer or a serviceman"))
    A("")
    A(simple_pun("138", "6 months", 6))
    A("")
    A(rule("offence under s 138", AF,
           "Whether the accused has committed an offence punishable under section 138 of the Penal Code 1871 (abetment of an act of insubordination by an officer or serviceman)",
           f"""        "Whoever"
    AND f's `abets what he knows to be an act of insubordination by such officer or serviceman`
    AND {MEMBER_LADDER}
    AND "shall, if"
    AND f's `such act of insubordination is committed in consequence of that abetment`"""))
    A("")
    A(charge("138", "abetment of an act of insubordination by an officer or a serviceman", "offence under s 138",
             """CONCAT "did abet what you knew to be an act of insubordination by ", `one person` (f's `the serviceman`), ", and such act of insubordination was committed in consequence of that abetment", `the to-wit clause` (f's `to wit`)""",
             [("f's `abets what he knows to be an act of insubordination by such officer or serviceman`", "abets what he knows to be an act of insubordination"),
              (MEMBER_EXPR, "by an officer or serviceman in the Singapore Armed Forces or visiting forces (or, by section 140B, the Singapore Police Force)"),
              ("f's `such act of insubordination is committed in consequence of that abetment`", "such act of insubordination is committed in consequence of that abetment")], AF))
    A("")

    # 139
    SV = "Service Discipline Saving Facts"
    A(section("139", "Saving"))
    A("")
    A(facts(SV, "Penal Code 1871 s 139", [
        ("provision is made in any law relating to the discipline of the Singapore Armed Forces for the punishment of an offence corresponding to an offence defined in this Chapter", "B", "Does a law on Singapore Armed Forces discipline (for example the Singapore Armed Forces Act 1972 - not in this job's inputs) provide for punishing an offence corresponding to the Chapter 7 offence in question?"),
        ("the person is subject to such provision", "B", "Is the accused subject to that provision?"),
    ]))
    A("")
    A(rule("not subject to punishment under this Code within section 139", SV,
           "Whether section 139 of the Penal Code 1871 takes a person out of punishment under the Code for a Chapter 7 offence (service discipline saving)",
           """        "Where"
    AND f's `provision is made in any law relating to the discipline of the Singapore Armed Forces for the punishment of an offence corresponding to an offence defined in this Chapter`
    AND "no person who"
    AND f's `the person is subject to such provision`
    AND "shall be subject to punishment under this Code for the offence defined in this Chapter\"""",
           comment="A bar to punishment, not an element: like a general exception (PLAN section 5) it is\nnot repeated in the Chapter 7 ladders. At integration the charge sheet reads it\nbeside them. No charge of its own."))
    A("")

    # 140
    SG = "Serviceman Garb Facts"
    A(section("140", "Wearing the dress of a serviceman"))
    A("")
    A(facts(SG, "Penal Code 1871 s 140; s 140B", [
        ("not being a serviceman in the Singapore Armed Forces or any visiting forces lawfully present in Singapore", "B", "Is the accused NOT a serviceman in the Singapore Armed Forces or visiting forces (or, by s 140B, a member of the Singapore Police Force)?"),
        ("wears any garb or carries any token resembling any garb or token used by such a serviceman", "B", "Did the accused wear a garb, or carry a token, resembling one used by such a serviceman (or police officer)?"),
        ("with the intention that it may be believed that he is such a serviceman", "B", "Did the accused intend it to be believed that they were such a serviceman?"),
        ("the garb or token", "S", "The garb or token, as it is to read in the charge"),
        TO_WIT,
    ]))
    A("")
    A(simple_pun("140", "6 months", 6, "fine which may extend to $2,500", 2500))
    A("")
    A(rule("offence under s 140", SG,
           "Whether the accused has committed an offence punishable under section 140 of the Penal Code 1871 (wearing the dress of a serviceman)",
           """        "Whoever,"
    AND f's `not being a serviceman in the Singapore Armed Forces or any visiting forces lawfully present in Singapore`
    AND f's `wears any garb or carries any token resembling any garb or token used by such a serviceman`
    AND f's `with the intention that it may be believed that he is such a serviceman`"""))
    A("")
    A(charge("140", "wearing the dress of a serviceman", "offence under s 140",
             """CONCAT "not being a serviceman in the Singapore Armed Forces, did wear or carry ", f's `the garb or token`, ", resembling a garb or token used by such a serviceman, with the intention that it might be believed that you were such a serviceman", `the to-wit clause` (f's `to wit`)""",
             [("f's `not being a serviceman in the Singapore Armed Forces or any visiting forces lawfully present in Singapore`", "not being a serviceman"),
              ("f's `wears any garb or carries any token resembling any garb or token used by such a serviceman`", "wears a garb or carries a token resembling one used by such a serviceman"),
              ("f's `with the intention that it may be believed that he is such a serviceman`", "with the intention that it may be believed that he is such a serviceman")], SG))
    A("")
    A(section("140A", "\"Harbour\""))
    A("")
    A(rule("harbours within section 140A", HB,
           "Whether the accused \"harbours\" a person, as Chapter 7 of the Penal Code 1871 uses the word (s 140A)",
           """        "In this Chapter, 'harbour' includes"
    ..  f's `harbours the person in the ordinary sense of the word`
    OR  f's `supplies the person with shelter, food, drink, money, clothes, arms, ammunition, or means of conveyance`
    OR  f's `assists the person in any way to evade apprehension`""",
           comment="The same words as s 130A, for Chapter 7; the drill-down for s 136's harbouring leaf."))
    A("")
    A(section("140B", "Application of Chapter 7 to Singapore Police Force"))
    A("")
    A("-- Encoded as the leaf `a member of the Singapore Police Force or any volunteer,")
    A("-- auxiliary or special force attached to it`, ORed with the armed-forces leaf in")
    A("-- every Chapter 7 ladder, and named in the @desc of ss 137 and 140's leaves.")
    A("")
    return "\n".join(out)


def tests():
    T = []
    A = T.append
    A("§ `Chapters 6, 6A, 6B and 7 - tests`")
    A("")
    A(fixture("121 illus", "Waging War Facts", ["wages war against the Government"], {"to wit": "by joining an insurrection against the Government"},
              comment="s 121 illus: A joins an insurrection against the Government. A has committed the offence defined in this section."))
    A("-- s 121 illus")
    A("#ASSERT `offence under s 121` `121 illus`")
    A("#ASSERT (`charge under s 121` `121 illus`)'s text EQUALS \"You, Tan Ah Kow, are charged that you, on or about the 3rd day of March 2026, at about 10.15 am, at Block 123 Ang Mo Kio Avenue 3, Singapore, did wage war against the Government, to wit, by joining an insurrection against the Government, and you have thereby committed an offence punishable under section 121 of the Penal Code 1871.\"")
    A("-- s 121's punishment is \"death, or ... imprisonment for life\" - so ss 115, 118 and 512(1)'s words reach it")
    A("#ASSERT `punishable with death or imprisonment for life` `punishment prescribed by s 121`")
    A(fixture("121: nothing done", "Waging War Facts", []))
    A("#ASSERT (`charge under s 121` `121: nothing done`)'s refusal EQUALS \"A charge under section 121 would assert that the facts fulfil every legal condition of waging or attempting to wage war or abetting the waging of war against the Government (CPC s 123(5)). On the facts given they do not: wages war against the Government, or attempts to wage, or abets the waging of, such war.\"")
    A(fixture("121A: the plot", "Plot against the President Facts", ["plans the death of or hurt to or unlawful imprisonment or restraint of the President"]))
    A("#ASSERT `offence under s 121A` `121A: the plot`")
    A("#ASSERT NOT `offence under s 121B` `121A: the plot`")
    A(fixture("130: the parole-breaker's helper", "Aiding Escape of Prisoner of State Facts",
              ["knowingly", "aids or assists any prisoner of State or prisoner of war in escaping from lawful custody"],
              comment="s 130 Explanation: a prisoner of war at large on parole within limits in Singapore escapes from lawful\ncustody by going beyond those limits; A knowingly drives him past them."))
    A("-- s 130 Explanation")
    A("#ASSERT `offence under s 130` `130: the parole-breaker's helper`")
    A(fixture("130A: supplying food", "Harbour Facts", ["supplies the person with shelter, food, drink, money, clothes, arms, ammunition, or means of conveyance"]))
    A("#ASSERT `harbours within section 130A` `130A: supplying food`")
    A("#ASSERT `harbours within section 140A` `130A: supplying food`")
    A(fixture("128: the gaoler", "Prisoner of State Custody Facts",
              ["public servant", "having the custody of any prisoner of State or prisoner of war", "voluntarily", "such prisoner escapes from the place in which he is confined"]))
    A("#ASSERT `offence under s 128` `128: the gaoler`")
    A("#ASSERT NOT `offence under s 129` `128: the gaoler`")
    A("")
    A(fixture("130B: piracy, life endangered", "Piracy Facts",
              ["does any act that, by the law of nations, is piracy",
               "while committing or attempting to commit piracy, murders or attempts to murder another person or does any act that is likely to endanger the life of another person"]))
    A("#ASSERT `offence under s 130B(2)` `130B: piracy, life endangered`")
    A("-- s 130B(2): \"he shall be punished with death\"")
    A("#ASSERT (`charge under s 130B(2)` `130B: piracy, life endangered`)'s punishment EQUALS \"death\"")
    A("#ASSERT `fixed by law or carries a minimum sentence` `punishment prescribed by s 130B(2), where the pirate murders or endangers life`")
    A(fixture("130C: mutiny on a Singapore ship", "Piratical Acts Facts", ["does or attempts to do a mutinous act on a Singapore ship"]))
    A("#ASSERT `offence under s 130C` `130C: mutiny on a Singapore ship`")
    A("")
    A(fixture("130D: killing with intent", "Genocide Facts",
              ["with intent to destroy, in whole or in part, a national, an ethnical, a racial or a religious group", "killing members of the group", "the offence consists of the killing of any person"]))
    A("#ASSERT `commits genocide` `130D: killing with intent`")
    A("#ASSERT (`charge under s 130E` `130D: killing with intent`)'s section EQUALS \"130E(a)\"")
    A("#ASSERT (`charge under s 130E` `130D: killing with intent`)'s punishment EQUALS \"death\"")
    A(fixture("130D: the acts without the intent", "Genocide Facts", ["forcibly transferring children of the group to another group"]))
    A("-- s 130D: the acts without the intent to destroy the group are not genocide")
    A("#ASSERT NOT `commits genocide` `130D: the acts without the intent`")
    A("")
    A(fixture("132: mutiny follows", "Armed Forces Facts",
              ["an officer or a serviceman in the Singapore Armed Forces or any visiting forces lawfully present in Singapore",
               "abets the committing of mutiny by such officer or serviceman", "mutiny is committed in consequence of that abetment"]))
    A("#ASSERT `offence under s 131` `132: mutiny follows`")
    A("#ASSERT `offence under s 132` `132: mutiny follows`")
    A(fixture("140B: abetting a police officer's desertion", "Armed Forces Facts",
              ["a member of the Singapore Police Force or any volunteer, auxiliary or special force attached to it", "abets the desertion of such officer or serviceman"],
              comment="s 140B: Chapter 7 applies, with the necessary modifications, to the Singapore Police Force."))
    A("-- s 140B")
    A("#ASSERT `offence under s 135` `140B: abetting a police officer's desertion`")
    A(fixture("134: assault abetted but not committed", "Armed Forces Facts",
              ["an officer or a serviceman in the Singapore Armed Forces or any visiting forces lawfully present in Singapore",
               "abets an assault by such officer or serviceman on any superior officer being in the execution of his office"]))
    A("#ASSERT `offence under s 133` `134: assault abetted but not committed`")
    A("#ASSERT NOT `offence under s 134` `134: assault abetted but not committed`")
    A(fixture("137: the careless master", "Deserter on Merchant Vessel Facts",
              ["the master or person in charge of a merchant vessel", "on board of which any deserter from the Singapore Armed Forces or any visiting forces lawfully present in Singapore is concealed",
               "he might have known of such concealment, but for some neglect of his duty as such master or person in charge, or but for some want of discipline on board of the vessel"]))
    A("#ASSERT `offence under s 137` `137: the careless master`")
    A("#ASSERT (`charge under s 137` `137: the careless master`)'s punishment EQUALS \"fine not exceeding $1,500\"")
    A(fixture("139: a serviceman under service law", "Service Discipline Saving Facts",
              ["provision is made in any law relating to the discipline of the Singapore Armed Forces for the punishment of an offence corresponding to an offence defined in this Chapter",
               "the person is subject to such provision"]))
    A("#ASSERT `not subject to punishment under this Code within section 139` `139: a serviceman under service law`")
    A(fixture("140: the costume", "Serviceman Garb Facts",
              ["not being a serviceman in the Singapore Armed Forces or any visiting forces lawfully present in Singapore",
               "wears any garb or carries any token resembling any garb or token used by such a serviceman"]))
    A("-- no intention that it be believed he is a serviceman: not within s 140")
    A("#ASSERT NOT `offence under s 140` `140: the costume`")
    A("")
    return "\n".join(T)
