"""pc-state-public-common.l4 - helpers the state-public parts share."""

HEADER = """-- Singapore Penal Code 1871 - state-public group (Chapters 6, 6A, 6B, 7, 8, 9,
-- 10; ss 121-190): the helpers the group's parts share. No section of the Code
-- lives here; each part IMPORTs this module.
--
-- GENERATED by notes/state-public-gen/build.py; edit part_common.py and rebuild."""

BODY = r'''
IMPORT prelude
IMPORT `pc-domain`
IMPORT `pc-general`

§ `state-public - shared helpers`

-- `the to-wit clause` was defined here; it now lives in pc-general.l4's
-- "Shared helpers, hoisted at integration", because body-a defined it too.
'''


def module():
    return HEADER + "\n" + BODY
