"""pc-state-public-tests.l4 - assembled from each part's tests()."""

HEADER = """-- Tests for the state-public group of the Penal Code 1871 encoding: Chapters 6,
-- 6A, 6B, 7, 8, 9 and 10 (ss 121-190).
--
-- Expected values come FROM THE SOURCE: each Illustration the Code prints is
-- cited on the line above its assertion as `-- s N illus (x)`; boundary cases
-- are cited to the words they test. A failing assertion here is a finding, not
-- a typo - never edit an expected value to match what the code computed.
--
-- GENERATED by notes/state-public-gen/build.py from the part files' tests();
-- edit there and rebuild.
--
-- Fixtures list every field; a leaf not named TRUE in a fixture is FALSE, which
-- is also what the charge generator's schema completion does with an unknown."""

COMMON = r'''
§ `Shared fixtures`

`sample particulars` MEANS Particulars WITH
    accused            IS "Tan Ah Kow"
    date               IS "the 3rd day of March 2026"
    time               IS "10.15 am"
    place              IS "Block 123 Ang Mo Kio Avenue 3"
    `co-accused`       IS ""
    `common intention` IS FALSE

`nobody` MEANS Person WITH
    name           IS ""
    `described as` IS ""
    pronoun        IS they
    kind           IS `a human being`

`Sergeant Lim` MEANS Person WITH
    name           IS "Lim Ah Seng"
    `described as` IS "a police officer attached to Ang Mo Kio Police Division"
    pronoun        IS he
    kind           IS `a human being`

`Lieutenant Siti` MEANS Person WITH
    name           IS "Siti binte Rahman"
    `described as` IS "a paramedic of the Singapore Civil Defence Force"
    pronoun        IS she
    kind           IS `a human being`

`Z` MEANS Person WITH
    name           IS "Zainal bin Osman"
    `described as` IS ""
    pronoun        IS he
    kind           IS `a human being`
'''


def module(files, tests):
    imports = ["IMPORT prelude", "IMPORT `pc-domain`", "IMPORT `pc-general`"]
    imports += [f"IMPORT `{f[:-3]}`" for f in files]
    return "\n".join([HEADER, ""] + imports + [COMMON] + tests)
