"""Tests for mda-punishment.l4 and mda-enforcement.l4.  Expected values are read off the printed Second Schedule and the sections (source/MDA1973.txt).
The Schedule's cells are written here AS PRINTED ("Maximum 20 years and 15 strokes") and parsed into a Punishment by `parse`; they are not taken from
mda_schedule.py, which transcribed the same table separately.

Run: python generators/mda_tests_2.py   (writes ../mda-tests-punishment.l4 and ../mda-tests-enforcement.l4)"""
import re, sys, os
sys.path.insert(0, os.path.dirname(__file__))
from fixtures import Types, Out

ROW = os.path.join(os.path.dirname(__file__), '..')
types = Types(os.path.join(ROW, 'mda-types.l4'), os.path.join(ROW, 'written-law-interface.l4'))
def q(x): return '`%s`' % x


def parse(text):
    """Printed cell -> Punishment literal.  'Death'; 'Maximum ...; Minimum ...' with years, months, '$n', 'n strokes', 'imprisonment for life', 'or both'."""
    if text.strip() == 'Death':
        return '(`Punishment` OF TRUE, FALSE, 0, 0, 0, 0, 0, 0, FALSE)'
    f = dict(life=False, maxm=0, minm=0, maxf=0, minf=0, mins=0, maxs=0, alt=False)
    for part in text.split('; '):
        kind = 'max' if part.startswith('Maximum') else 'min'
        m = re.search(r'(\d+) years', part)
        if m: f[kind + 'm'] = int(m.group(1)) * 12
        m = re.search(r'(\d+) months', part)
        if m: f[kind + 'm'] = int(m.group(1))
        m = re.search(r'\$([\d,]+)', part)
        if m: f[kind + 'f'] = int(m.group(1).replace(',', ''))
        m = re.search(r'(\d+) strokes', part)
        if m: f[kind + 's'] = int(m.group(1))
        if 'imprisonment for life' in part: f['life'] = True
        if 'or both' in part: f['alt'] = True
    b = lambda v: 'TRUE' if v else 'FALSE'
    return '(`Punishment` OF FALSE, %s, %d, %d, %d, %d, %d, %d, %s)' % (b(f['life']), f['maxm'], f['minm'], f['maxf'], f['minf'], f['mins'], f['maxs'], b(f['alt']))


class Suite:
    def __init__(self, header): self.o = Out(types, header)
    def case(self, name, rec, *true, **vals): self.o.case(name, rec, *true, **vals)
    def section(self, t): self.o.section(t)
    def raw(self, text): self.o.assert_(text)
    def yes(self, pred, *args): self.o.assert_('`%s` %s' % (pred, ' '.join(self.a(x) for x in args)))
    def no(self, pred, *args): self.o.assert_('NOT `%s` %s' % (pred, ' '.join(self.a(x) for x in args)))
    @staticmethod
    def a(x): return str(x) if not isinstance(x, str) else (x if x in ('TRUE', 'FALSE') or x.startswith('(') else q(x))


# ======================================================================================================================== punishment
S = Suite("""IMPORT prelude
IMPORT `mda-types`
IMPORT `mda-second-schedule`
IMPORT `mda-section-punishments`
IMPORT `mda-punishment`

-- Tests for mda-punishment.l4, mda-second-schedule.l4 and mda-section-punishments.l4 (Misuse of Drugs Act 1973, ss 33, 33A, 33B and the Second Schedule).
-- Expected values are the Schedule's cells as printed, parsed by generators/mda_tests_2.py.  Generated by generators/mda_tests_2.py.""")
DQ, SQ = 'Drug Quantity Facts', 'Scheduled Quantity Facts'
FRAG = {'opium': 'the weight of opium', 'morphine in opium': 'the weight of morphine in the opium', 'morphine': 'the weight of morphine in the controlled drug', 'diamorphine': 'the weight of diamorphine',
        'cannabis': 'the weight of cannabis in', 'cannabis mixture': 'the weight of cannabis mixture', 'cannabis resin': 'the weight of cannabis resin', 'cocaine': 'the weight of cocaine',
        'methamphetamine': 'the weight of methamphetamine'}
made = set()
def qty(**w):
    name = 'quantities ' + ', '.join('%s %s' % (k.replace('_', ' '), v) for k, v in sorted(w.items())) if w else 'no quantities'
    if name not in made:
        made.add(name)
        S.case(name, DQ, **{FRAG[k.replace('_', ' ')]: v for k, v in w.items()})
    return name
S.case('nothing manufactured in particular', SQ)
S.case('morphine manufactured', SQ, 'is morphine or a salt')
S.case('diamorphine manufactured', SQ, 'is diamorphine or a salt')
S.case('cocaine manufactured', SQ, 'is cocaine or a salt')
S.case('methamphetamine manufactured', SQ, 'is methamphetamine or a salt')
A, B, C, NC = 'Class A drug', 'Class B drug', 'Class C drug', 'Not in any class'
def sched(section, cls, qname, sqname, printed):
    S.raw('`the two punishments are the same` (`the Second Schedule punishment` "%s" %s %s %s) %s' % (section, q(cls), q(qname), q(sqname), parse(printed)))

LIFE = 'Maximum 30 years or imprisonment for life and 15 strokes; Minimum 20 years and 15 strokes'
S.section('Second Schedule: the row count and the deleted rows')
S.raw('count `the Second Schedule` EQUALS 86')
S.raw('count (`the Second Schedule rows for the section` "5") EQUALS 19')
S.raw('count (`the Second Schedule rows for the section` "8(b)") EQUALS 0')
S.raw('count (`the Second Schedule rows for the section` "13") EQUALS 0')
S.raw('count (`the Second Schedule rows for the section` "31(2)") EQUALS 0')
S.raw('count (`the Second Schedule rows for the section` "31A(2)") EQUALS 0')
S.raw('count `the punishments the sections state` EQUALS 49')

S.section('5(1). traffic: by class of drug, as printed')
for cls, printed in [(A, 'Maximum 20 years and 15 strokes; Minimum 5 years and 5 strokes'), (B, 'Maximum 20 years and 10 strokes; Minimum 3 years and 3 strokes'), (C, 'Maximum 10 years and 5 strokes; Minimum 2 years and 2 strokes')]:
    sched('5', cls, qty(), 'nothing manufactured in particular', printed)
S.section('6(1). manufacture: by class of drug, as printed')
for cls, printed in [(A, 'Maximum 30 years or imprisonment for life and 15 strokes; Minimum 10 years and 5 strokes'), (B, 'Maximum 30 years or imprisonment for life and 15 strokes; Minimum 10 years and 5 strokes'),
                     (C, 'Maximum 20 years and 15 strokes; Minimum 5 years and 5 strokes')]:
    sched('6', cls, qty(), 'nothing manufactured in particular', printed)
S.section('7(1). import or export: by class of drug, as printed')
for cls, printed in [(A, 'Maximum 30 years or imprisonment for life and 15 strokes; Minimum 5 years and 5 strokes'), (B, 'Maximum 30 years or imprisonment for life and 15 strokes; Minimum 5 years and 5 strokes'),
                     (C, 'Maximum 20 years and 15 strokes; Minimum 3 years and 5 strokes')]:
    sched('7', cls, qty(), 'nothing manufactured in particular', printed)

S.section('5 and 7, sixth column: each specified quantity at, below and above its figures')
TRADE = [('cannabis', 330, 500), ('cannabis mixture', 660, 1000), ('cannabis resin', 130, 200), ('cocaine', 20, 30), ('diamorphine', 10, 15), ('methamphetamine', 167, 250), ('morphine', 20, 30)]
for section in ['5', '7']:
    classA = 'Maximum 20 years and 15 strokes; Minimum 5 years and 5 strokes' if section == '5' else 'Maximum 30 years or imprisonment for life and 15 strokes; Minimum 5 years and 5 strokes'
    for sub, lo, hi in TRADE:
        sched(section, A, qty(**{sub: lo - 1}), 'nothing manufactured in particular', classA)     # below the band: the class column
        sched(section, A, qty(**{sub: lo}), 'nothing manufactured in particular', LIFE)             # "not less than" lo
        sched(section, A, qty(**{sub: hi}), 'nothing manufactured in particular', LIFE)             # "not more than" hi
        sched(section, A, qty(**{sub: hi + 1}), 'nothing manufactured in particular', 'Death')     # "more than" hi
        sched(section, B, qty(**{sub: hi + 1}), 'nothing manufactured in particular', 'Death')     # the class does not matter
    # opium: both the weight of opium and the morphine it contains
    sched(section, A, qty(opium=800, morphine_in_opium=20), 'nothing manufactured in particular', LIFE)
    sched(section, A, qty(opium=1200, morphine_in_opium=20), 'nothing manufactured in particular', LIFE)
    sched(section, A, qty(opium=1000, morphine_in_opium=40), 'nothing manufactured in particular', LIFE)
    sched(section, A, qty(opium=1201, morphine_in_opium=31), 'nothing manufactured in particular', 'Death')
    sched(section, A, qty(opium=799, morphine_in_opium=20), 'nothing manufactured in particular', classA)
    sched(section, A, qty(opium=1000, morphine_in_opium=19), 'nothing manufactured in particular', classA)
    sched(section, A, qty(opium=1201, morphine_in_opium=30), 'nothing manufactured in particular', classA)
S.section('5 and 7, sixth column: a drug containing two specified quantities (fork F4)')
sched('5', A, qty(cocaine=25, diamorphine=12), 'nothing manufactured in particular', LIFE)
S.raw('REFUSED `the Second Schedule punishment` "5" `Class A drug` `%s` `nothing manufactured in particular`' % qty(cocaine=35, cannabis=400))
sched('5', A, qty(cocaine=35, diamorphine=16), 'nothing manufactured in particular', 'Death')

S.section('6, sixth column: manufacture of morphine, diamorphine, cocaine, methamphetamine')
for sqn in ['morphine manufactured', 'diamorphine manufactured', 'cocaine manufactured', 'methamphetamine manufactured']:
    for cls in [A, C]:
        sched('6', cls, qty(), sqn, 'Death')

S.section('8(a). possession: below, within and above each band, as printed')
LOW = 'Maximum 10 years or $20,000 or both (subject to section 33(3B))'
MID = 'Maximum 20 years and 10 strokes; Minimum 10 years and 5 strokes'
TOP = 'Maximum 30 years and 15 strokes; Minimum 20 years and 10 strokes'
POSS = [('cannabis', 330, 500), ('cannabis mixture', 660, 1000), ('cannabis resin', 130, 200), ('cocaine', 20, 30), ('diamorphine', 10, 15), ('methamphetamine', 167, 250), ('morphine', 20, 30)]
for sub, lo, hi in POSS:
    sched('8(a)', A, qty(**{sub: lo - 1}), 'nothing manufactured in particular', LOW)
    sched('8(a)', A, qty(**{sub: lo}), 'nothing manufactured in particular', MID)
    sched('8(a)', A, qty(**{sub: hi}), 'nothing manufactured in particular', MID)
    sched('8(a)', A, qty(**{sub: hi + 1}), 'nothing manufactured in particular', TOP)
sched('8(a)', B, qty(opium=799), 'nothing manufactured in particular', LOW)
sched('8(a)', B, qty(opium=800, morphine_in_opium=20), 'nothing manufactured in particular', MID)
sched('8(a)', B, qty(opium=1200, morphine_in_opium=20), 'nothing manufactured in particular', MID)
sched('8(a)', B, qty(opium=1201, morphine_in_opium=31), 'nothing manufactured in particular', TOP)
sched('8(a)', B, qty(opium=1000, morphine_in_opium=10), 'nothing manufactured in particular', LOW)       # no band: 8(a)(9)
sched('8(a)', C, qty(), 'nothing manufactured in particular', LOW)                                      # 8(a)(9): any other controlled drug

S.section('11, 11E: by class; the seventh column; and the sections that are not in the Schedule')
for sec, rows in [('11', [(A, 'Maximum 10 years or $40,000 or both; Minimum 2 years or $4,000 or both'), (B, 'Maximum 10 years or $40,000 or both; Minimum 2 years or $4,000 or both'),
                          (C, 'Maximum 5 years or $10,000 or both; Minimum 12 months or $2,000 or both')]),
                  ('11E', [(A, 'Maximum 30 years and 15 strokes; Minimum 10 years and 10 strokes'), (B, 'Maximum 30 years and 15 strokes; Minimum 6 years and 6 strokes'),
                           (C, 'Maximum 20 years and 15 strokes; Minimum 4 years and 4 strokes')])]:
    for cls, printed in rows:
        sched(sec, cls, qty(), 'nothing manufactured in particular', printed)
for sec, printed in [('9', 'Maximum 3 years or $10,000 or both'), ('10', 'Maximum 20 years or $40,000 or both; Minimum 3 years or $5,000 or both'),
                     ('10A', 'Maximum 20 years or $200,000 or both'),
                     ('30(1)(a)', 'Maximum 3 years or $5,000 or both; Minimum 6 months or $1,000 or both'), ('30(1)(b)', 'Maximum 3 years or $5,000 or both; Minimum 6 months or $1,000 or both'),
                     ('30(1)(c)', 'Maximum 3 years or $5,000 or both; Minimum 6 months or $1,000 or both'), ('30(1)(d)', 'Maximum 12 months or $5,000 or both'),
                     ('31(2A)', 'Maximum 4 years or $10,000 or both'), ('31A(2A)', 'Maximum 4 years or $10,000 or both'), ('31B(2)', 'Maximum 2 years or $5,000 or both')]:
    sched(sec, NC, qty(), 'nothing manufactured in particular', printed)
S.raw('REFUSED `the Second Schedule punishment` "99" `Class A drug` `no quantities` `nothing manufactured in particular`')
S.raw('REFUSED `the Second Schedule punishment` "8(b)" `Class A drug` `no quantities` `nothing manufactured in particular`')

S.section('33(4A), (4B), (4D): trafficking, import and export')
AN = 'Antecedent Facts'
P1, A21, RECIP, ADM, SAFA = 'under section 5(1), 7, 11F(1) or 11H(1)', 'is 21 years', 'intended recipient', 'previous admissions', 'consumption of a specified drug under section 34'
S.case('no antecedents', AN)
S.case('previous trafficking conviction', AN, P1)
S.case('adult, young recipient', AN, A21, RECIP)
S.case('under 21, young recipient', AN, RECIP)
S.case('adult, no young recipient', AN, A21)
S.case('previous conviction and adult, young recipient', AN, P1, A21, RECIP)
REP = {A: 'Maximum 30 years; Minimum 10 years and 10 strokes', B: 'Maximum 30 years; Minimum 6 years and 6 strokes', C: 'Maximum 20 years; Minimum 4 years and 4 strokes'}
def band(cls):
    mx, mn = {A: (360, 120), B: (360, 72), C: (240, 48)}[cls]; ms = {A: 10, B: 6, C: 4}[cls]
    return '(`Punishment` OF FALSE, FALSE, %d, %d, 0, 0, %d, 15, FALSE)' % (mx, mn, ms)
for sec in ['5', '7']:
    for cls in [A, B, C]:
        for anc in ['previous trafficking conviction', 'adult, young recipient', 'previous conviction and adult, young recipient']:
            S.raw('`the two punishments are the same` (`the punishment on conviction of an offence under section 5(1) or 7` "%s" %s `no quantities` `nothing manufactured in particular` %s) %s' % (sec, q(cls), q(anc), band(cls)))
        for anc in ['no antecedents', 'under 21, young recipient', 'adult, no young recipient']:
            S.raw('`the two punishments are the same` (`the punishment on conviction of an offence under section 5(1) or 7` "%s" %s `no quantities` `nothing manufactured in particular` %s) (`the Second Schedule punishment` "%s" %s `no quantities` `nothing manufactured in particular`)' % (sec, q(cls), q(anc), sec, q(cls)))
    # 33(4D): where the sixth column applies, 4A and 4B do not
    S.raw('`the two punishments are the same` (`the punishment on conviction of an offence under section 5(1) or 7` "%s" `Class A drug` `%s` `nothing manufactured in particular` `previous conviction and adult, young recipient`) %s' % (sec, qty(cannabis=501), parse('Death')))
    S.raw('`the two punishments are the same` (`the punishment on conviction of an offence under section 5(1) or 7` "%s" `Class A drug` `%s` `nothing manufactured in particular` `adult, young recipient`) %s' % (sec, qty(cannabis=400), parse(LIFE)))

S.section('33(3B). repeat possession')
S.case('previous possession conviction', AN, 'a previous conviction under section 8(a) or 11I(1)(a)')
for sub, lo, hi in POSS[:3]:
    S.raw('`the two punishments are the same` (`the punishment on conviction of an offence under section 8(a)` `Class A drug` `%s` `nothing manufactured in particular` `previous possession conviction`) %s' % (qty(**{sub: lo - 1}), '(`Punishment` OF FALSE, FALSE, 120, 24, 20000, 0, 0, 0, FALSE)'))
    S.raw('`the two punishments are the same` (`the punishment on conviction of an offence under section 8(a)` `Class A drug` `%s` `nothing manufactured in particular` `previous possession conviction`) %s' % (qty(**{sub: lo}), parse(MID)))
    S.raw('`the two punishments are the same` (`the punishment on conviction of an offence under section 8(a)` `Class A drug` `%s` `nothing manufactured in particular` `no antecedents`) %s' % (qty(**{sub: lo - 1}), parse(LOW)))
S.raw('`the two punishments are the same` (`the punishment on conviction of an offence under section 8(a)` `Class A drug` `no quantities` `nothing manufactured in particular` `previous possession conviction`) (`Punishment` OF FALSE, FALSE, 120, 24, 20000, 0, 0, 0, FALSE)')
S.raw('`the two punishments are the same` (`the punishment on conviction of an offence under section 8(a)` `Class A drug` `no quantities` `nothing manufactured in particular` `no antecedents`) %s' % parse(LOW))

S.section('33(3A), (4), (4AA), (4AB), 33A. consumption and failures to provide a specimen')
SPEC, OTHER, URINE, HAIR = 'Consumption of a specified drug (section 8(b)(ii))', 'Consumption of another controlled drug (section 8(b)(i))', 'Failure to provide a urine specimen (section 31(2))', 'Failure to provide a hair specimen (section 31A(2))'
POST, PRE = 'committed on or after 1 April 2019', 'x'
def cons(name, offence, anc, printed):
    S.raw('`the two punishments are the same` (`the punishment on conviction of consumption or of failing to provide a specimen` %s %s) %s' % (q(offence), q(anc), printed))
THREE_A = '(`Punishment` OF FALSE, FALSE, 120, 12, 20000, 0, 0, 0, FALSE)'   # 33(3A): not less than 1 year, not more than 10 years, fine not exceeding $20,000
MIN3 = '(`Punishment` OF FALSE, FALSE, 0, 36, 0, 0, 0, 0, FALSE)'            # not less than 3 years
S33A = '(`Punishment` OF FALSE, FALSE, 84, 60, 0, 0, 3, 6, FALSE)'           # 5 to 7 years and 3 to 6 strokes
S33A2 = '(`Punishment` OF FALSE, FALSE, 156, 84, 0, 0, 6, 12, FALSE)'        # 7 to 13 years and 6 to 12 strokes
S.case('first offence after 1 April 2019', AN, POST)
S.case('first offence before 1 April 2019', AN)
S.case('previous 8(b) conviction after 2019', AN, POST, 'under section 8(b) or 31(2)', 'under section 8(b), 11I(1)(b), 31(2) or 31A(2)')
S.case('previous 8(b) conviction before 2019', AN, 'under section 8(b) or 31(2)', 'under section 8(b), 11I(1)(b), 31(2) or 31A(2)')
S.case('previous psychoactive consumption conviction, after 2019', AN, POST, 'under section 11I(1)(b) or 31A(2)', 'under section 8(b), 11I(1)(b), 31(2) or 31A(2)')
S.case('previous admission, after 2019', AN, POST, 'previous admission under section 34(2)')
S.case('previous military consumption conviction, after 2019', AN, POST, 'consumption of a controlled drug or psychoactive substance under section 34')
S.case('previous admission, before 2019', AN, 'previous admission under section 34(2)')
S.case('2 previous admissions', AN, POST, **{'the number of the accused\'s previous admissions': 2})
S.case('2 previous specified-drug convictions', AN, POST, **{'previous convictions for consumption of a specified drug under section 8(b)': 2})
S.case('2 previous urine failures', AN, POST, **{'previous convictions for failure to provide a urine specimen': 2})
S.case('1 admission and 1 specified-drug conviction', AN, POST, **{'the number of the accused\'s previous admissions': 1, 'previous convictions for consumption of a specified drug under section 8(b)': 1})
S.case('1 admission and 1 urine failure', AN, POST, **{'the number of the accused\'s previous admissions': 1, 'previous convictions for failure to provide a urine specimen': 1})
S.case('1 specified-drug conviction and 1 urine failure', AN, POST, **{'previous convictions for consumption of a specified drug under section 8(b)': 1, 'previous convictions for failure to provide a urine specimen': 1})
S.case('1 admission only', AN, POST, **{'the number of the accused\'s previous admissions': 1})
S.case('1 specified-drug conviction only', AN, POST, **{'previous convictions for consumption of a specified drug under section 8(b)': 1})
S.case('2 previous hair failures', AN, POST, **{'previous convictions for failure to provide a hair specimen': 2})
S.case('2 previous military convictions', AN, POST, **{'previous convictions for consumption of a specified drug under section 34 of the Singapore Armed Forces Act 1972': 2})
S.case('1 specified-drug conviction and 1 hair failure', AN, POST, **{'previous convictions for consumption of a specified drug under section 8(b)': 1, 'previous convictions for failure to provide a hair specimen': 1})
S.case('1 urine failure and 1 hair failure', AN, POST, **{'previous convictions for failure to provide a urine specimen': 1, 'previous convictions for failure to provide a hair specimen': 1})
S.case('2 previous admissions, before 2019', AN, **{'the number of the accused\'s previous admissions': 2})
S.case('convicted under 33A already', AN, POST, 'convicted under section 33A(1), (1A) or (1B)', **{'the number of the accused\'s previous admissions': 2})
for o in [SPEC, OTHER, URINE, HAIR]:
    cons('first', o, 'first offence after 1 April 2019', THREE_A)
    S.raw('REFUSED `the punishment on conviction of consumption or of failing to provide a specimen` %s `first offence before 1 April 2019`' % q(o))
cons('4', SPEC, 'previous 8(b) conviction after 2019', MIN3)
cons('4', OTHER, 'previous 8(b) conviction after 2019', MIN3)
cons('4', URINE, 'previous 8(b) conviction after 2019', MIN3)
cons('4', OTHER, 'previous 8(b) conviction before 2019', MIN3)       # 33(4) has no date
cons('4AA', OTHER, 'previous psychoactive consumption conviction, after 2019', MIN3)
cons('4AA', OTHER, 'previous admission, after 2019', MIN3)
cons('4AA', URINE, 'previous military consumption conviction, after 2019', MIN3)
cons('4AB', HAIR, 'previous 8(b) conviction after 2019', MIN3)
cons('4AB', HAIR, 'previous admission, after 2019', MIN3)
cons('4AB', HAIR, 'previous psychoactive consumption conviction, after 2019', MIN3)
S.raw('REFUSED `the punishment on conviction of consumption or of failing to provide a specimen` %s `previous admission, before 2019`' % q(OTHER))
for anc in ['2 previous admissions', '2 previous specified-drug convictions', '2 previous urine failures', '1 admission and 1 specified-drug conviction', '1 admission and 1 urine failure', '1 specified-drug conviction and 1 urine failure']:
    cons('33A(1)', SPEC, anc, S33A); cons('33A(1)', URINE, anc, S33A); cons('33A(1A)', HAIR, anc, S33A)
cons('33A(1)', OTHER, '2 previous admissions', THREE_A)   # 8(b) of a drug that is not a specified drug is outside 33A
for anc in ['1 admission only', '1 specified-drug conviction only']:
    cons('no 33A', SPEC, anc, THREE_A)
for anc in ['2 previous hair failures', '2 previous military convictions', '1 specified-drug conviction and 1 hair failure', '1 urine failure and 1 hair failure']:
    for o in [SPEC, URINE, HAIR]:
        cons('33A(1B)', o, anc, S33A)
cons('33A(1B)', OTHER, '2 previous hair failures', THREE_A)
S.raw('`the two punishments are the same` (`the punishment on conviction of consumption or of failing to provide a specimen` %s `convicted under 33A already`) %s' % (q(SPEC), S33A2))
S.raw('`the two punishments are the same` (`the punishment on conviction of consumption or of failing to provide a specimen` %s `convicted under 33A already`) %s' % (q(URINE), S33A2))
S.raw('`the two punishments are the same` (`the punishment on conviction of consumption or of failing to provide a specimen` %s `convicted under 33A already`) %s' % (q(HAIR), S33A2))
S.raw('NOT `the two punishments are the same` (`the punishment on conviction of consumption or of failing to provide a specimen` %s `convicted under 33A already`) %s' % (q(OTHER), S33A2))
S.yes('section 33A(1), (1A) or (1B) applies', SPEC, '2 previous admissions')
S.no('section 33A(1), (1A) or (1B) applies', HAIR, '2 previous admissions, before 2019')
S.yes('section 33A(1), (1A) or (1B) applies', SPEC, '2 previous admissions, before 2019')

S.section('33(3C), (3D): consumption of a psychoactive substance')
S.case('no previous consumption', AN)
S.case('previous 11I(1)(b) conviction', AN, 'under section 8(b), 11I(1)(b), 31(2) or 31A(2)')
S.case('previous admission', AN, 'previous admission under section 34(2)')
S.case('previous military conviction', AN, 'consumption of a controlled drug or psychoactive substance under section 34')
S.raw('`the two punishments are the same` (`the punishment on conviction of an offence under section 11I(1)(b)` `no previous consumption`) (`Punishment` OF FALSE, FALSE, 120, 0, 20000, 0, 0, 0, TRUE)')
for anc in ['previous 11I(1)(b) conviction', 'previous admission', 'previous military conviction']:
    S.raw('`the two punishments are the same` (`the punishment on conviction of an offence under section 11I(1)(b)` %s) (`Punishment` OF FALSE, FALSE, 120, 36, 0, 0, 0, 0, FALSE)' % q(anc))

S.section('33(4C), 11A and the other bands the sections state')
S.case('a young gathering, adult organiser', AN, A21, 'gathering consists')
S.case('a young gathering, organiser under 21', AN, 'gathering consists')
S.case('an adult gathering, adult organiser', AN, A21)
S.raw('`the two punishments are the same` (`the punishment on conviction of an offence under section 11A` `a young gathering, adult organiser`) (`Punishment` OF FALSE, FALSE, 240, 60, 0, 0, 3, 10, FALSE)')
for anc in ['a young gathering, organiser under 21', 'an adult gathering, adult organiser']:
    S.raw('`the two punishments are the same` (`the punishment on conviction of an offence under section 11A` %s) (`Punishment` OF FALSE, FALSE, 240, 36, 0, 0, 0, 10, FALSE)' % q(anc))
def sect(offence, rep, enh, printed):
    S.raw('`the two punishments are the same` (`the punishment the section states for the offence` "%s" %s %s) %s' % (offence, rep, enh, printed))
def E(maxm=0, minm=0, maxf=0, minf=0, mins=0, maxs=0, alt=False):
    return '(`Punishment` OF FALSE, FALSE, %d, %d, %d, %d, %d, %d, %s)' % (maxm, minm, maxf, minf, mins, maxs, 'TRUE' if alt else 'FALSE')
Y = 12
sect('11B(1) or (2)', 'FALSE', 'FALSE', E(maxm=10 * Y)); sect('11B(1) or (2)', 'TRUE', 'FALSE', E(maxm=10 * Y, minm=2 * Y))
sect('11C(1)', 'FALSE', 'FALSE', E(maxm=10 * Y)); sect('11C(1)', 'TRUE', 'FALSE', E(maxm=10 * Y, minm=2 * Y))
sect('11D(1)', 'TRUE', 'FALSE', E(maxm=10 * Y, minm=2 * Y)); sect('11D(2)', 'FALSE', 'FALSE', E(maxm=5 * Y, maxf=10000, alt=True)); sect('11D(2)', 'TRUE', 'FALSE', E(maxm=5 * Y, minm=12))
sect('11F(1)', 'FALSE', 'FALSE', E(maxm=10 * Y, minm=2 * Y, maxf=10000, minf=4000))
sect('11F(1)', 'TRUE', 'FALSE', E(maxm=20 * Y, minm=4 * Y, maxf=20000, minf=8000))
sect('11F(1)', 'FALSE', 'TRUE', E(maxm=20 * Y, minm=4 * Y, mins=4, maxs=15))
sect('11F(1)', 'TRUE', 'TRUE', E(maxm=20 * Y, minm=4 * Y, mins=4, maxs=15))
sect('11G(1)', 'FALSE', 'FALSE', E(maxm=20 * Y, minm=5 * Y, maxf=20000, minf=10000))
sect('11H(1)', 'FALSE', 'FALSE', E(maxm=20 * Y, minm=3 * Y, maxf=20000, minf=6000)); sect('11H(1)', 'TRUE', 'FALSE', E(maxm=20 * Y, minm=4 * Y, maxf=20000, minf=8000))
sect('11H(1)', 'TRUE', 'TRUE', E(maxm=20 * Y, minm=4 * Y, mins=4, maxs=15))
sect('11I(1)(a)', 'FALSE', 'FALSE', E(maxm=10 * Y, maxf=20000, alt=True)); sect('11I(1)(a)', 'TRUE', 'FALSE', E(maxm=10 * Y, minm=2 * Y, maxf=20000))
sect('11K(1)', 'FALSE', 'FALSE', E(maxm=3 * Y, maxf=10000, alt=True)); sect('11L(1)', 'FALSE', 'FALSE', E(maxm=5 * Y, minm=12, maxf=10000, minf=2000, alt=True))
sect('11M(1)', 'FALSE', 'FALSE', E(maxm=20 * Y, minm=3 * Y, maxs=10)); sect('11M(1)', 'FALSE', 'TRUE', E(maxm=20 * Y, minm=5 * Y, mins=3, maxs=10))
sect('11N(1) or (2)', 'FALSE', 'FALSE', E(maxm=10 * Y)); sect('11N(1) or (2)', 'TRUE', 'FALSE', E(maxm=10 * Y, minm=2 * Y))
sect('11O(1)', 'TRUE', 'FALSE', E(maxm=10 * Y, minm=2 * Y)); sect('11P(1)', 'FALSE', 'FALSE', E(maxm=10 * Y)); sect('11P(2)', 'TRUE', 'FALSE', E(maxm=5 * Y, minm=12))
sect('11Q(1)', 'FALSE', 'FALSE', E(maxm=20 * Y, minm=4 * Y, mins=4, maxs=15))
sect('13(a) or (c)', 'FALSE', 'FALSE', E(maxm=10 * Y, minm=2 * Y, maxf=40000, minf=4000, alt=True))
sect('34A(2)', 'FALSE', 'FALSE', E(maxf=5000)); sect('38A(5)', 'FALSE', 'FALSE', E(maxf=1500)); sect('40B(4)(a)', 'FALSE', 'FALSE', E(maxm=1, maxf=1000, alt=True))
S.raw('REFUSED `the punishment the section states for the offence` "99" FALSE FALSE')

S.section('33B. discretion of the court not to impose the sentence of death')
SB = 'Section 33B Facts'
CONV, RESTR, CERT, ABN = 'is convicted of an offence under section 5(1) or 7', 'involvement was restricted', 'certifies to a court', 'abnormality of mind'
S.case('33B certified courier', SB, CONV, RESTR, CERT)
S.case('33B courier with abnormality of mind', SB, CONV, RESTR, ABN)
S.case('33B courier with both', SB, CONV, RESTR, CERT, ABN)
S.case('33B certified, not a courier', SB, CONV, CERT)
S.case('33B courier, nothing more', SB, CONV, RESTR)
S.case('33B not convicted of a capital offence', SB, RESTR, CERT)
S.raw('`the sentence where the sixth column punishment is death` `33B certified courier` EQUALS `The court may impose imprisonment for life and not fewer than 15 strokes of the cane instead (section 33B(1)(a))`')
S.raw('`the sentence where the sixth column punishment is death` `33B courier with abnormality of mind` EQUALS `The court must impose imprisonment for life instead (section 33B(1)(b))`')
S.raw('`the sentence where the sixth column punishment is death` `33B courier with both` EQUALS `The court must impose imprisonment for life instead (section 33B(1)(b))`')
S.raw('`the sentence where the sixth column punishment is death` `33B certified, not a courier` EQUALS `The sentence of death stands`')
S.raw('`the sentence where the sixth column punishment is death` `33B courier, nothing more` EQUALS `The sentence of death stands`')
S.raw('REFUSED `the sentence where the sixth column punishment is death` `33B not convicted of a capital offence`')

S.section('The quantity bands: boundaries')
BD = 'Quantity Band'
S.case('band 330 to 500', BD, 'lower bound is inclusive', 'upper bound is inclusive', **{'lower bound in grammes': 330, 'upper bound in grammes': 500})
S.case('band more than 500', BD, **{'lower bound in grammes': 500})
S.case('band less than 330', BD, **{'upper bound in grammes': 330})
S.yes('the quantity falls within the band', 'band 330 to 500', 330, 0); S.yes('the quantity falls within the band', 'band 330 to 500', 500, 0)
S.no('the quantity falls within the band', 'band 330 to 500', 329.9, 0); S.no('the quantity falls within the band', 'band 330 to 500', 500.1, 0)
S.yes('the quantity falls within the band', 'band more than 500', 500.1, 0); S.no('the quantity falls within the band', 'band more than 500', 500, 0)
S.yes('the quantity falls within the band', 'band less than 330', 329.9, 0); S.no('the quantity falls within the band', 'band less than 330', 330, 0)
S.no('the quantity falls within the band', 'band less than 330', 0, 0)
S.o.write(os.path.join(ROW, 'mda-tests-punishment.l4'))

# ======================================================================================================================== enforcement
S = Suite("""IMPORT prelude
IMPORT `written-law-interface`
IMPORT `mda-types`
IMPORT `mda-enforcement`

-- Tests for mda-enforcement.l4 (Misuse of Drugs Act 1973, ss 24 to 28, 30 to 32, 53).
-- Expected values are read off the Act's text.  Generated by generators/mda_tests_2.py.""")
BUREAU, DIRECTOR, SGT, JUNIOR, SPECIAL, SENIOR, CUSTOMS, IMM, SAF, OTHERP = ('an officer of the Bureau', 'the Director of the Central Narcotics Bureau', 'a police officer not below the rank of sergeant', 'a police officer below the rank of sergeant',
    'a special police officer', 'a senior officer of customs', 'an officer of customs who is not a senior officer of customs', 'an immigration officer',
    'a serving member of the Singapore Armed Forces appointed by the Minister as an enforcement officer', 'some other person')
ALL = [BUREAU, DIRECTOR, SGT, JUNIOR, SPECIAL, SENIOR, CUSTOMS, IMM, SAF, OTHERP]
def only(pred, who, *args):
    for r in ALL:
        (S.yes if r in who else S.no)(pred, r, *args)

S.section('The officers')
only('the officer is a police officer of any rank', [SGT, JUNIOR])
only('the officer is an officer of customs', [SENIOR, CUSTOMS])
only('the officer is an officer of the Bureau', [BUREAU, DIRECTOR])
S.section('24. search of premises without a warrant: the officers named, and a non-senior customs officer is not')
only('the officer is one section 24(1) names', [BUREAU, DIRECTOR, SGT, JUNIOR, SPECIAL, SENIOR])
SP = 'Search Premises Facts'
S.case('suspects a drug in the premises', SP, 'a controlled drug, controlled substance, psychoactive substance or article liable to seizure')
S.case('suspects a vehicle', SP, 'a vehicle, autonomous vehicle, unmanned aircraft')
S.case('suspects an offender', SP, 'a person who has committed or is reasonably suspected')
S.case('suspects nothing', SP)
S.case('suspects a drug in the premises and the thing found', SP, 'a controlled drug, controlled substance, psychoactive substance or article liable to seizure', 'a thing found is a controlled drug')
S.case('suspects only the thing found', SP, 'a thing found is a controlled drug')
for v in ['suspects a drug in the premises', 'suspects a vehicle', 'suspects an offender']:
    only('the officer may without a warrant enter and search the place or premises', [BUREAU, DIRECTOR, SGT, JUNIOR, SPECIAL, SENIOR], v)
    only('the officer may search a person found in the place or premises', [BUREAU, DIRECTOR, SGT, JUNIOR, SPECIAL, SENIOR], v)
S.no('the officer may without a warrant enter and search the place or premises', BUREAU, 'suspects nothing')
S.no('the officer may without a warrant enter and search the place or premises', BUREAU, 'suspects only the thing found')
S.yes('the officer may seize and detain what is found', BUREAU, 'suspects a drug in the premises and the thing found')
S.no('the officer may seize and detain what is found', BUREAU, 'suspects a drug in the premises')
S.no('the officer may seize and detain what is found', CUSTOMS, 'suspects a drug in the premises and the thing found')

S.section('25 and 25A. arrest, search of a woman, bail')
only('the officer is one section 25(1) names', [BUREAU, DIRECTOR, SGT, JUNIOR, SPECIAL, SENIOR, CUSTOMS])
AR = 'Arrest Facts'
S.case('has committed', AR, 'the person has committed an offence under this Act or an arrestable offence under the regulations')
S.case('reasonably suspected', AR, 'reasonably suspects that the person has committed')
S.case('no ground', AR)
S.case('woman arrested, man searches', AR, 'the person has committed an offence under this Act or an arrestable offence under the regulations', 'the person to be searched is a woman')
S.case('woman arrested, woman searches', AR, 'the person has committed an offence under this Act or an arrestable offence under the regulations', 'the person to be searched is a woman', 'the searcher is a woman')
S.case('man arrested, woman searches', AR, 'the person has committed an offence under this Act or an arrestable offence under the regulations', 'the searcher is a woman')
for v in ['has committed', 'reasonably suspected']:
    only('the officer may arrest and search the person without a warrant', [BUREAU, DIRECTOR, SGT, JUNIOR, SPECIAL, SENIOR, CUSTOMS], v)
S.no('the officer may arrest and search the person without a warrant', BUREAU, 'no ground')
S.no('the search of the person arrested is permitted', BUREAU, 'woman arrested, man searches')
S.yes('the search of the person arrested is permitted', BUREAU, 'woman arrested, woman searches')
S.yes('the search of the person arrested is permitted', BUREAU, 'man arrested, woman searches')
S.yes('the search of the person arrested is permitted', BUREAU, 'has committed')
S.no('the search of the person arrested is permitted', IMM, 'woman arrested, woman searches')
for r in ALL:
    (S.yes if r in [BUREAU, DIRECTOR] else S.no)('the person may be released on bail or on personal bond granted by the grantor', 'TRUE', r)
    S.no('the person may be released on bail or on personal bond granted by the grantor', 'FALSE', r)

S.section('26. search of a ship, hovercraft, aircraft, vehicle or train; and of persons arriving or departing')
SV = 'Search Vessel Facts'
S.case('suspects a drug in a ship', SV, 'in the ship, hovercraft, aircraft, vehicle or train')
S.case('suspects a drug in an unmanned aircraft', SV, 'in the autonomous vehicle, unmanned aircraft or unmanned vessel')
S.case('person arriving', SV, 'arriving in Singapore')
S.case('nothing suspected', SV)
only('the officer may stop, board and search the ship, hovercraft, aircraft, vehicle or train and search the persons in it', [BUREAU, DIRECTOR, SGT, JUNIOR, SPECIAL, SENIOR, CUSTOMS], 'suspects a drug in a ship')
only('the officer may intercept and search the autonomous vehicle, unmanned aircraft or unmanned vessel', [BUREAU, DIRECTOR, SGT, JUNIOR, SPECIAL, SENIOR, CUSTOMS], 'suspects a drug in an unmanned aircraft')
only('the officer may search the person arriving in or about to depart from Singapore', [BUREAU, DIRECTOR, SGT, JUNIOR, SPECIAL, SENIOR, CUSTOMS], 'person arriving')
S.no('the officer may stop, board and search the ship, hovercraft, aircraft, vehicle or train and search the persons in it', BUREAU, 'nothing suspected')
S.no('the officer may stop, board and search the ship, hovercraft, aircraft, vehicle or train and search the persons in it', BUREAU, 'suspects a drug in an unmanned aircraft')
S.no('the officer may intercept and search the autonomous vehicle, unmanned aircraft or unmanned vessel', BUREAU, 'suspects a drug in a ship')
S.no('the officer may search the person arriving in or about to depart from Singapore', BUREAU, 'nothing suspected')

S.section('27 and 28. forfeiture')
FF = 'Forfeiture Facts'
S.case('offence proved, drug used in it', FF, 'it is proved to the satisfaction', 'was the subject matter of or was used')
S.case('offence proved, drug not connected', FF, 'it is proved to the satisfaction')
S.case('drug connected, offence not proved', FF, 'was the subject matter of or was used')
S.yes('an order for the forfeiture of the drug, substance or article is to be made', 'offence proved, drug used in it')
S.no('an order for the forfeiture of the drug, substance or article is to be made', 'offence proved, drug not connected')
S.no('an order for the forfeiture of the drug, substance or article is to be made', 'drug connected, offence not proved')
S.case('no prosecution, month expired', FF, 'there is no prosecution', 'one month has expired')
S.case('no prosecution, month expired, claim made', FF, 'there is no prosecution', 'one month has expired', 'a claim to it was made')
S.case('no prosecution, month not expired', FF, 'there is no prosecution')
S.case('prosecution, month expired', FF, 'one month has expired')
S.yes('the drug, substance or article is deemed to be forfeited to the Government', 'no prosecution, month expired')
S.no('the drug, substance or article is deemed to be forfeited to the Government', 'no prosecution, month expired, claim made')
S.no('the drug, substance or article is deemed to be forfeited to the Government', 'no prosecution, month not expired')
S.no('the drug, substance or article is deemed to be forfeited to the Government', 'prosecution, month expired')
SHIP, VEH, PP_, BIG, OWNERX, CONVF = ('the ship, hovercraft, aircraft, unmanned aircraft or unmanned vessel, or a component, has been proved', 'the vehicle, autonomous vehicle or a component has been proved',
                                      'the Public Prosecutor applies', 'of more than 200 tons net', 'the owner establishes', 'a person has been convicted')
S.case('convicted, ship used', FF, CONVF, SHIP)
S.case('convicted, ship used, big ship', FF, CONVF, SHIP, BIG)
S.case('convicted, ship used, owner establishes', FF, CONVF, SHIP, OWNERX)
S.case('not convicted, ship used', FF, SHIP)
S.case('convicted, vehicle used, prosecutor applies', FF, CONVF, VEH, PP_)
S.case('convicted, vehicle used, no application', FF, CONVF, VEH)
S.case('convicted, vehicle used, prosecutor applies, owner establishes', FF, CONVF, VEH, PP_, OWNERX)
S.case('convicted, vehicle used, prosecutor applies, big-ship flag set', FF, CONVF, VEH, PP_, BIG)
S.yes('the court may order forfeiture of the ship, hovercraft, aircraft or unmanned craft', 'convicted, ship used')
S.no('the court may order forfeiture of the ship, hovercraft, aircraft or unmanned craft', 'convicted, ship used, big ship')
S.no('the court may order forfeiture of the ship, hovercraft, aircraft or unmanned craft', 'convicted, ship used, owner establishes')
S.no('the court may order forfeiture of the ship, hovercraft, aircraft or unmanned craft', 'not convicted, ship used')
S.yes('the court is to order forfeiture of the vehicle', 'convicted, vehicle used, prosecutor applies')
S.no('the court is to order forfeiture of the vehicle', 'convicted, vehicle used, no application')
S.no('the court is to order forfeiture of the vehicle', 'convicted, vehicle used, prosecutor applies, owner establishes')
S.yes('the court is to order forfeiture of the vehicle', 'convicted, vehicle used, prosecutor applies, big-ship flag set')

S.section('30. obstruction')
OB = 'Obstruction Facts'
for tag, frag in [('(a)', 'obstructed an officer'), ('(b)', 'failed to comply with a lawful requirement'), ('(c)', 'without reasonable excuse, failed to furnish'), ('(d)', 'furnished to such an officer')]:
    S.case('30(1)%s' % tag, OB, frag)
    for t2 in ['(a)', '(b)', '(c)', '(d)']:
        (S.yes if t2 == tag else S.no)('an offence under section 30(1)%s is made out' % t2, '30(1)%s' % tag)

S.section('31, 31A, 31B. specimens')
SS = 'Specimen Facts'
SUSP, DIRORD, FAILED, FAILORD, DIV, SEAL, NEG = ('reasonably suspects that the person has committed', 'the Director has ordered', 'failed, without reasonable excuse, to provide', 'failed, without reasonable excuse, to comply',
                                                 'divided into 3 parts', 'each of the remaining 2 parts', 'preliminary urine test was negative')
S.case('suspected, failed to provide', SS, SUSP, FAILED)
S.case('suspected, provided', SS, SUSP)
S.case('failed to provide, not suspected', SS, FAILED)
S.case('Director ordered, failed to comply', SS, DIRORD, FAILORD)
S.case('Director ordered, complied', SS, DIRORD)
S.case('failed to comply, no order', SS, FAILORD)
only('the officer may require a specimen of urine', [BUREAU, DIRECTOR, SGT, IMM, SAF], 'suspected, provided')
only('the officer may require a specimen of hair or oral fluid', [BUREAU, DIRECTOR, SGT, IMM], 'suspected, provided')
S.no('the officer may require a specimen of urine', BUREAU, 'failed to provide, not suspected')
only('an offence under section 31(2) is made out', [BUREAU, DIRECTOR, SGT, IMM, SAF], 'suspected, failed to provide')
only('an offence under section 31A(2) is made out', [BUREAU, DIRECTOR, SGT, IMM], 'suspected, failed to provide')
only('an offence under section 31B(2) is made out', [BUREAU, DIRECTOR, SGT, IMM], 'suspected, failed to provide')
S.no('an offence under section 31(2) is made out', BUREAU, 'suspected, provided')
S.no('an offence under section 31(2) is made out', BUREAU, 'failed to provide, not suspected')
S.yes('an offence under section 31(2A) is made out', 'Director ordered, failed to comply')
S.no('an offence under section 31(2A) is made out', 'Director ordered, complied')
S.no('an offence under section 31(2A) is made out', 'failed to comply, no order')
S.case('urine specimen divided and tested properly', SS, DIV, SEAL)
S.case('urine specimen divided, parts not sealed and tested', SS, DIV)
S.case('urine specimen not divided', SS, SEAL)
S.yes('the urine specimen has been dealt with as section 31(4) requires', 'urine specimen divided and tested properly')
S.no('the urine specimen has been dealt with as section 31(4) requires', 'urine specimen divided, parts not sealed and tested')
S.no('the urine specimen has been dealt with as section 31(4) requires', 'urine specimen not divided')
S.case('preliminary test negative', SS, NEG)
S.yes('the officer may discard the remaining 2 parts of the specimen', 'preliminary test negative')
S.no('the officer may discard the remaining 2 parts of the specimen', 'urine specimen divided and tested properly')

S.section('32. investigation by officers of the Bureau')
for r in ALL:
    (S.yes if r in [BUREAU, DIRECTOR] else S.no)('the officer has all the powers of a police officer in relation to an investigation into an arrestable offence', r, 'TRUE')
    S.no('the officer has all the powers of a police officer in relation to an investigation into an arrestable offence', r, 'FALSE')
only('the officer is deemed to be an officer not below the rank of inspector of police', [BUREAU, DIRECTOR])

S.section('53 and the statement the Act gives the Code')
CF = 'Court Facts'
S.case('the punishment is death', CF, 'the punishment in question is the punishment of death')
S.case('the punishment is not death', CF)
S.no('a District Court has power to impose the punishment', 'the punishment is death')
S.yes('a District Court has power to impose the punishment', 'the punishment is not death')
S.raw('(`the Misuse of Drugs Act 1973\'s statement about its offences`)\'s `the Act` EQUALS "Misuse of Drugs Act 1973"')
S.raw('(`the Misuse of Drugs Act 1973\'s statement about its offences`)\'s `the Act empowers the police to arrest without warrant for the offence`')
S.raw('NOT (`the Misuse of Drugs Act 1973\'s statement about its offences`)\'s `the Act deems the offence to be an arrestable offence for the purposes of the Criminal Procedure Code 2010`')
S.raw('(`the Misuse of Drugs Act 1973\'s statement about its offences`)\'s `the Act shows the offence as triable by a District Court under that Act`')
S.raw('NOT (`the Misuse of Drugs Act 1973\'s statement about its offences`)\'s `the Act shows the offence as triable by a Magistrate\'s Court under that Act`')
S.o.write(os.path.join(ROW, 'mda-tests-enforcement.l4'))
print('mda_tests_2 written')
