#!/usr/bin/env python3
"""Run every census scenario through every question, on two dates, and write CENSUS.md.

Generates census-cells.l4 (one #EVAL per cell, nothing else), runs it with
`l4 run --json`, and lays the results out as tables. No value in CENSUS.md is typed by
hand: each cell is the printed result of one #EVAL, or the refusal it produced.

Usage: L4=/path/to/l4 python3 census.py
"""
import json, os, re, subprocess, pathlib, datetime

HERE = pathlib.Path(__file__).resolve().parent
L4 = os.environ.get("L4", "l4")
SCENARIOS = ["S%02d" % i for i in range(1, 13)]
DATES = [("1 October 2026", "`1 October 2026`"), ("1 February 2027", "`1 February 2027`")]

# (column heading, L4 function, takes a date?)
DUTY = [
    ("EU 50(2) provider must mark", "`EU 50(2): the provider must ensure it is marked`", True),
    ("WA s.2(1) provider must include provenance data", "`WA s.2(1): the provider must include provenance data`", True),
    ("CA 22757.3(a) provider must include latent disclosure", "`CA 22757.3(a): the provider must include a latent disclosure`", True),
    ("all three agree", "`the three regimes agree on whether it must be marked`", True),
]
ENOUGH = [
    ("EU Code 1.1 marking meets Measure 1.1", "`EU Code 1.1: its marking meets Measure 1.1`", False),
    ("WA s.2(2) deemed compliant (C2PA safe harbour)", "`WA s.2(2): its provenance data is deemed compliant`", False),
    ("CA 22757.3(a)(1) items not conveyed", "`CA 22757.3(a)(1): the items it does not convey`", True),
    ("CA 22757.3(a) disclosure meets the section", "`CA 22757.3(a): its disclosure meets the section`", True),
]
DISPLAY = [
    ("EU 50(4) deep fake: deployer must disclose", "`EU 50(4): what a deployer must disclose of a deep fake`", True),
    ("EU 50(4) text: deployer must disclose", "`EU 50(4): what a deployer must disclose of public-interest text`", True),
    ("CA 22757.3.1 large platform's interface must show", "`CA 22757.3.1: what the platform's interface must make available`", True),
]

SHORT = {
    "TRUE": "yes", "FALSE": "no", "EMPTY": "none missing",
    "`no disclosure under Article 50(4)`": "no",
    "`disclosure that the content has been artificially generated or manipulated`": "**disclose**",
    "`disclosure of the existence of such generated or manipulated content, in a manner that does not hamper the display or enjoyment of the work`": "**disclose, limited (artistic work)**",
    "`nothing under 22757.3.1`": "nothing (not yet operative)",
}

def render(r):
    if r["kind"] == "refused":
        return "REFUSES: " + r["reason"].strip()
    v = r["value"].strip()
    if v in SHORT:
        return SHORT[v]
    m = re.match(r"`the interface must make available` OF (TRUE|FALSE), (NOTHING|\(JUST OF \"[^\"]*\"\)), (TRUE|FALSE)$", v)
    if m:
        name = "none named" if m.group(2) == "NOTHING" else "names " + m.group(2)[len("(JUST OF "):-1]
        return "provenance data: %s; %s; signatures: %s" % (SHORT[m.group(1)], name, SHORT[m.group(3)])
    if v.startswith("LIST "):
        return ", ".join(x.strip().strip("`").split(")")[0] + ")" for x in v[5:].split(","))
    return v

def main():
    cells, lines = [], [
        "-- GENERATED by census.py: one #EVAL per census cell. Do not edit by hand.",
        "", "IMPORT prelude", "IMPORT `census`", "IMPORT `test-kit`", ""]
    for dlabel, dexpr in DATES:
        for s in SCENARIOS:
            for col, fn, dated in DUTY + ENOUGH + DISPLAY:
                lines.append("#EVAL %s `%s`%s" % (fn, s, (" " + dexpr) if dated else ""))
                cells.append((dlabel, s, col))
    (HERE / "census-cells.l4").write_text("\n".join(lines) + "\n")
    out = subprocess.run([L4, "run", str(HERE / "census-cells.l4"), "--json"], capture_output=True, text=True, cwd=HERE)
    results = json.loads(out.stdout)["results"]
    assert len(results) == len(cells), (len(results), len(cells))
    labels = {}
    # scenario labels, read from census.l4 so they match the module
    for m in re.finditer(r"^`(S\d\d)` MEANS\n    `scenario` \"([^\"]*)\"", (HERE / "census.l4").read_text(), re.M):
        labels[m.group(1)] = m.group(2)[4:]
    table = {}
    for (dlabel, s, col), r in zip(cells, results):
        table[(dlabel, s, col)] = render(r)
    # An "is it enough?" cell only matters where that regime imposes the duty. Where it
    # does not, say so instead of printing a value that reads like non-compliance.
    governs = {ENOUGH[0][0]: DUTY[0][0], ENOUGH[1][0]: DUTY[1][0], ENOUGH[2][0]: DUTY[2][0], ENOUGH[3][0]: DUTY[2][0]}
    for (dlabel, s, col) in list(table):
        if col in governs and table[(dlabel, s, governs[col])] == "no":
            table[(dlabel, s, col)] = "n/a (no duty)"

    md = ["# Census: AI-content labelling across the EU, Washington and California", "",
          "GENERATED by `census.py` from `census-cells.l4`; every cell is the printed result of one `#EVAL`, or the refusal it produced. Do not edit by hand.",
          "The scenarios, and the judgements each one supposes, are in `census.l4`. Read `NOTES.md` section 5 before relying on any cell.", ""]
    INFORCE = {
        "1 October 2026": "In force on this date: EU Article 50 (since 2 August 2026; providers whose systems were on the EU market before then have until 2 December 2026, Art. 111(4)), and California 22757.3 as amended by SB 1000 (since 30 September 2026). NOT yet in force: Washington E2SHB 1170 (s.9: 1 February 2027), so every Washington cell is no; and California 22757.3.1 (operative 1 January 2027).",
        "1 February 2027": "In force on this date: all of it -- EU Article 50, Washington E2SHB 1170 (from today), California 22757.3 and 22757.3.1.",
    }
    for dlabel, _ in DATES:
        md += ["## On %s" % dlabel, "", INFORCE[dlabel], ""]
        for title, cols in [("Must the provider mark it?", DUTY), ("Is the marking it carries enough?", ENOUGH), ("What must a deployer or platform disclose?", DISPLAY)]:
            md += ["### %s" % title, "", "| scenario | " + " | ".join(c[0] for c in cols) + " |", "|---|" + "---|" * len(cols)]
            for s in SCENARIOS:
                md.append("| %s %s | " % (s, labels.get(s, "")) + " | ".join(table[(dlabel, s, c[0])] for c in cols) + " |")
            md.append("")
        dis = [s for s in SCENARIOS if table[(dlabel, s, "all three agree")] == "no"]
        md += ["### Where the three regimes disagree on whether it must be marked, on %s" % dlabel, ""]
        for s in dis:
            md.append("- **%s %s**: EU %s, Washington %s, California %s." % (s, labels.get(s, ""),
                      table[(dlabel, s, DUTY[0][0])], table[(dlabel, s, DUTY[1][0])], table[(dlabel, s, DUTY[2][0])]))
        if not dis:
            md.append("- none")
        md.append("")
    (HERE / "CENSUS.md").write_text("\n".join(md))
    print("wrote %d cells" % len(cells))

if __name__ == "__main__":
    main()
