"""Tests for pca-evidence.l4 and pca-procedure.l4.  Expected values are read off the text of the Act (source/PCA1960.txt), never off
the encoding.

Run: python generators/pca_tests_2.py   (writes ../pca-tests-evidence.l4 and ../pca-tests-procedure.l4)"""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from fixtures import Types, Out

ROW = os.path.join(os.path.dirname(__file__), '..')
types = Types(os.path.join(ROW, 'pca-types.l4'), os.path.join(ROW, 'written-law-interface.l4'))
def q(x): return '`%s`' % x

# ------------------------------------------------------------------------------------------------ evidence
o = Out(types, """IMPORT prelude
IMPORT `pca-types`
IMPORT `pca-evidence`

-- Tests for pca-evidence.l4 (Prevention of Corruption Act 1960, ss 23, 24, 25, 36).
-- Expected values are read off the Act's text.  Generated by generators/pca_tests_2.py.""")
E = 'Corruption Evidence Facts'
PROC, CUSTOM, TRIAL, DISPROP, ACCRETION, BYOTHER, BELIEVE, PAID, TRIAL_UNDER, FALSEINF, JUSTICE = (
    'the proceeding is a civil or criminal proceeding under this Act', 'customary in a profession', 'the trial or inquiry is into an offence',
    'disproportionate to his or her known sources', 'obtained at or about the time', 'are held or obtained by another person', 'there is reason to believe',
    'the witness paid or delivered', 'the proceeding is a trial for an offence under this Act', 'wilfully made in his or her complaint', 'justice cannot be fully done')

o.section('23. evidence of custom is inadmissible')
o.case('custom evidence in a proceeding under the Act', E, PROC, CUSTOM)
o.case('custom evidence in another proceeding', E, CUSTOM)
o.case('other evidence in a proceeding under the Act', E, PROC)
o.assert_('`evidence of custom is made inadmissible by section 23` `custom evidence in a proceeding under the Act`')
o.assert_('NOT `evidence of custom is made inadmissible by section 23` `custom evidence in another proceeding`')
o.assert_('NOT `evidence of custom is made inadmissible by section 23` `other evidence in a proceeding under the Act`')

o.section('24. disproportionate pecuniary resources')
o.case('24 own resources', E, TRIAL, DISPROP)
o.case('24 own accretion', E, TRIAL, ACCRETION)
o.case('24 resources held by a nominee, reason to believe', E, TRIAL, DISPROP, BYOTHER, BELIEVE)
o.case('24 resources held by another, no reason to believe', E, TRIAL, DISPROP, BYOTHER)
o.case('24 no trial', E, DISPROP)
o.case('24 trial, nothing disproportionate', E, TRIAL)
o.case('24 reason to believe, nothing held by another', E, TRIAL, DISPROP, BELIEVE)
o.assert_('`the court may take the disproportionate resources into consideration as corroboration` `24 own resources`')
o.assert_('`the court may take the disproportionate resources into consideration as corroboration` `24 own accretion`')
o.assert_('`the court may take the disproportionate resources into consideration as corroboration` `24 resources held by a nominee, reason to believe`')
o.assert_('`the court may take the disproportionate resources into consideration as corroboration` `24 reason to believe, nothing held by another`')
o.assert_('NOT `the court may take the disproportionate resources into consideration as corroboration` `24 resources held by another, no reason to believe`')
o.assert_('NOT `the court may take the disproportionate resources into consideration as corroboration` `24 no trial`')
o.assert_('NOT `the court may take the disproportionate resources into consideration as corroboration` `24 trial, nothing disproportionate`')
o.assert_('`the accused is treated as holding the resources, property or accretion` `24 resources held by a nominee, reason to believe`')
o.assert_('NOT `the accused is treated as holding the resources, property or accretion` `24 resources held by another, no reason to believe`')
o.assert_('`the accused is treated as holding the resources, property or accretion` `24 own resources`')

o.section('25. accomplice: no presumption of unworthiness by reason only of the payment')
o.case('25 payer witness in the trial', E, TRIAL, PAID)
o.case('25 payer witness, other proceeding', E, PAID)
o.case('25 witness who paid nothing', E, TRIAL)
o.assert_('`the witness may not be presumed unworthy of credit by reason only of the payment` `25 payer witness in the trial`')
o.assert_('NOT `the witness may not be presumed unworthy of credit by reason only of the payment` `25 payer witness, other proceeding`')
o.assert_('NOT `the witness may not be presumed unworthy of credit by reason only of the payment` `25 witness who paid nothing`')

o.section('36. protection of informers')
o.case('36 trial, informer lied', E, TRIAL_UNDER, FALSEINF)
o.case('36 trial, informer did not lie', E, TRIAL_UNDER)
o.case('36 trial, justice argument only', E, TRIAL_UNDER, JUSTICE)
o.case('36 other proceeding, justice requires', E, JUSTICE)
o.case('36 other proceeding, informer lied', E, FALSEINF)
o.case('36 other proceeding, nothing', E)
o.assert_('`the court may require disclosure concerning the informer under section 36(3)` `36 trial, informer lied`')
o.assert_('NOT `the court may require disclosure concerning the informer under section 36(3)` `36 trial, informer did not lie`')
o.assert_('NOT `the court may require disclosure concerning the informer under section 36(3)` `36 trial, justice argument only`')
o.assert_('`the court may require disclosure concerning the informer under section 36(3)` `36 other proceeding, justice requires`')
o.assert_('NOT `the court may require disclosure concerning the informer under section 36(3)` `36 other proceeding, informer lied`')
o.assert_('NOT `the court may require disclosure concerning the informer under section 36(3)` `36 other proceeding, nothing`')
o.assert_('`a witness may be required to disclose the name or address of the informer` `36 trial, informer lied`')
o.assert_('NOT `a witness may be required to disclose the name or address of the informer` `36 other proceeding, nothing`')
o.write(os.path.join(ROW, 'pca-tests-evidence.l4'))

# ------------------------------------------------------------------------------------------------ procedure
o = Out(types, """IMPORT prelude
IMPORT `written-law-interface`
IMPORT `pca-types`
IMPORT `pca-procedure`

-- Tests for pca-procedure.l4 (Prevention of Corruption Act 1960, ss 3, 4, 15 to 22, 32 to 35, 37).
-- Expected values are read off the Act's text.  Generated by generators/pca_tests_2.py.""")
DIR, DEP, ASST, SI = '`the Director of the Corrupt Practices Investigation Bureau`', '`a deputy director`', '`an assistant director`', '`a special investigator`'
ASP, INSP, POL, OTH, MAG, NOBODY = ('`a police officer of or above the rank of assistant superintendent`', '`a police officer not below the rank of inspector but below assistant superintendent`',
                                     '`another police officer`', '`some other person`', '`a Magistrate`', '`some other person`')
def pred(name, *args, neg=False):
    return ('NOT ' if neg else '') + '`%s` %s' % (name, ' '.join(args))

o.section('3 and 4. who the officers are')
P_ACT = 'the officer may exercise the powers conferred by the Act on the Director or a special investigator'
for r in [DIR, DEP, ASST, SI]:
    o.assert_(pred(P_ACT, r))
    o.assert_(pred('the officer is deemed a public servant within the meaning of the Penal Code 1871', r))
for r in [ASP, INSP, POL, MAG, OTH]:
    o.assert_(pred(P_ACT, r, neg=True))
    o.assert_(pred('the officer is deemed a public servant within the meaning of the Penal Code 1871', r, neg=True))
for r in [DIR, SI]:
    o.assert_(pred('the officer is deemed to be an officer not below the rank of inspector of police', r))
for r in [DEP, ASST, ASP, INSP, POL, MAG, OTH]:
    o.assert_(pred('the officer is deemed to be an officer not below the rank of inspector of police', r, neg=True))
for r in [SI, ASP, INSP]:
    o.assert_(pred('the officer is a special investigator or a police officer not below the rank of inspector', r))
for r in [DIR, DEP, ASST, POL, MAG, OTH]:
    o.assert_(pred('the officer is a special investigator or a police officer not below the rank of inspector', r, neg=True))
for r in [ASP, INSP, POL]:
    o.assert_(pred('the officer is a police officer', r))
for r in [DIR, DEP, ASST, SI, MAG, OTH]:
    o.assert_(pred('the officer is a police officer', r, neg=True))

AR = 'Arrest Facts'
o.section('15. powers of arrest')
for tag, frag in [('concerned', 'has been concerned in an offence'), ('complaint', 'a reasonable complaint has been made'), ('information', 'credible information has been received'), ('suspicion', 'a reasonable suspicion exists')]:
    o.case('arrest ground: %s' % tag, AR, frag)
    o.assert_(pred('the officer may arrest the person without a warrant', DIR, q('arrest ground: %s' % tag)))
    o.assert_(pred('the officer may arrest the person without a warrant', SI, q('arrest ground: %s' % tag)))
    o.assert_(pred('the officer may arrest the person without a warrant', DEP, q('arrest ground: %s' % tag)))
    o.assert_(pred('the officer may arrest the person without a warrant', POL, q('arrest ground: %s' % tag), neg=True))
    o.assert_(pred('the officer may arrest the person without a warrant', MAG, q('arrest ground: %s' % tag), neg=True))
o.case('arrest no ground', AR)
o.assert_(pred('the officer may arrest the person without a warrant', DIR, '`arrest no ground`', neg=True))
o.case('arrest, woman searched by a man', AR, 'has been concerned in an offence', 'the person arrested is a female')
o.case('arrest, woman searched by a woman', AR, 'has been concerned in an offence', 'the person arrested is a female', 'the searcher is a female')
o.case('arrest, man searched by a man', AR, 'has been concerned in an offence')
o.case('arrest, man searched by a woman', AR, 'has been concerned in an offence', 'the searcher is a female')
o.assert_(pred('the officer may search the person arrested', SI, '`arrest, woman searched by a man`', neg=True))
o.assert_(pred('the officer may search the person arrested', SI, '`arrest, woman searched by a woman`'))
o.assert_(pred('the officer may search the person arrested', SI, '`arrest, man searched by a man`'))
o.assert_(pred('the officer may search the person arrested', SI, '`arrest, man searched by a woman`'))
o.assert_(pred('the officer may search the person arrested', POL, '`arrest, man searched by a man`', neg=True))
o.assert_(pred('the officer may search the person arrested', SI, '`arrest no ground`', neg=True))
o.assert_('`the arrested person has been taken to a place section 15(3) allows` TRUE FALSE')
o.assert_('`the arrested person has been taken to a place section 15(3) allows` FALSE TRUE')
o.assert_('NOT `the arrested person has been taken to a place section 15(3) allows` FALSE FALSE')

o.section('16. bail or bond')
for g in [DIR, SI, ASP, INSP, POL]:
    o.assert_('`the person may be released on bail or on his or her own bond granted by the grantor` TRUE %s' % g)
    o.assert_('NOT `the person may be released on bail or on his or her own bond granted by the grantor` FALSE %s' % g)
for g in [DEP, ASST, MAG, OTH]:
    o.assert_('NOT `the person may be released on bail or on his or her own bond granted by the grantor` TRUE %s' % g)

IP = 'Investigation Power Facts'
PC_A, ACT_OFF, ARRESTABLE, PPORDER, PPSAT, PPBOOK, BOOKREL = (
    'the case relates to an offence under section 165', 'the case relates to an offence under this Act', 'the case relates to an arrestable offence under a written law',
    'the Public Prosecutor has ordered', 'is satisfied that there are reasonable grounds', 'considers that evidence of an offence', "the banker's book relates to that person")
o.section('17, 19. investigation powers, with and without the Public Prosecutor\'s order')
o.case('inv Penal Code 165 or 213 to 215', IP, PC_A)
o.case('inv offence under the Act', IP, ACT_OFF)
o.case('inv arrestable offence disclosed', IP, ARRESTABLE)
o.case('inv only the Public Prosecutor\'s order', IP, PPORDER)
o.case('inv nothing', IP)
for v in ['inv Penal Code 165 or 213 to 215', 'inv offence under the Act', 'inv arrestable offence disclosed']:
    for r in [DIR, SI, DEP, ASST]:
        o.assert_(pred('the officer may exercise police investigation powers without the order of the Public Prosecutor', r, q(v)))
    o.assert_(pred('the officer may exercise police investigation powers without the order of the Public Prosecutor', POL, q(v), neg=True))
    o.assert_(pred('the officer may exercise police investigation powers', DIR, q(v)))
o.assert_(pred('the officer may exercise police investigation powers without the order of the Public Prosecutor', DIR, "`inv only the Public Prosecutor's order`", neg=True))
o.assert_(pred('the officer may exercise police investigation powers on the order of the Public Prosecutor', DIR, "`inv only the Public Prosecutor's order`"))
o.assert_(pred('the officer may exercise police investigation powers on the order of the Public Prosecutor', SI, "`inv only the Public Prosecutor's order`"))
o.assert_(pred('the officer may exercise police investigation powers on the order of the Public Prosecutor', DEP, "`inv only the Public Prosecutor's order`", neg=True))
o.assert_(pred('the officer may exercise police investigation powers on the order of the Public Prosecutor', POL, "`inv only the Public Prosecutor's order`", neg=True))
o.assert_(pred('the officer may exercise police investigation powers', SI, "`inv only the Public Prosecutor's order`"))
o.assert_(pred('the officer may exercise police investigation powers', SI, '`inv nothing`', neg=True))

o.section('18(1) and 20(1). orders of the Public Prosecutor')
o.case('PP satisfied there are grounds', IP, PPSAT)
o.case('PP considers evidence is in a banker\'s book of a servant', IP, PPBOOK, BOOKREL)
o.case('PP considers evidence is in a banker\'s book, unrelated', IP, PPBOOK)
o.case('banker\'s book of a servant, PP does not consider', IP, BOOKREL)
for r in [DIR, SI, ASP]:
    o.assert_(pred("the Public Prosecutor's order under section 18(1) may name the officer", r, '`PP satisfied there are grounds`'))
    o.assert_(pred("the Public Prosecutor's order under section 18(1) may name the officer", r, '`inv nothing`', neg=True))
    o.assert_(pred("the Public Prosecutor's order under section 20(1) may authorise the officer to inspect the banker's book", r, "`PP considers evidence is in a banker's book of a servant`"))
    o.assert_(pred("the Public Prosecutor's order under section 20(1) may authorise the officer to inspect the banker's book", r, "`PP considers evidence is in a banker's book, unrelated`", neg=True))
    o.assert_(pred("the Public Prosecutor's order under section 20(1) may authorise the officer to inspect the banker's book", r, "`banker's book of a servant, PP does not consider`", neg=True))
for r in [DEP, ASST, INSP, POL]:
    o.assert_(pred("the Public Prosecutor's order under section 18(1) may name the officer", r, '`PP satisfied there are grounds`', neg=True))
    o.assert_(pred("the Public Prosecutor's order under section 20(1) may authorise the officer to inspect the banker's book", r, "`PP considers evidence is in a banker's book of a servant`", neg=True))

SE = 'Search Facts'
INFO, CONCEAL, DELAY, WARRANT = ('it appears upon information and after such inquiry', 'has reasonable cause to believe that such a document', 'by reason of the delay in obtaining a search warrant', 'a warrant has been issued')
o.section('22. search and seizure')
o.case('search: information and reasonable cause', SE, INFO)
o.case('search: concealed and delay', SE, CONCEAL, DELAY)
o.case('search: concealed, no delay', SE, CONCEAL)
o.case('search: delay, nothing concealed', SE, DELAY)
o.case('search: warrant issued', SE, WARRANT)
o.case('search: nothing', SE)
o.assert_(pred('the issuer may issue a search warrant', MAG, '`search: information and reasonable cause`'))
o.assert_(pred('the issuer may issue a search warrant', DIR, '`search: information and reasonable cause`'))
o.assert_(pred('the issuer may issue a search warrant', SI, '`search: information and reasonable cause`', neg=True))
o.assert_(pred('the issuer may issue a search warrant', POL, '`search: information and reasonable cause`', neg=True))
o.assert_(pred('the issuer may issue a search warrant', MAG, '`search: nothing`', neg=True))
for r in [SI, ASP, INSP]:
    o.assert_(pred('the officer may enter and search under a warrant', r, '`search: warrant issued`'))
    o.assert_(pred('the officer may enter and search under a warrant', r, '`search: nothing`', neg=True))
    o.assert_(pred('the officer may enter and search without a warrant', r, '`search: concealed and delay`'))
    o.assert_(pred('the officer may enter and search without a warrant', r, '`search: concealed, no delay`', neg=True))
    o.assert_(pred('the officer may enter and search without a warrant', r, '`search: delay, nothing concealed`', neg=True))
for r in [POL, DIR, MAG, OTH]:
    o.assert_(pred('the officer may enter and search under a warrant', r, '`search: warrant issued`', neg=True))
    o.assert_(pred('the officer may enter and search without a warrant', r, '`search: concealed and delay`', neg=True))

o.section('32(1) and 34. the statement the Act gives the Code')
o.assert_('`every offence under the Act is deemed an arrestable offence`')
o.assert_('`a District Court may try any offence under the Act and award the full punishment for it`')
o.assert_('(`the Prevention of Corruption Act 1960\'s statement about its offences`)\'s `the Act` EQUALS "Prevention of Corruption Act 1960"')
o.assert_('NOT (`the Prevention of Corruption Act 1960\'s statement about its offences`)\'s `the Act empowers the police to arrest without warrant for the offence`')
o.assert_('NOT (`the Prevention of Corruption Act 1960\'s statement about its offences`)\'s `the Act shows the offence as triable by a Magistrate\'s Court under that Act`')

PR = 'Procedure Facts'
o.section('33, 35, 37. consent, examination of offenders, citizens abroad')
o.case('33 instituted by the Public Prosecutor', PR, 'instituted by the Public Prosecutor')
o.case('33 instituted with consent', PR, 'instituted with the consent')
o.case('33 instituted by a private person', PR)
o.assert_('`the prosecution under the Act may be instituted` `33 instituted by the Public Prosecutor`')
o.assert_('`the prosecution under the Act may be instituted` `33 instituted with consent`')
o.assert_('NOT `the prosecution under the Act may be instituted` `33 instituted by a private person`')
o.case('35 two charged', PR, 'two or more persons are charged')
o.case('35 one charged', PR)
o.case('35 required and made full discovery', PR, 'was required by the court under section 35(1)', 'makes true and full discovery')
o.case('35 required, no full discovery', PR, 'was required by the court under section 35(1)')
o.case('35 full discovery, never required', PR, 'makes true and full discovery')
o.assert_('`the court may require one or more of the persons charged to give evidence for the prosecution` `35 two charged`')
o.assert_('NOT `the court may require one or more of the persons charged to give evidence for the prosecution` `35 one charged`')
o.assert_('`the person is entitled to a certificate of indemnity` `35 required and made full discovery`')
o.assert_('NOT `the person is entitled to a certificate of indemnity` `35 required, no full discovery`')
o.assert_('NOT `the person is entitled to a certificate of indemnity` `35 full discovery, never required`')
o.case('37 citizen abroad', PR, 'a citizen of Singapore', 'committed in a place outside Singapore')
o.case('37 citizen at home', PR, 'a citizen of Singapore')
o.case('37 foreigner abroad', PR, 'committed in a place outside Singapore')
o.assert_('`the person may be dealt with as if the offence had been committed within Singapore` `37 citizen abroad`')
o.assert_('NOT `the person may be dealt with as if the offence had been committed within Singapore` `37 citizen at home`')
o.assert_('NOT `the person may be dealt with as if the offence had been committed within Singapore` `37 foreigner abroad`')
o.write(os.path.join(ROW, 'pca-tests-procedure.l4'))
print('pca_tests_2 written')
