"""Tests for pca-offences.l4.  Expected values are read off the text of the Act (source/PCA1960.txt), never off the encoding.

Run: python generators/pca_tests_1.py   (writes ../pca-tests-offences.l4)"""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from fixtures import Types, Out

ROW = os.path.join(os.path.dirname(__file__), '..')
types = Types(os.path.join(ROW, 'pca-types.l4'))
def q(x): return '`%s`' % x

o = Out(types, """IMPORT prelude
IMPORT `pca-types`
IMPORT `pca-offences`

-- Tests for pca-offences.l4 (Prevention of Corruption Act 1960, ss 2, 5 to 14, 18(2), 21(2), 26 to 32(2)).
-- Expected values are read off the Act's text.  Generated by generators/pca_tests_1.py.""")

# field fragments --------------------------------------------------------------------------------------------------
G = 'Gratification Facts'
G_MONEY, G_OFFICE, G_PAY, G_SERVICE, G_OFFER = 'money or a gift', 'an office, employment or contract', 'a payment, release', 'any other service', 'an offer, undertaking'

o.section('2. gratification: each of the five paragraphs alone')
o.case('thing a: money', G, G_MONEY)
o.case('thing b: office', G, G_OFFICE)
o.case('thing c: release of a debt', G, G_PAY)
o.case('thing d: favour', G, G_SERVICE)
o.case('thing e: promise', G, G_OFFER)
o.case('thing none', G)
for v in ['thing a: money', 'thing b: office', 'thing c: release of a debt', 'thing d: favour', 'thing e: promise']:
    o.assert_('`the thing is a gratification` %s' % q(v))
o.assert_('NOT `the thing is a gratification` `thing none`')

A = 'Agency Facts'
o.section('2. agent; and the wider meaning for section 8')
o.case('agent employed', A, 'employed by or acting for another')
o.case('agent trustee', A, 'trustee, administrator or executor')
o.case('agent serving government', A, 'serving the Government or was under')
o.case('agent subcontractor', A, 'subcontractor')
o.case('agent none', A)
for v in ['agent employed', 'agent trustee', 'agent serving government']:
    o.assert_('`the person is an agent` %s' % q(v))
    o.assert_('`the person is an agent for the purposes of section 8` %s' % q(v))
o.assert_('NOT `the person is an agent` `agent subcontractor`')
o.assert_('`the person is an agent for the purposes of section 8` `agent subcontractor`')
o.assert_('NOT `the person is an agent` `agent none`')
o.assert_('NOT `the person is an agent for the purposes of section 8` `agent none`')

P = 'Presumption Facts'
EMP, DEAL, DEALAG, CON = 'in the employment of the Government', 'received from, a person who has', 'received from, an agent of a person', 'contrary is proved'
o.section('8. the presumption of corruption')
o.case('p employee and dealer', P, EMP, DEAL)
o.case('p employee and dealer, contrary proved', P, EMP, DEAL, CON)
o.case('p employee and dealer agent', P, EMP, DEALAG)
o.case('p dealer only', P, DEAL)
o.case('p employee only', P, EMP)
o.case('p none', P)
o.assert_('`the presumption of section 8 operates` `p employee and dealer` `agent none`')
o.assert_('NOT `the presumption of section 8 operates` `p employee and dealer, contrary proved` `agent none`')
o.assert_('`the presumption of section 8 operates` `p employee and dealer agent` `agent subcontractor`')
o.assert_('`the presumption of section 8 operates` `p employee and dealer agent` `agent employed`')
o.assert_('NOT `the presumption of section 8 operates` `p employee and dealer agent` `agent none`')
o.assert_('NOT `the presumption of section 8 operates` `p dealer only` `agent employed`')
o.assert_('NOT `the presumption of section 8 operates` `p employee only` `agent employed`')
o.assert_('NOT `the presumption of section 8 operates` `p none` `agent employed`')

S5 = 'Section 5 Facts'
S_SOL, S_GIVE, S_COR, S_L1, S_L2 = 'solicited or received', 'gave, promised or offered', 'acted corruptly', 'inducement to, reward for, or on account of, any person doing', 'a member, officer or servant of a public body'
o.section('5. punishment for corruption')
o.case('s5 receipt, corruptly, limb i', S5, S_SOL, S_COR, S_L1)
o.case('s5 receipt, corruptly, limb ii', S5, S_SOL, S_COR, S_L2)
o.case('s5 receipt, corruptly, no limb', S5, S_SOL, S_COR)
o.case('s5 receipt, not corruptly, limb i', S5, S_SOL, S_L1)
o.case('s5 receipt only', S5, S_SOL)
o.case('s5 offer, corruptly, limb i', S5, S_GIVE, S_COR, S_L1)
o.case('s5 offer, corruptly, limb ii', S5, S_GIVE, S_COR, S_L2)
o.case('s5 offer, corruptly, no limb', S5, S_GIVE, S_COR)
o.case('s5 offer, not corruptly, limb i', S5, S_GIVE, S_L1)
o.case('s5 no act, corruptly, limb i', S5, S_COR, S_L1)
o.case('s5 receipt and offer, corruptly, limb i', S5, S_SOL, S_GIVE, S_COR, S_L1)
NOT_PRESUMED, PRESUMED = 'FALSE', 'TRUE'
for v in ['s5 receipt, corruptly, limb i', 's5 receipt, corruptly, limb ii']:
    o.assert_('`an offence under section 5(a) is made out` %s `thing a: money` FALSE' % q(v))
for v in ['s5 receipt, corruptly, no limb', 's5 receipt, not corruptly, limb i', 's5 receipt only', 's5 offer, corruptly, limb i', 's5 no act, corruptly, limb i']:
    o.assert_('NOT `an offence under section 5(a) is made out` %s `thing a: money` FALSE' % q(v))
o.assert_('NOT `an offence under section 5(a) is made out` `s5 receipt, corruptly, limb i` `thing none` FALSE')
o.assert_('`an offence under section 5(a) is made out` `s5 receipt only` `thing a: money` TRUE')
o.assert_('`an offence under section 5(a) is made out` `s5 receipt, not corruptly, limb i` `thing d: favour` TRUE')
o.assert_('NOT `an offence under section 5(a) is made out` `s5 receipt only` `thing none` TRUE')
o.assert_('NOT `an offence under section 5(a) is made out` `s5 no act, corruptly, limb i` `thing a: money` TRUE')
for v in ['s5 offer, corruptly, limb i', 's5 offer, corruptly, limb ii']:
    o.assert_('`an offence under section 5(b) is made out` %s `thing b: office` FALSE' % q(v))
for v in ['s5 offer, corruptly, no limb', 's5 offer, not corruptly, limb i', 's5 receipt, corruptly, limb i']:
    o.assert_('NOT `an offence under section 5(b) is made out` %s `thing b: office` FALSE' % q(v))
o.assert_('`an offence under section 5(b) is made out` `s5 offer, not corruptly, limb i` `thing b: office` TRUE')
o.assert_('NOT `an offence under section 5(b) is made out` `s5 offer, corruptly, limb i` `thing none` FALSE')
o.assert_('`an offence under section 5(a) is made out` `s5 receipt and offer, corruptly, limb i` `thing a: money` FALSE')
o.assert_('`an offence under section 5(b) is made out` `s5 receipt and offer, corruptly, limb i` `thing a: money` FALSE')
o.assert_('`the gratification was corruptly an inducement or reward of the kind section 5 names` `s5 receipt, corruptly, limb i` FALSE')
o.assert_('NOT `the gratification was corruptly an inducement or reward of the kind section 5 names` `s5 receipt, corruptly, no limb` FALSE')
o.assert_('`the gratification was corruptly an inducement or reward of the kind section 5 names` `s5 receipt only` TRUE')

S6 = 'Section 6 Facts'
S6_ACC, S6_GIVE, S6_COR, S6_IND, S6_GAVEDOC, S6_USEDDOC, S6_INT, S6_FALSE, S6_MISLEAD = (
    'agent accepted or obtained', 'gave, agreed to give or offered a gratification to an agent', 'acted corruptly',
    'inducement or reward for doing or forbearing', 'knowingly gave an agent a receipt', 'being an agent, knowingly used',
    'principal is interested', 'contains a statement', 'intended to mislead')
o.section('6. corrupt transactions with agents')
o.case('s6 acceptance, corruptly, inducement', S6, S6_ACC, S6_COR, S6_IND)
o.case('s6 acceptance, not corruptly, inducement', S6, S6_ACC, S6_IND)
o.case('s6 acceptance, corruptly, no inducement', S6, S6_ACC, S6_COR)
o.case('s6 giving, corruptly, inducement', S6, S6_GIVE, S6_COR, S6_IND)
o.case('s6 giving, corruptly, no inducement', S6, S6_GIVE, S6_COR)
o.case('s6 no act, corruptly, inducement', S6, S6_COR, S6_IND)
o.assert_('`an offence under section 6(a) is made out` `s6 acceptance, corruptly, inducement` `thing a: money` `agent employed` FALSE')
o.assert_('`an offence under section 6(a) is made out` `s6 acceptance, corruptly, inducement` `thing a: money` `agent trustee` FALSE')
o.assert_('`an offence under section 6(a) is made out` `s6 acceptance, corruptly, inducement` `thing a: money` `agent serving government` FALSE')
o.assert_('NOT `an offence under section 6(a) is made out` `s6 acceptance, corruptly, inducement` `thing a: money` `agent none` FALSE')
o.assert_('NOT `an offence under section 6(a) is made out` `s6 acceptance, corruptly, inducement` `thing a: money` `agent subcontractor` FALSE')
o.assert_('NOT `an offence under section 6(a) is made out` `s6 acceptance, not corruptly, inducement` `thing a: money` `agent employed` FALSE')
o.assert_('NOT `an offence under section 6(a) is made out` `s6 acceptance, corruptly, no inducement` `thing a: money` `agent employed` FALSE')
o.assert_('`an offence under section 6(a) is made out` `s6 acceptance, not corruptly, inducement` `thing a: money` `agent employed` TRUE')
o.assert_('`an offence under section 6(a) is made out` `s6 acceptance, corruptly, no inducement` `thing a: money` `agent employed` TRUE')
o.assert_('NOT `an offence under section 6(a) is made out` `s6 giving, corruptly, inducement` `thing a: money` `agent employed` FALSE')
o.assert_('NOT `an offence under section 6(a) is made out` `s6 acceptance, corruptly, inducement` `thing none` `agent employed` FALSE')
o.assert_('`an offence under section 6(b) is made out` `s6 giving, corruptly, inducement` `thing a: money` `agent employed` FALSE')
o.assert_('NOT `an offence under section 6(b) is made out` `s6 giving, corruptly, inducement` `thing a: money` `agent none` FALSE')
o.assert_('NOT `an offence under section 6(b) is made out` `s6 giving, corruptly, inducement` `thing a: money` `agent subcontractor` FALSE')
o.assert_('NOT `an offence under section 6(b) is made out` `s6 giving, corruptly, no inducement` `thing a: money` `agent employed` FALSE')
o.assert_('`an offence under section 6(b) is made out` `s6 giving, corruptly, no inducement` `thing a: money` `agent employed` TRUE')
o.assert_('NOT `an offence under section 6(b) is made out` `s6 acceptance, corruptly, inducement` `thing a: money` `agent employed` FALSE')
o.assert_('NOT `an offence under section 6(b) is made out` `s6 giving, corruptly, inducement` `thing none` `agent employed` FALSE')

o.case('s6c gave a false document', S6, S6_GAVEDOC, S6_INT, S6_FALSE, S6_MISLEAD)
o.case('s6c agent used a false document', S6, S6_USEDDOC, S6_INT, S6_FALSE, S6_MISLEAD)
o.case('s6c gave a document, principal not interested', S6, S6_GAVEDOC, S6_FALSE, S6_MISLEAD)
o.case('s6c gave a document, nothing false', S6, S6_GAVEDOC, S6_INT, S6_MISLEAD)
o.case('s6c gave a document, not meant to mislead', S6, S6_GAVEDOC, S6_INT, S6_FALSE)
o.case('s6c neither gave nor used', S6, S6_INT, S6_FALSE, S6_MISLEAD)
o.assert_('`an offence under section 6(c) is made out` `s6c gave a false document` `agent none` `agent employed`')
o.assert_('NOT `an offence under section 6(c) is made out` `s6c gave a false document` `agent none` `agent none`')
o.assert_('`an offence under section 6(c) is made out` `s6c agent used a false document` `agent employed` `agent none`')
o.assert_('NOT `an offence under section 6(c) is made out` `s6c agent used a false document` `agent none` `agent none`')
o.assert_('NOT `an offence under section 6(c) is made out` `s6c gave a document, principal not interested` `agent none` `agent employed`')
o.assert_('NOT `an offence under section 6(c) is made out` `s6c gave a document, nothing false` `agent none` `agent employed`')
o.assert_('NOT `an offence under section 6(c) is made out` `s6c gave a document, not meant to mislead` `agent none` `agent employed`')
o.assert_('NOT `an offence under section 6(c) is made out` `s6c neither gave nor used` `agent employed` `agent employed`')

o.section('8 with 5 and 6: the presumption supplies "corruptly" and the inducement or reward')
o.assert_('`an offence under section 5(a) is made out` `s5 receipt only` `thing a: money` (`the presumption of section 8 operates` `p employee and dealer` `agent none`)')
o.assert_('NOT `an offence under section 5(a) is made out` `s5 offer, corruptly, limb i` `thing a: money` TRUE')
o.assert_('`an offence under section 6(a) is made out` `s6 acceptance, not corruptly, inducement` `thing a: money` `agent employed` (`the presumption of section 8 operates` `p employee and dealer` `agent none`)')
o.assert_('NOT `an offence under section 6(a) is made out` `s6 acceptance, not corruptly, inducement` `thing a: money` `agent employed` (`the presumption of section 8 operates` `p employee and dealer, contrary proved` `agent none`)')
o.assert_('`an offence under section 6(b) is made out` `s6 giving, corruptly, no inducement` `thing a: money` `agent employed` (`the presumption of section 8 operates` `p employee and dealer agent` `agent subcontractor`)')

S9 = 'Section 9 Facts'
S9_ACC, S9_GIVE, S9_BELIEVE1, S9_BELIEVE2, S9_POW, S9_NOINT, S9_NODID, S9_NOTREL = (
    'agent corruptly accepted', 'accused corruptly gave', 'had reason to believe or suspect that the gratification was offered',
    'had reason to believe or suspect that the agent had the power', 'the agent had the power, right or opportunity to do, show or forbear', 'accepted the gratification without intending',
    'did not in fact do', 'not in relation to the principal')
o.section('9. guilty notwithstanding that the purpose is not carried out')
o.case('s9(1) reason to believe, all four excuses present', S9, S9_ACC, S9_BELIEVE1)
o.case('s9(1) reason to believe, no excuse present', S9, S9_ACC, S9_BELIEVE1, S9_POW)
o.case('s9(1) the excuses present', S9, S9_ACC, S9_BELIEVE1, S9_NOINT, S9_NODID, S9_NOTREL)
o.case('s9(1) no reason to believe', S9, S9_ACC)
o.case('s9(1) not accepted', S9, S9_BELIEVE1)
o.case('s9(2) reason to believe', S9, S9_GIVE, S9_BELIEVE2)
o.case('s9(2) reason to believe, the excuses present', S9, S9_GIVE, S9_BELIEVE2, S9_NOINT, S9_NODID, S9_NOTREL)
o.case('s9(2) no reason to believe', S9, S9_GIVE)
o.case('s9(2) not given', S9, S9_BELIEVE2)
for v in ['s9(1) reason to believe, all four excuses present', 's9(1) reason to believe, no excuse present', 's9(1) the excuses present']:
    o.assert_('`an offence under section 6(a) is made out by section 9(1)` %s `thing a: money` `agent employed`' % q(v))
for v in ['s9(1) no reason to believe', 's9(1) not accepted']:
    o.assert_('NOT `an offence under section 6(a) is made out by section 9(1)` %s `thing a: money` `agent employed`' % q(v))
o.assert_('NOT `an offence under section 6(a) is made out by section 9(1)` `s9(1) reason to believe, no excuse present` `thing a: money` `agent none`')
o.assert_('NOT `an offence under section 6(a) is made out by section 9(1)` `s9(1) reason to believe, no excuse present` `thing none` `agent employed`')
for v in ['s9(2) reason to believe', 's9(2) reason to believe, the excuses present']:
    o.assert_('`an offence under section 6(b) is made out by section 9(2)` %s `thing a: money` `agent employed`' % q(v))
for v in ['s9(2) no reason to believe', 's9(2) not given']:
    o.assert_('NOT `an offence under section 6(b) is made out by section 9(2)` %s `thing a: money` `agent employed`' % q(v))
o.assert_('NOT `an offence under section 6(b) is made out by section 9(2)` `s9(2) reason to believe` `thing a: money` `agent none`')

S10 = 'Section 10 Facts'
S10_OFFER, S10_INT, S10_KIND, S10_IND, S10_SOL = ('offered a gratification to a person who had made a tender', 'with intent to obtain the contract', 'contract was for performing work',
    "inducement or a reward for the tenderer's withdrawing", 'solicited or accepted a gratification as an inducement or a reward for withdrawing a tender made by the accused')
o.section('10. corruptly procuring withdrawal of tenders')
o.case('s10(a) full', S10, S10_OFFER, S10_INT, S10_KIND, S10_IND)
o.case('s10(a) no intent to obtain the contract', S10, S10_OFFER, S10_KIND, S10_IND)
o.case('s10(a) not for withdrawal', S10, S10_OFFER, S10_INT, S10_KIND)
o.case('s10(a) not a contract of the kind', S10, S10_OFFER, S10_INT, S10_IND)
o.case('s10(b) solicited', S10, S10_SOL)
o.case('s10 nothing', S10)
o.assert_('`an offence under section 10(a) is made out` `s10(a) full` `thing a: money`')
for v in ['s10(a) no intent to obtain the contract', 's10(a) not for withdrawal', 's10(a) not a contract of the kind', 's10(b) solicited', 's10 nothing']:
    o.assert_('NOT `an offence under section 10(a) is made out` %s `thing a: money`' % q(v))
o.assert_('NOT `an offence under section 10(a) is made out` `s10(a) full` `thing none`')
o.assert_('`an offence under section 10(b) is made out` `s10(b) solicited` `thing a: money`')
o.assert_('NOT `an offence under section 10(b) is made out` `s10(a) full` `thing a: money`')
o.assert_('NOT `an offence under section 10(b) is made out` `s10(b) solicited` `thing none`')

S11 = 'Section 11 Facts'
o.section('11. bribery of a Member of Parliament')
o.case('s11 offer to a Member', S11, 'offered a gratification to a Member of Parliament', "capacity as a Member")
o.case('s11 Member accepts', S11, 'being a Member of Parliament, solicited or accepted', "capacity as a Member")
o.case('s11 offer to a Member, not in his capacity', S11, 'offered a gratification to a Member of Parliament')
o.case('s11 Member accepts, not in his capacity', S11, 'being a Member of Parliament, solicited or accepted')
o.assert_('`an offence under section 11(a) is made out` `s11 offer to a Member` `thing a: money`')
o.assert_('NOT `an offence under section 11(a) is made out` `s11 offer to a Member, not in his capacity` `thing a: money`')
o.assert_('NOT `an offence under section 11(a) is made out` `s11 Member accepts` `thing a: money`')
o.assert_('NOT `an offence under section 11(a) is made out` `s11 offer to a Member` `thing none`')
o.assert_('`an offence under section 11(b) is made out` `s11 Member accepts` `thing a: money`')
o.assert_('NOT `an offence under section 11(b) is made out` `s11 Member accepts, not in his capacity` `thing a: money`')
o.assert_('NOT `an offence under section 11(b) is made out` `s11 offer to a Member` `thing a: money`')

S12 = 'Section 12 Facts'
S12_V, S12_O, S12_A = ('voting or abstaining from voting', 'performing or abstaining from performing', 'procuring or preventing the passing of a vote')
o.section('12. bribery of a member of a public body: three alternative purposes')
for tag, frag in [('vote', S12_V), ('official act', S12_O), ('aid in a vote or contract', S12_A)]:
    o.case('s12 offer for %s' % tag, S12, 'offered a gratification to a member of a public body', frag)
    o.case('s12 member accepts for %s' % tag, S12, 'being a member of a public body, solicited or accepted', frag)
    o.assert_('`an offence under section 12(a) is made out` %s `thing a: money`' % q('s12 offer for %s' % tag))
    o.assert_('`an offence under section 12(b) is made out` %s `thing a: money`' % q('s12 member accepts for %s' % tag))
    o.assert_('NOT `an offence under section 12(b) is made out` %s `thing a: money`' % q('s12 offer for %s' % tag))
    o.assert_('NOT `an offence under section 12(a) is made out` %s `thing a: money`' % q('s12 member accepts for %s' % tag))
o.case('s12 offer, no purpose', S12, 'offered a gratification to a member of a public body')
o.case('s12 acceptance, no purpose', S12, 'being a member of a public body, solicited or accepted')
o.assert_('NOT `an offence under section 12(a) is made out` `s12 offer, no purpose` `thing a: money`')
o.assert_('NOT `an offence under section 12(b) is made out` `s12 acceptance, no purpose` `thing a: money`')
o.assert_('NOT `an offence under section 12(a) is made out` `s12 offer for vote` `thing none`')

I = 'Inchoate Offence Facts'
o.section('29, 30, 31. abetment, attempt, conspiracy')
o.case('inchoate abetment', I, 'abetted, within the meaning of the Penal Code 1871, the commission of an offence under this Act')
o.case('inchoate abetment abroad', I, 'commission outside Singapore')
o.case('inchoate attempt', I, 'attempted to commit')
o.case('inchoate conspiracy', I, 'criminal conspiracy')
o.case('inchoate none', I)
for v in ['inchoate abetment', 'inchoate abetment abroad', 'inchoate attempt', 'inchoate conspiracy']:
    o.assert_('`the accused is deemed to have committed the offence by section 29, 30 or 31` %s' % q(v))
o.assert_('NOT `the accused is deemed to have committed the offence by section 29, 30 or 31` `inchoate none`')

II = 'Investigation Offence Facts'
o.section('18(2) and 21(2). failing to disclose; failing to comply with the Public Prosecutor\'s notice')
o.case('18(2) ordered and failed', II, 'an order of the Public Prosecutor under section 18(1)', 'failed to disclose')
o.case('18(2) failed, no order', II, 'failed to disclose')
o.case('18(2) ordered, complied', II, 'an order of the Public Prosecutor under section 18(1)')
o.assert_('`an offence under section 18(2) is made out` `18(2) ordered and failed`')
o.assert_('NOT `an offence under section 18(2) is made out` `18(2) failed, no order`')
o.assert_('NOT `an offence under section 18(2) is made out` `18(2) ordered, complied`')
o.case('21(2) notice, offence kind, wilful failure', II, 'a written notice of the Public Prosecutor under section 21(1)', 'the offence investigated is an offence', 'wilfully neglected')
o.case('21(2) notice, kind, complied', II, 'a written notice of the Public Prosecutor under section 21(1)', 'the offence investigated is an offence')
o.case('21(2) no notice', II, 'the offence investigated is an offence', 'wilfully neglected')
o.case('21(2) notice, offence not of the kinds', II, 'a written notice of the Public Prosecutor under section 21(1)', 'wilfully neglected')
o.assert_('`an offence under section 21(2) is made out` `21(2) notice, offence kind, wilful failure`')
for v in ['21(2) notice, kind, complied', '21(2) no notice', '21(2) notice, offence not of the kinds']:
    o.assert_('NOT `an offence under section 21(2) is made out` %s' % q(v))

S26 = 'Section 26 Facts'
o.section('26. obstruction of search; 27. legal obligation to give information')
for tag, frag in [('(a) refused access', 'refused the Director or an officer authorised to enter or search access'), ('(b) obstructed', 'assaulted, obstructed, hindered or delayed'),
                  ('(c) failed to comply with a demand', 'failed to comply with a lawful demand'), ('(d) refused information', 'refused or neglected to give information')]:
    o.case('s26%s' % tag, S26, frag)
    o.assert_('`an offence under section 26 is made out` %s' % q('s26%s' % tag))
o.case('s26 nothing', S26)
o.assert_('NOT `an offence under section 26 is made out` `s26 nothing`')
S27 = 'Section 27 Facts'
o.case('s27 all three', S27, 'was required by the Director', 'the duty of the Director', 'in the person\'s power')
o.case('s27 not in his power', S27, 'was required by the Director', 'the duty of the Director')
o.case('s27 not a subject of the Director\'s duty', S27, 'was required by the Director', 'in the person\'s power')
o.case('s27 not required', S27, 'the duty of the Director', 'in the person\'s power')
o.assert_('`the person is legally bound to give the information` `s27 all three`')
for v in ['s27 not in his power', "s27 not a subject of the Director's duty", 's27 not required']:
    o.assert_('NOT `the person is legally bound to give the information` %s' % q(v))

S28 = 'Section 28 Facts'
o.section('28. false statements and information')
o.case('s28(a)', S28, 'relating to the commission of an offence')
o.case('s28(b)', S28, 'to the Director or a special investigator any other')
o.case('s28 none', S28)
o.assert_('`an offence under section 28 is made out` `s28(a)`')
o.assert_('`an offence under section 28 is made out` `s28(b)`')
o.assert_('NOT `an offence under section 28 is made out` `s28 none`')

S32 = 'Section 32(2) Facts'
o.section('32(2). public officer failing to arrest the giver of a gratification')
o.case('s32(2) offered, did nothing', S32, 'a gratification was corruptly given or offered')
o.case('s32(2) offered, arrested and made over', S32, 'a gratification was corruptly given or offered', 'arrested the person who gave or offered')
o.case('s32(2) offered, excused', S32, 'a gratification was corruptly given or offered', 'had a reasonable excuse')
o.case('s32(2) nothing offered', S32)
o.assert_('`an offence under section 32(2) is made out` `s32(2) offered, did nothing`')
o.assert_('NOT `an offence under section 32(2) is made out` `s32(2) offered, arrested and made over`')
o.assert_('NOT `an offence under section 32(2) is made out` `s32(2) offered, excused`')
o.assert_('NOT `an offence under section 32(2) is made out` `s32(2) nothing offered`')

o.section('The Penal Code sections the Act names: three lists, not one')
for s in ['165', '213', '214', '215']:
    o.assert_('`the Penal Code section is one that sections 17(1)(a) and 28(a) name` "%s"' % s)
    o.assert_('`the Penal Code section is one that sections 20, 21, 22, 24 and 35 name` "%s"' % s)
for s in ['161', '162', '163', '164']:
    o.assert_('NOT `the Penal Code section is one that sections 17(1)(a) and 28(a) name` "%s"' % s)
    o.assert_('`the Penal Code section is one that sections 20, 21, 22, 24 and 35 name` "%s"' % s)
for s in ['160', '166', '212', '216', '420']:
    o.assert_('NOT `the Penal Code section is one that sections 17(1)(a) and 28(a) name` "%s"' % s)
    o.assert_('NOT `the Penal Code section is one that sections 20, 21, 22, 24 and 35 name` "%s"' % s)
o.assert_('count `the Penal Code sections named in sections 17(1)(a) and 28(a)` EQUALS 4')
o.assert_('count `the Penal Code sections named in sections 20, 21, 22, 24 and 35` EQUALS 8')

C = 'Government Contract Facts'
o.section('5, 6, 7 and the others. Punishment')
o.case('no contract', C)
o.case('Government contract', C, 'with the Government or any department')
o.case('public body contract', C, 'with a public body')
o.case('subcontract', C, 'subcontract')
for v in ['Government contract', 'public body contract', 'subcontract']:
    o.assert_('`the matter or transaction was a government or public body contract, or a subcontract` %s' % q(v))
o.assert_('NOT `the matter or transaction was a government or public body contract, or a subcontract` `no contract`')
OFF = {
 'Corruption by soliciting or receiving (section 5(a))': (100000, 60, 84), 'Corruption by giving, promising or offering (section 5(b))': (100000, 60, 84),
 'Agent accepting or obtaining a gratification (section 6(a))': (100000, 60, 84), 'Giving a gratification to an agent (section 6(b))': (100000, 60, 84),
 'False receipt, account or document given to or used by an agent (section 6(c))': (100000, 60, 84),
 'Offering a gratification for the withdrawal of a tender (section 10(a))': (100000, 84, 84),
 'Soliciting or accepting a gratification for withdrawing a tender (section 10(b))': (100000, 84, 84),
 'Offering a gratification to a Member of Parliament (section 11(a))': (100000, 84, 84),
 'Member of Parliament soliciting or accepting a gratification (section 11(b))': (100000, 84, 84),
 'Offering a gratification to a member of a public body (section 12(a))': (100000, 84, 84),
 'Member of a public body soliciting or accepting a gratification (section 12(b))': (100000, 84, 84),
 'Failure to disclose information or produce documents to an authorised person (section 18(2))': (2000, 12, 12),
 'Failure to comply with a notice of the Public Prosecutor (section 21(2))': (10000, 12, 12),
 'Obstruction of search and failure to give information (section 26)': (10000, 12, 12),
 'False or misleading information (section 28)': (10000, 12, 12),
 'Public officer failing to arrest the giver of a gratification (section 32(2))': (5000, 6, 6),
}
for off, (fine, months, months_c) in OFF.items():
    for cv, m in [('no contract', months), ('Government contract', months_c), ('public body contract', months_c), ('subcontract', months_c)]:
        o.assert_('(`the punishment for the offence` %s %s)\'s `the maximum fine in dollars` EQUALS %d' % (q(off), q(cv), fine))
        o.assert_('(`the punishment for the offence` %s %s)\'s `the maximum imprisonment in months` EQUALS %d' % (q(off), q(cv), m))
    o.assert_('(`the punishment for abetting, attempting or conspiring to commit the offence` %s `no contract`)\'s `the maximum imprisonment in months` EQUALS %d' % (q(off), months))
o.assert_('(`the ceiling for an offence under section 5 or 6` `Government contract`)\'s `the maximum imprisonment in months` EQUALS 84')
o.assert_('(`the ceiling for an offence under section 5 or 6` `no contract`)\'s `the maximum imprisonment in months` EQUALS 60')

o.section('13. penalty in addition')
for off in OFF:
    acc = off in ['Corruption by soliciting or receiving (section 5(a))', 'Agent accepting or obtaining a gratification (section 6(a))',
                  'Soliciting or accepting a gratification for withdrawing a tender (section 10(b))', 'Member of Parliament soliciting or accepting a gratification (section 11(b))',
                  'Member of a public body soliciting or accepting a gratification (section 12(b))']
    o.assert_('%s`the offence is committed by the acceptance of a gratification` %s' % ('' if acc else 'NOT ', q(off)))
S13 = 'Section 13 Facts'
CONV, MONEY, ASSESS, TIC = 'is convicted of an offence committed by the acceptance', 'is a sum of money', 'can be assessed', 'taken into consideration under section 148'
o.case('s13 convicted, money', S13, CONV, MONEY, **{'the amount of the gratification': 5000})
o.case('s13 convicted, assessable only', S13, CONV, ASSESS, **{'the amount of the gratification': 12000})
o.case('s13 convicted, neither money nor assessable', S13, CONV, **{'the amount of the gratification': 700})
o.case('s13 not convicted of acceptance', S13, MONEY, **{'the amount of the gratification': 5000})
o.case('s13 convicted, money, other offences considered', S13, CONV, MONEY, TIC, **{'the amount of the gratification': 5000, 'the total amount or value of the gratification specified': 8000})
o.case('s13 convicted, money, no other offences', S13, CONV, MONEY, **{'the amount of the gratification': 5000, 'the total amount or value of the gratification specified': 8000})
o.case('s13 not convicted, other offences considered', S13, MONEY, TIC, **{'the total amount or value of the gratification specified': 8000})
o.assert_('`the court must order a penalty under section 13(1)` `s13 convicted, money`')
o.assert_('`the court must order a penalty under section 13(1)` `s13 convicted, assessable only`')
o.assert_('NOT `the court must order a penalty under section 13(1)` `s13 convicted, neither money nor assessable`')
o.assert_('NOT `the court must order a penalty under section 13(1)` `s13 not convicted of acceptance`')
o.assert_('`the penalty under section 13(1) in dollars` `s13 convicted, money` EQUALS JUST 5000')
o.assert_('`the penalty under section 13(1) in dollars` `s13 convicted, assessable only` EQUALS JUST 12000')
o.assert_('`the penalty under section 13(1) in dollars` `s13 convicted, neither money nor assessable` EQUALS NOTHING')
o.assert_('`the penalty under section 13(1) in dollars` `s13 not convicted of acceptance` EQUALS NOTHING')
o.assert_('`the greatest increase of the penalty the court may make under section 13(2) in dollars` `s13 convicted, money, other offences considered` EQUALS 8000')
o.assert_('`the greatest increase of the penalty the court may make under section 13(2) in dollars` `s13 convicted, money, no other offences` EQUALS 0')
o.assert_('`the greatest increase of the penalty the court may make under section 13(2) in dollars` `s13 not convicted, other offences considered` EQUALS 0')
o.assert_('`the greatest increase of the penalty the court may make under section 13(2) in dollars` `s13 convicted, money` EQUALS 0')

S14 = 'Section 14 Facts'
o.section('14. principal may recover the amount of a secret gift')
o.case('s14 principal v agent', S14, 'has, in contravention of this Act, been given', 'plaintiff is the principal', 'defendant is the agent or the person')
o.case('s14 stranger sues', S14, 'has, in contravention of this Act, been given', 'defendant is the agent or the person')
o.case('s14 principal sues a stranger', S14, 'has, in contravention of this Act, been given', 'plaintiff is the principal')
o.case('s14 no contravening gift', S14, 'plaintiff is the principal', 'defendant is the agent or the person')
o.assert_('`the principal may recover the amount as a civil debt` `s14 principal v agent`')
for v in ['s14 stranger sues', 's14 principal sues a stranger', 's14 no contravening gift']:
    o.assert_('NOT `the principal may recover the amount as a civil debt` %s' % q(v))

o.write(os.path.join(ROW, 'pca-tests-offences.l4'))
print('pca_tests_1 written')
