#!/usr/bin/env python3
"""Write GLOSSARY.md: the hand-written Part A (templates/GLOSSARY-A.md) and a generated Part B, one row per type
DECLAREd in law08-nouns.l4, with its fields or constructors and the source lines quoted above it.

  python3 -I tools/gen_glossary.py
"""
import os, re

HERE = os.path.dirname(os.path.abspath(__file__))
DEP = os.path.dirname(HERE)
SRC = re.compile(r"^\s*-- src:(?:([A-Za-z][\w.-]*):)?(\d+)(?:-(\d+))?\s*\|\s*(.*)$")
SHORT = {None: "", "law08-2022-qh15-577-578": "b:", "law139-2025-qh15": "a:"}


def cut(text, n=64):
    text = re.sub(r"\s+", " ", text).strip()
    if len(text) <= n:
        return text.rstrip(".,;:")
    c = text[:n].rsplit(" ", 1)[0]
    return c.rstrip(".,;:- ")


def main():
    lines = open(os.path.join(DEP, "law08-nouns.l4"), encoding="utf-8").read().split("\n")
    block = []  # the src lines since the previous DECLARE
    rows = []
    i = 0
    section = ""
    while i < len(lines):
        ln = lines[i]
        m = SRC.match(ln)
        if m:
            block.append((m.group(1), int(m.group(2)), m.group(4)))
        elif ln.startswith("§§"):
            section = ln[2:].strip().strip("`")
            block = []
        elif ln.startswith("DECLARE"):
            d = re.match(r"^DECLARE\s+(`[^`]+`|\w+)\s+(HAS|IS ONE OF)(.*)$", ln)
            name, kind, rest = d.group(1), d.group(2), d.group(3)
            items = []
            j = i + 1
            if kind == "HAS":
                while j < len(lines) and (lines[j].startswith((" ", "\t")) or not lines[j].strip()):
                    if not lines[j].strip():
                        break
                    f = re.match(r"^\s+(`[^`]+`)\s+IS\s+(?:A|AN)\s+(.+?)\s*$", lines[j])
                    if f:
                        items.append(f.group(1).strip("`"))
                    j += 1
            else:
                if rest.strip():
                    items = [x.strip().strip("`") for x in rest.split(",") if x.strip()]
                while j < len(lines) and lines[j].startswith((" ", "\t")):
                    t = re.sub(r"\s*--.*$", "", lines[j]).strip()
                    if t:
                        items.append(t.strip("`"))
                    j += 1
            if block:
                first = block[0]
                last = block[-1]
                tag = SHORT.get(first[0], first[0] + ":") if first[0] else ""
                where = f"src:{tag}{first[1]}" + (f"-{last[1]}" if last[1] != first[1] and (last[0] == first[0]) else "")
                viet = cut(first[2])
            else:
                where, viet = "(no source line: a type of this encoding's own)", ""
            rows.append((viet, name.strip("`"), kind, items, where, section))
            block = []
            i = j
            continue
        i += 1
    head = open(os.path.join(DEP, "templates", "GLOSSARY-A.md"), encoding="utf-8").read()
    out = [
        "# GLOSSARY: Vietnamese source, English encoding",
        "",
        "Law 08/2022/QH15 on Insurance Business (Luật Kinh doanh bảo hiểm), encoded in L4 with English identifiers (`@lang en`) and the Vietnamese quoted mechanically from the deposited gazette texts.",
        "Part A is hand-written: every term Điều 4 defines, and the other terms that carry weight, with the translation risk of each English rendering.",
        "Part B is generated by `tools/gen_glossary.py` from `law08-nouns.l4`: one row for every type that module declares, with its fields (records) or constructors (enumerations) and the first Vietnamese line quoted above it.",
        "Nothing here is legal advice and no Vietnamese-qualified lawyer has read it.",
        "",
        head.rstrip(),
        "",
        "## Part B. Every type and field declared in law08-nouns.l4",
        "",
        "The first column is the first line of Vietnamese source quoted above the declaration, cut at a word boundary (a prefix of that line, so it occurs verbatim in the source).",
        "The `where` column is the range of source lines quoted for the declaration. A record field is an English sentence a witness could answer yes or no (or give a date or a sum) for; it is the clause of the quoted lines that it renders.",
        "The translation risk of the enum constructors and fields is that of Part A's term for the same concept; where a field is a conclusion of English drafting rather than a Vietnamese term, no risk is separately recorded.",
        "",
        "| Vietnamese term (verbatim) | English identifier in the L4 | English meaning, one line | where defined or used (Điều / clause, src line) | translation risk |",
        "| --- | --- | --- | --- | --- |",
    ]
    for viet, name, kind, items, where, section in rows:
        kinds = "record, fields: " if kind == "HAS" else "enumeration, constructors: "
        meaning = kinds + "; ".join(items)
        meaning = meaning.replace("|", "/")
        out.append(f"| {viet} | `{name}` | {meaning} | {where} ({section}) | see Part A for the term; none further |")
    out.append("")
    open(os.path.join(DEP, "GLOSSARY.md"), "w", encoding="utf-8").write("\n".join(out))
    print(f"GLOSSARY.md: {len(rows)} types")


if __name__ == "__main__":
    main()
