# The fork register and the findings of NOTES.md, as data, so that NOTES.md and encoding.json carry the same ids and counts.
# A fork is an ambiguity this encoding RESOLVED; a finding is a defect in the instrument as written.
# Each fork: (id, one line for encoding.json, article and source lines, the readings seen, the one taken, and the text that licenses each).
# Each finding: (id, one line, source lines, a minimal scenario, the evidence: a section of law08-tests-findings.l4 or "reading only").

FORKS = [
    ("F1", "Which kind of day 'ngay' is (calendar or working); read as calendar days.",
     "Điều 30, 31, 35, 37, 70, 72, 74, 80, 83, 93, 96, 112, 113, 136; src:707-708, 723, 761-762, 782, 1307, 1336-1342, 1394-1400, 1541-1542, 1652, 1972, 2039, 2343, 2396-2415.",
     "(i) calendar days; (ii) working days.",
     "(i) calendar days, counted from the day named as day 0 (the last day is that day plus N).",
     "Điều 117(2) writes 'ngày làm việc' (working days) where it means them (src:2559, 2562, 2564); the Law defines neither phrase. The contrast licenses (i) for the plain 'ngày'. Outside knowledge about the Civil Code's rules on periods is not used."),
    ("F2", "Rules that read no vintage date do not refuse before 1 January 2023.",
     "Điều 156(1), src:b:524-525.",
     "(i) every rule refuses for a date before the commencement; (ii) only rules with dated arms do.",
     "(ii).",
     "Only a rule with a dated arm has a pre-commencement arm to write; the others quote one text. A question about a date before 2023 should be asked of a pinned vintage (tests do)."),
    ("F3", "Điều 3(1): the consequence for a later law that differs without saying what content it applies is not stated.",
     "Điều 3(1), src:50-56.",
     "(i) the differing provision is ineffective; (ii) the later law prevails; (iii) this Law prevails.",
     "None: the rule answers only whether the condition (the later law 'phải xác định cụ thể') is met.",
     "The text states the condition and no consequence."),
    ("F4", "Điều 4(6): the two limbs of brokerage are alternatives.",
     "Điều 4(6), src:96-100.",
     "(i) either limb makes the activity brokerage; (ii) both are needed.",
     "(i).",
     "The semicolon after the first limb ('...doanh nghiệp tái bảo hiểm, chi nhánh nước ngoài tại Việt Nam;') introduces a second activity of the same kind, not a further condition."),
    ("F5", "Điều 8(2)(c) and Law 139 Điều 2(1): whether 'hoạt động xây dựng' is wider than 'hoạt động đầu tư xây dựng'.",
     "Điều 8(2)(c), src:231; Law 139 Điều 2(1), src:a:321-322.",
     "(i) wider; (ii) narrower; (iii) the same.",
     "None: the two phrases are two separate input facts; neither is defined in the sources.",
     "Any reading would rest on the law on construction, which is not a source (outside knowledge, unverified)."),
    ("F6", "Điều 63(3): 'từ 01 năm trở xuống' is a term of 12 months or less, and the two products of (b) are each separately allowed.",
     "Điều 63(3)(b)-(c), src:1158-1163; Law 139 Điều 1(2), src:a:33-39.",
     "(i) 12 months or less; (ii) strictly under one year; and for 'và': (i) each product separately; (ii) both together.",
     "(i) and (i).",
     "'Trở xuống' means 'and below', so the bound is inclusive; the list of exceptions would be empty if 'và' required both products at once."),
    ("F7", "Điều 22(2), 35, 47(2): a refund net of reasonable costs cannot be negative.",
     "Điều 22(2), src:549-551; Điều 35, src:764-766; Điều 47(2), src:943-945, 949-951.",
     "(i) refuse when costs exceed the premium; (ii) refund zero; (iii) the insured owes the difference.",
     "(i).",
     "The Law says 'sau khi trừ các chi phí hợp lý (nếu có)' and nothing on the floor."),
    ("F8", "Điều 26: which side may terminate on which ground.",
     "Điều 26, src:623-635.",
     "(i) each ground belongs to the side the ground implies (non-payment and unsafe property: the insurer; non-acceptance of a change of risk: either; refusal of a portfolio transfer: the policyholder); (ii) either side on every ground.",
     "(i).",
     "The chapeau gives the right to 'doanh nghiệp bảo hiểm ... hoặc bên mua bảo hiểm' without allocating; (ii) would let a policyholder who stopped paying 'terminate for non-payment'."),
    ("F9", "Điều 28: all three conditions of the transfer are conditions of effect.",
     "Điều 28, src:679-689.",
     "(i) the insured person's consent (life), the transferee's interest, and notice plus the insurer's consent are all required; (ii) only paragraph 3 is a condition of effect.",
     "(i).",
     "Paragraph 2 says the transferee 'phải có' an insurable interest and paragraph 1 requires the written consent; paragraph 3 alone speaks of effect ('chỉ có hiệu lực khi')."),
    ("F10", "Điều 30(1): the last day of the one year is the anniversary of the starting day, plus the force majeure days; the leap-day start is not decided.",
     "Điều 30(1), src:707-710.",
     "(i) the anniversary; (ii) the day before it.",
     "(i); a start on 29 February is not asserted in any test (the library's `add years` clamps to 28 February).",
     "'01 năm kể từ ngày xảy ra sự kiện' fixes a year from a day; the Law does not say whether the starting day counts."),
    ("F11", "Điều 30(2)-(3): which start day wins when the claimant did not know of the event and a third person has also made a demand.",
     "Điều 30(2)-(3), src:711-717.",
     "(i) the third person's demand; (ii) the day the claimant learned.",
     "(i): paragraph 3 is the more specific (liability) rule.",
     "Both paragraphs say 'thời hạn quy định tại khoản 1 Điều này được tính từ'."),
    ("F12", "Điều 31(2): the interest rate is the parties' (Civil Code) and is taken as a rate per day; there is no default.",
     "Điều 31(2), src:725-729.",
     "(i) a per-day input; (ii) a per-year input with a 365-day year; (iii) a default.",
     "(i), with no default.",
     "'Lãi suất ... xác định theo thỏa thuận của các bên theo quy định của Bộ luật Dân sự': the rate and its unit come from outside the sources, and the brief forbids a default."),
    ("F13", "Điều 27(2): the premium refund 'theo thỏa thuận' is taken as the premium paid for the remaining period.",
     "Điều 27(2), src:658-662.",
     "(i) the premium for the remaining period; (ii) that less costs.",
     "(i).",
     "Điều 27(2) allows no deduction, unlike Điều 22(2), 35, 47."),
    ("F14", "Điều 35: 'thời hạn trên 01 năm' is tested by the last day of the term falling after the first anniversary of the first day.",
     "Điều 35, src:761.",
     "(i) after the anniversary; (ii) 366 days or more; (iii) inclusive counting of the last day.",
     "(i): a term of 1 January 2025 to 1 January 2026 is exactly a year, and to 2 January 2026 is more.",
     "The Law does not say how a term is measured."),
    ("F15", "Điều 35: the 21 days run from the day the policyholder receives the contract, which is day 0.",
     "Điều 35, src:761-762.",
     "(i) day 0, so the last day is the day plus 21; (ii) day 1, so the day plus 20.",
     "(i).",
     "'Trong thời hạn 21 ngày kể từ ngày nhận được'."),
    ("F16", "Điều 35 applies to every contract of more than a year, not only life and health.",
     "Điều 35, src:760-769 and Mục 2 heading, src:737-739.",
     "(i) every class, by the words; (ii) life and health only, by the placement under Mục 2.",
     "(i).",
     "The words begin 'Đối với các hợp đồng bảo hiểm có thời hạn trên 01 năm' with no limit; Điều 21(1)(đ) lists a right to rescind under Điều 35 for the policyholder in general. See finding W6."),
    ("F17", "Điều 37(2): the 60 days of grace run from a date the contract or the instalment fixes; the encoding takes that date as an input.",
     "Điều 37(2), src:780-782.",
     "(i) from the due date of the unpaid instalment; (ii) from notice by the insurer.",
     "Neither: the start date is an input field.",
     "The text gives the length and not the start."),
    ("F18", "Điều 39: for a minor the parent's or guardian's written consent also satisfies the person's own consent in paragraph 1.",
     "Điều 39(1)-(2), src:805-811.",
     "(i) the parent's consent satisfies both; (ii) the minor's own consent is also needed.",
     "(i).",
     "A minor's written consent to a contract on their own death is not a coherent requirement beside 39(2)(a)."),
    ("F19", "Điều 40(3): 'giá trị hoàn lại ... hoặc toàn bộ số phí bảo hiểm đã đóng sau khi trừ các chi phí hợp lý' is a single figure supplied as an input.",
     "Điều 40(3), src:835-838.",
     "(i) the surrender value if there is one, else the premium less costs; (ii) the larger; (iii) the contract chooses.",
     "None: the figure is an input.",
     "The Law leaves the choice to 'thỏa thuận trong hợp đồng bảo hiểm'."),
    ("F20", "Điều 46(1): the reduction cannot take the compensation below zero.",
     "Điều 46(1), src:922-927.",
     "(i) floor at zero; (ii) refuse.",
     "(i).",
     "The reduction is 'tương ứng với thiệt hại mà' the insurer bears, which can exceed the compensation."),
    ("F21", "Điều 47(2)(a): 'tương ứng' is premium x (sum insured - market value) / sum insured.",
     "Điều 47(2)(a), src:941-945.",
     "(i) that; (ii) premium x excess / market value; (iii) a pro rata over the term.",
     "(i).",
     "'Số phí bảo hiểm đã đóng tương ứng với số tiền bảo hiểm vượt quá giá thị trường': the premium paid is for the whole sum insured, so the part for the excess is the excess over the sum insured."),
    ("F22", "Điều 47(2)(b): 'bồi thường thiệt hại tương ứng với giá thị trường ... tại thời điểm xảy ra thiệt hại' is read as capped at that market value.",
     "Điều 47(2)(b), src:946-952.",
     "(i) the lesser of the loss and the market value at the loss; (ii) the loss in the ratio of the market value to the sum insured.",
     "(i).",
     "The sentence says the insurer 'chỉ chịu trách nhiệm' for the loss corresponding to the market value, which reads as a cap; a ratio would need a stated denominator."),
    ("F23", "Working days (Điều 117): Saturday and Sunday are not working days and a calendar of other non-working days is supplied.",
     "Điều 117(2)-(3), src:2559-2566.",
     "(i) weekends excluded, holidays supplied; (ii) a six-day week; (iii) no calendar: refuse.",
     "(i).",
     "The Law defines 'ngày làm việc' nowhere in the sources. Which weekdays are working days in Vietnam is outside the sources, so holidays are an input and only the weekend rule is assumed."),
    ("F24", "Điều 98(2): the last year's contribution is limited to the room left under the maximum.",
     "Điều 98(2), src:2074-2075.",
     "(i) 5% of profit capped by the room; (ii) always 5%, then stop.",
     "(i).",
     "'Cho đến khi bằng mức tối đa'."),
    ("F25", "Điều 101 (V2): the second paragraph names no duty for a reinsurer or a mutual organisation, so none is applied.",
     "Điều 101(2), src:a:206-214.",
     "(i) no duty; (ii) the non-life duty extends to reinsurers.",
     "(i).",
     "The paragraph names life insurers and non-life insurers/branches only."),
    ("F26", "Điều 65: the Law's two thresholds and the Government's 'mức tổng tài sản tối thiểu phù hợp với từng thời kỳ' both apply.",
     "Điều 65(1)(d), (2), (3), src:1211-1228.",
     "(i) the member must reach both; (ii) the Government's figure replaces the Law's.",
     "(i).",
     "Paragraph 3 says the Government fixes the minimum 'căn cứ quy định tại điểm d khoản 1 và khoản 2', i.e. on the basis of the Law's figures; whether it may lower them is not said (finding W10)."),
    ("F27", "Điều 58(1): 'trong thời hạn bảo hiểm' qualifies the act (an occurrence rule); the claims-made reading is also encoded, separately.",
     "Điều 58(1), src:1083-1086.",
     "(i) the act within the term; (ii) the third person's claim within the term.",
     "Both are functions; the rule used elsewhere is (i).",
     "The modifier follows both 'yêu cầu' and 'hành vi gây thiệt hại'; the sentence has no comma. Finding W8."),
    ("F28", "Điều 87(3): a product line the article does not name has no premium-method requirement.",
     "Điều 87(3), src:1776-1782; Điều 87(1), src:1757-1759.",
     "(i) no requirement; (ii) refuse.",
     "(i), by Điều 87(1) ('chủ động, tự chịu trách nhiệm').",
     "A refusal would mean the Law forbids what it does not mention."),
    ("F29", "Điều 81: 'doanh nghiệp' (V1) and 'tổ chức' (V2) in the experience limb for board members are not distinguished.",
     "Điều 81(2)(c), src:1561-1568; Law 139 Điều 1(5), src:a:90-99.",
     "(i) one field for both; (ii) two fields.",
     "(i); the V2 widening for the chief executive (insurer-only versus any insurance, finance or banking organisation) is encoded with two fields.",
     "The sources do not define either word; a witness would have no way to tell them apart."),
    ("F30", "Điều 127(1) (V1): 'cùng loại hình bảo hiểm' is tested by the two principals carrying on a type of insurance in common.",
     "Điều 127(1), src:2735-2743.",
     "(i) overlap of the types each principal may carry on; (ii) the principals' own primary types.",
     "(i).",
     "The Law lets a life insurer carry on health insurance (Điều 63(3)(a)), so the 'type' of an insurer is a set."),
    ("F31", "Điều 64(1): limb (a) applies to every founder, limb (b) to organisations, limb (c) to licensed insurers founding a new one; '10% trở lên' includes 10%.",
     "Điều 64(1), src:1166-1179.",
     "(i) that; (ii) limb (b) also to individuals.",
     "(i).",
     "Limb (b) begins 'Tổ chức có tư cách pháp nhân'; Điều 66(2) separately limits individuals to 10%."),
    ("F32", "Điều 79(1)(b): 'ít nhất 20% số thành viên Hội đồng quản trị phải là thành viên độc lập' is tested without rounding.",
     "Điều 79(1)(b), src:1504.",
     "(i) independent members at least 0.2 x the board; (ii) rounded up.",
     "(i): one independent of four (25%) and one of five (20%) pass, one of six (16.7%) fails.",
     "No rounding rule is stated."),
    ("F33", "Điều 40(1)-(2): the beneficiary at fault is not paid; the other beneficiaries are; where there is a single beneficiary the exclusion applies to the claim.",
     "Điều 40(1)(b)-(c), (2), src:821-834.",
     "(i) that; (ii) the insurer pays the policyholder's estate.",
     "(i), with the Điều 40(3) refund to the policyholder.",
     "Paragraph 2 protects 'những người thụ hưởng khác' only."),
    ("F34", "Inclusive bounds: 'không được ... quá 30%' (99(2)(d)), 'tối thiểu 75%' (90(2)(đ)), 'trở lên' (120(1)(m)) are tested with the figure itself passing.",
     "Điều 99(2)(d), src:2097; Điều 90(2)(đ), src:1895; Điều 120(1)(m), src:2620.",
     "(i) inclusive; (ii) exclusive.",
     "(i).",
     "'Không quá', 'tối thiểu' and 'trở lên' all include the figure."),
    ("F35", "Điều 120(1)(đ): a transfer that takes a holder to 10% or above, or below 10%, is unusual information; a move inside either band is not.",
     "Điều 120(1)(đ), src:2602-2603.",
     "(i) crossing the 10% line in either direction; (ii) any transfer by or to a 10% holder.",
     "(i).",
     "The text names the two crossings."),
    ("F36", "Điều 73(1): the extension is counted in months from the licence date, 12 + n.",
     "Điều 73(1), src:1345-1351; src:a:44-52.",
     "(i) 12 + n months from the licence; (ii) n months from the original deadline.",
     "(i) (the same date as (ii)).",
     "'Thời gian gia hạn tối đa là 12 tháng'."),
    ("F37", "Dated arms and the day in the question: a deferred commencement (Điều 156(2)) is asked of two clocks, the text in force and the day.",
     "Điều 156(2), src:b:528-530; src:a:292-295.",
     "(i) the day is an input beside the rule-version axis; (ii) the rule-version date doubles as the day.",
     "(i).",
     "A question 'was Điều 110 in force on 1 June 2029' has a different answer under the text as made and under the amended text; (ii) cannot ask that."),
    ("F38", "Điều 8(5), 17(2), 87(5)-(6) and the other delegations: the Government's and the Minister's content is never supplied; a rule that needs it refuses.",
     "Every delegation in NOTES.md section 1.",
     "(i) refuse; (ii) assume the Law's own default where it has one.",
     "(i) where the article has no fallback, (ii) never invented.",
     "'Inputs, never defaults' (BRIEF.md)."),
]

FINDINGS = [
    ("W1", "The replaced Điều 73 drops the bar on carrying on insurance business before the date of official operation.",
     "src:1377-1379; Law 139 Điều 1(3), src:a:40-68.",
     "An insurer that trades before its opening date breaches Điều 73(4) in V1; in V2 and V3 no paragraph says so (Điều 9(1)-(2) still bar business without or outside a licence, which a licensed insurer has).",
     "law08-tests-findings.l4, section W1."),
    ("W2", "From 2028 to 2030 the V2 text has the capital adequacy ratio (Điều 95) in force but not the supervisory measures (Điều 109-114, 116), while old Điều 77-81, 83, 98 and the interim duty of Điều 156(4) run on.",
     "Điều 156(2), src:b:528-530; Law 139 Điều 1(14), src:a:292-310; Điều 91(1), src:1936-1937.",
     "On 1 June 2029 the V1 text has the control measure in force and the V2 text does not; an insurer at the control level can be ordered nothing; Điều 91(1) lists a transfer required under Điều 113(8) as a case of portfolio transfer, which cannot arise.",
     "law08-tests-findings.l4, section W2."),
    ("W3", "Điều 153(1)(c) lets the Ministry ask banks about breaches of provisions not yet in force (Điều 95, 99(3)-(4), 109, 110).",
     "src:b:473-483 (file 2, lines 473-483); Điều 156(2).",
     "On 1 June 2025 Điều 109 and 110 are not in force even in part, and under the V2 text they are not in force until 2031.",
     "law08-tests-findings.l4, section W3."),
    ("W4", "The repeal of Điều 155 from 1 July 2026 says nothing of the lines it added to the Investment Law's Appendix IV.",
     "src:b:516-522; Law 139 Điều 2(8), src:a:339.",
     "Is insurance brokerage still a conditional investment line on 2 July 2026? The Law repeals the amending provision and does not say whether the amendment stays; V3 answers with silence.",
     "law08-tests-findings.l4, section W4."),
    ("W5", "V3 repeals Điều 143 (conditions for ancillary services) and strikes ancillary services from the bar in Điều 9(3), yet Điều 4(7), 63(1)(c), 131(2) and 140-142 still let insurers, brokers and others supply them.",
     "src:b:259-286; Law 139 Điều 2(6) and 2(8), src:a:333-339; Điều 63(1)(c), src:1147.",
     "An adviser with no degree is outside Điều 143 in V2 (and fails it) but in V3 Điều 143 does not exist; an unqualified ancillary provider's act is prohibited in V2 and not in V3.",
     "law08-tests-findings.l4, section W5."),
    ("W6", "Điều 35 sits in the section on life and health contracts, but its words give every contract of more than a year a 21-day withdrawal.",
     "src:760-769; Mục 2 heading, src:737-739.",
     "A ten-year property contract: the policyholder may refuse to go on on day 10 and recover the premium less reasonable costs.",
     "law08-tests-findings.l4, section W6."),
    ("W7", "Điều 26 gives either side the right to terminate on four grounds without saying which side may use which.",
     "src:623-635.",
     "Read literally, a policyholder who has not paid is a side that 'may terminate' for the non-payment.",
     "law08-tests-findings.l4, section W7 (shows the reading the encoding takes)."),
    ("W8", "Điều 58(1) reads as an occurrence rule or as a claims-made rule, with opposite answers.",
     "src:1083-1086.",
     "A claim made after the term for an act within it: liability arises on one reading and not on the other; a claim within the term for an earlier act, the reverse.",
     "law08-tests-findings.l4, section W8."),
    ("W9", "Điều 148(2) names the general rules, life, health and property contracts of Chương II for a mutual organisation's contracts and is silent on damage and liability contracts, though Điều 15(1) lists damage contracts separately.",
     "src:b:358-361; Điều 15(1), src:370-377.",
     "A mutual organisation's liability contract: no rule of Chương II is named.",
     "law08-tests-findings.l4, section W9."),
    ("W10", "Điều 65(3) lets the Government fix the minimum total assets 'for each period' on the basis of figures the Law itself states.",
     "src:1211-1228.",
     "A Vietnamese company with 2,500 billion of assets passes the Law's 2,000 billion and fails a Government minimum of 3,000 billion; the Law does not say whether the Government may set it lower than the Law.",
     "law08-tests-findings.l4, section W10."),
    ("W11", "After Điều 69 is repealed (V2) the 60 days of Điều 70(1) still run from a 'hồ sơ hợp lệ' the Law no longer describes.",
     "src:1283-1305, 1307; Law 139 Điều 2(7), src:a:336-337.",
     "The clock runs from receipt of a complete and valid dossier (an input) but the Law cannot say when a dossier is complete.",
     "law08-tests-findings.l4, section W11."),
    ("W12", "Điều 127(1) in V1 and V2 bars different pairs of principals.",
     "src:2735-2743; Law 139 Điều 1(9), src:a:224-233.",
     "An individual who is an agent of a life insurer that also sells health insurance and of a health insurer: barred in V1, free in V2.",
     "law08-tests-findings.l4, section W12."),
    ("W13", "V2 drops 'the right to manage an enterprise under the Law on Enterprises' from the general conditions of an officer.",
     "src:1550; Law 139 Điều 1(5), src:a:79-85.",
     "An officer without that right meets the general conditions in V2 and not in V1.",
     "law08-tests-findings.l4, section W13."),
    ("W14", "The deposit of Điều 96 is 2% of the MINIMUM charter capital at establishment, so it does not grow with the insurer.",
     "src:2031-2033.",
     "An insurer that has grown tenfold deposits the same sum.",
     "law08-tests-findings.l4, section W14."),
    ("W15", "Điều 98 sets aside 5% of after-tax profit until a maximum the Government fixes; the Law gives no maximum, so the contribution cannot be computed from the Law alone.",
     "src:2074-2075.",
     "A fund with no maximum supplied: the encoding refuses.",
     "law08-tests-findings.l4, section W15."),
    ("W16", "The Law counts 'ngày' without defining it and uses 'ngày làm việc' only in Điều 117.",
     "src:2559-2566 and passim.",
     "Seven days from Monday 3 March 2025: Monday 10 March as calendar days, Wednesday 12 March as working days.",
     "law08-tests-findings.l4, section W16."),
    ("W17", "The V2 extension of agent certificates in Điều 157(2) restores a use the V1 text had ended.",
     "src:b:544-547; Law 139 Điều 1(15), src:a:312-317.",
     "On 1 March 2026 an old agent certificate is usable under the V2 text and not under the V1 text.",
     "law08-tests-findings.l4, section W17."),
    ("W18", "Two rules for the same shortfall of assets on a transfer of portfolio: a pro rata refund (Điều 27(4)) and a negotiated reduction (Điều 92(3)).",
     "src:670-678, 1953-1960.",
     "Assets at 80% of the reserve: the terminating policyholder gets 80% of the surrender value; a policyholder who stays must negotiate a reduction whose measure the Law does not give.",
     "law08-tests-findings.l4, section W18."),
    ("W19", "The phrase swaps of Law 139/2025/QH15 Điều 2(1) (Điều 8) and Điều 1(2) (Điều 63) change who is covered, not only wording.",
     "Law 139 Điều 2(1), src:a:321-322; Điều 1(2), src:a:32-39.",
     "A product in 'hoạt động xây dựng' only is compulsory insurance in V2 and not in V1, and the reverse for one in 'hoạt động đầu tư xây dựng' only.",
     "law08-tests-findings.l4, section W19."),
    ("W20", "Điều 40(1)(a) counts the 2 years from the first premium OR from the restoration, so a restored old contract has a fresh suicide exclusion.",
     "src:816-820.",
     "A ten-year-old contract restored on 1 March 2025: a suicide on 1 March 2026 is excluded.",
     "law08-tests-findings.l4, section W20."),
    ("W21", "Điều 25(1)(h) makes void a contract made because a party was deceived, except in the case of Điều 22, where a deliberate misstatement by either side gives rescission and a refund instead; the Law does not draw the line between the two.",
     "src:612-613, 543-559.",
     "A policyholder who was lied to by the insurer's agent about the terms: void from the making (25(1)(h)) or rescindable with a refund (22(3))?",
     "law08-tests-findings.l4, section W21 (shows the exception)."),
    ("R1", "Điều 116(3)(c) ranks only claims the insurer 'đã ... chấp thuận chi trả': a claim not yet accepted has no rank at all.",
     "src:2520-2523.",
     "A policyholder with a disputed or unresolved claim in the bankruptcy of an insurer.",
     "reading only."),
    ("R2", "Điều 115(1)(d) refers to 'thời gian áp dụng biện pháp kiểm soát' (Điều 113), which does not exist until 2028 (V1) or 2031 (V2), though Điều 115 takes effect in 2023.",
     "src:2491-2492; Điều 156(2).",
     "A foreign branch that fails to restore its ratio after a control period before 2028.",
     "reading only (the dates are tested at law08-tests-ch7-commencement.l4)."),
    ("R3", "Điều 135 and 138(8) cite Điều 71 and 117 whole; Điều 71(3) and 117(3) are repealed from V2, so a broker has no registry-notification duty and no 7-working-day notice duty in V2.",
     "src:b:99-100, 197-200; Law 139 Điều 2(7), src:a:336-337.",
     "A broker's licence is granted in 2026: no provision tells the Ministry to notify the business register.",
     "reading only."),
    ("R4", "Điều 3(3) (new in V2) states the right to contribute capital in terms that overlap Điều 64(1)(a) and 133(1)(a) (repealed the same day), but speaks of 'góp vốn thành lập, quản lý, kiểm soát' rather than of licensing conditions.",
     "Law 139 Điều 1(1), src:a:26-30; Điều 2(7), src:a:336-337.",
     "Whether a person who acquires shares after the licence is covered.",
     "reading only."),
    ("R5", "Law 139/2025/QH15 was passed on 10 December 2025 and published in Công báo số 39 of 22 January 2026 but takes effect on 1 January 2026, and its Điều 1(15) extends a period that V1 ended on 31 December 2025.",
     "Law 139 Điều 3(1), src:a:343-344; passed, src:a:349-350; the gazette header, src:a:4; Điều 1(15), src:a:314-317.",
     "Between 1 and 22 January 2026 the V2 text was in force and not yet published.",
     "reading only (the publication rules are outside the sources)."),
    ("R6", "Điều 157(3) keeps ancillary certificates usable though Điều 143(4), the basis for issuing them, is repealed from V3.",
     "src:b:548-549, 284-286; Law 139 Điều 2(8), src:a:339.",
     "A holder of an ancillary insurance certificate after 1 July 2026.",
     "reading only."),
    ("R7", "Early intervention and control are triggered by a ratio 'ở mức phải áp dụng' which the Law does not state (the Minister decides, Điều 109(3)), and the Ministry's choice of measures in Điều 112(6) and 113(8) is 'tùy theo tính chất, mức độ, rủi ro' with no criteria.",
     "src:2336-2342, 2381-2386, 2364-2372, 2429-2444, 2298-2300.",
     "Two insurers in the same position treated differently.",
     "reading only (the encoding takes the trigger as an input fact)."),
    ("R8", "Điều 65(1)(d) asks 2 billion US dollars of a foreign member and Điều 65(2) 2,000 billion VND of a Vietnamese one; at any rate near the one widely reported these differ by a large factor (outside knowledge, unverified; no exchange rate is in the sources).",
     "src:1211-1226.",
     "A Vietnamese member needs a far smaller balance sheet than a foreign one.",
     "reading only (outside knowledge, unverified)."),
    ("R9", "Điều 3(1) says a later law that wants to differ 'phải xác định cụ thể' what it applies, but gives no consequence for failing.",
     "src:50-56.",
     "A later law silent on the point.",
     "reading only (fork F3)."),
    ("R10", "Điều 8(2)(c): the Law does not define 'hoạt động đầu tư xây dựng' or 'hoạt động xây dựng', so whether the V2 change widens or narrows compulsory construction insurance cannot be told from the sources.",
     "Law 139 Điều 2(1), src:a:321-322.",
     "A designer or a surveyor.",
     "reading only (outside knowledge would be needed)."),
]
