#!/usr/bin/env python3
"""Regenerates the "Readings" section of ito-il29-test-people.l4: the readings of the forks of row IL-29, the defaults
with one fork set (L4 has no record update syntax), and with two forks set.  Usage: gen_readings.py FILE.l4
(rewrites everything from the line "§ `Readings`" to the end of the file)."""
import pathlib
import sys

FIELDS = [
    ("ties", "A reading of ties that all lie one way", "declined where only the ties would decide"),
    ("rebuttal", "A reading of a rebutted presumption", "declined where a rebutted presumption is the only fact"),
    ("windows", "A reading of how a window of time is matched with a tax year", "declined where the readings differ"),
    ("five years", "A reading of the five preceding tax years", "declined where the readings differ"),
    ("ninety days", "A reading of the 90 days", "declined where the readings differ"),
    ("journalist or athlete", "A reading of a foreign journalist or athlete", "declined where the readings differ"),
    ("years deemed", "A reading of the tax years the second limb deems", "declined where the readings differ"),
    ("partial day", "A reading of a day partly outside Israel", "declined where the readings differ"),
    ("both statuses", "A reading of a person who is both an Israeli resident and a foreign resident", "declined where the readings differ"),
    ("part-year connection", "A reading of a connection that lasted part of a tax year", "declined where the readings differ"),
    ("midpoint", "A reading of a midpoint in rounding to ten shekels", "declined where the midpoint decides"),
    ("excess deduction", "A reading of a deduction that exceeds the value", "declined where the readings differ"),
    ("old schedule", "A reading of the schedule that the temporary provision reduces", "declined where the readings differ"),
    ("depreciation base", "A reading of the base of the use depreciation", "declined where the readings differ"),
    ("part month", "A reading of a part of a month", "declined where the readings differ"),
    ("part month of depreciation", "A reading of a part of a month of use depreciation", "declined where the readings differ"),
]
PAIRS = [("windows", "ninety days"), ("windows", "five years"), ("windows", "journalist or athlete"), ("partial day", "years deemed"),
         ("part month", "excess deduction"), ("old schedule", "excess deduction"), ("depreciation base", "part month of depreciation"),
         ("midpoint", "excess deduction")]
TYPES = {f: t for f, t, d in FIELDS}
DEFAULT = {f: d for f, t, d in FIELDS}

out = ["§ `Readings`", "", "-- The default readings, with one fork set; generated by tools/gen_readings.py, one constructor per fork (L4 has no record update).", ""]
for f, t, d in FIELDS:
    out += [f"GIVEN x IS A `{t}`", "GIVETH A `The readings of the forks of row IL-29`", f"`the defaults, except {f} read` x MEANS",
            "    `The readings of the forks of row IL-29` WITH"]
    out += [f"        `{g}` IS " + ("x" if g == f else f"`{DEFAULT[g]}`") for g, _, _ in FIELDS] + [""]
out += ["", "-- Two forks set at once (generated).", ""]
for f, g in PAIRS:
    out += [f"GIVEN x IS A `{TYPES[f]}`", f"      y IS A `{TYPES[g]}`", "GIVETH A `The readings of the forks of row IL-29`",
            f"`the defaults, except {f} read` x `and {g} read` y MEANS", "    `The readings of the forks of row IL-29` WITH"]
    out += [f"        `{h}` IS " + ("x" if h == f else "y" if h == g else f"`{DEFAULT[h]}`") for h, _, _ in FIELDS] + [""]
p = pathlib.Path(sys.argv[1])
s = p.read_text()
p.write_text(s[: s.index("§ `Readings`")] + "\n".join(out))
