"""Tests for cpc-second-schedule.l4 (the Second Schedule and ss 159, 211A).  Expected values are read off the printed Schedule and the
two sections (source/CPC2010.txt), never off the encoding."""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from fixtures import Types, Out

ROW = os.path.join(os.path.dirname(__file__), '..')
types = Types(os.path.join(ROW, 'cpc-types.l4'), os.path.join(ROW, 'ea-cpc-interface.l4'))
def q(x): return '`%s`' % x

o = Out(types, """IMPORT prelude
IMPORT `cpc-types`
IMPORT `cpc-second-schedule`

-- Tests for cpc-second-schedule.l4 (Criminal Procedure Code 2010, Second Schedule, ss 159 and 211A).
-- Expected values are read off the printed Schedule and the two sections.  Generated by generators/cpc_tests_2.py.""")

ACT = 'the Act under which the offence is created'
SEC = 'the section of that Act, without subsections'
OLD = 'as in force immediately before the date'
def w(var, act, sec='', old=False):
    o.case(var, 'Written Law Offence Facts', *([OLD] if old else []), **{ACT: act, SEC: sec})

o.section('The Schedule as printed: 32 items')
o.assert_('count `the Second Schedule` EQUALS 32')
items = [('1','Arms and Explosives Act 1913'),('2','Arms Offences Act 1973'),('2A','Banishment Act 1959'),('3','Banking Act 1970'),('3A','Casino Control Act 2006'),('4','Computer Misuse Act 1993'),('5','Corrosive and Explosive Substances and Offensive Weapons Act 1958'),('6','Corruption, Drug Trafficking and Other Serious Crimes (Confiscation of Benefits) Act 1992'),('7','Criminal Law (Temporary Provisions) Act 1955'),('7A','Guns, Explosives and Weapons Control Act 2021'),('8','Hijacking of Aircraft and Protection of Aircraft and International Airports Act 1978'),('9','Immigration Act 1959'),('9A','Infrastructure Protection Act 2017'),('10','Internal Security Act 1960'),('10A','Maintenance of Racial Harmony Act 2025'),('11','Maintenance of Religious Harmony Act 1990'),('12','Misuse of Drugs Act 1973'),('12A','Moneylenders Act 2008'),('13','Oaths and Declarations Act 2000'),('14','Official Secrets Act 1935'),('15','Passports Act 2007'),('16','Penal Code 1871'),('16A','Prevention of Corruption Act 1960'),('16B','Prevention of Human Trafficking Act 2014'),('17','Prisons Act 1933'),('18','Protected Areas and Protected Places Act'),('19','Public Entertainments Act 1958'),('20','Public Order and Safety (Special Powers) Act 2018'),('20A','Remote Gambling Act 2014'),('21','Securities and Futures Act 2001'),('22','Sedition Act 1948'),('23','Vandalism Act 1966')]
assert len(items) == 32
for n, a in items:
    o.assert_('(at (`the Second Schedule items for the Act` "%s") 0)\'s `item number` EQUALS "%s"' % (a, n))
o.assert_('count (`the Second Schedule items for the Act` "Road Traffic Act 1961") EQUALS 0')

o.section('An offence under a listed law')
for i, (n, a) in enumerate(items):
    if a in ('Banishment Act 1959', 'Immigration Act 1959'):
        continue
    w('law %s' % n, a, '10')
    o.assert_('`the offence is under a law specified in the Second Schedule` `law %s`' % n)
w('Road Traffic Act 1961', 'Road Traffic Act 1961', '10')
w('Consumer Protection (Fair Trading) Act 2003', 'Consumer Protection (Fair Trading) Act 2003', '10')
w('Criminal Procedure Code 2010', 'Criminal Procedure Code 2010', '10')
o.assert_('NOT `the offence is under a law specified in the Second Schedule` `Road Traffic Act 1961`')
o.assert_('NOT `the offence is under a law specified in the Second Schedule` `Consumer Protection (Fair Trading) Act 2003`')
o.assert_('NOT `the offence is under a law specified in the Second Schedule` `Criminal Procedure Code 2010`')

o.section('Item 9: Immigration Act 1959 (other than sections 6 and 15)')
w('Immigration Act s 6', 'Immigration Act 1959', '6')
w('Immigration Act s 15', 'Immigration Act 1959', '15')
w('Immigration Act s 5', 'Immigration Act 1959', '5')
w('Immigration Act s 57', 'Immigration Act 1959', '57')
w('Immigration Act s 16', 'Immigration Act 1959', '16')
o.assert_('NOT `the offence is under a law specified in the Second Schedule` `Immigration Act s 6`')
o.assert_('NOT `the offence is under a law specified in the Second Schedule` `Immigration Act s 15`')
for v in ['Immigration Act s 5', 'Immigration Act s 57', 'Immigration Act s 16']:
    o.assert_('`the offence is under a law specified in the Second Schedule` %s' % q(v))

o.section('Item 2A: Banishment Act 1959 as in force before the Immigration (Amendment) Act 2023')
w('Banishment Act, the old version', 'Banishment Act 1959', '8', old=True)
w('Banishment Act, any other version', 'Banishment Act 1959', '8')
o.assert_('`the offence is under a law specified in the Second Schedule` `Banishment Act, the old version`')
o.assert_('NOT `the offence is under a law specified in the Second Schedule` `Banishment Act, any other version`')
o.assert_('(at (`the Second Schedule items for the Act` "Banishment Act 1959") 0)\'s `qualification` EQUALS "as in force immediately before the date of commencement of section 61 of the Immigration (Amendment) Act 2023"')
o.assert_('(at (`the Second Schedule items for the Act` "Immigration Act 1959") 0)\'s `qualification` EQUALS "other than sections 6 and 15"')
o.assert_('(at (`the Second Schedule items for the Act` "Protected Areas and Protected Places Act") 0)\'s `Act as printed` EQUALS "Protected Areas and Protected Places Act (Cap. 256, 2013 Revised Edition)"')

o.section('159. State Courts (Part 9): Second Schedule law and a District Court trial')
D = 'the offence is to be tried in a District Court'
CONS = 'all parties consent to have the criminal case disclosure procedures apply'
def d(var, *true): o.case(var, 'State Court Disclosure Facts', *true)
d('tried in a District Court', D)
d('tried elsewhere', )
d('tried elsewhere with consent', CONS)
d('tried in a District Court with consent', D, CONS)
w('Penal Code offence', 'Penal Code 1871', '379')
w('Road Traffic Act offence', 'Road Traffic Act 1961', '10')
o.assert_('`the criminal case disclosure procedures of Part 9 apply by section 159(1)` `Penal Code offence` `tried in a District Court`')
o.assert_('NOT `the criminal case disclosure procedures of Part 9 apply by section 159(1)` `Penal Code offence` `tried elsewhere`')
o.assert_('NOT `the criminal case disclosure procedures of Part 9 apply by section 159(1)` `Road Traffic Act offence` `tried in a District Court`')
o.assert_('NOT `the criminal case disclosure procedures of Part 9 apply by section 159(1)` `Penal Code offence` `tried elsewhere with consent`')
o.assert_('`the criminal case disclosure procedures of Part 9 apply` `Penal Code offence` `tried in a District Court`')
o.assert_('NOT `the criminal case disclosure procedures of Part 9 apply` `Penal Code offence` `tried elsewhere`')
o.assert_('NOT `the criminal case disclosure procedures of Part 9 apply` `Road Traffic Act offence` `tried in a District Court`')
o.assert_('`the criminal case disclosure procedures of Part 9 apply` `Penal Code offence` `tried elsewhere with consent`')
o.assert_('`the criminal case disclosure procedures of Part 9 apply` `Road Traffic Act offence` `tried in a District Court with consent`')
o.assert_('`the criminal case disclosure procedures of Part 9 apply` `Road Traffic Act offence` `tried elsewhere with consent`')
o.assert_('NOT `the criminal case disclosure procedures of Part 9 apply` `Road Traffic Act offence` `tried elsewhere`')
o.assert_('`the criminal case disclosure procedures of Part 9 apply` `Immigration Act s 5` `tried in a District Court`')
o.assert_('NOT `the criminal case disclosure procedures of Part 9 apply` `Immigration Act s 6` `tried in a District Court`')

o.section('211A. General Division of the High Court (Part 10 Division 5)')
MUST = 'the offence must be tried in the General Division of the High Court'
DES = 'the Public Prosecutor designates the General Division of the High Court to try the offence'
def h(var, *true): o.case(var, 'High Court Disclosure Facts', *true)
h('must be tried in the High Court', MUST)
h('designated for the High Court', DES)
h('neither', )
h('neither, with consent', CONS)
h('must be tried in the High Court, with consent', MUST, CONS)
h('designated for the High Court, with consent', DES, CONS)
o.assert_('`the criminal case disclosure procedures of Part 10 Division 5 apply by section 211A(1)` `Road Traffic Act offence` `must be tried in the High Court`')
o.assert_('`the criminal case disclosure procedures of Part 10 Division 5 apply by section 211A(1)` `Penal Code offence` `designated for the High Court`')
o.assert_('NOT `the criminal case disclosure procedures of Part 10 Division 5 apply by section 211A(1)` `Road Traffic Act offence` `designated for the High Court`')
o.assert_('NOT `the criminal case disclosure procedures of Part 10 Division 5 apply by section 211A(1)` `Penal Code offence` `neither`')
o.assert_('NOT `the criminal case disclosure procedures of Part 10 Division 5 apply by section 211A(1)` `Penal Code offence` `neither, with consent`')
o.assert_('`the criminal case disclosure procedures of Part 10 Division 5 apply` `Road Traffic Act offence` `must be tried in the High Court`')
o.assert_('`the criminal case disclosure procedures of Part 10 Division 5 apply` `Road Traffic Act offence` `designated for the High Court, with consent`')
o.assert_('`the criminal case disclosure procedures of Part 10 Division 5 apply` `Road Traffic Act offence` `must be tried in the High Court, with consent`')
o.assert_('NOT `the criminal case disclosure procedures of Part 10 Division 5 apply` `Road Traffic Act offence` `designated for the High Court`')
o.assert_('NOT `the criminal case disclosure procedures of Part 10 Division 5 apply` `Road Traffic Act offence` `neither`')
o.assert_('NOT `the criminal case disclosure procedures of Part 10 Division 5 apply` `Road Traffic Act offence` `neither, with consent`')
o.assert_('`the criminal case disclosure procedures of Part 10 Division 5 apply` `Penal Code offence` `designated for the High Court`')
o.assert_('NOT `the criminal case disclosure procedures of Part 10 Division 5 apply` `Immigration Act s 15` `designated for the High Court`')
o.write(os.path.join(ROW, 'cpc-tests-second-schedule.l4'))
print('cpc_tests_2 written')
