"""Tests for cpc-other-laws.l4: the Code's treatment of an offence under the Prevention of Corruption Act 1960 and under the Misuse of Drugs Act 1973.

The statements below are copies of what those two rows compute from their own sections (sg/prevention-of-corruption-act-1960, pca-procedure.l4, ss 32(1) and 34;
sg/misuse-of-drugs-act-1973, mda-enforcement.l4, ss 25(1) and 53); each of those rows asserts the same values in its own tests.  The expected treatments are read
off the First Schedule's last four rows (source/CPC2010.txt) and ss 2(1), 7 to 9, applied to the punishment each Act's own section prints.

Run: python generators/cpc_tests_3.py   (writes ../cpc-tests-other-laws.l4)"""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from fixtures import Types, Out

ROW = os.path.join(os.path.dirname(__file__), '..')
types = Types(os.path.join(ROW, 'cpc-types.l4'), os.path.join(ROW, 'written-law-interface.l4'))
def q(x): return '`%s`' % x

o = Out(types, """IMPORT prelude
IMPORT `written-law-interface`
IMPORT `cpc-types`
IMPORT `cpc-offence-procedure`
IMPORT `cpc-second-schedule`
IMPORT `cpc-other-laws`

-- Tests for cpc-other-laws.l4: an offence under the Prevention of Corruption Act 1960 and under the Misuse of Drugs Act 1973, read with what each Act says about its own
-- offences.  Expected values are read off the First Schedule's last four rows and ss 2(1), 7 to 9.  Generated by generators/cpc_tests_3.py.""")

ST = 'Written Law Procedure Statement'
PCA, MDA, NONE = 'the PCA statement', 'the MDA statement', 'a statement by an Act that says nothing'
DEEMS, EMPOWERS, DC, MC = 'deems the offence', 'empowers the police', 'District Court under that Act', "Magistrate's Court under that Act"
o.section('The statements the two Acts make, as their own rows compute them')
o.case(PCA, ST, DEEMS, DC, **{'the Act': 'Prevention of Corruption Act 1960'})
o.case(MDA, ST, EMPOWERS, DC, **{'the Act': 'Misuse of Drugs Act 1973'})
o.case(NONE, ST, **{'the Act': 'Road Traffic Act 1961'})
o.case('a statement that empowers the police but gives no court', ST, EMPOWERS, **{'the Act': 'Road Traffic Act 1961'})
o.case('a statement that gives a Magistrate\'s Court', ST, MC, **{'the Act': 'Road Traffic Act 1961'})

J = 'Jurisdiction Facts'
YRS = 'the maximum term of imprisonment'
def case(name, years, death=False, life=False, fine_only=False):
    true = [t for t, on in [('punishable with death', death), ('imprisonment for life', life), ('fine-only', fine_only)] if on]
    o.case(name, J, *true, **{YRS: years})

# --------------------------------------------------------------------------------------------------------------------- Prevention of Corruption Act
o.section('The Prevention of Corruption Act 1960: ss 32(1) and 34')
case('PCA s 5 or 6: at most 5 years', 5)
case('PCA s 7: at most 7 years', 7)
case('PCA s 26 or 28: at most 1 year', 1)
case('PCA s 32(2): at most 6 months', 0.5)
def treat(case_name, stmt, arrest, warrant, bail, mc, dc):
    for pred, want in [('the offence under the Act is an arrestable offence', arrest), ('a Magistrate\'s Court may try the offence under the Act', mc), ('a District Court may try the offence under the Act', dc)]:
        o.assert_('%s`%s` %s %s' % ('' if want else 'NOT ', pred, q(case_name), q(stmt)))
    for pred, want in [('a warrant ordinarily issues for the offence under another written law', warrant), ('the offence under another written law is bailable', bail)]:
        o.assert_('%s`%s` %s' % ('' if want else 'NOT ', pred, q(case_name)))
# name, statement, arrestable, warrant, bailable, MC, DC
treat('PCA s 5 or 6: at most 5 years', PCA, True, True, False, True, True)       # 3 to under 7 years: arrestable, warrant, not bailable; 7(1)(a): at most 5 years
treat('PCA s 7: at most 7 years', PCA, True, True, False, False, True)           # 7 years or upwards; more than 5 years, so not 7(1)(a); the Act does not show a Magistrate's Court
treat('PCA s 26 or 28: at most 1 year', PCA, True, False, True, True, True)      # under 3 years: only the Act's deeming makes it arrestable; summons; bailable
treat('PCA s 32(2): at most 6 months', PCA, True, False, True, True, True)
o.section('The same offences without the Act\'s statement: what the Code alone says')
treat('PCA s 26 or 28: at most 1 year', NONE, False, False, True, True, True)    # under 3 years and no power in the law offended against: not arrestable
treat('PCA s 5 or 6: at most 5 years', NONE, True, True, False, True, True)      # 3 to under 7 years: arrestable by the band
treat('PCA s 7: at most 7 years', NONE, True, True, False, False, True)


# --------------------------------------------------------------------------------------------------------------------- Misuse of Drugs Act
o.section('The Misuse of Drugs Act 1973: ss 25(1) and 53')
case('MDA s 30(1)(d): at most 12 months', 1)
case('MDA s 31B(2): at most 2 years', 2)
case('MDA s 9: at most 3 years', 3)
case('MDA s 8(b) by s 33(3A): at most 10 years', 10)
case('MDA s 5(1), Class A: at most 20 years', 20)
case('MDA s 6, Class A: life', 30, life=True)
case('MDA s 5(1), a capital quantity: death', 0, death=True)
treat('MDA s 30(1)(d): at most 12 months', MDA, True, False, True, True, True)    # under 3 years, but the Act empowers the police to arrest without warrant (s 25(1))
treat('MDA s 31B(2): at most 2 years', MDA, True, False, True, True, True)
treat('MDA s 9: at most 3 years', MDA, True, True, False, True, True)
treat('MDA s 8(b) by s 33(3A): at most 10 years', MDA, True, True, False, False, True)      # more than 5 years; 8(1): at most 10 years
treat('MDA s 5(1), Class A: at most 20 years', MDA, True, True, False, False, True)        # more than 10 years: only s 9(3)(b), the Act showing the District Court, brings it in
treat('MDA s 6, Class A: life', MDA, True, True, False, False, True)
treat('MDA s 5(1), a capital quantity: death', MDA, True, True, False, False, False)       # s 9(3): "other than an offence punishable with death"
o.section('The Misuse of Drugs Act 1973 without s 53: a District Court cannot try a 20-year offence on the Code alone')
treat('MDA s 5(1), Class A: at most 20 years', NONE, True, True, False, False, False)
treat('MDA s 30(1)(d): at most 12 months', NONE, False, False, True, True, True)
o.assert_('`the offence under the Act is an arrestable offence` `MDA s 30(1)(d): at most 12 months` `a statement that empowers the police but gives no court`')
o.assert_('NOT `a District Court may try the offence under the Act` `MDA s 5(1), Class A: at most 20 years` `a statement that empowers the police but gives no court`')
o.assert_('`a Magistrate\'s Court may try the offence under the Act` `MDA s 5(1), Class A: at most 20 years` `a statement that gives a Magistrate\'s Court`')

o.section('The procedural treatment as one record')
for case_name, st, exp in [('PCA s 26 or 28: at most 1 year', PCA, dict(arrest=True, warrant=False, bail=True, mc=True, dc=True, hc=True)),
                           ('MDA s 5(1), a capital quantity: death', MDA, dict(arrest=True, warrant=True, bail=False, mc=False, dc=False, hc=True))]:
    t = '(`the procedural treatment of an offence under the Act` %s %s)' % (q(case_name), q(st))
    for field, key in [('the police may ordinarily arrest without warrant', 'arrest'), ('a warrant ordinarily issues in the first instance', 'warrant'), ('the offence is bailable of right', 'bail'),
                       ("a Magistrate's Court may try the offence", 'mc'), ('a District Court may try the offence', 'dc'), ('the General Division of the High Court may try the offence', 'hc')]:
        o.assert_('%s%s\'s `%s`' % ('' if exp[key] else 'NOT ', t, field))

o.section('Completing the jurisdiction facts keeps what the case shows')
o.assert_('(`the jurisdiction facts completed from the Act\'s statement` `MDA s 5(1), a capital quantity: death` `the MDA statement`)\'s `the offence is punishable with death`')
o.assert_('NOT (`the jurisdiction facts completed from the Act\'s statement` `MDA s 9: at most 3 years` `the MDA statement`)\'s `the offence is punishable with death`')
o.assert_('(`the jurisdiction facts completed from the Act\'s statement` `MDA s 6, Class A: life` `the MDA statement`)\'s `the offence is punishable with imprisonment for life`')
o.assert_('(`the jurisdiction facts completed from the Act\'s statement` `MDA s 9: at most 3 years` `the MDA statement`)\'s `the maximum term of imprisonment provided by law, in years` EQUALS 3')
o.assert_('(`the jurisdiction facts completed from the Act\'s statement` `MDA s 9: at most 3 years` `the MDA statement`)\'s `a law other than the Penal Code 1871 shows the offence as triable by a District Court under that law`')
o.assert_('NOT (`the jurisdiction facts completed from the Act\'s statement` `MDA s 9: at most 3 years` `the MDA statement`)\'s `a law other than the Penal Code 1871 shows the offence as triable by a Magistrate\'s Court under that law`')
o.assert_('NOT (`the jurisdiction facts completed from the Act\'s statement` `MDA s 9: at most 3 years` `a statement by an Act that says nothing`)\'s `a law other than the Penal Code 1871 shows the offence as triable by a District Court under that law`')

o.section('The Second Schedule: items 12 (Misuse of Drugs Act 1973) and 16A (Prevention of Corruption Act 1960)')
for st, want in [(PCA, True), (MDA, True), (NONE, False)]:
    for sec in ['5', '6', '30']:
        o.assert_('%s`the Act\'s offence is under a law specified in the Second Schedule` %s "%s"' % ('' if want else 'NOT ', q(st), sec))
o.assert_('(`the written law offence facts for the Act\'s offence` `the PCA statement` "5")\'s `the Act under which the offence is created` EQUALS "Prevention of Corruption Act 1960"')
o.assert_('(`the written law offence facts for the Act\'s offence` `the MDA statement` "5")\'s `the Act under which the offence is created` EQUALS "Misuse of Drugs Act 1973"')
o.assert_('(at (`the Second Schedule items for the Act` "Prevention of Corruption Act 1960") 0)\'s `item number` EQUALS "16A"')
o.assert_('(at (`the Second Schedule items for the Act` "Misuse of Drugs Act 1973") 0)\'s `item number` EQUALS "12"')
D = 'State Court Disclosure Facts'
H = 'High Court Disclosure Facts'
o.case('tried in a District Court', D, 'is to be tried in a District Court')
o.case('tried in a Magistrate\'s Court', D)
o.case('must be tried in the High Court', H, 'must be tried in the General Division')
o.case('designated for the High Court', H, 'designates the General Division')
for st in [PCA, MDA]:
    w = '(`the written law offence facts for the Act\'s offence` %s "5")' % q(st)
    o.assert_('`the criminal case disclosure procedures of Part 9 apply` %s `tried in a District Court`' % w)
    o.assert_('NOT `the criminal case disclosure procedures of Part 9 apply` %s `tried in a Magistrate\'s Court`' % w)
    o.assert_('`the criminal case disclosure procedures of Part 10 Division 5 apply` %s `designated for the High Court`' % w)
    o.assert_('`the criminal case disclosure procedures of Part 10 Division 5 apply` %s `must be tried in the High Court`' % w)
w = '(`the written law offence facts for the Act\'s offence` `a statement by an Act that says nothing` "5")'
o.assert_('NOT `the criminal case disclosure procedures of Part 9 apply` %s `tried in a District Court`' % w)
o.assert_('NOT `the criminal case disclosure procedures of Part 10 Division 5 apply` %s `designated for the High Court`' % w)
o.assert_('`the criminal case disclosure procedures of Part 10 Division 5 apply` %s `must be tried in the High Court`' % w)
o.write(os.path.join(ROW, 'cpc-tests-other-laws.l4'))
print('cpc_tests_3 written')
