"""Tests for cpc-offence-procedure.l4 (the First Schedule and ss 2(1), 7 to 9).  Expected values are read off the printed Schedule
(source/CPC2010.pdf, and the layout text where it is unambiguous) and off the Code's text, never off the encoding."""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from fixtures import Types, Out

ROW = os.path.join(os.path.dirname(__file__), '..')
types = Types(os.path.join(ROW, 'cpc-types.l4'), os.path.join(ROW, 'ea-cpc-interface.l4'))
def q(x): return '`%s`' % x

o = Out(types, """IMPORT prelude
IMPORT `ea-cpc-interface`
IMPORT `cpc-types`
IMPORT `cpc-first-schedule`
IMPORT `cpc-offence-procedure`

-- Tests for cpc-offence-procedure.l4 (Criminal Procedure Code 2010, the First Schedule and ss 2(1), 7 to 9).
-- Expected values are read off the printed First Schedule and the Code's text.  Generated by generators/cpc_tests_1.py.""")

def row(sec, i=0):
    return '(at (`the First Schedule rows for the Penal Code section` "%s") %d)' % (sec, i)

o.section('The First Schedule as a lookup')
o.assert_('`the First Schedule has a row for the Penal Code section` "379"')
o.assert_('NOT `the First Schedule has a row for the Penal Code section` "1000"')
o.assert_('count (`the First Schedule rows for the Penal Code section` "193") EQUALS 2')
o.assert_('count (`the First Schedule rows for the Penal Code section` "222") EQUALS 3')
o.assert_('count (`the First Schedule rows for the Penal Code section` "130B") EQUALS 2')
o.assert_('count (`the rows of the First Schedule`) EQUALS 482')

o.section('Standard rows, read off the printed columns')
# 379 Theft: May arrest without warrant | Warrant | Not bailable | Imprisonment for 3 years, or fine, or both | Magistrate's Court or District Court
o.assert_('`the row says the police may ordinarily arrest without warrant` %s' % row('379'))
o.assert_('`the row says a warrant ordinarily issues` %s' % row('379'))
o.assert_('NOT `the row says the offence is bailable of right` %s' % row('379'))
o.assert_("`the row shows the offence as triable by a Magistrate's Court` %s" % row('379'))
o.assert_('`the row shows the offence as triable by a District Court` %s' % row('379'))
# 506 Criminal intimidation: May arrest | Warrant | Not bailable | MC or DC
o.assert_('`the row says the police may ordinarily arrest without warrant` %s' % row('506', 0))
o.assert_('NOT `the row says the offence is bailable of right` %s' % row('506', 0))
# 500 Defamation: May not arrest | Summons | Bailable | MC or DC
o.assert_('NOT `the row says the police may ordinarily arrest without warrant` %s' % row('500'))
o.assert_('NOT `the row says a warrant ordinarily issues` %s' % row('500'))
o.assert_('`the row says the offence is bailable of right` %s' % row('500'))
o.assert_("`the row shows the offence as triable by a Magistrate's Court` %s" % row('500'))
# 489H Delivering to another altered currency: May arrest | Warrant | Not bailable | Imprisonment for 10 years, and fine | District Court
o.assert_("NOT `the row shows the offence as triable by a Magistrate's Court` %s" % row('489H'))
o.assert_('`the row shows the offence as triable by a District Court` %s' % row('489H'))
# 193: two rows, judicial proceeding (7 years, DC) and any other case (3 years, MC or DC)
o.assert_("NOT `the row shows the offence as triable by a Magistrate's Court` %s" % row('193', 0))
o.assert_("`the row shows the offence as triable by a Magistrate's Court` %s" % row('193', 1))
o.assert_('(at (`the First Schedule rows for the Penal Code section` "193") 0)\'s `maximum punishment` EQUALS "Imprisonment for 7 years, and fine"')
o.assert_('(at (`the First Schedule rows for the Penal Code section` "193") 1)\'s `maximum punishment` EQUALS "Imprisonment for 3 years, and fine"')
# 512(1) attempt: a blank seventh column means the General Division of the High Court alone
o.assert_('%s\'s `court rule` EQUALS `General Division of the High Court only`' % row('512(1)'.rstrip('()1')) if False else '(at (`the First Schedule rows for the Penal Code section` "512") 0)\'s `court rule` EQUALS `General Division of the High Court only`')
o.assert_('NOT `the row shows the offence as triable by a District Court` (at (`the First Schedule rows for the Penal Code section` "512") 0)')
o.assert_('NOT `the row shows the offence as triable by a Magistrate\'s Court` (at (`the First Schedule rows for the Penal Code section` "512") 0)')
# the printed section is kept with its subsection
o.assert_('(at (`the First Schedule rows for the Penal Code section` "375") 0)\'s `printed section` EQUALS "375(2)"')
o.assert_('(at (`the First Schedule rows for the Penal Code section` "512") 0)\'s `printed section` EQUALS "512(1)"')
o.assert_('(at (`the First Schedule rows for the Penal Code section` "512") 1)\'s `printed section` EQUALS "512(2)"')

o.section('Derived rows answer only with the underlying offence')
o.refused('`the row says the police may ordinarily arrest without warrant` %s' % row('109'))
o.refused('`the row says a warrant ordinarily issues` %s' % row('109'))
o.refused('`the row says the offence is bailable of right` %s' % row('109'))
o.refused("`the row shows the offence as triable by a Magistrate's Court` %s" % row('109'))
# 73: enhanced penalties: arrest and process are fixed, bail and punishment follow the offence
o.assert_('`the row says the police may ordinarily arrest without warrant` %s' % row('73'))
o.assert_('`the row says a warrant ordinarily issues` %s' % row('73'))
o.refused('`the row says the offence is bailable of right` %s' % row('73'))
o.assert_("`the row shows the offence as triable by a Magistrate's Court` %s" % row('73'))
# 150: the process follows the offence committed by the person hired
o.assert_('`the row says the police may ordinarily arrest without warrant` %s' % row('150'))
o.refused('`the row says a warrant ordinarily issues` %s' % row('150'))
# 196: arrest, process and bail are fixed; the court follows the false-evidence offence
o.assert_('`the row says a warrant ordinarily issues` %s' % row('196'))
o.assert_('NOT `the row says the offence is bailable of right` %s' % row('196'))
o.refused("`the row shows the offence as triable by a Magistrate's Court` %s" % row('196'))
# the treatment of a derived row given the underlying offence: abetment (s 109) of theft (s 379) and of defamation (s 500)
o.raw("`treatment of theft` MEANS `the procedural treatment of a row` %s" % row('379'))
o.raw("`treatment of defamation` MEANS `the procedural treatment of a row` %s" % row('500'))
o.assert_("(`the procedural treatment of a derived row` %s `treatment of theft`)'s `the police may ordinarily arrest without warrant`" % row('109'))
o.assert_("(`the procedural treatment of a derived row` %s `treatment of theft`)'s `a warrant ordinarily issues in the first instance`" % row('109'))
o.assert_("NOT (`the procedural treatment of a derived row` %s `treatment of theft`)'s `the offence is bailable of right`" % row('109'))
o.assert_("(`the procedural treatment of a derived row` %s `treatment of theft`)'s `a Magistrate's Court may try the offence`" % row('109'))
o.assert_("NOT (`the procedural treatment of a derived row` %s `treatment of defamation`)'s `the police may ordinarily arrest without warrant`" % row('109'))
o.assert_("NOT (`the procedural treatment of a derived row` %s `treatment of defamation`)'s `a warrant ordinarily issues in the first instance`" % row('109'))
o.assert_("(`the procedural treatment of a derived row` %s `treatment of defamation`)'s `the offence is bailable of right`" % row('109'))
# s 73 enhanced penalties over defamation: the bail answer follows defamation (bailable), the arrest answer is the row's own (may arrest)
o.assert_("(`the procedural treatment of a derived row` %s `treatment of defamation`)'s `the police may ordinarily arrest without warrant`" % row('73'))
o.assert_("(`the procedural treatment of a derived row` %s `treatment of defamation`)'s `the offence is bailable of right`" % row('73'))
o.assert_("(`the procedural treatment of a derived row` %s `treatment of theft`)'s `the General Division of the High Court may try the offence`" % row('73'))
# the treatment of a standard row
o.assert_("(`the procedural treatment of a row` %s)'s `the police may ordinarily arrest without warrant`" % row('379'))
o.assert_("(`the procedural treatment of a row` %s)'s `the General Division of the High Court may try the offence`" % row('379'))
o.refused("(`the procedural treatment of a row` %s)'s `the police may ordinarily arrest without warrant`" % row('109'))

o.section('Offences against laws other than the Penal Code 1871: the printed bands')
def jf(var, *true, **vals):
    o.case(var, 'Jurisdiction Facts', *true, **vals)
M = 'the maximum term of imprisonment provided by law, in years'
jf('other law: death', 'punishable with death')
jf('other law: life imprisonment', 'punishable with imprisonment for life')
jf('other law: 7 years', **{M: 7})
jf('other law: 6 years', **{M: 6})
jf('other law: 3 years', **{M: 3})
jf('other law: 2 years', **{M: 2})
jf('other law: fine only', 'fine-only offence')
for v in ['other law: death', 'other law: life imprisonment', 'other law: 7 years']:
    o.assert_("`the offence is punishable with death or imprisonment of 7 years or upwards` %s" % q(v))
    o.assert_("`the offence under another written law is an arrestable offence` %s FALSE" % q(v))
    o.assert_("`a warrant ordinarily issues for the offence under another written law` %s" % q(v))
    o.assert_("NOT `the offence under another written law is bailable` %s" % q(v))
for v in ['other law: 6 years', 'other law: 3 years']:
    o.assert_("`the offence is punishable with imprisonment of 3 years or upwards but less than 7` %s" % q(v))
    o.assert_("`the offence under another written law is an arrestable offence` %s FALSE" % q(v))
    o.assert_("`a warrant ordinarily issues for the offence under another written law` %s" % q(v))
    o.assert_("NOT `the offence under another written law is bailable` %s" % q(v))
for v in ['other law: 2 years', 'other law: fine only']:
    o.assert_("`the offence is punishable with imprisonment of less than 3 years or with fine only` %s" % q(v))
    o.assert_("NOT `the offence under another written law is an arrestable offence` %s FALSE" % q(v))
    o.assert_("`the offence under another written law is an arrestable offence` %s TRUE" % q(v))
    o.assert_("NOT `a warrant ordinarily issues for the offence under another written law` %s" % q(v))
    o.assert_("`the offence under another written law is bailable` %s" % q(v))
o.assert_("NOT `the offence is punishable with imprisonment of 3 years or upwards but less than 7` `other law: 7 years`")
o.assert_("NOT `the offence is punishable with imprisonment of less than 3 years or with fine only` `other law: 3 years`")
o.assert_("NOT `the offence is punishable with imprisonment of less than 3 years or with fine only` `other law: life imprisonment`")
o.assert_("`the offence under another written law is an arrestable offence` `other law: death` FALSE")
# the printed bands themselves (the four last rows of the table)
o.assert_("count (filter (GIVEN r YIELD r's `printed section` EQUALS \"Other written law\") `the rows of the First Schedule`) EQUALS 4")
o.assert_("(at (filter (GIVEN r YIELD r's `printed section` EQUALS \"Other written law\") `the rows of the First Schedule`) 0)'s `bail rule` EQUALS `Not bailable`")
o.assert_("(at (filter (GIVEN r YIELD r's `printed section` EQUALS \"Other written law\") `the rows of the First Schedule`) 1)'s `arrest rule` EQUALS `May arrest without warrant`")
o.assert_("(at (filter (GIVEN r YIELD r's `printed section` EQUALS \"Other written law\") `the rows of the First Schedule`) 2)'s `arrest rule` EQUALS `May not arrest without warrant unless specifically empowered by the law offended against`")
o.assert_("(at (filter (GIVEN r YIELD r's `printed section` EQUALS \"Other written law\") `the rows of the First Schedule`) 3)'s `bail rule` EQUALS `Bailable`")
o.assert_("(at (filter (GIVEN r YIELD r's `printed section` EQUALS \"Other written law\") `the rows of the First Schedule`) 3)'s `court rule` EQUALS `According to sections 7, 8 and 9`")

o.section('7 to 9. Which court tries the offence')
jf('j 5 years', **{M: 5})
jf('j 6 years', **{M: 6})
jf('j 10 years', **{M: 10})
jf('j 11 years', **{M: 11})
jf('j fine only', 'fine-only offence')
jf('j death', 'punishable with death')
jf('j life', 'punishable with imprisonment for life')
jf('j 6 years authorised by the PP', 'Public Prosecutor has authorised in writing', **{M: 6})
jf('j 11 years authorised by the PP', 'Public Prosecutor has authorised in writing', **{M: 11})
jf('j 4 years authorised by the PP', 'Public Prosecutor has authorised in writing', **{M: 4})
jf('j 8 years, Penal Code, shown MC in column 7', 'the offence is under the Penal Code 1871', "First Schedule shows the offence as triable by a Magistrate's Court", **{M: 8})
jf('j 8 years, other law, shown MC under that law', "a law other than the Penal Code 1871 shows the offence as triable by a Magistrate's Court", **{M: 8})
jf('j 8 years, Penal Code, shown MC but the offence is under another law', "First Schedule shows the offence as triable by a Magistrate's Court", **{M: 8})
jf('j 15 years, Penal Code, shown DC in column 7', 'the offence is under the Penal Code 1871', 'First Schedule shows the offence as triable by a District Court', **{M: 15})
jf('j 15 years, other law, shown DC under that law', 'a law other than the Penal Code 1871 shows the offence as triable by a District Court', **{M: 15})
jf('j 15 years, PP applies and the accused consents', 'Public Prosecutor applies to the District Court', 'accused consents, or if more than one', **{M: 15})
jf('j 15 years, PP applies, accused does not consent', 'Public Prosecutor applies to the District Court', **{M: 15})
jf('j 15 years, accused consents, PP does not apply', 'accused consents, or if more than one', **{M: 15})
jf('j death, PP applies and the accused consents', 'punishable with death', 'Public Prosecutor applies to the District Court', 'accused consents, or if more than one')
jf('j death, shown DC in column 7', 'punishable with death', 'the offence is under the Penal Code 1871', 'First Schedule shows the offence as triable by a District Court')
for v, mc in [('j 5 years', True), ('j 6 years', False), ('j 10 years', False), ('j 11 years', False), ('j fine only', True), ('j death', False), ('j life', False)]:
    o.assert_("%s`a Magistrate's Court has jurisdiction under section 7(1)(a)` %s" % ('' if mc else 'NOT ', q(v)))
for v, dc in [('j 5 years', True), ('j 6 years', True), ('j 10 years', True), ('j 11 years', False), ('j fine only', True), ('j death', False), ('j life', False)]:
    o.assert_("%s`a District Court has jurisdiction under section 8(1)` %s" % ('' if dc else 'NOT ', q(v)))
o.assert_("`a Magistrate's Court may try the offence under section 9(1)` `j 6 years authorised by the PP`")
o.assert_("NOT `a Magistrate's Court may try the offence under section 9(1)` `j 11 years authorised by the PP`")
o.assert_("NOT `a Magistrate's Court may try the offence under section 9(1)` `j 4 years authorised by the PP`")
o.assert_("NOT `a Magistrate's Court may try the offence under section 9(1)` `j 6 years`")
o.assert_("`a Magistrate's Court may try the offence under section 9(2)` `j 8 years, Penal Code, shown MC in column 7`")
o.assert_("`a Magistrate's Court may try the offence under section 9(2)` `j 8 years, other law, shown MC under that law`")
o.assert_("NOT `a Magistrate's Court may try the offence under section 9(2)` `j 8 years, Penal Code, shown MC but the offence is under another law`")
o.assert_("`a Magistrate's Court may try the offence` `j 5 years`")
o.assert_("`a Magistrate's Court may try the offence` `j 6 years authorised by the PP`")
o.assert_("`a Magistrate's Court may try the offence` `j 8 years, Penal Code, shown MC in column 7`")
o.assert_("NOT `a Magistrate's Court may try the offence` `j 6 years`")
o.assert_("`a District Court may try the offence under section 9(3)` `j 15 years, Penal Code, shown DC in column 7`")
o.assert_("`a District Court may try the offence under section 9(3)` `j 15 years, other law, shown DC under that law`")
o.assert_("`a District Court may try the offence under section 9(3)` `j 15 years, PP applies and the accused consents`")
o.assert_("NOT `a District Court may try the offence under section 9(3)` `j 15 years, PP applies, accused does not consent`")
o.assert_("NOT `a District Court may try the offence under section 9(3)` `j 15 years, accused consents, PP does not apply`")
o.assert_("NOT `a District Court may try the offence under section 9(3)` `j death, PP applies and the accused consents`")
o.assert_("NOT `a District Court may try the offence under section 9(3)` `j death, shown DC in column 7`")
o.assert_("`a District Court may try the offence` `j 10 years`")
o.assert_("`a District Court may try the offence` `j 15 years, PP applies and the accused consents`")
o.assert_("NOT `a District Court may try the offence` `j 11 years`")
o.assert_("NOT `a District Court may try the offence` `j death`")
o.assert_("NOT (`the trial courts for the offence` `j 6 years`)'s `a Magistrate's Court may try the offence`")
o.assert_("(`the trial courts for the offence` `j 6 years`)'s `a District Court may try the offence`")
o.assert_("(`the trial courts for the offence` `j death`)'s `the General Division of the High Court may try the offence`")
o.refused("(`the trial courts for the offence` `j 6 years`)'s `the police may ordinarily arrest without warrant`")

o.write(os.path.join(ROW, 'cpc-tests-offence-procedure.l4'))
print('cpc_tests_1 written')
