---
config:
  railroad:
    nonTerminalFill: "#ffffff"
    nonTerminalStroke: "#222222"
    nonTerminalTextColor: "#111111"
    terminalFill: "transparent"
    terminalStroke: "transparent"
    terminalTextColor: "#888888"
    lineColor: "#8a8a8a"
    markerFill: "#222222"
    strokeWidth: 1.5
    fontSize: 15
---
railroad-beta
extortion_is_robbery = sequence(terminal("(3)"), nonterminal("commits extortion OF (f's extortion)"), terminal("is “robbery” if the offender, at the time of committing the extortion, is"), nonterminal("f's in the presence of the person put in fear"), terminal(", and commits the extortion by putting that person in fear of"), choice(nonterminal("f's instant death"), nonterminal("f's instant hurt"), nonterminal("f's instant wrongful restraint")), choice(nonterminal("f's to that person"), nonterminal("f's to some other person")), terminal(", and, by so putting in fear, induces the person so put in fear"), nonterminal("f's then and there"), terminal("to deliver up the thing extorted"));
