---
config:
  railroad:
    nonTerminalFill: "#ffffff"
    nonTerminalStroke: "#222222"
    nonTerminalTextColor: "#111111"
    terminalFill: "transparent"
    terminalStroke: "transparent"
    terminalTextColor: "#888888"
    lineColor: "#8a8a8a"
    markerFill: "#222222"
    strokeWidth: 1.5
    fontSize: 15
---
railroad-beta
whoever_commits_robbery_shall_be_so_punished = sequence(sequence(terminal("392. Whoever"), nonterminal("commits robbery OF f")), terminal("IMPLIES"), nonterminal("liable under s 392 OF f"));
