#!/usr/bin/env python3
"""Generate nii-schedule-j-tables.l4 from the two tables of Schedule J in the deposited source.

Every figure in the generated module is read from a cell of the source table; nothing is typed by
hand. A cell "–" becomes NOTHING. A cell "X {{ח:הערה|(הוראת שעה בשנים 2024 עד 2027: Y)}}" gives the
printed figure X, and Y for the separate row or totals row the generator emits for 2024-2027.
Any cell of another shape stops the generator, so a change in the source cannot slip through.

The rows are laid out with positional OF construction under one ruler comment per table, the
column widths computed here (writing-l4-rules SKILL.md, "Statutory tables: generate the layout,
do not type it"). No ditto is used: every row is written out whole.

Usage: python3 -I schedule_j.py SOURCE.wiki.txt OUT.l4
"""
import re
import sys

SRC_PATH, OUT = sys.argv[1], sys.argv[2]
SRC = open(SRC_PATH, encoding="utf-8").read().split("\n")

TABLES = [
    # (key, title, label line, first heading line, first item line, totals line, col D note)
    ("temporary", "the temporary version, for 2025-2026", 4714, 4716, 4720, 4730, True),
    ("permanent", "the permanent version", 4732, 4734, 4738, 4748, False),
]

BRANCH = {
    "אימהות": "`maternity`",
    "אימהות – מבוטח שאינו עובד ואינו עובד עצמאי": "`maternity`",
    "ילדים": "`children`",
    "נפגעי עבודה": "`work injury`",
    "נפגעי תאונות": "`accident injury`",
    "אבטלה": "`unemployment`",
    "זכויות עובדים בהליכי חדלות פירעון": "`employees' rights in insolvency proceedings`",
    "נכות": "`disability`",
    "סיעוד": "`long-term care`",
    "אזרחים ותיקים ושאירים": "`senior citizens and survivors`",
}

NOTE = re.compile(r"^([0-9]+\.[0-9]+) \{\{ח:הערה\|\(הוראת שעה בשנים 2024 עד 2027: ([0-9]+\.[0-9]+)\)\}\}$")
NUM = re.compile(r"^[0-9]+\.[0-9]+$")

RULER = ("item, branch,"
         " C above: employee, self-employed, neither;"
         " C not above: employee, self-employed, neither;"
         " D upper, D not above; E")


def cells(n):
    line = SRC[n - 1]
    return re.findall(r"<t[dh][^>]*>(.*?)</t[dh]>", line)


def parse_cell(c, line_no):
    """-> (printed, in_2024_2027) as L4 text, e.g. ('JUST 1.96', 'JUST 2.06')."""
    c = c.strip()
    if c == "–":
        return "NOTHING", "NOTHING"
    if NUM.match(c):
        return f"JUST {c}", f"JUST {c}"
    m = NOTE.match(c)
    if m:
        return f"JUST {m.group(1)}", f"JUST {m.group(2)}"
    sys.exit(f"schedule_j.py: unexpected cell at source line {line_no}: {c!r}")


def parse_total(c, line_no):
    c = c.strip()
    if NUM.match(c):
        return c, c
    m = NOTE.match(c)
    if m:
        return m.group(1), m.group(2)
    sys.exit(f"schedule_j.py: unexpected totals cell at source line {line_no}: {c!r}")


def layout(rows):
    """rows: list of list of str. Pad each column to its widest entry, comma-separated."""
    last = len(rows[0]) - 1
    widths = [max(len(r[i]) for r in rows) + (1 if i < last else 0) for i in range(len(rows[0]))]
    out = []
    for r in rows:
        parts = [(r[i] + ("," if i < last else "")).ljust(widths[i]) for i in range(len(r))]
        out.append(" ".join(parts).rstrip())
    return out


def name(key, what):
    return f"`Schedule J ({key} version), {what}`"


out = []
w = out.append
w("@lang en")
w("IMPORT prelude")
w("IMPORT `nii-il04-nouns`")
w("")
w("-- National Insurance Law, Schedule J (לוח י׳): THE TWO TABLES, AS DATA.")
w("--")
w("-- GENERATED by tools/schedule_j.py from the deposited source; do not edit by hand. Edit the")
w("-- generator and run it again (python3 -I tools/schedule_j.py SOURCE nii-schedule-j-tables.l4),")
w("-- then tools/srcquote.py over the result. Each row's `src:` line is the source row it was read")
w("-- from; a reviewer checks a row by reading the two lines one above the other.")
w("--")
w("-- Figures are percentages as printed (1.40 means 1.40%). A cell printed \"–\" is NOTHING.")
w("-- Item 4 and the totals row carry the editors' note \"(הוראת שעה בשנים 2024 עד 2027: …)\" in some")
w("-- cells; for each such row the generator emits the row as printed AND the row as read in")
w("-- 2024-2027, with the noted figure in place of the printed one. Which rows apply in which year")
w("-- is decided in nii-schedule-j.l4, not here.")
w("")
w("§ `Schedule J — the two tables, as printed`")
w("--@SRC 4709-4711")
w("")
for key, title, label, head, first, total, _ in TABLES:
    w(f"§§ `Schedule J, {title}`")
    w(f"--@SRC {label - 1}-{label}")
    w(f"--@SRC {head}-{head + 3}")
    w("")
    printed_rows, read_rows, names = [], [], []
    for n in range(first, first + 10):
        cs = cells(n)
        if len(cs) != 11:
            sys.exit(f"schedule_j.py: source line {n} has {len(cs)} cells, expected 11")
        item = cs[0].strip().rstrip(".")
        branch = BRANCH.get(cs[1].strip())
        if branch is None:
            sys.exit(f"schedule_j.py: unknown branch at source line {n}: {cs[1]!r}")
        pr, rd = zip(*(parse_cell(c, n) for c in cs[2:]))
        printed_rows.append((n, item, [item, branch] + list(pr)))
        if pr != rd:
            read_rows.append((n, item, [item, branch] + list(rd)))
    body = layout([r for _, _, r in printed_rows] + [r for _, _, r in read_rows])
    k = 0
    w(f"--          {RULER}")
    for n, item, _ in printed_rows:
        nm = name(key, f"item {item}")
        names.append(nm)
        w(f"@ref National Insurance Law, Schedule J ({title}), item {item} (source line {n})")
        w(f"--@SRC {n}")
        w(f"{nm} MEANS `A row of Schedule J` OF {body[k]}")
        k += 1
        w("")
    w(f"-- The same items with the figure the editors note for 2024-2027 in place of the printed one.")
    noted = {}
    for n, item, _ in read_rows:
        nm = name(key, f"item {item}, with the figures noted for 2024-2027")
        noted[item] = nm
        w(f"@ref National Insurance Law, Schedule J ({title}), item {item}, editorial note \"(הוראת שעה בשנים 2024 עד 2027: …)\" (source line {n})")
        w(f"--@SRC {n}")
        w(f"{nm} MEANS `A row of Schedule J` OF {body[k]}")
        k += 1
        w("")
    w(f"@ref National Insurance Law, Schedule J ({title}), items 1-10 (source lines {first}-{first + 9})")
    w("GIVETH A LIST OF `A row of Schedule J`")
    w(f"{name(key, 'items as printed')} MEANS")
    w("    LIST " + ("\n       , ".join(names)))
    w("")
    w(f"@ref National Insurance Law, Schedule J ({title}), items 1-10, with the editorial notes for 2024-2027 (source lines {first}-{first + 9})")
    w("GIVETH A LIST OF `A row of Schedule J`")
    w(f"{name(key, 'items as read in 2024-2027')} MEANS")
    sel = [noted.get(nm.split("item ")[1].rstrip("`"), nm) for nm in names]
    w("    LIST " + ("\n       , ".join(sel)))
    w("")
    tc = cells(total)
    if len(tc) != 11 or tc[1].strip() != "סך הכל":
        sys.exit(f"schedule_j.py: source line {total} is not the totals row")
    tp, tr = zip(*(parse_total(c, total) for c in tc[2:]))
    tl = layout([list(tp), list(tr)])
    w(f"--          C above: employee, self-employed, neither; C not above: employee, self-employed, neither; D upper, D not above; E")
    w(f"@ref National Insurance Law, Schedule J ({title}), totals row (source line {total})")
    w(f"--@SRC {total}")
    w(f"{name(key, 'totals as printed')}           MEANS `The totals row of Schedule J` OF {tl[0]}")
    w(f"@ref National Insurance Law, Schedule J ({title}), totals row, editorial notes for 2024-2027 (source line {total})")
    w(f"{name(key, 'totals as read in 2024-2027')} MEANS `The totals row of Schedule J` OF {tl[1]}")
    w("")

open(OUT, "w", encoding="utf-8").write("\n".join(out) + "\n")
print(f"schedule_j.py: wrote {OUT}")
