"""Tests for ea-relevancy.l4 and ea-statements.l4.  Expected values are read off the Act's text and
its illustrations (source/EA1893.txt), never off the encoding."""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from fixtures import Types, Out

ROW = os.path.join(os.path.dirname(__file__), '..')
types = Types(os.path.join(ROW, 'ea-types.l4'), os.path.join(ROW, 'ea-cpc-interface.l4'))

def q(x): return '`%s`' % x

# ---------------------------------------------------------------- relevancy
o = Out(types, """IMPORT prelude
IMPORT `ea-cpc-interface`
IMPORT `ea-types`
IMPORT `ea-relevancy`

-- Tests for ea-relevancy.l4 (Evidence Act 1893, ss 2, 3(3) to (5), 5 to 16, 106, 138).
-- Every expected value is read off the Act's text or one of its illustrations; the illustration is
-- named beside the case.  Generated by generators/ea_tests_1.py from ea-types.l4.""")

o.section('2. Application')
o.case('a trial in court', 'Application Facts', 'judicial proceeding in or before a court')
o.case('an affidavit presented to a court', 'Application Facts', 'judicial proceeding in or before a court', 'affidavit presented to a court or officer')
o.case('an arbitration', 'Application Facts', 'judicial proceeding in or before a court', 'before an arbitrator')
o.assert_("`Parts 1, 2 and 3 apply` `a trial in court`")
o.assert_("NOT `Parts 1, 2 and 3 apply` `an affidavit presented to a court`")
o.assert_("NOT `Parts 1, 2 and 3 apply` `an arbitration`")

o.section('3(3) to (5). Proved, disproved, not proved')
o.case('court believes the fact exists', 'Finding Facts', 'believes the fact to exist')
o.case('court finds existence so probable', 'Finding Facts', 'considers its existence so probable')
o.case('court believes the fact does not exist', 'Finding Facts', 'believes the fact does not exist')
o.case('court finds non-existence so probable', 'Finding Facts', 'non-existence so probable')
o.case('court neither believes nor finds probable', 'Finding Facts')
o.case('contradictory findings', 'Finding Facts', 'believes the fact to exist', 'believes the fact does not exist')
o.assert_("`the finding on the fact` `court believes the fact exists` EQUALS `proved`")
o.assert_("`the finding on the fact` `court finds existence so probable` EQUALS `proved`")
o.assert_("`the finding on the fact` `court believes the fact does not exist` EQUALS `disproved`")
o.assert_("`the finding on the fact` `court finds non-existence so probable` EQUALS `disproved`")
o.assert_("`the finding on the fact` `court neither believes nor finds probable` EQUALS `not proved`")
o.refused("`the finding on the fact` `contradictory findings`")

o.section('5 to 16. Routes to relevancy, one case each (the illustrations)')
# section 6, illustration (a)
o.case('s6 ill a the beating', 'Relevancy Facts', 'forms part of the same transaction')
o.assert_("`the fact is relevant under section 6` `s6 ill a the beating`")
o.assert_("`evidence may be given of the fact under section 5` `s6 ill a the beating`")
# section 7, illustration (a): shortly before the robbery B went to a fair with money
o.case('s7 ill a the fair', 'Relevancy Facts', 'occasion, cause or effect')
o.assert_("`the fact is relevant under section 7` `s7 ill a the fair`")
# section 7, illustration (b): marks on the ground from a struggle
o.case('s7 ill b the marks on the ground', 'Relevancy Facts', 'constitutes the state of things')
o.assert_("`the fact is relevant under section 7` `s7 ill b the marks on the ground`")
# section 7: opportunity (illustration (c): habits of B known to A which afforded an opportunity)
o.case('s7 ill c the opportunity', 'Relevancy Facts', 'afforded an opportunity')
o.assert_("`the fact is relevant under section 7` `s7 ill c the opportunity`")
# section 8(1), illustration (b) motive and (c) preparation
o.case('s8 ill b the motive', 'Relevancy Facts', 'shows or constitutes a motive')
o.case('s8 ill c the preparation', 'Relevancy Facts', 'shows or constitutes a preparation')
o.assert_("`the fact is relevant under section 8(1)` `s8 ill b the motive`")
o.assert_("`the fact is relevant under section 8(1)` `s8 ill c the preparation`")
# section 8(2), illustration (i): A absconded after the crime
o.case('s8 ill i the absconding', 'Relevancy Facts', 'conduct of a party or of an agent', 'influences or is influenced')
o.assert_("`the fact is relevant as conduct under section 8(2)` `s8 ill i the absconding`")
# section 8(2), illustration (j): prompt complaint is conduct of the person an offence against whom is the subject; the bare statement is not conduct
o.case('s8 ill j the prompt complaint', 'Relevancy Facts', 'conduct of a person an offence against whom', 'influences or is influenced')
o.case('s8 ill j the bare statement', 'Relevancy Facts', 'conduct of a person an offence against whom', 'influences or is influenced', 'the fact is a statement')
o.assert_("`the fact is relevant as conduct under section 8(2)` `s8 ill j the prompt complaint`")
o.assert_("NOT `the fact is relevant as conduct under section 8(2)` `s8 ill j the bare statement`")
# Explanation 1: a statement that accompanies and explains an act other than a statement is conduct
o.case('s8 expl 1 statement accompanying an act', 'Relevancy Facts', 'conduct of a party or of an agent', 'influences or is influenced', 'the fact is a statement', 'accompanies and explains an act')
o.assert_("`the fact is relevant as conduct under section 8(2)` `s8 expl 1 statement accompanying an act`")
# Explanation 2 / illustration (f): "The police are coming..." said in A's presence
o.case('s8 ill f the police are coming', 'Relevancy Facts', 'statement made to a person, or in the person')
o.assert_("`the statement is relevant under section 8(2) Explanation 2` `s8 ill f the police are coming`")
# section 9, illustration (c): sudden and urgent business is relevant; its details are not, except insofar as necessary
o.case('s9 ill c sudden urgent business', 'Relevancy Facts', 'necessary to explain or introduce', 'necessary for that purpose')
o.case('s9 ill c details of the business', 'Relevancy Facts', 'necessary to explain or introduce')
o.assert_("`the fact is relevant under section 9` `s9 ill c sudden urgent business`")
o.assert_("NOT `the fact is relevant under section 9` `s9 ill c details of the business`")
# section 9, the other limbs
o.case('s9 identity', 'Relevancy Facts', 'establishes the identity', 'necessary for that purpose')
o.case('s9 time or place', 'Relevancy Facts', 'fixes the time or place', 'necessary for that purpose')
o.case('s9 relation of parties', 'Relevancy Facts', 'shows the relation of the parties', 'necessary for that purpose')
o.case('s9 rebuts an inference', 'Relevancy Facts', 'supports or rebuts an inference', 'necessary for that purpose')
for v in ['s9 identity', 's9 time or place', 's9 relation of parties', 's9 rebuts an inference']:
    o.assert_("`the fact is relevant under section 9` %s" % q(v))
# section 10: the conspiracy illustration, and the case before the intention was first entertained
o.case('s10 the conspirators', 'Relevancy Facts', 'reasonable ground to believe that 2 or more persons', 'something said, done or written', 'in reference to their common intention', 'came after the time')
o.case('s10 before the intention was entertained', 'Relevancy Facts', 'reasonable ground to believe that 2 or more persons', 'something said, done or written', 'in reference to their common intention')
o.case('s10 no reasonable ground', 'Relevancy Facts', 'something said, done or written', 'in reference to their common intention', 'came after the time')
o.assert_("`the fact is relevant under section 10` `s10 the conspirators`")
o.assert_("NOT `the fact is relevant under section 10` `s10 before the intention was entertained`")
o.assert_("NOT `the fact is relevant under section 10` `s10 no reasonable ground`")
# section 11, illustration (a): that A was at Penang that day
o.case('s11 ill a at Penang', 'Relevancy Facts', 'inconsistent with a fact in issue')
o.case('s11 ill b highly improbable', 'Relevancy Facts', 'highly probable or improbable')
o.assert_("`the fact is relevant under section 11` `s11 ill a at Penang`")
o.assert_("`the fact is relevant under section 11` `s11 ill b highly improbable`")
# section 12
o.case('s12 damages', 'Relevancy Facts', 'damages are claimed', 'determine the amount of damages')
o.case('s12 no claim for damages', 'Relevancy Facts', 'determine the amount of damages')
o.assert_("`the fact is relevant under section 12` `s12 damages`")
o.assert_("NOT `the fact is relevant under section 12` `s12 no claim for damages`")
# section 13, illustration: the fishery
o.case('s13 the fishery deed', 'Relevancy Facts', 'question is as to the existence of a right or custom', 'transaction by which the right or custom')
o.case('s13 instance of exercise', 'Relevancy Facts', 'question is as to the existence of a right or custom', 'particular instance in which the right')
o.case('s13 no question of right', 'Relevancy Facts', 'transaction by which the right or custom')
o.assert_("`the fact is relevant under section 13` `s13 the fishery deed`")
o.assert_("`the fact is relevant under section 13` `s13 instance of exercise`")
o.assert_("NOT `the fact is relevant under section 13` `s13 no question of right`")
# section 14, illustration (p): a statement of intention to commit that crime is relevant; of a general disposition is not
o.case('s14 ill p intention to commit that crime', 'Relevancy Facts', 'shows the existence of a state of mind', 'state of mind, body or bodily feeling is in issue or relevant', 'in reference to the particular matter')
o.case('s14 ill p general disposition', 'Relevancy Facts', 'shows the existence of a state of mind', 'state of mind, body or bodily feeling is in issue or relevant')
o.assert_("`the fact is relevant under section 14` `s14 ill p intention to commit that crime`")
o.assert_("NOT `the fact is relevant under section 14` `s14 ill p general disposition`")
# section 14 Explanation 2, illustration (b): the previous conviction for delivering a counterfeit coin
o.case('s14 expl 2 previous conviction', 'Relevancy Facts', 'previous conviction of the accused', 'previous commission by the accused')
o.case('s14 expl 2 conviction without relevant commission', 'Relevancy Facts', 'previous conviction of the accused')
o.assert_("`the previous conviction is relevant under section 14 Explanation 2` `s14 expl 2 previous conviction`")
o.assert_("NOT `the previous conviction is relevant under section 14 Explanation 2` `s14 expl 2 conviction without relevant commission`")
# section 15, illustration (a): the series of fires
o.case('s15 ill a series of fires', 'Relevancy Facts', 'question whether an act was accidental', 'series of similar occurrences')
o.assert_("`the fact is relevant under section 15` `s15 ill a series of fires`")
# section 16, illustration (a): the course of business for letters
o.case('s16 ill a letters to the post', 'Relevancy Facts', 'question whether a particular act was done', 'course of business according to which')
o.assert_("`the fact is relevant under section 16` `s16 ill a letters to the post`")

o.section('3(2) and 5. A fact in issue; a fact relevant under another provision; no other fact')
o.case('s5 ill a fact in issue', 'Relevancy Facts', 'the fact is a fact in issue')
o.case('s5 relevant by another provision', 'Relevancy Facts', 'declared relevant by another provision')
o.case('s5 an irrelevant fact', 'Relevancy Facts')
o.case('s5 expl disentitled', 'Relevancy Facts', 'the fact is a fact in issue', 'disentitled by a provision of the law relating to civil procedure')
o.assert_("`evidence may be given of the fact under section 5` `s5 ill a fact in issue`")
o.assert_("`evidence may be given of the fact under section 5` `s5 relevant by another provision`")
o.assert_("NOT `evidence may be given of the fact under section 5` `s5 an irrelevant fact`")
o.assert_("NOT `evidence may be given of the fact under section 5` `s5 expl disentitled`")

o.section('106 and 138(2). Proof of a fact that must come first')
# 138 illustration (a): the death must be proved before the statement is given
o.case('s138 ill a death not yet proved', 'Relevancy Facts', 'declared relevant by another provision', 'admissible only upon proof of some other fact')
o.case('s138 ill a death proved', 'Relevancy Facts', 'declared relevant by another provision', 'admissible only upon proof of some other fact', 'has been proved, or the party has undertaken')
o.case('s138 no preliminary fact needed', 'Relevancy Facts', 'declared relevant by another provision')
o.assert_("NOT `the court admits the evidence of the fact` `s138 ill a death not yet proved`")
o.assert_("`the court admits the evidence of the fact` `s138 ill a death proved`")
o.assert_("`the court admits the evidence of the fact` `s138 no preliminary fact needed`")
o.write(os.path.join(ROW, 'ea-tests-relevancy.l4'))

# ---------------------------------------------------------------- statements
o = Out(types, """IMPORT prelude
IMPORT `ea-cpc-interface`
IMPORT `ea-types`
IMPORT `ea-statements`

-- Tests for ea-statements.l4 (Evidence Act 1893, ss 17 to 23, 31, 32, 32A, 32B, 32C, 33).
-- Expected values are read off the Act's text and illustrations.  Generated by generators/ea_tests_1.py.""")

o.raw("""`criminal proceedings with the Code's notice conditions met` MEANS `Code Conclusions` WITH
    `the notice requirements and other conditions prescribed under section 428 of the Criminal Procedure Code 2010 are complied with` IS TRUE
    `evidence of the fact is admissible by virtue of section 265 or 266 of the Criminal Procedure Code 2010` IS FALSE
`criminal proceedings without the Code's notice conditions met` MEANS `Code Conclusions` WITH
    `the notice requirements and other conditions prescribed under section 428 of the Criminal Procedure Code 2010 are complied with` IS FALSE
    `evidence of the fact is admissible by virtue of section 265 or 266 of the Criminal Procedure Code 2010` IS FALSE
""")

o.section('17 to 20. Admissions and confessions')
o.case('party statement suggesting an inference', 'Admission Facts', 'oral or documentary', 'suggests an inference', 'maker is a party to the proceeding')
o.case('statement by an authorised agent', 'Admission Facts', 'oral or documentary', 'suggests an inference', 'maker is an agent of a party')
o.case('statement by a stranger', 'Admission Facts', 'oral or documentary', 'suggests an inference')
o.case('representative who no longer holds the character', 'Admission Facts', 'oral or documentary', 'suggests an inference', 'maker is a party to the proceeding', 'party suing or sued in a representative character')
o.case('representative who held the character', 'Admission Facts', 'oral or documentary', 'suggests an inference', 'maker is a party to the proceeding', 'party suing or sued in a representative character', 'held that representative character')
o.case('interested person during the interest', 'Admission Facts', 'oral or documentary', 'suggests an inference', 'proprietary or pecuniary interest', 'during the continuance of the maker')
o.case('interested person after the interest', 'Admission Facts', 'oral or documentary', 'suggests an inference', 'proprietary or pecuniary interest')
o.case('predecessor in interest during the interest', 'Admission Facts', 'oral or documentary', 'suggests an inference', 'from whom a party to the suit derived', 'during the continuance of the maker')
# section 19 illustration: C's statement that C owed B rent is an admission against A, who undertook to collect rents
o.case('s19 ill C owed B rent', 'Admission Facts', 'oral or documentary', 'suggests an inference', 'position or liability must be proved', 'would be relevant as against the maker', 'occupied the position or was subject')
# section 20 illustration: "Go and ask C, C knows all about it"
o.case('s20 ill C the person referred to', 'Admission Facts', 'oral or documentary', 'suggests an inference', 'expressly referred for information')
o.case('no inference suggested', 'Admission Facts', 'oral or documentary', 'maker is a party to the proceeding')
o.assert_("`the statement is an admission` `party statement suggesting an inference`")
o.assert_("`the statement is an admission` `statement by an authorised agent`")
o.assert_("NOT `the statement is an admission` `statement by a stranger`")
o.assert_("NOT `the statement is an admission` `representative who no longer holds the character`")
o.assert_("`the statement is an admission` `representative who held the character`")
o.assert_("`the statement is an admission` `interested person during the interest`")
o.assert_("NOT `the statement is an admission` `interested person after the interest`")
o.assert_("`the statement is an admission` `predecessor in interest during the interest`")
o.assert_("`the statement is an admission` `s19 ill C owed B rent`")
o.assert_("`the statement is an admission` `s20 ill C the person referred to`")
o.assert_("NOT `the statement is an admission` `no inference suggested`")
# 17(2) confession
o.case('accused stating the inference', 'Admission Facts', 'oral or documentary', 'suggests an inference', 'maker is a party to the proceeding', 'maker is a person accused of an offence', 'states or suggests the inference that the maker committed')
o.case('accused admitting only a collateral fact', 'Admission Facts', 'oral or documentary', 'suggests an inference', 'maker is a party to the proceeding', 'maker is a person accused of an offence')
o.case('non-accused stating the inference', 'Admission Facts', 'oral or documentary', 'suggests an inference', 'maker is a party to the proceeding', 'states or suggests the inference that the maker committed')
o.assert_("`the statement is a confession` `accused stating the inference`")
o.assert_("NOT `the statement is a confession` `accused admitting only a collateral fact`")
o.assert_("`the statement is an admission` `accused admitting only a collateral fact`")
o.assert_("NOT `the statement is a confession` `non-accused stating the inference`")

o.section('21. Proof of admissions against and by the maker')
o.case('s21 ill a statement by B proved against B', 'Admission Facts', 'sought to be proved against the maker')
o.case('s21 ill a statement by A proved by A', 'Admission Facts', 'sought to be proved by or on behalf of the maker')
o.case('s21 ill b the captain proves his own book', 'Admission Facts', 'sought to be proved by or on behalf of the maker', 'if the maker were dead, it would be relevant between third persons under section 32')
o.case('s21(b) state of mind with conduct', 'Admission Facts', 'sought to be proved by or on behalf of the maker', 'state of mind or body, relevant or in issue')
o.case('s21 ill d relevant otherwise than as an admission', 'Admission Facts', 'sought to be proved by or on behalf of the maker', 'relevant otherwise than as an admission')
o.assert_("`section 21 permits the admission to be proved` `s21 ill a statement by B proved against B`")
o.assert_("NOT `section 21 permits the admission to be proved` `s21 ill a statement by A proved by A`")
o.assert_("`section 21 permits the admission to be proved` `s21 ill b the captain proves his own book`")
o.assert_("`section 21 permits the admission to be proved` `s21(b) state of mind with conduct`")
o.assert_("`section 21 permits the admission to be proved` `s21 ill d relevant otherwise than as an admission`")

o.section('22 and 23. Oral admissions as to documents; admissions in civil cases')
o.case('s22 oral admission without entitlement', 'Admission Facts', 'oral admission as to the contents of a document')
o.case('s22 oral admission with entitlement', 'Admission Facts', 'oral admission as to the contents of a document', 'entitled to give secondary evidence')
o.case('s22 genuineness in question', 'Admission Facts', 'oral admission as to the contents of a document', 'genuineness of a document produced')
o.case('s22 not an admission about a document', 'Admission Facts')
o.assert_("NOT `section 22 permits the admission to be proved` `s22 oral admission without entitlement`")
o.assert_("`section 22 permits the admission to be proved` `s22 oral admission with entitlement`")
o.assert_("`section 22 permits the admission to be proved` `s22 genuineness in question`")
o.assert_("`section 22 permits the admission to be proved` `s22 not an admission about a document`")
o.case('s23 civil with an express condition', 'Admission Facts', 'civil proceedings', 'express condition that evidence of it is not to be given')
o.case('s23 civil with an inferred agreement', 'Admission Facts', 'civil proceedings', 'can infer that the parties agreed')
o.case('s23 criminal with an express condition', 'Admission Facts', 'express condition that evidence of it is not to be given')
o.case('s23 civil, advocate compellable under section 128', 'Admission Facts', 'civil proceedings', 'express condition that evidence of it is not to be given', 'an advocate or solicitor may be compelled to give evidence of under section 128')
o.case('s23 civil, legal counsel compellable under section 128A', 'Admission Facts', 'civil proceedings', 'express condition that evidence of it is not to be given', 'a legal counsel in an entity may be compelled to give evidence of under section 128A')
o.assert_("`section 23 excludes the admission` `s23 civil with an express condition`")
o.assert_("`section 23 excludes the admission` `s23 civil with an inferred agreement`")
o.assert_("NOT `section 23 excludes the admission` `s23 criminal with an express condition`")
o.assert_("NOT `section 23 excludes the admission` `s23 civil, advocate compellable under section 128`")
o.assert_("NOT `section 23 excludes the admission` `s23 civil, legal counsel compellable under section 128A`")
# the whole route: a party's statement is relevant and may be proved against the party
o.case('whole route a party statement proved against the party', 'Admission Facts', 'oral or documentary', 'suggests an inference', 'maker is a party to the proceeding', 'sought to be proved against the maker')
o.assert_("`the admission is relevant and may be proved` `whole route a party statement proved against the party`")
o.assert_("NOT `the admission is relevant and may be proved` `s21 ill a statement by A proved by A`")

o.section('32(1). Statements by persons who need not be called, one case for each paragraph')
base = ['the statement was made by a person, whether orally, in a document or otherwise', 'the statement is of a relevant fact']
def hs(var, *true, **vals):
    o.case(var, 'Hearsay Facts', *(base + list(true)), **vals)
KP = 'the kind of proceedings'
hs('s32(1)(a) ill a the dying statement', 'statement is made by a person as to the cause of that person', 'cause of that person\'s death comes into question', **{KP: 'criminal proceedings'})
hs('s32(1)(a) cause of death not in question', 'statement is made by a person as to the cause of that person', **{KP: 'criminal proceedings'})
hs('s32(1)(b) ill b the surgeon\'s diary', 'was made by a person in the ordinary course of a trade', **{KP: 'criminal proceedings'})
hs('s32(1)(b) compiled record', 'record compiled by a person acting in the ordinary course', **{KP: 'criminal proceedings'})
hs('s32(1)(c) against pecuniary interest', 'against the pecuniary or proprietary interest', **{KP: 'criminal proceedings'})
hs('s32(1)(c) exposing to prosecution', 'would expose or would have exposed the maker', **{KP: 'criminal proceedings'})
o.case('s32(1)(d) all three conditions', 'Hearsay Facts', *(base + ['gives the opinion of the maker', 'likely to be aware', 'before any controversy', 'notice requirements and other conditions prescribed in the Rules of Court']), **{KP: 'civil proceedings'})
o.case('s32(1)(d) made after the controversy arose', 'Hearsay Facts', *(base + ['gives the opinion of the maker', 'likely to be aware', 'notice requirements and other conditions prescribed in the Rules of Court']), **{KP: 'civil proceedings'})
hs('s32(1)(e) relationship before the dispute', 'relates to the existence of a relationship by blood, marriage or adoption between persons as to whose', 'made before the question in dispute was raised', **{KP: 'criminal proceedings'})
hs('s32(1)(e) relationship after the dispute arose', 'relates to the existence of a relationship by blood, marriage or adoption between persons as to whose', **{KP: 'criminal proceedings'})
hs('s32(1)(f) pedigree', 'between deceased persons', 'made before the question in dispute was raised', **{KP: 'criminal proceedings'})
hs('s32(1)(g) deed', 'contained in a deed or other document relating to a transaction', **{KP: 'criminal proceedings'})
hs('s32(1)(h) crowd remarks', 'made by a number of persons', **{KP: 'criminal proceedings'})
hs('s32(1)(i) refuses to be sworn', 'the maker is compellable to give evidence', 'attends or is brought before the court', 'refuses to be sworn or affirmed', **{KP: 'criminal proceedings'})
hs('s32(1)(i) sworn but gives no evidence', 'the maker is compellable to give evidence', 'attends or is brought before the court', 'sworn or affirmed but refuses', **{KP: 'criminal proceedings'})
hs('s32(1)(i) not compellable', 'attends or is brought before the court', 'refuses to be sworn or affirmed', **{KP: 'criminal proceedings'})
hs('s32(1)(j)(i) dead', 'the maker is dead', **{KP: 'criminal proceedings'})
hs('s32(1)(j)(i) unfit', 'unfit because of a bodily or mental condition', **{KP: 'criminal proceedings'})
hs('s32(1)(j)(ii) cannot be found', 'cannot be found', **{KP: 'criminal proceedings'})
hs('s32(1)(j)(iii) outside Singapore', 'outside Singapore and it is not practicable', **{KP: 'criminal proceedings'})
hs('s32(1)(j)(iv) competent not compellable', 'competent but not compellable', **{KP: 'criminal proceedings'})
hs('s32 no paragraph applies', **{KP: 'criminal proceedings'})
for v in ['s32(1)(a) ill a the dying statement','s32(1)(b) ill b the surgeon\'s diary','s32(1)(b) compiled record','s32(1)(c) against pecuniary interest','s32(1)(c) exposing to prosecution','s32(1)(e) relationship before the dispute','s32(1)(f) pedigree','s32(1)(g) deed','s32(1)(h) crowd remarks','s32(1)(i) refuses to be sworn','s32(1)(i) sworn but gives no evidence','s32(1)(j)(i) dead','s32(1)(j)(i) unfit','s32(1)(j)(ii) cannot be found','s32(1)(j)(iii) outside Singapore','s32(1)(j)(iv) competent not compellable']:
    o.assert_("`the statement is relevant under section 32(1)` %s `criminal proceedings with the Code's notice conditions met`" % q(v))
o.assert_("`the statement is relevant under section 32(1)` `s32(1)(d) all three conditions` `criminal proceedings with the Code's notice conditions met`")
o.assert_("NOT `the statement is relevant under section 32(1)` `s32(1)(d) made after the controversy arose` `criminal proceedings with the Code's notice conditions met`")
o.assert_("NOT `the statement is relevant under section 32(1)` `s32(1)(a) cause of death not in question` `criminal proceedings with the Code's notice conditions met`")
o.assert_("NOT `the statement is relevant under section 32(1)` `s32(1)(e) relationship after the dispute arose` `criminal proceedings with the Code's notice conditions met`")
o.assert_("NOT `the statement is relevant under section 32(1)` `s32(1)(i) not compellable` `criminal proceedings with the Code's notice conditions met`")
o.assert_("NOT `the statement is relevant under section 32(1)` `s32 no paragraph applies` `criminal proceedings with the Code's notice conditions met`")
o.assert_("`the statement falls within section 32(1)(a)` `s32(1)(a) ill a the dying statement`")
o.assert_("`the statement falls within section 32(1)(b)` `s32(1)(b) compiled record`")

o.section('32(4). Notice requirements')
o.assert_("NOT `the statement is relevant under section 32(1)` `s32(1)(j)(i) dead` `criminal proceedings without the Code's notice conditions met`")
o.assert_("NOT `the notice requirements of section 32(4) are complied with` `s32(1)(j)(i) dead` `criminal proceedings without the Code's notice conditions met`")
o.assert_("`the notice requirements of section 32(4) are complied with` `s32(1)(d) all three conditions` `criminal proceedings without the Code's notice conditions met`")
o.assert_("`the statement is relevant under section 32(1)` `s32(1)(d) all three conditions` `criminal proceedings without the Code's notice conditions met`")
o.case('s32(4)(b) civil with the Rules of Court notice', 'Hearsay Facts', *(base + ['the maker is dead', 'notice requirements and other conditions prescribed in the Rules of Court']), **{KP: 'civil proceedings'})
o.case('s32(4)(b) civil without the Rules of Court notice', 'Hearsay Facts', *(base + ['the maker is dead']), **{KP: 'civil proceedings'})
o.assert_("`the statement is relevant under section 32(1)` `s32(4)(b) civil with the Rules of Court notice` `criminal proceedings without the Code's notice conditions met`")
o.assert_("NOT `the statement is relevant under section 32(1)` `s32(4)(b) civil without the Rules of Court notice` `criminal proceedings with the Code's notice conditions met`")

o.section('32(1)(k), (6) and (7). Agreement')
ag = 'the parties to the proceedings agree that for the purpose'
o.case('s32(1)(k) agreement in a civil case', 'Hearsay Facts', *(base + [ag]), **{KP: 'civil proceedings'})
o.case('s32(6) prosecution statement, accused unrepresented', 'Hearsay Facts', *(base + [ag, 'given in evidence on the prosecution']), **{KP: 'criminal proceedings'})
o.case('s32(6) prosecution statement, accused represented', 'Hearsay Facts', *(base + [ag, 'given in evidence on the prosecution', 'accused or a co-accused was represented by an advocate']), **{KP: 'criminal proceedings'})
o.case('s32(6) defence statement, accused unrepresented', 'Hearsay Facts', *(base + [ag]), **{KP: 'criminal proceedings'})
o.case('s32(7) old committal agreement in High Court proceedings', 'Hearsay Facts', *(base + [ag, 'accused or a co-accused was represented by an advocate', 'examining Magistrate conducting a committal hearing', 'before the General Division of the High Court']), **{KP: 'criminal proceedings'})
o.case('s32(7) old committal agreement, proceedings elsewhere', 'Hearsay Facts', *(base + [ag, 'accused or a co-accused was represented by an advocate', 'examining Magistrate conducting a committal hearing']), **{KP: 'criminal proceedings'})
o.assert_("`the statement falls within section 32(1)(k)` `s32(1)(k) agreement in a civil case`")
o.assert_("NOT `the statement falls within section 32(1)(k)` `s32(6) prosecution statement, accused unrepresented`")
o.assert_("`the statement falls within section 32(1)(k)` `s32(6) prosecution statement, accused represented`")
o.assert_("`the statement falls within section 32(1)(k)` `s32(6) defence statement, accused unrepresented`")
o.assert_("NOT `the statement falls within section 32(1)(k)` `s32(7) old committal agreement in High Court proceedings`")
o.assert_("`the statement falls within section 32(1)(k)` `s32(7) old committal agreement, proceedings elsewhere`")
# (k) is outside the notice requirement of 32(4)
o.assert_("`the statement is relevant under section 32(1)` `s32(1)(k) agreement in a civil case` `criminal proceedings without the Code's notice conditions met`")

o.section('32(3), 32A and 32(2). Interests of justice; utterances; written records')
o.case('s32(3) not in the interests of justice', 'Hearsay Facts', *(base + ['the maker is dead', 'not be in the interests of justice']), **{KP: 'criminal proceedings'})
o.assert_("NOT `the statement is relevant under section 32(1)` `s32(3) not in the interests of justice` `criminal proceedings with the Code's notice conditions met`")
o.case('s32A a protest implying the fact', 'Hearsay Facts', 'the statement was made by a person, whether orally, in a document or otherwise', 'protest, greeting or other verbal utterance', 'the maker is dead', **{KP: 'criminal proceedings'})
o.assert_("`the statement is relevant under section 32(1)` `s32A a protest implying the fact` `criminal proceedings with the Code's notice conditions met`")
o.case('s32(2) oral statement put into writing', 'Hearsay Facts', 'put by another person, at the maker', **{KP: 'criminal proceedings'})
o.assert_("`the written record is treated as the maker's statement for section 32(1)(a), (c) to (j)` `s32(2) oral statement put into writing`")
o.assert_("NOT `the written record is treated as the maker's statement for section 32(1)(a), (c) to (j)` `s32 no paragraph applies`")

o.section('32B. Opinions; 32C. Credibility of an absent maker')
o.case('s32B opinion that could be given orally', 'Opinion Statement Facts', 'statement of opinion', 'admissible in those proceedings if made through direct oral evidence')
o.case('s32B opinion that could not be given orally', 'Opinion Statement Facts', 'statement of opinion')
o.assert_("`the statement of opinion is relevant under section 32(1)` `s32B opinion that could be given orally` `s32(1)(j)(i) dead` `criminal proceedings with the Code's notice conditions met`")
o.assert_("NOT `the statement of opinion is relevant under section 32(1)` `s32B opinion that could not be given orally` `s32(1)(j)(i) dead` `criminal proceedings with the Code's notice conditions met`")
o.case('s32B(3) lay witness conveying what was perceived', 'Opinion Statement Facts', 'statement of opinion', 'called as a witness', 'not qualified to give expert evidence', 'conveying relevant facts personally perceived')
o.case('s32B(3) opinion not conveying perceived facts', 'Opinion Statement Facts', 'statement of opinion', 'called as a witness', 'not qualified to give expert evidence')
o.assert_("`the lay opinion is admissible as evidence of what the witness perceived` `s32B(3) lay witness conveying what was perceived`")
o.assert_("NOT `the lay opinion is admissible as evidence of what the witness perceived` `s32B(3) opinion not conveying perceived facts`")
o.case('s32C absent maker, evidence admissible had the maker been called', 'Credibility of Absent Maker Facts', 'given in evidence by virtue of section 32(1)', 'not called as a witness', 'would have been admissible to undermine or support')
o.case('s32C maker called as a witness', 'Credibility of Absent Maker Facts', 'given in evidence by virtue of section 32(1)', 'would have been admissible to undermine or support')
o.case('s32C(1)(b) with permission', 'Credibility of Absent Maker Facts', 'given in evidence by virtue of section 32(1)', 'not called as a witness', 'could have been put to the maker in cross-examination', 'court gives permission')
o.case('s32C(1)(b) without permission', 'Credibility of Absent Maker Facts', 'given in evidence by virtue of section 32(1)', 'not called as a witness', 'could have been put to the maker in cross-examination')
o.case('s32C(2) inconsistent statement', 'Credibility of Absent Maker Facts', 'given in evidence by virtue of section 32(1)', 'not called as a witness', 'another statement inconsistent with it')
o.assert_("`evidence going to the credibility of the absent maker is admissible under section 32C(1)(a)` `s32C absent maker, evidence admissible had the maker been called`")
o.assert_("NOT `evidence going to the credibility of the absent maker is admissible under section 32C(1)(a)` `s32C maker called as a witness`")
o.assert_("`evidence going to the credibility of the absent maker is admissible under section 32C(1)(b)` `s32C(1)(b) with permission`")
o.assert_("NOT `evidence going to the credibility of the absent maker is admissible under section 32C(1)(b)` `s32C(1)(b) without permission`")
o.assert_("`evidence of an inconsistent statement by the absent maker is admissible under section 32C(2)` `s32C(2) inconsistent statement`")

o.section('33. Evidence given in an earlier proceeding')
fb = ['evidence was given by a witness in a judicial proceeding', 'the adverse party in the first proceeding had the right and opportunity to cross-examine', 'questions in issue were substantially the same']
o.case('s33 witness dead, same parties', 'Former Testimony Facts', *(fb + ['the witness is dead', 'between the same parties or their representatives']))
o.case('s33 witness dead, same prosecutor and accused (Explanation)', 'Former Testimony Facts', *(fb + ['the witness is dead', 'criminal trial or inquiry and the later proceeding']))
o.case('s33 witness kept out of the way', 'Former Testimony Facts', *(fb + ['kept out of the way by the adverse party', 'between the same parties or their representatives']))
o.case('s33 witness cannot be found', 'Former Testimony Facts', *(fb + ['cannot be found', 'between the same parties or their representatives']))
o.case('s33 unreasonable delay or expense', 'Former Testimony Facts', *(fb + ['unreasonable in the circumstances', 'between the same parties or their representatives']))
o.case('s33 no opportunity to cross-examine', 'Former Testimony Facts', 'evidence was given by a witness in a judicial proceeding', 'the witness is dead', 'between the same parties or their representatives', 'questions in issue were substantially the same')
o.case('s33 different parties', 'Former Testimony Facts', *(fb + ['the witness is dead']))
o.case('s33 witness available', 'Former Testimony Facts', *(fb + ['between the same parties or their representatives']))
for v in ['s33 witness dead, same parties', 's33 witness dead, same prosecutor and accused (Explanation)', 's33 witness kept out of the way', 's33 witness cannot be found', 's33 unreasonable delay or expense']:
    o.assert_("`the earlier evidence is relevant under section 33` %s" % q(v))
for v in ['s33 no opportunity to cross-examine', 's33 different parties', 's33 witness available']:
    o.assert_("NOT `the earlier evidence is relevant under section 33` %s" % q(v))
o.write(os.path.join(ROW, 'ea-tests-statements.l4'))
print('ea_tests_1 written')
