#!/usr/bin/env python3
"""Generate homecare-tests-figures.l4 from the raw source text.

  python3 -I tools/gen_figure_tests.py ../../source/raw/liberty-homecare.txt > homecare-tests-figures.l4

Every expected value in the generated module is PARSED from a line of the raw text, never typed:
the script finds each figure with a pattern anchored in the source words, converts Vietnamese
number format (`40.000.000` is forty million; `,` would be a decimal point), and writes an
#ASSERT whose right-hand side is that parsed number, under a `-- src:N | ...` quotation of the
line it came from (quoted with the same normalisation as tools/vnsrc.py). If a pattern does not
match its line exactly once, the script stops: the source moved and the test must be re-read.

The short-period scale (src:957-962) is read row by row, and each printed row becomes the
assertion that the encoded row has the same bound and share, plus two boundary cases.
"""
import re
import sys
import unicodedata


def nfc(s):
    return unicodedata.normalize("NFC", s)


def quote(raw, n):
    return "-- src:%d | %s" % (n, re.sub(r"\s+", " ", nfc(raw[n - 1])).strip())


def vn_number(tok):
    """`40.000.000` -> 40000000; `5` -> 5; `12,5` -> 12.5 (Vietnamese decimal comma)."""
    tok = tok.strip()
    if "," in tok:
        whole, frac = tok.split(",", 1)
        return float(whole.replace(".", "") + "." + frac)
    return int(tok.replace(".", ""))


def find(raw, n, pattern):
    line = nfc(raw[n - 1])
    ms = re.findall(pattern, line)
    if len(ms) != 1:
        sys.exit("gen_figure_tests: pattern %r matched %d times on src:%d: %r" % (pattern, len(ms), n, line))
    return ms[0]


def lit(x):
    """An L4 numeric literal with `_` thousands separators, from an int."""
    s = str(x)
    out = []
    while len(s) > 3:
        out.insert(0, s[-3:])
        s = s[:-3]
    out.insert(0, s)
    return "_".join(out)


def main():
    raw = open(sys.argv[1], encoding="utf-8").read().split("\n")
    o = []
    w = o.append
    w("@lang en")
    w("IMPORT prelude")
    w("IMPORT daydate")
    w("IMPORT `homecare-nouns`")
    w("IMPORT `homecare-definitions`")
    w("IMPORT `homecare-general-conditions`")
    w("IMPORT `homecare-part1`")
    w("IMPORT `homecare-part2`")
    w("IMPORT `homecare-part3`")
    w("IMPORT `homecare-perils`")
    w("IMPORT `homecare-test-fixtures`")
    w("")
    w("-- GENERATED by tools/gen_figure_tests.py from ../../source/raw/liberty-homecare.txt. Do not edit;")
    w("-- regenerate. Each expected value is parsed from the quoted line above it (Vietnamese number")
    w("-- format: the dot groups thousands). The rules under test are written by hand elsewhere; this")
    w("-- module checks that every figure the document prints is the figure the rules use.")
    w("")
    w("§ `Tests: the figures the document prints`")
    w("")

    # --- Part 1, Extension 2: 40.000.000 dong or 5% of the sum insured
    n = 349
    thr = vn_number(find(raw, n, r"vượt quá ([\d.]+)\s*$"))
    pct = vn_number(find(raw, n + 1, r"hoặc (\d+)% của số tiền bảo hiểm"))
    w("§§ `Part 1, Extension 2`")
    w(quote(raw, n)); w(quote(raw, n + 1))
    w("#ASSERT `Extension 2: the fixed threshold, in dong` EQUALS %s" % lit(thr))
    w("#ASSERT `Extension 2: the share of the sum insured` EQUALS %d%%" % pct)
    # the boundary where the two limbs cross: SI at which pct% equals the fixed threshold
    si = thr * 100 // pct
    w("-- At a sum insured of %s the two limbs are equal; a claim of exactly that is inside." % lit(si))
    w("#ASSERT `Extension 2: no inventory of undamaged property is needed for a claim of` %s `on an item insured for` %s" % (lit(thr), lit(si)))
    w("#ASSERT NOT `Extension 2: no inventory of undamaged property is needed for a claim of` %s `on an item insured for` %s" % (lit(thr + 1), lit(si)))
    w("")

    # --- Part 1, Extensions 3-6: the 10% caps, against the 2026 Summary's HYPOTHETICAL sums insured
    home_si, total_si = 2_000_000_000, 2_500_000_000
    p3 = vn_number(find(raw, 367, r"vượt quá (\d+)% tổng số tiền bảo hiểm cho Ngôi Nhà"))
    p4 = vn_number(find(raw, 374, r"vượt quá (\d+)% số tiền được"))
    p5 = vn_number(find(raw, 385, r"không vượt quá (\d+)%\s*$"))
    p6 = vn_number(find(raw, 391, r"không vượt quá (\d+)% số"))
    w("§§ `Part 1, Extensions 3-6: each cap is the printed share of a sum insured`")
    w("-- The fixture Summary insures the Home for 2,000,000,000 and Part 1 for 2,500,000,000 in all")
    w("-- (HYPOTHETICAL figures); each claim below is far above its cap, so the cap is what is paid.")
    w(quote(raw, 366)); w(quote(raw, 367))
    w("#ASSERT `Extension 3: architects' and engineers' fees payable under` `the 2026 Summary` `on` (`The costs claimed under the Part 1 Extensions` WITH `the claim for this loss` IS 0, `architects', surveyors' and engineers' fees incurred` IS 9_000_000_000, `the fees allowed by the scales of the professional bodies` IS 9_000_000_000, `fire fighting costs incurred` IS 0, `costs of removing debris` IS 0, `costs of dismantling or demolishing` IS 0, `costs of shoring or propping up` IS 0, `costs of temporary protection` IS 0) EQUALS %s" % lit(home_si * p3 // 100))
    w(quote(raw, 374)); w(quote(raw, 375))
    w("#ASSERT `Extension 4: fire fighting costs payable under` `the 2026 Summary` `on` (`The costs claimed under the Part 1 Extensions` WITH `the claim for this loss` IS 0, `architects', surveyors' and engineers' fees incurred` IS 0, `the fees allowed by the scales of the professional bodies` IS 0, `fire fighting costs incurred` IS 9_000_000_000, `costs of removing debris` IS 0, `costs of dismantling or demolishing` IS 0, `costs of shoring or propping up` IS 0, `costs of temporary protection` IS 0) EQUALS %s" % lit(total_si * p4 // 100))
    w(quote(raw, 385)); w(quote(raw, 386))
    w("#ASSERT `Extension 5: debris removal payable under` `the 2026 Summary` `for` `the Home` `on` (`The costs claimed under the Part 1 Extensions` WITH `the claim for this loss` IS 0, `architects', surveyors' and engineers' fees incurred` IS 0, `the fees allowed by the scales of the professional bodies` IS 0, `fire fighting costs incurred` IS 0, `costs of removing debris` IS 9_000_000_000, `costs of dismantling or demolishing` IS 0, `costs of shoring or propping up` IS 0, `costs of temporary protection` IS 0) EQUALS %s" % lit(home_si * p5 // 100))
    w(quote(raw, 391)); w(quote(raw, 392))
    w("#ASSERT `Extension 6: temporary protection payable under` `the 2026 Summary` `on` (`The costs claimed under the Part 1 Extensions` WITH `the claim for this loss` IS 0, `architects', surveyors' and engineers' fees incurred` IS 0, `the fees allowed by the scales of the professional bodies` IS 0, `fire fighting costs incurred` IS 0, `costs of removing debris` IS 0, `costs of dismantling or demolishing` IS 0, `costs of shoring or propping up` IS 0, `costs of temporary protection` IS 9_000_000_000) EQUALS %s" % lit(total_si * p6 // 100))
    w("")

    # --- Part 1, Extension 7: 72 hours
    h = vn_number(find(raw, 395, r"thời hạn (\d+) giờ liên tục"))
    w("§§ `Part 1, Extension 7`")
    w(quote(raw, 395))
    w("#ASSERT `Extension 7: the hours in one event` EQUALS %d" % h)
    w("#ASSERT `Extension 7: the number of events, for losses at hours` (LIST 0, %d) EQUALS 1" % h)
    w("#ASSERT `Extension 7: the number of events, for losses at hours` (LIST 0, %d) EQUALS 2" % (h + 1))
    w("")

    # --- Peril 9(d): more than 30 consecutive days unattended
    d9 = vn_number(find(raw, 275, r"quá (\d+) ngày liên tiếp"))
    w("§§ `Insured Peril 9(d)`")
    w(quote(raw, 275))
    w("#ASSERT NOT elem `Peril 9(d): the Home unattended for more than 30 consecutive days` (`Peril 9, theft` `a brick house` (`a loss to` `the Contents` `of` (LIST `furniture, a refrigerator, washing machine or similar household good`) `owned by` `the Insured` `at` `inside a lockable part of the Home` `on` (YMD 2026 3 10) `by` `theft or attempted theft` `with` (LIST `force or violence used to enter`) `, unattended for` %d `days`))" % d9)
    w("#ASSERT elem `Peril 9(d): the Home unattended for more than 30 consecutive days` (`Peril 9, theft` `a brick house` (`a loss to` `the Contents` `of` (LIST `furniture, a refrigerator, washing machine or similar household good`) `owned by` `the Insured` `at` `inside a lockable part of the Home` `on` (YMD 2026 3 10) `by` `theft or attempted theft` `with` (LIST `force or violence used to enter`) `, unattended for` %d `days`))" % (d9 + 1))
    w("")

    # --- Part 2: tenant's liability 160.000.000; exclusion 3's 60 and 90 days
    tl = vn_number(find(raw, 514, r"Giới hạn ([\d.]+) Đồng cho mỗi Sự Cố"))
    d60 = vn_number(find(raw, 545, r"trong (\d+) ngày"))
    d90 = vn_number(find(raw, 546, r"hơn (\d+) ngày liên tục"))
    w("§§ `Part 2: the tenant's liability limit, and exclusion 3's periods`")
    w(quote(raw, 514))
    w("#ASSERT `the tenant's liability limit for each Occurrence, in dong` EQUALS %s" % lit(tl))
    w(quote(raw, 545)); w(quote(raw, 546))
    for days, intends, expect in [(10, d60, True), (10, d60 - 1, False), (d90 + 1, 0, True), (d90, 0, False)]:
        w("#ASSERT %s`the person injured is Family or usually resides with the Insured` (`a liability of` `the Insured named in the Policy Summary` `for` (LIST `bodily injury, illness or disability`) `to` (JUST (`A person injured` WITH `relation to the Insured` IS NOTHING, `regularly lives with the Insured at the Insured Location` IS FALSE, `has used the Home` IS TRUE, `has used the Home as a place to live` IS FALSE, `lives with the Insured` IS %s, `days the person intends or intended to make the Home the main residence` IS %d, `consecutive days the person used the Home or lived with the Insured` IS %d, `employed by the Insured or a resident and injured in that work` IS FALSE)) `and` NOTHING `with` EMPTY `, decided by` `a first-instance judgment of a competent Vietnamese court`)"
          % ("" if expect else "NOT ", "TRUE" if intends else "FALSE", intends, days))
    w("")

    # --- Part 3: 10% / 6 months; death 3 months, 160.000.000 or 50%, ages 5-65; helper 4.000.000
    acc = vn_number(find(raw, 653, r"Giới hạn Bồi thường trong thời hạn bảo hiểm: (\d+)%"))
    months = vn_number(find(raw, 654, r"Tối đa là (\d+) tháng"))
    dm = vn_number(find(raw, 660, r"^\s*(\d+) tháng"))
    dl = vn_number(find(raw, 661, r"thời hạn bảo hiểm: ([\d.]+) Đồng"))
    ds = vn_number(find(raw, 661, r"hoặc (\d+)% Số tiền"))
    a_lo, a_hi = [vn_number(x) for x in find(raw, 663, r"từ (\d+) – (\d+)")]
    hl = vn_number(find(raw, 682, r"Giới hạn Bồi thường: ([\d.]+) Đồng"))
    w("§§ `Part 3`")
    w(quote(raw, 653)); w(quote(raw, 654))
    w("#ASSERT `Part 3: the accommodation limit, as a share of the Part 1 total sum insured` EQUALS %d%%" % acc)
    w("#ASSERT `Part 3: the months insured` EQUALS %d" % months)
    w(quote(raw, 660)); w(quote(raw, 661)); w(quote(raw, 662)); w(quote(raw, 663))
    w("#ASSERT `Part 3: the months within which death must follow` EQUALS %d" % dm)
    w("#ASSERT `Part 3: the death benefit's fixed limit, in dong` EQUALS %s" % lit(dl))
    w("#ASSERT `Part 3: the death benefit's share of the Part 1 sum insured` EQUALS %d%%" % ds)
    w("#ASSERT `Part 3: the youngest age for the death benefit` EQUALS %d" % a_lo)
    w("#ASSERT `Part 3: the oldest age for the death benefit` EQUALS %d" % a_hi)
    # the death limit is the lesser: with Part 1 total 2,500,000,000 the fixed figure binds
    w("-- Against the fixture's HYPOTHETICAL Part 1 total of 2,500,000,000, the lesser is the fixed figure.")
    w("#ASSERT `Part 3: the death benefit limit under` `the 2026 Summary` EQUALS %s" % lit(min(dl, total_si * ds // 100)))
    w(quote(raw, 682))
    w("#ASSERT `Part 3: the domestic helper limit for the Period, in dong` EQUALS %s" % lit(hl))
    w("")

    # --- GC3(d) 30 days, GC4(g) 30 days, GC7(b) 12 months, GC11 30 days
    g3 = vn_number(find(raw, 829, r"hơn (\d+) ngày"))
    g4 = vn_number(find(raw, 851, r"trong vòng (\d+) ngày"))
    g7a = vn_number(find(raw, 910, r"trong vòng (\d+) tháng"))
    g7b = vn_number(find(raw, 914, r"trong vòng (\d+) tháng"))
    g11 = vn_number(find(raw, 949, r"trước (\d+) ngày"))
    w("§§ `General Conditions 3, 4, 7 and 11: the periods`")
    w(quote(raw, 828)); w(quote(raw, 829))
    for days, expect in [(g3, False), (g3 + 1, True)]:
        w("#ASSERT %selem `GC3(d): the Home vacant for more than 30 days` (`the grounds under the General Conditions on` (`The Insured's conduct` WITH `observed and fulfilled the terms of the policy` IS TRUE, `the statements in the Proposal Form were true` IS TRUE, `misrepresented, misdescribed or omitted a matter in a document` IS FALSE, `the Insurer elected to avoid the policy for misdescription` IS FALSE, `the Insured Location was used other than as a residence` IS FALSE, `precautions or circumstances changed so as to increase the risk` IS FALSE, `the property was moved to another building or place` IS FALSE, `consecutive days the Home had been vacant` IS %d, `the interest passed otherwise than by will or operation of law` IS FALSE, `the Insurer endorsed its consent before the loss` IS FALSE, `gave immediate written notice with full particulars` IS TRUE, `forwarded every writ, summons and notice on receipt` IS TRUE, `admitted or offered payment without written consent` IS FALSE, `notified the police immediately` IS TRUE, `acted immediately to minimise the loss` IS TRUE, `disclosed all other insurances` IS TRUE, `the date the written claim was delivered` IS JUST (YMD 2026 3 20), `the date to which the Insurer extended time in writing` IS NOTHING, `kept receipts or proof of value` IS TRUE, `took reasonable precautions` IS TRUE, `obstructed or failed to comply with the Insurer's requirements` IS FALSE, `the claim is fraudulent in any respect` IS FALSE, `used fraudulent means or devices` IS FALSE, `the loss was caused wilfully or with the Insured's connivance` IS FALSE, `the date the claim was rejected` IS NOTHING, `the date the rejection was challenged` IS NOTHING, `the date of an arbitral award on the claim` IS NOTHING, `the date the award was challenged` IS NOTHING) `, event on` (YMD 2026 3 10) `, theft` FALSE `, under` (LIST `Part 1`) `, as at` (YMD 2026 4 1))"
          % ("" if expect else "NOT ", days))
    w(quote(raw, 851))
    w("#ASSERT `GC4(g): the last day for the written claim on an event of` (YMD 2026 3 10) `, extended to` NOTHING EQUALS (YMD 2026 3 10) PLUS %d" % g4)
    w(quote(raw, 910)); w(quote(raw, 914))
    w("#ASSERT `GC7(b): the last day to challenge a decision of` (YMD 2026 3 10) EQUALS `add months` (YMD 2026 3 10) %d" % g7a)
    w("#ASSERT `GC7(b): the last day to challenge a decision of` (YMD 2026 3 10) EQUALS `add months` (YMD 2026 3 10) %d" % g7b)
    w(quote(raw, 949))
    w("#ASSERT `GC11: the day an Insurer's cancellation takes effect, the notice sent on` (YMD 2026 5 1) EQUALS (YMD 2026 5 1) PLUS %d" % g11)
    w("")

    # --- GC11 short-period scale, row by row
    w("§§ `GC11: the short-period scale, one assertion per printed row`")
    w(quote(raw, 957)); w(quote(raw, 958))
    rows = []
    for n in range(959, 963):
        line = nfc(raw[n - 1])
        m = re.match(r"\s*(Đến|Từ \d+ tháng đến|Trên) (\d+) tháng\s+(\d+)% trên Phí Bảo hiểm năm\s*$", line)
        if not m:
            sys.exit("gen_figure_tests: short-period row src:%d does not parse: %r" % (n, line))
        rows.append((n, m.group(1), int(m.group(2)), int(m.group(3))))
    for i, (n, kind, months_, share) in enumerate(rows):
        w(quote(raw, n))
        bound = "NOTHING" if kind == "Trên" else "JUST %d" % months_
        w("#ASSERT at (`the short-period scale`) %d EQUALS (`A row of the short-period scale` OF %s, %d%%)" % (i, bound, share))
    # boundaries, from the parsed rows: a cancellation exactly N months in is the first row
    # whose bound is N (F-short-period); a day later falls in the next row.
    w("-- Boundaries: cancelled exactly N months after 1 January 2026, and one day later.")
    upper = [(m_, s) for (_, k, m_, s) in rows if k != "Trên"]
    nxt = [s for (_, k, m_, s) in rows][1:]
    for (m_, s), s_next in zip(upper, nxt):
        w("#ASSERT `GC11: the short-period share for a policy under` `the 2026 Summary` `cancelled by the Insured with effect on` (`add months` (YMD 2026 1 1) %d) EQUALS %d%%" % (m_, s))
        w("#ASSERT `GC11: the short-period share for a policy under` `the 2026 Summary` `cancelled by the Insured with effect on` ((`add months` (YMD 2026 1 1) %d) PLUS 1) EQUALS %d%%" % (m_, s_next))
    w("")
    sys.stdout.write("\n".join(o) + "\n")


if __name__ == "__main__":
    main()
