#!/usr/bin/env python3
"""Derive the four-jurisdiction comparison table by RUNNING the modules.

The table in README.md is the corpus's headline claim, and a table typed by
hand is a claim nothing checks.  This script builds a throwaway .l4 file with
one #EVAL per (fixture, jurisdiction), runs it, and parses the results back
out, so the table is a function of the code rather than of anyone's memory.

    L4=/path/to/l4 python3 make-table.py

Writes comparison-table.md and comparison-table.json beside this script.
Exit 0 on success.

RUN IT WITH JL4_LIBRARY_PATH UNSET.  The binary then resolves its own embedded
prelude, which matches it by construction.  Pinning the variable at a library
tree newer than the binary is the trap described in NOTES.md section 5: the
prelude fails to load and every rule reports "could not find a definition",
which reads as a broken encoding and is not one.

The England column prints a REFUSAL on two fixtures.  That is a result, not an
error -- see README.md, Delta 4 -- and the parser reports it as `refuses`.
"""
import json, os, re, subprocess, sys, tempfile

CASES = [
    "Digilandmall -- the third appellant",
    "Digilandmall -- the second appellant",
    "Hartog v Colin and Shields",
    "Riverlate Properties v Paul",
    "Taylor v Johnson",
    "Smith v Hughes",
    "Smith v Hughes -- counterfactual, risk not borne",
    "Donovan v RRL Corp",
    "Quoine v B2C2",
    "Quoine -- counterfactual, enforcement unconscionable",
]
JURIS = [
    ("Singapore",      "what Singapore law does"),
    ("England & Wales","what English law does"),
    ("Australia",      "what Taylor v Johnson does"),
    ("Restatement",    "what the Restatement does"),
]
IMPORTS = ["prelude", "mistake-domain", "sg-unilateral-mistake", "ew-unilateral-mistake",
           "au-unilateral-mistake", "us-unilateral-mistake", "mistake-comparison",
           "mistake-cases"]

def main():
    here = os.path.dirname(os.path.abspath(__file__))
    modules = os.path.abspath(os.path.join(here, ".."))
    l4 = os.environ.get("L4", "l4")

    lines = [f"IMPORT `{m}`" if "-" in m else f"IMPORT {m}" for m in IMPORTS] + [""]
    order = []
    for c in CASES:
        for label, fn in JURIS:
            lines.append(f"#EVAL `the name of` (`{fn}` `{c}`)")
            order.append((c, label))

    # the probe must sit beside the modules so importer-relative resolution finds them
    probe = os.path.join(modules, "_comparison-table-probe.l4")
    open(probe, "w").write("\n".join(lines) + "\n")
    env = dict(os.environ); env.pop("JL4_LIBRARY_PATH", None)
    try:
        p = subprocess.run([l4, "run", probe], capture_output=True, text=True, env=env)
    finally:
        os.unlink(probe)
    if p.returncode != 0:
        sys.stderr.write(p.stdout + p.stderr)
        sys.stderr.write(f"\n{l4} run exited {p.returncode}\n")
        return 1

    blocks = re.split(r"Evaluation\[(\d+)\] @ [^\n]*\n", p.stdout)[1:]
    res = {}
    for i in range(0, len(blocks), 2):
        body = blocks[i + 1]
        m = re.search(r"Result:\s*\n\s*(.+?)\n", body)
        v = m.group(1).strip() if m else "??"
        if v.startswith("The model refuses"):
            v = "refuses"
        res[int(blocks[i])] = v.strip('"')
    if len(res) != len(order):
        sys.stderr.write(f"expected {len(order)} evaluations, got {len(res)}\n")
        return 1

    rows = {}
    for i, (case, label) in enumerate(order, start=1):
        rows.setdefault(case, {})[label] = res[i]

    json.dump(rows, open(os.path.join(here, "comparison-table.json"), "w"), indent=2)
    heads = [l for l, _ in JURIS]
    out = ["# Comparison table — DERIVED, do not edit", "",
           "Generated by `make-table.py`, which runs the modules. Do not hand-edit: re-run it.", "",
           "| case | " + " | ".join(heads) + " |",
           "| --- | " + " | ".join("---" for _ in heads) + " |"]
    for c in CASES:
        out.append("| " + c + " | " + " | ".join(rows[c][h] for h in heads) + " |")
    out.append("")
    open(os.path.join(here, "comparison-table.md"), "w").write("\n".join(out))
    print("\n".join(out))
    return 0

if __name__ == "__main__":
    sys.exit(main())
